"""
comprehensive_ablation_multidamage.py
======================================
Stage-0 multi-damage ablation: can a single drive-by pass LOCALISE and QUANTIFY
scour at TWO independent piers? This drives the same Optuna/training pipeline as
the single-scour ablation, but in MULTI-OUTPUT REGRESSION mode (one continuous
head per target support), against a dataset generated by scour_MATLAB/A00_Run.m
with damage_mode='multi_scour'.

Reduced grid (deliberately light — see paper-strategy):
    Phase 1 — single-DOF sweep   (8 sensors)            -> 8 studies / architecture
    Phase 2 — best-pair          (the 2 best singles)   -> 1 study  / architecture
            = 9 studies per architecture (NO leave-one-out, NO full-8DOF).
    Single Optuna seed, no 30-seed Monte-Carlo (run_robustness=False).

Architecture order (cost-aware):
    1. PAA + N-HiTS                 — the single-scour champion backbone.
    2. PAA + Space2Vec + N-HiTS     — does the spatial embedding help localisation?
       (Space2Vec grounds the signal to bridge position — plausibly useful when
        the task is *which* pier.) Only if S2V does NOT help, try the LSTM arm
        (commented below).

Workflow
--------
1. Generate the Stage-0 dataset on the PC (A00 multi_scour), move it under
   data/<DATASET>, and set DATASET + TARGET_SUPPORTS to match scour_supports.
2. Run this script: Phase 1 first. Inspect the per-pier / aggregate MSE, pick the
   two best single sensors, set PAIR_DOFS, and re-run for Phase 2.

The task switch is `task='regression'` in each config (core/task.py). Leave it
out — or run the single-scour scripts — to get the original classification.
"""

import optuna

from core.utils       import (set_global_seed, define_save_locations,
                              IDX_TO_DOF_NAME)
from training.pipeline import execute_ablation_pipeline

optuna.logging.set_verbosity(optuna.logging.WARNING)

# =============================================================================
#  Configuration
# =============================================================================
# Dataset folder under data/ generated by A00 multi_scour. MUST carry per-file
# data.scour_vector (the loader reads the targets from it).
DATASET         = "multidamage_stage0"          # <-- set to your generated folder

# 1-based MATLAB support indices that carry independent scour = the regression
# targets. MUST equal A00's scour_supports (default the two internal piers).
TARGET_SUPPORTS = [2, 3]

TASK            = "regression"
DISCRETIZATION  = 1            # kept for cache/scaler naming consistency (unused by the heads)
N_TRIALS        = 75           # lighter HPO than the single-scour 200
EPOCHS          = 50
OPTUNA_SEED     = 42           # single seed — no multi-seed Monte-Carlo for the reduced grid
ALL_DOFS        = list(range(8))

# Set AFTER Phase 1 to the two best single sensors, then re-run for Phase 2.
PAIR_DOFS       = None         # e.g. [2, 5]

ARCHITECTURES = [
    {"name_short": "PAA_NHiTS",     "method": "PAA",
     "use_space2vec": False, "use_lstm": False, "use_nhits": True,
     "model_type": "1D_MODULAR"},
    {"name_short": "PAA_S2V_NHiTS", "method": "PAA",
     "use_space2vec": True,  "use_lstm": False, "use_nhits": True,
     "model_type": "1D_MODULAR"},
    # Only if Space2Vec does NOT help, uncomment the LSTM arm:
    # {"name_short": "PAA_LSTM_NHiTS", "method": "PAA",
    #  "use_space2vec": False, "use_lstm": True, "use_nhits": True,
    #  "model_type": "1D_MODULAR"},
]


# =============================================================================
#  Helpers
# =============================================================================
def make_config(arch: dict, dofs: list[int]) -> dict:
    """One experiment_path entry — a multi-output REGRESSION config."""
    dof_str = "_".join(str(d) for d in dofs)
    return {
        "name":            f"{arch['name_short']}_DOFs_{dof_str}_seed{OPTUNA_SEED}",
        "method":          arch["method"],
        "dofs":            list(dofs),
        "discretization":  DISCRETIZATION,
        "use_space2vec":   arch["use_space2vec"],
        "use_lstm":        arch["use_lstm"],
        "use_nhits":       arch["use_nhits"],
        "model_type":      arch["model_type"],
        # --- the multi-output regression switch (core/task.py) ---
        "task":            TASK,
        "target_supports": TARGET_SUPPORTS,
    }


def run_phase(phase_label: str, dofs: list[int]) -> None:
    """Run every architecture on one DOF subset (single Optuna seed, no MC)."""
    configs = [make_config(arch, dofs) for arch in ARCHITECTURES]
    db, out, cache = define_save_locations(
        phase_label, dataset=DATASET, DOFs=dofs, discretization=DISCRETIZATION,
    )
    print(f"\n{'#' * 64}\n#  {phase_label}   DOFs={dofs}   targets={TARGET_SUPPORTS}\n"
          f"#  archs: {[a['name_short'] for a in ARCHITECTURES]}\n{'#' * 64}")
    execute_ablation_pipeline(
        experiment_path = configs,
        database_name   = db,
        output_dir_name = out,
        cache_dir_name  = cache,
        dataset         = DATASET,
        n_trials        = N_TRIALS,
        epochs          = EPOCHS,
        optuna_seed     = OPTUNA_SEED,
        use_pruner      = True,
        run_robustness  = False,     # reduced grid: single seed, no 30-seed MC
    )


def phase_1_single_dof() -> None:
    print("\n" + "=" * 64 + "\n  STAGE 0 · PHASE 1 — single-DOF sweep\n" + "=" * 64)
    for dof in ALL_DOFS:
        run_phase(f"MD0_SingleDOF_{IDX_TO_DOF_NAME[dof]}", [dof])


def phase_2_pair() -> None:
    if not PAIR_DOFS:
        print("\n[Phase 2 skipped] Set PAIR_DOFS to the two best single sensors "
              "from Phase 1, then re-run.")
        return
    a, b = (IDX_TO_DOF_NAME[i] for i in PAIR_DOFS)
    print("\n" + "=" * 64 + f"\n  STAGE 0 · PHASE 2 — best pair {a} + {b}\n" + "=" * 64)
    run_phase(f"MD0_Pair_{a}__{b}", list(PAIR_DOFS))


# =============================================================================
#  Driver
# =============================================================================
if __name__ == "__main__":
    set_global_seed(OPTUNA_SEED)
    phase_1_single_dof()
    phase_2_pair()
    print("\n" + "=" * 64 + "\n  Stage-0 multi-damage ablation finished.\n" + "=" * 64)
