"""
comprehensive_ablation_multidamage.py
======================================
Stage-0 multi-damage ablation: can a single drive-by pass LOCALISE and QUANTIFY
scour at TWO independent piers? Drives the same Optuna/training pipeline as the
single-scour ablation, but in MULTI-OUTPUT REGRESSION mode (one continuous head
per target support), against a dataset generated by scour_MATLAB/A00_Run.m with
STAGE='stage0_multiscour' (damage_mode='multi_scour').

TURNKEY: run once, no manual editing. The script
    1. Phase 1 - single-DOF sweep (8 sensors) x the active architectures
       x SEEDS independent Optuna runs.
    2. Auto-selects the two best single sensors (lowest CHAMPION_ARCH agg MSE,
       MEDIAN across seeds).
    3. Phase 2 - the best pair (+ any EXTRA_PAIRS) x the active architectures.
    4. Writes a results summary (leaderboard CSV with one row per seed +
       a seed-aggregated median/IQR leaderboard + per-head MSE + localisation
       accuracy + a predicted-vs-true parity plot).

ARCHITECTURE POLICY: selected ONCE at Stage 0 (all arms run), then FIXED -
Stage 1/2 run CHAMPION_ARCH only, so later stages vary one factor at a time
(bearing head at Stage 1; EOVs at stage1_crack/stage1_full; scale at Stage 2),
never the backbone too.

Reduced grid (see paper-strategy): SEEDS independent Optuna seeds per config
(default 3 - architecture-consistency across seeds, reported as median + IQR;
the train/val split stays FIXED at random_state=42 in trainer.py, so seed
variance = init/HPO variance only). Still no 30-seed per-trial Monte-Carlo
(run_robustness=False), NO leave-one-out, NO full-8DOF.

Architectures (cost-aware):
    1. PAA + N-HiTS               - the single-scour champion backbone.
    2. PAA + Space2Vec + N-HiTS   - does the spatial embedding help localisation?
       (Space2Vec grounds the signal to bridge position - plausibly useful when
        the task is *which* pier.)
    3. PAA + LSTM + N-HiTS        - does a recurrent temporal encoder help? Added
       because S2V did NOT help the Stage-0 champion (it hurt the winning pair);
       stacks CNN -> LSTM -> N-HiTS pool, the LSTM size Optuna-tuned.

The task switch is `task='regression'` in each config (core/task.py). Leave it
out - or run the single-scour scripts - to get the original classification.
"""

# Force UTF-8 stdout/stderr so any decorative log character never raises
# UnicodeEncodeError on a Windows cp1252 console (e.g. Python 3.10 in a plain
# terminal). errors="replace" guarantees no crash even on an odd stream.
import sys as _sys
for _stream in (_sys.stdout, _sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except Exception:   # noqa: BLE001  — best-effort; ASCII-only logs are the real fix
        pass

import csv
import os

import numpy as np
import optuna
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader

from core            import task
from core.dataset    import get_or_create_cache, MemmapDataset
from core.models     import build_model
from core.utils      import (set_global_seed, define_save_locations,
                             IDX_TO_DOF_NAME)
from training.pipeline import execute_ablation_pipeline
from training.trainer  import DEVICE

optuna.logging.set_verbosity(optuna.logging.WARNING)

# =============================================================================
#  Configuration
# =============================================================================
# ===== STAGE selector — mirrors scour_MATLAB/A00_Run.m's STAGE preset =====
# Pick the stage whose dataset you generated with A00. Each sets the dataset
# folder, the scour targets, and whether bearing heads are added. The DATASET
# names follow A00's case_name convention; VERIFY the exact folder name (esp.
# the states<N> count) against what landed in data/ before a long run.
STAGE = "s0_scour"   # see the ladder below; mirrors scour_MATLAB/A00_Run.m

# THE LADDER (mirrors A00_Run.m; ONE factor changes per rung so any degradation
# is attributable). HEADS = scour (per pier) + bearing (per abutment) ONLY;
# crack / rail profile / track-layer / wheel damage are NUISANCES the network
# must be INVARIANT to, never estimate. Folder names are SHORT
# (<stage>_L<len>_st<nstates>) — the full descriptor lives in case_info.case_desc
# (Windows MAX_PATH; the old ~110-char names broke it).
#   states = 250 LHS + anchors; anchors = 1 healthy + n_piers*4 (+ 2*4 if bearing)
_LADDER = {
    # L60 / 3-span, scour piers 2 & 3
    "s0_scour":       ("s0_scour_L60_st259",        [2, 3],    None),
    "s11_bear":       ("s11_bear_L60_st267",        [2, 3],    ["left", "right"]),
    "s12_crack":      ("s12_crack_L60_st259",       [2, 3],    None),
    "s13_bearcrack":  ("s13_bearcrack_L60_st267",   [2, 3],    ["left", "right"]),
    "s14_prof":       ("s14_prof_L60_st267",        [2, 3],    ["left", "right"]),
    "s15_track":      ("s15_track_L60_st267",       [2, 3],    ["left", "right"]),
    "s16_all":        ("s16_all_L60_st267",         [2, 3],    ["left", "right"]),
    # L99.6 / 4-span scale-up, scour piers 2, 3 & 4
    "s21_scour4":     ("s21_scour4_L99.6_st263",    [2, 3, 4], None),
    "s22_bearcrack4": ("s22_bearcrack4_L99.6_st271", [2, 3, 4], ["left", "right"]),
    "s23_all4":       ("s23_all4_L99.6_st271",      [2, 3, 4], ["left", "right"]),
}
if STAGE not in _LADDER:
    raise ValueError(f"unknown STAGE {STAGE!r} - pick one of {list(_LADDER)}")
DATASET, TARGET_SUPPORTS, BEARING_TARGETS = _LADDER[STAGE]   # CONFIRM st<N> vs the folder A00 writes

# Bearing heads (Stage 1+): laid out AFTER the scour heads, reported separately
# (scour_mse vs bearing_mse) + a leakage/disentanglement report; localisation
# stays on the scour heads. None = scour-only (Stage 0, byte-identical).

TASK           = "regression"
DISCRETIZATION = 1            # kept for cache/scaler naming consistency (unused by the heads)
N_TRIALS       = 100          # raised from 75 (2026-07-12): TPE startup auto-scales
                              # to n_trials//4 = 25 random trials (pipeline), so a
                              # bigger budget also buys a wider initial sampling.
EPOCHS         = 50
# Independent Optuna seeds per config: the ablation is cheap next to MATLAB
# generation, so we buy architecture-consistency evidence (median + IQR across
# seeds). The train/val split is FIXED (random_state=42 in trainer.py) - seed
# variance is init/HPO variance only. Use [42] to reproduce the legacy
# single-seed grid; extend to 5 seeds (+[7, 314]) if the PC is idle.
SEEDS          = [42, 1337, 2026]
ALL_DOFS       = list(range(8))

# Best pair. Leave None to auto-select the two best single sensors from Phase 1
# (lowest PAA+N-HiTS aggregate MSE). Set explicitly (e.g. [2, 5]) to override.
PAIR_DOFS = None

# Designed pairs to run IN ADDITION to the auto-selected best pair, e.g. the
# physics-motivated mixed unsprung+sprung fusion pair (wheel = profile
# reference, sprung = inertial bridge response; TSD-residual logic - see
# docs/framework_rationale.md 2026-07-12). DOF map: 0 CarBody_Vert,
# 1 FrontBogie_Vert, 2 RearBogie_Vert, 3 Wheel1_Vert, 4 Wheel2_Vert,
# 5 CarBody_Pitch, 6 FrontBogie_Pitch, 7 RearBogie_Pitch.
# L100 PILOT RESULT (2026-07-13): under heavy roughness EOV the mixed pair
# FrontBogie_Vert+Wheel1_Vert BEAT the auto pair Wheel1+Wheel2 by 17% scour
# MSE (105 vs 126) and +5pp localisation (0.797 vs 0.744), although
# FrontBogie_Vert ALONE was collapse-level there (327) - the TSD-residual
# fusion mechanism (wheel = profile reference, bogie = filtered response).
# CarBody_Vert+Wheel1 was WORSE than wheel+wheel (156): the sprung partner
# must sit LOW in the suspension chain. Keep the mixed pair in every stage
# for chain-wide comparability.
EXTRA_PAIRS: list[list[int]] = [[1, 3]]   # FrontBogie_Vert + Wheel1_Vert

# Fresh-run tag (2026-07-12 user policy: re-runs start FROM SCRATCH, never
# extend). When set (e.g. "v7"), every study/output name gets the suffix, so
# re-ablating a dataset that already holds studies trains NEW full-budget
# studies while the old DB rows and weights stay untouched (provenance).
# Leave "" for the first run on a new dataset (nothing to collide with).
RUN_TAG = ""

# Load-time sensor noise (None = the noise-free chain default). Generation is
# NOISE-FREE from stage1_crack onward (A00 use_signal_noise=false; folder tag
# varVST); when a study needs measurement noise, inject it here - see
# core/dataset._inject_sensor_noise. E.g. {"mode": "legacy_wheel",
# "desvio": 0.05} reproduces the legacy MATLAB D01 wheel-only model on
# noise-free data. The cache stem is noise-tagged (clean/noisy never collide).
SENSOR_NOISE = None


def _cfg_suffix() -> str:
    """Suffix appended to every study/config name. Keeps differently-configured
    runs (load-time noise, fresh-run tag) in SEPARATE Optuna studies - without
    it, re-running a stage with a different SENSOR_NOISE would silently RESUME
    and extend studies whose earlier trials trained on differently-noised data."""
    s = f"_nz-{SENSOR_NOISE['mode']}" if SENSOR_NOISE else ""
    return s + (f"_{RUN_TAG}" if RUN_TAG else "")

# Where the leaderboard + parity/leakage plots are written (stage-tagged).
SUMMARY_DIR = os.path.join("results", f"{STAGE}_summary")

# ===== Architecture policy: SELECT at Stage 0, FIX thereafter ================
# Stage 0 is the architecture-SELECTION stage: every arm runs (the paper's
# architecture table). Stage 1/2 change the SCIENCE (bearing head, scale +
# EOV), not the backbone, so they run the fixed CHAMPION_ARCH only - one
# factor varies at a time. Re-running Stage 0 is RESUMABLE: studies that
# already hold n_trials trials are skipped (pipeline), so adding an arm only
# trains that arm's studies.
ALL_ARCHITECTURES = [
    {"name_short": "PAA_NHiTS",     "method": "PAA",
     "use_space2vec": False, "use_lstm": False, "use_nhits": True,
     "model_type": "1D_MODULAR"},
    {"name_short": "PAA_S2V_NHiTS", "method": "PAA",
     "use_space2vec": True,  "use_lstm": False, "use_nhits": True,
     "model_type": "1D_MODULAR"},
    # LSTM arm ENABLED (per the plan): S2V did not help the Stage-0 champion - it
    # HURT the winning pair (+69% MSE) - so we test a recurrent temporal encoder.
    # This stacks CNN -> LSTM -> N-HiTS multi-rate pool; the LSTM size/depth are
    # Optuna-tuned (trainer._suggest_params gates on use_lstm). Heaviest arm, most
    # overfit-prone on the single-seed grid - read a marginal win with caution.
    {"name_short": "PAA_LSTM_NHiTS", "method": "PAA",
     "use_space2vec": False, "use_lstm": True, "use_nhits": True,
     "model_type": "1D_MODULAR"},
]

# The backbone carried into Stage 1/2, and the arch used to RANK single sensors
# for the auto-pair. CONFIRM against the completed 3-arm Stage-0 leaderboard
# BEFORE running Stage 1/2 (change only if another arm wins Stage 0).
CHAMPION_ARCH = "PAA_NHiTS"

if STAGE == "stage0_multiscour":
    ARCHITECTURES = ALL_ARCHITECTURES      # selection stage - run every arm
else:
    ARCHITECTURES = [a for a in ALL_ARCHITECTURES
                     if a["name_short"] == CHAMPION_ARCH]
    if not ARCHITECTURES:
        raise ValueError(f"CHAMPION_ARCH {CHAMPION_ARCH!r} is not one of "
                         f"{[a['name_short'] for a in ALL_ARCHITECTURES]}")

RANK_ARCH = CHAMPION_ARCH

# Records every phase that ran so the summary can re-evaluate each champion.
_RAN_PHASES: list[dict] = []


# =============================================================================
#  Config / phase helpers
# =============================================================================
def make_config(arch: dict, dofs: list[int], seed: int) -> dict:
    """One experiment_path entry - a multi-output REGRESSION config."""
    dof_str = "_".join(str(d) for d in dofs)
    return {
        "name":            f"{arch['name_short']}_DOFs_{dof_str}_seed{seed}{_cfg_suffix()}",
        "seed":            seed,
        "sensor_noise":    SENSOR_NOISE,
        "name_short":      arch["name_short"],
        "method":          arch["method"],
        "dofs":            list(dofs),
        "discretization":  DISCRETIZATION,
        "use_space2vec":   arch["use_space2vec"],
        "use_lstm":        arch["use_lstm"],
        "use_nhits":       arch["use_nhits"],
        "model_type":      arch["model_type"],
        # --- the multi-output regression switch (core/task.py) ---
        "task":            TASK,
        "target_supports": TARGET_SUPPORTS,
        "bearing_targets": BEARING_TARGETS,   # None for Stage 0
    }


def run_phase(phase_label: str, dofs: list[int]) -> None:
    """Run every architecture x every seed on one DOF subset (no per-trial MC).

    One pipeline call per seed: study names carry the seed suffix, so a re-run
    (or a seed added later) only trains the missing studies (pipeline resume).
    """
    db, out, cache = define_save_locations(
        phase_label, dataset=DATASET, DOFs=dofs, discretization=DISCRETIZATION,
    )
    all_configs: list[dict] = []
    for seed in SEEDS:
        configs = [make_config(arch, dofs, seed) for arch in ARCHITECTURES]
        print(f"\n{'#' * 64}\n#  {phase_label}   DOFs={dofs}   targets={TARGET_SUPPORTS}   seed={seed}\n"
              f"#  archs: {[a['name_short'] for a in ARCHITECTURES]}\n{'#' * 64}")
        execute_ablation_pipeline(
            experiment_path = configs,
            database_name   = db,
            output_dir_name = out,
            cache_dir_name  = cache,
            dataset         = DATASET,
            n_trials        = N_TRIALS,
            epochs          = EPOCHS,
            optuna_seed     = seed,
            use_pruner      = True,
            run_robustness  = False,   # reduced grid: no 30-seed per-trial MC
        )
        all_configs.extend(configs)
    _RAN_PHASES.append({"phase_label": phase_label, "dofs": list(dofs),
                        "configs": all_configs, "db": db,
                        "output_dir": out, "cache_dir": cache})


def phase_1_single_dof() -> None:
    print("\n" + "=" * 64 + "\n  STAGE 0 - PHASE 1 - single-DOF sweep\n" + "=" * 64)
    for dof in ALL_DOFS:
        run_phase(f"MD0_SingleDOF_{IDX_TO_DOF_NAME[dof]}", [dof])


def auto_select_pair() -> list[int]:
    """Two best single sensors by RANK_ARCH aggregate MSE (MEDIAN across seeds)."""
    if PAIR_DOFS:
        print(f"\n[pair] using user-set PAIR_DOFS = {PAIR_DOFS}")
        return list(PAIR_DOFS)

    scores: list[tuple[float, int, int]] = []      # (median MSE, dof, n_seeds)
    for dof in ALL_DOFS:
        phase_label = f"MD0_SingleDOF_{IDX_TO_DOF_NAME[dof]}"
        db, _, _ = define_save_locations(phase_label, DATASET, [dof], DISCRETIZATION)
        vals: list[float] = []
        for seed in SEEDS:
            study_name = f"{RANK_ARCH}_DOFs_{dof}_seed{seed}{_cfg_suffix()}"
            try:
                study = optuna.load_study(study_name=study_name, storage=db)
                vals.append(study.best_value)
            except Exception as e:                           # noqa: BLE001
                print(f"  [pair] skip DOF {dof} seed {seed} "
                      f"({IDX_TO_DOF_NAME[dof]}): {e}")
        if vals:
            scores.append((float(np.median(vals)), dof, len(vals)))

    if len(scores) < 2:
        raise RuntimeError("auto-pair needs >=2 completed single-DOF studies.")
    scores.sort(key=lambda t: t[0])
    print("\n[pair] single-sensor ranking (MEDIAN aggregate MSE, %^2, lower=better):")
    for mse, dof, n in scores:
        print(f"        {IDX_TO_DOF_NAME[dof]:<18} DOF {dof}   MSE {mse:.3f}  ({n} seeds)")
    best = sorted(dof for _, dof, _ in scores[:2])
    print(f"[pair] -> best two sensors: {[IDX_TO_DOF_NAME[d] for d in best]}  (DOFs {best})")
    return best


def phase_2_pair(pair: list[int]) -> None:
    a, b = (IDX_TO_DOF_NAME[i] for i in pair)
    print("\n" + "=" * 64 + f"\n  STAGE 0 - PHASE 2 - best pair {a} + {b}\n" + "=" * 64)
    run_phase(f"MD0_Pair_{a}__{b}", list(pair))


# =============================================================================
#  Results summary - the actual Stage-0 answer
# =============================================================================
def _val_loader(config: dict, cache_dir: str):
    """Canonical (seed-42) validation loader + processed shape for one config."""
    X, y, _ = get_or_create_cache(config, DATASET, cache_dir)
    _, val_idx = train_test_split(np.arange(len(y)), test_size=0.20, random_state=42)
    loader = DataLoader(
        MemmapDataset(X, y, val_idx, label_dtype=task.label_dtype(config)),
        batch_size=64, shuffle=False,
    )
    return loader, X.shape


def evaluate_champion(config: dict, db: str, output_dir: str, cache_dir: str) -> dict | None:
    """Rebuild a phase's champion, load its exported weights, return full metrics."""
    weights = os.path.join(output_dir, config["name"], "DT_champion_weights.pth")
    if not os.path.exists(weights):
        print(f"  [summary] no champion weights for {config['name']} - skipped.")
        return None
    try:
        study = optuna.load_study(study_name=config["name"], storage=db)
    except Exception as e:                                   # noqa: BLE001
        print(f"  [summary] cannot load study {config['name']}: {e}")
        return None

    loader, shape = _val_loader(config, cache_dir)
    model, _ = build_model(config, study.best_params, shape, DEVICE)
    model.load_state_dict(torch.load(weights, map_location=DEVICE))
    return task.evaluate(model, loader, config, DEVICE)


def summarize() -> None:
    """Leaderboard CSV + per-head MSE + localisation accuracy + parity plot, plus
    (Stage 1+) a scour-vs-bearing disentanglement/leakage report."""
    os.makedirs(SUMMARY_DIR, exist_ok=True)
    rows: list[dict] = []
    print("\n" + "=" * 64 + f"\n  {STAGE} - RESULTS SUMMARY\n" + "=" * 64)

    for ph in _RAN_PHASES:
        for cfg in ph["configs"]:
            m = evaluate_champion(cfg, ph["db"], ph["output_dir"], ph["cache_dir"])
            if not m:
                continue
            per_head = m.get("per_head_mse", [])
            # Head columns: scour heads named by support; any extra heads are the
            # Stage-1 bearing targets (laid out after the scour heads).
            n_s = len(TARGET_SUPPORTS)
            bt = cfg.get("bearing_targets") or []
            head_cols = {}
            for i, v in enumerate(per_head):
                if i < n_s:
                    head_cols[f"mse_support_{TARGET_SUPPORTS[i]}"] = round(v, 4)
                else:
                    bname = bt[i - n_s] if (i - n_s) < len(bt) else (i - n_s)
                    head_cols[f"mse_bearing_{bname}"] = round(v, 4)
            row = {
                "phase":        ph["phase_label"],
                "architecture": cfg["name_short"],
                "dofs":         "+".join(IDX_TO_DOF_NAME[d] for d in cfg["dofs"]),
                "seed":         cfg.get("seed", SEEDS[0]),
                "n_sensors":    len(cfg["dofs"]),
                "agg_mse":      round(m["mse"], 4),
                "agg_mae":      round(m["mae"], 4),
                "localisation_acc": (round(m["primary"], 4)
                                     if m["primary"] == m["primary"] else "nan"),
            }
            # Stage-1 scour-vs-bearing split (present only when bearing heads exist)
            if "scour_mse" in m:
                row["scour_mse"]   = round(m["scour_mse"], 4)
                row["bearing_mse"] = round(m["bearing_mse"], 4)
            row.update(head_cols)
            rows.append(row)

    if not rows:
        print("  [summary] nothing to summarise (no champions found).")
        return

    rows.sort(key=lambda r: r["agg_mse"])
    # union of keys across rows so DictWriter never trips on a missing column
    fields = list(dict.fromkeys(k for r in rows for k in r))
    csv_path = os.path.join(SUMMARY_DIR, "leaderboard.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    print(f"  Leaderboard ({len(rows)} models) -> {csv_path}")
    print(f"  Best: {rows[0]['architecture']} on {rows[0]['dofs']} "
          f"(seed {rows[0]['seed']})  agg_MSE={rows[0]['agg_mse']}  "
          f"loc_acc={rows[0]['localisation_acc']}")

    _median_leaderboard(rows)
    _parity_plot_for_best(rows[0])
    if BEARING_TARGETS:
        disentanglement_report(rows)


def _median_leaderboard(rows: list[dict]) -> None:
    """Seed-aggregated leaderboard: median + IQR per (phase, architecture, dofs).

    The paper-facing table (see ablation methodology: report median, not mean -
    occasional HPO/init collapses inflate the mean). One row per config; the
    per-seed rows stay available in leaderboard.csv.
    """
    groups: dict[tuple, list[dict]] = {}
    for r in rows:
        groups.setdefault((r["phase"], r["architecture"], r["dofs"]), []).append(r)

    num_cols = [k for k in rows[0]
                if k not in ("phase", "architecture", "dofs", "seed", "n_sensors")]
    agg_rows: list[dict] = []
    for (phase, arch, dofs), grp in groups.items():
        row = {"phase": phase, "architecture": arch, "dofs": dofs,
               "n_sensors": grp[0]["n_sensors"], "n_seeds": len(grp)}
        for col in num_cols:
            vals = [g[col] for g in grp
                    if isinstance(g.get(col), (int, float))]
            if not vals:
                continue
            row[col] = round(float(np.median(vals)), 4)
            if col == "agg_mse" and len(vals) > 1:
                q75, q25 = np.percentile(vals, [75, 25])
                row["agg_mse_iqr"] = round(float(q75 - q25), 4)
        agg_rows.append(row)

    agg_rows.sort(key=lambda r: r.get("agg_mse", float("inf")))
    fields = list(dict.fromkeys(k for r in agg_rows for k in r))
    csv_path = os.path.join(SUMMARY_DIR, "leaderboard_median.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(agg_rows)
    print(f"  Median leaderboard ({len(agg_rows)} configs x {len(SEEDS)} seeds) "
          f"-> {csv_path}")


def _find_cfg(row: dict) -> tuple[dict | None, dict | None]:
    """(phase, config) dicts for a leaderboard row, or (None, None)."""
    ph = next((p for p in _RAN_PHASES if p["phase_label"] == row["phase"]), None)
    if ph is None:
        return None, None
    cfg = next((c for c in ph["configs"]
                if c["name_short"] == row["architecture"]), None)
    return ph, cfg


def _predictions(ph: dict, cfg: dict) -> tuple[np.ndarray, np.ndarray] | None:
    """Champion predictions and ground truth on the canonical val set: (P, T)."""
    weights = os.path.join(ph["output_dir"], cfg["name"], "DT_champion_weights.pth")
    if not os.path.exists(weights):
        return None
    study = optuna.load_study(study_name=cfg["name"], storage=ph["db"])
    loader, shape = _val_loader(cfg, ph["cache_dir"])
    model, _ = build_model(cfg, study.best_params, shape, DEVICE)
    model.load_state_dict(torch.load(weights, map_location=DEVICE))
    model.eval()
    preds, trues = [], []
    with torch.no_grad():
        for bx, by in loader:
            preds.append(model(bx.to(DEVICE)).cpu().numpy())
            trues.append(by.numpy())
    return np.vstack(preds), np.vstack(trues)


def disentanglement_report(rows: list[dict]) -> None:
    """Stage-1 scour<->bearing leakage: does a seized bearing induce a false scour
    reading (the dangerous case), and vice versa? Uses the single-damage anchor
    subsets present in the data (scour-only / bearing-only states). Writes
    `disentanglement.csv` (one row per config with bearing heads)."""
    n_s = len(TARGET_SUPPORTS)
    S_THR, B_THR = 5.0, 20.0        # "damaged" thresholds: 5% scour, 20% seized
    out: list[dict] = []
    print("\n  --- Stage-1 disentanglement (scour<->bearing leakage) ---")
    for r in rows:
        ph, cfg = _find_cfg(r)
        if cfg is None or not cfg.get("bearing_targets"):
            continue
        pt = _predictions(ph, cfg)
        if pt is None:
            continue
        P, T = pt
        Ts, Tb = T[:, :n_s], T[:, n_s:]        # true scour / bearing
        Ps, Pb = P[:, :n_s], P[:, n_s:]        # pred scour / bearing
        s_max_t, b_max_t = Ts.max(1), Tb.max(1)
        # bearing-only states -> how much false SCOUR the model reports (bad)
        m_bear_only = (s_max_t < S_THR) & (b_max_t > B_THR)
        # scour-only states -> how much false BEARING the model reports
        m_scour_only = (b_max_t < S_THR) & (s_max_t > S_THR)
        leak_s = float(Ps[m_bear_only].max(1).mean()) if m_bear_only.any() else float("nan")
        leak_b = float(Pb[m_scour_only].max(1).mean()) if m_scour_only.any() else float("nan")
        out.append({
            "architecture": cfg["name_short"], "dofs": r["dofs"],
            "seed": cfg.get("seed", SEEDS[0]),
            "scour_leak_on_bearing_%": round(leak_s, 3),   # ideal ~0 (false scour alarm)
            "bearing_leak_on_scour_%": round(leak_b, 3),
            "n_bearing_only": int(m_bear_only.sum()),
            "n_scour_only":   int(m_scour_only.sum()),
        })
        print(f"    {cfg['name_short']:16} {r['dofs']:28} seed={cfg.get('seed', '?'):<5} "
              f"false-scour-from-bearing={leak_s:6.2f}%  "
              f"false-bearing-from-scour={leak_b:6.2f}%")
    if not out:
        return
    csv_path = os.path.join(SUMMARY_DIR, "disentanglement.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(out[0].keys()))
        w.writeheader()
        w.writerows(out)
    print(f"  Disentanglement -> {csv_path}  (low scour_leak_on_bearing = clean)")


def _parity_plot_for_best(best_row: dict) -> None:
    """Predicted-vs-true scatter per target head for the leaderboard winner."""
    ph, cfg = _find_cfg(best_row)
    if cfg is None:
        return
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:                                        # noqa: BLE001
        print("  [summary] matplotlib unavailable - parity plot skipped.")
        return
    pt = _predictions(ph, cfg)
    if pt is None:
        return
    P, T = pt

    n_s = len(TARGET_SUPPORTS)
    bt = cfg.get("bearing_targets") or []
    n = P.shape[1]
    fig, axes = plt.subplots(1, n, figsize=(5 * n, 4.5), squeeze=False)
    for i in range(n):
        ax = axes[0, i]
        is_scour = i < n_s
        label = (f"Scour support {TARGET_SUPPORTS[i]}" if is_scour
                 else f"Bearing {bt[i - n_s] if (i - n_s) < len(bt) else i - n_s}")
        unit = "scour (%)" if is_scour else "seized (%)"
        ax.scatter(T[:, i], P[:, i], s=10, alpha=0.4)
        lo, hi = 0, max(60 if is_scour else 100, float(T[:, i].max()) + 5)
        ax.plot([lo, hi], [lo, hi], "k--", lw=1)
        ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
        ax.set_xlabel(f"True {unit}"); ax.set_ylabel(f"Predicted {unit}")
        ax.set_title(label)
        ax.set_aspect("equal", "box")
    fig.suptitle(f"{STAGE} parity - {best_row['architecture']} on {best_row['dofs']}"
                 f" (seed {best_row.get('seed', '?')})")
    fig.tight_layout()
    out = os.path.join(SUMMARY_DIR, "parity_best.png")
    fig.savefig(out, dpi=150); plt.close(fig)
    print(f"  Parity plot -> {out}")


# =============================================================================
#  Driver
# =============================================================================
if __name__ == "__main__":
    print(f"\n### Multi-damage ablation - STAGE = {STAGE} ###")
    print(f"### DATASET = {DATASET}")
    print(f"### targets: scour {TARGET_SUPPORTS}"
          + (f" + bearing {BEARING_TARGETS}" if BEARING_TARGETS else "")
          + f"   seeds: {SEEDS}   trials/study: {N_TRIALS}\n")
    set_global_seed(SEEDS[0])
    phase_1_single_dof()
    auto_pair = auto_select_pair()
    phase_2_pair(auto_pair)
    for xp in EXTRA_PAIRS:
        xp = sorted(int(d) for d in xp)
        if xp == sorted(auto_pair):
            print(f"[extra-pair] {xp} is already the auto pair - skipped.")
            continue
        phase_2_pair(xp)
    summarize()
    print("\n" + "=" * 64 + f"\n  {STAGE} multi-damage ablation finished.\n" + "=" * 64)
