function assert_resume_case_identity( ...
        run_folder, previous, identity, provenance)
%ASSERT_RESUME_CASE_IDENTITY Reject a folder from any other run contract.
%
% This is the folder-level boundary.  Per-state stamps and payloads are checked
% separately by validate_resume_states, so neither side can authenticate the
% other by accident.

required = { ...
    'gen_schema', 'gen_fingerprint', ...
    'matlab_release', 'campaign_matlab_release', ...
    'release_qualification_run', ...
    'actual_matlab_environment_descriptor', ...
    'actual_matlab_environment_sha256', ...
    'campaign_matlab_environment_descriptor', ...
    'campaign_matlab_environment_sha256', ...
    'generator_source_root_sha256', ...
    'generator_source_digest_lines', ...
    'generator_source_file_count', ...
    'qualification_source_sha256'};
if ~isstruct(previous) || ~isscalar(previous) || ...
        ~all(isfield(previous, required))
    error('A00:ResumeCaseInfoFormat', ...
        ['A00 RESUME ABORTED: folder "%s" has incomplete or foreign ' ...
         'case_info provenance. Use a FRESH folder.'], run_folder);
end

if ~strcmp(previous.gen_schema, identity.gen_schema)
    error('A00:ResumeSchema', ...
        ['A00 RESUME ABORTED: folder "%s" holds generator schema "%s", ' ...
         'but this code is "%s". Move or delete the old folder.'], ...
        run_folder, previous.gen_schema, identity.gen_schema);
end
if ~strcmp(previous.gen_fingerprint, identity.gen_fingerprint)
    error('A00:ResumeFingerprint', ...
        ['A00 RESUME ABORTED: folder "%s" was generated with a DIFFERENT ' ...
         'configuration.\n  existing: %s\n  current : %s\nUse a fresh ' ...
         'folder.'], run_folder, previous.gen_fingerprint, ...
        identity.gen_fingerprint);
end

qualification_is_valid = ...
    isscalar(previous.release_qualification_run) && ...
    islogical(previous.release_qualification_run);
source_count_is_valid = ...
    isscalar(previous.generator_source_file_count) && ...
    isnumeric(previous.generator_source_file_count) && ...
    isfinite(previous.generator_source_file_count);
same_provenance = ...
    strcmp(previous.matlab_release, provenance.matlab_release) && ...
    strcmp(previous.campaign_matlab_release, ...
        provenance.campaign_matlab_release) && ...
    qualification_is_valid && ...
    previous.release_qualification_run == ...
        provenance.release_qualification_run && ...
    strcmp(previous.actual_matlab_environment_descriptor, ...
        provenance.actual_matlab_environment_descriptor) && ...
    strcmp(previous.actual_matlab_environment_sha256, ...
        provenance.actual_matlab_environment_sha256) && ...
    strcmp(previous.campaign_matlab_environment_descriptor, ...
        provenance.campaign_matlab_environment_descriptor) && ...
    strcmp(previous.campaign_matlab_environment_sha256, ...
        provenance.campaign_matlab_environment_sha256) && ...
    strcmp(previous.generator_source_root_sha256, ...
        provenance.generator_source_root_sha256) && ...
    strcmp(previous.generator_source_digest_lines, ...
        provenance.generator_source_digest_lines) && ...
    source_count_is_valid && ...
    previous.generator_source_file_count == ...
        provenance.generator_source_file_count && ...
    strcmp(previous.qualification_source_sha256, ...
        provenance.qualification_source_sha256);
if ~same_provenance
    error('A00:ResumeProvenance', ...
        ['A00 RESUME ABORTED: folder "%s" has a different MATLAB ' ...
         'environment, reviewed source, or run mode. Existing states may ' ...
         'never be restamped; use a FRESH folder.'], run_folder);
end
end
