function case_info = build_case_info( ...
        campaign, state, descriptor, identity, provenance, timestamp)
%BUILD_CASE_INFO Build the persisted machine/human campaign manifest.
%
% Values intended for human inspection are rendered explicitly; the canonical
% run fingerprint remains available separately as generation_config_json.

case_info = struct( ...
    'case_name', descriptor.case_name, ...
    'case_desc', descriptor.case_desc, ...
    'stage', campaign.STAGE, ...
    'gen_schema', identity.gen_schema, ...
    'gen_fingerprint', identity.gen_fingerprint, ...
    'generation_config_json', identity.generation_config_json, ...
    'generation_behavior_version', ...
        identity.generation_behavior_version, ...
    'channel_schema_id', identity.channel_schema_id, ...
    'state_design_kind', identity.state_design_kind, ...
    'matlab_release', provenance.matlab_release, ...
    'campaign_matlab_release', provenance.campaign_matlab_release, ...
    'actual_matlab_environment_descriptor', ...
        provenance.actual_matlab_environment_descriptor, ...
    'actual_matlab_environment_sha256', ...
        provenance.actual_matlab_environment_sha256, ...
    'campaign_matlab_environment_descriptor', ...
        provenance.campaign_matlab_environment_descriptor, ...
    'campaign_matlab_environment_sha256', ...
        provenance.campaign_matlab_environment_sha256, ...
    'generator_source_root_sha256', ...
        provenance.generator_source_root_sha256, ...
    'generator_source_digest_lines', ...
        provenance.generator_source_digest_lines, ...
    'generator_source_file_count', ...
        provenance.generator_source_file_count, ...
    'qualification_source_sha256', ...
        provenance.qualification_source_sha256, ...
    'release_qualification_run', ...
        provenance.release_qualification_run, ...
    'oor_flats_enabled', campaign.oor_flats_enabled, ...
    'timestamp', timestamp, ...
    'damage_mode', campaign.damage_mode, ...
    'L_bridge_m', campaign.L_bridge, ...
    'num_spans', campaign.num_spans, ...
    'num_supports', state.n_supp, ...
    'scour_supports', mat2str(campaign.scour_supports), ...
    'state_identity_version', state.state_identity_version, ...
    'joint_lhs_design', state.joint_lhs_design, ...
    'n_latent_bearing_dims', state.n_latent_bear, ...
    'random_stream_schedule_version', ...
        state.random_stream_schedule_version, ...
    'state_stream_names', strjoin(state.state_stream_names, ','), ...
    'passage_stream_names', strjoin(state.passage_stream_names, ','), ...
    'n_states', state.n_states, ...
    'passages_per_state', campaign.Npass, ...
    'max_parfor_workers', campaign.max_parfor_workers, ...
    'scour_dano_max_frac', campaign.dano_max, ...
    'n_target_healthy', sum(strcmp( ...
        state.StateFamily, 'target_healthy')), ...
    'n_scour_only', sum(strcmp(state.StateFamily, 'scour_only')), ...
    'n_bearing_only', sum(strcmp(state.StateFamily, 'bearing_only')), ...
    'n_nuisance_only', sum(strcmp(state.StateFamily, 'nuisance_only')), ...
    'n_joint', sum(strcmp(state.StateFamily, 'joint')), ...
    'n_anchor_reps', campaign.n_anchor_reps, ...
    'bearing_mode', campaign.bearing_mode, ...
    'bearing_intensity_Nm_rad', campaign.Bearing_Intensity, ...
    'bearing_fixity_max', campaign.bearing_fixity_max, ...
    'bearing_k_ref_Nm_rad', state.k_ref_bear, ...
    'bearing_label', 'fixity_ratio', ...
    'use_crack_eov', campaign.use_crack_eov, ...
    'crack_draw', campaign.crack_draw, ...
    'crack_p', campaign.crack_p, ...
    'crack_hog_ratio', campaign.crack_hog_ratio, ...
    'crack_hog_margin', campaign.crack_hog_margin, ...
    'crack_frac_range', mat2str(campaign.crack_frac_range), ...
    'crack_int_range', mat2str(campaign.crack_int_range), ...
    'crack_lc', campaign.crack_lc, ...
    'profile_mode', campaign.profile_mode, ...
    'profile_draw', campaign.profile_draw, ...
    'profile_jitter_sd_mm', campaign.profile_jitter_sd_mm, ...
    'profile_int_range', mat2str(campaign.profile_int_range), ...
    'profile_fra_classes', mat2str(campaign.profile_fra_classes), ...
    'profile_fixed_phase_seed', campaign.profile_fixed_phase_seed, ...
    'profile_spectrum_contract', campaign.profile_spectrum_contract, ...
    'rail_end_clearance_m', campaign.rail_end_clearance_m, ...
    'rail_end_clearance_decision_id', ...
        campaign.rail_end_clearance_decision_id, ...
    'use_track_eov', campaign.use_track_eov, ...
    'track_draw', campaign.track_draw, ...
    'track_L_app', campaign.track_L_app, ...
    'track_L_after', campaign.track_L_after, ...
    'ballast_rate_100m', campaign.ballast_rate_100m, ...
    'ballast_patch_len', mat2str(campaign.ballast_patch_len), ...
    'ballast_trans_mult', campaign.ballast_trans_mult, ...
    'ballast_trans_margin', campaign.ballast_trans_margin, ...
    'hang_rate_100m', campaign.hang_rate_100m, ...
    'hang_group_size', mat2str(campaign.hang_group_size), ...
    'hang_foul_mult', campaign.hang_foul_mult, ...
    'pad_p_fail', campaign.pad_p_fail, ...
    'pad_failure_rule', campaign.pad_failure_rule, ...
    'use_oor_eov', campaign.use_oor_eov, ...
    'oor_q_bogie', campaign.oor_q_bogie, ...
    'oor_p_trailing', campaign.oor_p_trailing, ...
    'oor_p_fresh', campaign.oor_p_fresh, ...
    'oor_len_fresh', mat2str(campaign.oor_len_fresh), ...
    'oor_len_runin', mat2str(campaign.oor_len_runin), ...
    'oor_radius', campaign.oor_radius, ...
    'poly_p_wheel', campaign.poly_p_wheel, ...
    'poly_orders', mat2str(campaign.poly_orders), ...
    'poly_amp_lnorm', mat2str(campaign.poly_amp_lnorm), ...
    'use_signal_noise', campaign.use_signal_noise, ...
    'noise_std', campaign.Desvio, ...
    'use_vehicle_variability', campaign.use_vehicle_variability, ...
    'use_speed_variability', campaign.use_speed_variability, ...
    'use_temp_variability', campaign.use_temp_variability, ...
    'n_vehicles', campaign.Nveh, ...
    'n_props_varied', campaign.Nprop, ...
    'temp_min_C', campaign.temp_min, ...
    'temp_max_C', campaign.temp_max, ...
    'vel_min_kmh', campaign.vel_min, ...
    'vel_max_kmh', campaign.vel_max);
if isfield(campaign, 'ballast_dry_stiffness_arm')
    case_info.ballast_dry_stiffness_arm = ...
        ttbi.dry_ballast_stiffness_arm(campaign);
    case_info.analysis_scope = 'dry-ballast-stiffness-sign-sensitivity';
end
end
