function identity = build_generation_identity(campaign, state, provenance)
%BUILD_GENERATION_IDENTITY Canonicalize every run-defining configuration value.
%
% Field order is explicit and stable because the JSON bytes themselves are
% persisted and hashed.  Any scientific knob, semantic-state row, RNG identity,
% reviewed source byte, or campaign environment change must move the
% fingerprint and prevent mixed-folder resume.

gen_schema = 'audit-2026-08-09-r12';
generation_behavior_version = 'generation-rules-v8';
channel_schema_id = 'physical8_v1';

config = struct( ...
    'schema', gen_schema, ...
    'generation_behavior_version', generation_behavior_version, ...
    'channel_schema_id', channel_schema_id, ...
    'campaign_matlab_release', provenance.campaign_matlab_release, ...
    'campaign_matlab_environment_sha256', ...
        provenance.campaign_matlab_environment_sha256, ...
    'generator_source_root_sha256', ...
        provenance.generator_source_root_sha256, ...
    'qualification_source_sha256', ...
        provenance.qualification_source_sha256, ...
    'STAGE', campaign.STAGE, ...
    'damage_mode', campaign.damage_mode, ...
    'L_bridge', campaign.L_bridge, ...
    'num_spans', campaign.num_spans, ...
    'scour_supports', campaign.scour_supports, ...
    'n_states', state.n_states, ...
    'Npass', campaign.Npass, ...
    'state_design_kind', state.state_design_kind, ...
    'state_identity_version', state.state_identity_version, ...
    'joint_lhs_design', state.joint_lhs_design, ...
    'n_latent_bearing_dims', state.n_latent_bear, ...
    'random_stream_schedule_version', ...
        state.random_stream_schedule_version, ...
    'state_stream_names', {state.state_stream_names}, ...
    'passage_stream_names', {state.passage_stream_names}, ...
    'max_parfor_workers', campaign.max_parfor_workers, ...
    'dano_max', campaign.dano_max, ...
    'include_anchors', campaign.include_anchors, ...
    'n_anchor_levels', campaign.n_anchor_levels, ...
    'damage_seed', campaign.damage_seed, ...
    'n_healthy_states', campaign.n_healthy_states, ...
    'n_anchor_reps', campaign.n_anchor_reps, ...
    'n_nuisance_states', campaign.n_nuisance_states, ...
    'bearing_mode', campaign.bearing_mode, ...
    'Bearing_Intensity', campaign.Bearing_Intensity, ...
    'bearing_fixity_max', campaign.bearing_fixity_max, ...
    'use_crack_eov', campaign.use_crack_eov, ...
    'crack_draw', campaign.crack_draw, ...
    'crack_p', campaign.crack_p, ...
    'crack_hog_ratio', campaign.crack_hog_ratio, ...
    'crack_hog_margin', campaign.crack_hog_margin, ...
    'crack_frac_range', campaign.crack_frac_range, ...
    'crack_int_range', campaign.crack_int_range, ...
    'crack_lc', campaign.crack_lc, ...
    'profile_mode', campaign.profile_mode, ...
    'profile_draw', campaign.profile_draw, ...
    'profile_jitter_sd_mm', campaign.profile_jitter_sd_mm, ...
    'profile_int_range', campaign.profile_int_range, ...
    'profile_fra_classes', campaign.profile_fra_classes, ...
    'profile_fixed_phase_seed', campaign.profile_fixed_phase_seed, ...
    'profile_spectrum_contract', campaign.profile_spectrum_contract, ...
    'rail_end_clearance_m', campaign.rail_end_clearance_m, ...
    'rail_end_clearance_decision_id', ...
        campaign.rail_end_clearance_decision_id, ...
    'use_track_eov', campaign.use_track_eov, ...
    'track_draw', campaign.track_draw, ...
    'track_L_app', campaign.track_L_app, ...
    'track_L_after', campaign.track_L_after, ...
    'hang_rate_100m', campaign.hang_rate_100m, ...
    'hang_group_size', campaign.hang_group_size, ...
    'hang_p_transition', campaign.hang_p_transition, ...
    'hang_trans_margin', campaign.hang_trans_margin, ...
    'hang_foul_mult', campaign.hang_foul_mult, ...
    'ballast_rate_100m', campaign.ballast_rate_100m, ...
    'ballast_patch_len', campaign.ballast_patch_len, ...
    'ballast_trans_mult', campaign.ballast_trans_mult, ...
    'ballast_trans_margin', campaign.ballast_trans_margin, ...
    'ballast_p_wet', campaign.ballast_p_wet, ...
    'ballast_eta_k_dry', campaign.ballast_eta_k_dry, ...
    'ballast_eta_c_dry', campaign.ballast_eta_c_dry, ...
    'ballast_eta_k_wet', campaign.ballast_eta_k_wet, ...
    'ballast_eta_c_wet', campaign.ballast_eta_c_wet, ...
    'pad_p_fail', campaign.pad_p_fail, ...
    'pad_failure_rule', campaign.pad_failure_rule, ...
    'pad_chi_range', campaign.pad_chi_range, ...
    'pad_weibull', campaign.pad_weibull, ...
    'pad_beta_range', campaign.pad_beta_range, ...
    'use_oor_eov', campaign.use_oor_eov, ...
    'oor_flats_enabled', campaign.oor_flats_enabled, ...
    'oor_q_bogie', campaign.oor_q_bogie, ...
    'oor_p_trailing', campaign.oor_p_trailing, ...
    'oor_p_fresh', campaign.oor_p_fresh, ...
    'oor_len_fresh', campaign.oor_len_fresh, ...
    'oor_len_runin', campaign.oor_len_runin, ...
    'oor_radius', campaign.oor_radius, ...
    'poly_p_wheel', campaign.poly_p_wheel, ...
    'poly_orders', campaign.poly_orders, ...
    'poly_amp_lnorm', campaign.poly_amp_lnorm, ...
    'poly_amp_bounds', campaign.poly_amp_bounds, ...
    'use_signal_noise', campaign.use_signal_noise, ...
    'Desvio', campaign.Desvio, ...
    'use_vehicle_variability', campaign.use_vehicle_variability, ...
    'use_speed_variability', campaign.use_speed_variability, ...
    'use_temp_variability', campaign.use_temp_variability, ...
    'Nveh', campaign.Nveh, ...
    'Nprop', campaign.Nprop, ...
    'temp_min', campaign.temp_min, ...
    'temp_max', campaign.temp_max, ...
    'vel_min', campaign.vel_min, ...
    'vel_max', campaign.vel_max);

% Sensitivity metadata is opt-in.  Omitting it from an ordinary campaign keeps
% the default configuration JSON contract unchanged; when present, the arm is
% fingerprinted so retained and reciprocal outputs can never share a resume
% identity.
if isfield(campaign, 'ballast_dry_stiffness_arm')
    config.ballast_dry_stiffness_arm = ...
        ttbi.dry_ballast_stiffness_arm(campaign);
end

% The realized state matrices and named streams are part of the contract, not
% merely values that can be regenerated from nominal seeds.
config.DamageStates = state.DamageStates;
config.BearingStates = state.BearingStates;
config.BearingFixity = state.BearingFixity;
config.StateFamily = state.StateFamily;
config.AnchorTarget = state.AnchorTarget;
config.AnchorLevel = state.AnchorLevel;
config.StateUID = state.StateUID;
config.StateSeedID = state.StateSeedID;
config.StateNamedStreamSeedID = state.StateNamedStreamSeedID;
config.PassageNamedStreamSeedIDFlat = ...
    state.PassageNamedStreamSeedIDFlat;
config.LatentBearingFixity = state.LatentBearingFixity;
config.LatentCrackOn = state.LatentCrackOn;
config.CrackOn = state.CrackOn;

generation_config_json = jsonencode(config);
identity = struct( ...
    'gen_schema', gen_schema, ...
    'generation_behavior_version', generation_behavior_version, ...
    'channel_schema_id', channel_schema_id, ...
    'state_design_kind', state.state_design_kind, ...
    'generation_config_json', generation_config_json, ...
    'gen_fingerprint', ttbi.sha256(generation_config_json));
end
