function attestation = build_generator_source_attestation(provenance)
%BUILD_GENERATOR_SOURCE_ATTESTATION Authenticate live bytes against the run.

required = { ...
    'gen_schema'; 'gen_fingerprint'; ...
    'generator_source_root_sha256'; ...
    'generator_source_digest_lines'; ...
    'generator_source_file_count'};
if ~isstruct(provenance) || ~isscalar(provenance) || ...
        ~all(isfield(provenance, required))
    error('ttbi:SourceAttestationProvenance', ...
        'Source attestation requires the complete run provenance.');
end

[source_root, source_lines, source_count] = generator_source_root();
if ~strcmp(source_root, provenance.generator_source_root_sha256) || ...
        ~strcmp(source_lines, provenance.generator_source_digest_lines) || ...
        source_count ~= provenance.generator_source_file_count
    error('A00:GeneratorSourceChangedDuringRun', ...
        ['Reviewed generator bytes or resolution changed during execution. ' ...
         'Refusing to continue; start a fresh run.']);
end

attestation = struct( ...
    'schema', 'ttbi-generator-worker-source-v1', ...
    'gen_schema', provenance.gen_schema, ...
    'gen_fingerprint', provenance.gen_fingerprint, ...
    'generator_source_root_sha256', source_root, ...
    'generator_source_digest_lines', source_lines, ...
    'generator_source_file_count', source_count);
end
