function context = build_execution_context(campaign, state_design, runtime)
%BUILD_EXECUTION_CONTEXT Select immutable inputs for the per-state worker.
%
% CAMPAIGN owns reviewed scientific knobs, STATE_DESIGN owns the immutable
% semantic-state/RNG catalogue, and RUNTIME owns output/provenance values that
% become known only after the run folder and fingerprint are prepared. This
% function deliberately selects fields one by one so accidental additions to
% either source struct are not silently broadcast into PARFOR workers.

context = struct();
context.n_states = state_design.n_states;
context.Npass = campaign.Npass;
context.dano_max = campaign.dano_max;
context.run_folder = runtime.run_folder;
context.run_folder_observation = runtime.run_folder_observation;
ttbi.assert_generation_output_directory( ...
    context.run_folder, context.run_folder_observation);
context.noise_std = campaign.Desvio;
context.use_signal_noise = campaign.use_signal_noise;

context.model = struct( ...
    'L_bridge', campaign.L_bridge, ...
    'num_spans', campaign.num_spans);

context.state = struct();
context.state.DamageStates = state_design.DamageStates;
context.state.BearingStates = state_design.BearingStates;
context.state.BearingFixity = state_design.BearingFixity;
context.state.k_ref_bear = state_design.k_ref_bear;
context.state.scour_supports = campaign.scour_supports;
context.state.StateFamily = state_design.StateFamily;
context.state.AnchorTarget = state_design.AnchorTarget;
context.state.AnchorLevel = state_design.AnchorLevel;
context.state.StateUID = state_design.StateUID;
context.state.StateSeedID = state_design.StateSeedID;
context.state.StateNamedStreamSeedID = ...
    state_design.StateNamedStreamSeedID;
context.state.PassageNamedStreamSeedID = ...
    state_design.PassageNamedStreamSeedID;
context.state.PassageNamedStreamSeedIDFlat = ...
    state_design.PassageNamedStreamSeedIDFlat;
context.state.random_stream_schedule_version = ...
    state_design.random_stream_schedule_version;
context.state.state_stream_names = state_design.state_stream_names;
context.state.passage_stream_names = state_design.passage_stream_names;
context.state.LatentBearingFixity = state_design.LatentBearingFixity;
context.state.LatentCrackOn = state_design.LatentCrackOn;
context.state.CrackOn = state_design.CrackOn;

context.operations = struct( ...
    'Npass', campaign.Npass, ...
    'Nveh', campaign.Nveh, ...
    'Nprop', campaign.Nprop, ...
    'use_vehicle_variability', campaign.use_vehicle_variability, ...
    'use_speed_variability', campaign.use_speed_variability, ...
    'use_temp_variability', campaign.use_temp_variability, ...
    'vel_min', campaign.vel_min, ...
    'vel_max', campaign.vel_max, ...
    'temp_min', campaign.temp_min, ...
    'temp_max', campaign.temp_max);

context.crack = struct( ...
    'use_crack_eov', campaign.use_crack_eov, ...
    'crack_draw', campaign.crack_draw, ...
    'crack_p', campaign.crack_p, ...
    'crack_hog_ratio', campaign.crack_hog_ratio, ...
    'crack_hog_margin', campaign.crack_hog_margin, ...
    'crack_frac_range', campaign.crack_frac_range, ...
    'crack_int_range', campaign.crack_int_range, ...
    'crack_lc', campaign.crack_lc, ...
    'L_bridge', campaign.L_bridge, ...
    'num_spans', campaign.num_spans);

context.profile = struct( ...
    'profile_mode', campaign.profile_mode, ...
    'profile_draw', campaign.profile_draw, ...
    'profile_spectrum_contract', campaign.profile_spectrum_contract, ...
    'profile_fra_classes', campaign.profile_fra_classes, ...
    'profile_fixed_phase_seed', campaign.profile_fixed_phase_seed, ...
    'rail_end_clearance_m', campaign.rail_end_clearance_m, ...
    'rail_end_clearance_decision_id', ...
        campaign.rail_end_clearance_decision_id, ...
    'profile_jitter_sd_mm', campaign.profile_jitter_sd_mm, ...
    'profile_int_range', campaign.profile_int_range);

context.track = struct( ...
    'use_track_eov', campaign.use_track_eov, ...
    'track_draw', campaign.track_draw, ...
    'track_L_app', campaign.track_L_app, ...
    'track_L_after', campaign.track_L_after, ...
    'L_bridge', campaign.L_bridge, ...
    'ballast_rate_100m', campaign.ballast_rate_100m, ...
    'ballast_patch_len', campaign.ballast_patch_len, ...
    'ballast_trans_mult', campaign.ballast_trans_mult, ...
    'ballast_trans_margin', campaign.ballast_trans_margin, ...
    'ballast_p_wet', campaign.ballast_p_wet, ...
    'ballast_eta_k_dry', campaign.ballast_eta_k_dry, ...
    'ballast_eta_c_dry', campaign.ballast_eta_c_dry, ...
    'ballast_eta_k_wet', campaign.ballast_eta_k_wet, ...
    'ballast_eta_c_wet', campaign.ballast_eta_c_wet, ...
    'hang_rate_100m', campaign.hang_rate_100m, ...
    'hang_group_size', campaign.hang_group_size, ...
    'hang_p_transition', campaign.hang_p_transition, ...
    'hang_trans_margin', campaign.hang_trans_margin, ...
    'hang_foul_mult', campaign.hang_foul_mult, ...
    'pad_weibull', campaign.pad_weibull, ...
    'pad_chi_range', campaign.pad_chi_range, ...
    'pad_beta_range', campaign.pad_beta_range, ...
    'pad_p_fail', campaign.pad_p_fail, ...
    'pad_failure_rule', campaign.pad_failure_rule);
if isfield(campaign, 'ballast_dry_stiffness_arm')
    context.track.ballast_dry_stiffness_arm = ...
        ttbi.dry_ballast_stiffness_arm(campaign);
end

context.oor = struct( ...
    'use_oor_eov', campaign.use_oor_eov, ...
    'Nveh', campaign.Nveh, ...
    'oor_flats_enabled', campaign.oor_flats_enabled, ...
    'oor_q_bogie', campaign.oor_q_bogie, ...
    'oor_p_trailing', campaign.oor_p_trailing, ...
    'oor_p_fresh', campaign.oor_p_fresh, ...
    'oor_len_fresh', campaign.oor_len_fresh, ...
    'oor_len_runin', campaign.oor_len_runin, ...
    'oor_radius', campaign.oor_radius, ...
    'poly_p_wheel', campaign.poly_p_wheel, ...
    'poly_orders', campaign.poly_orders, ...
    'poly_amp_lnorm', campaign.poly_amp_lnorm, ...
    'poly_amp_bounds', campaign.poly_amp_bounds);

context.contact = runtime.contact;
context.provenance = runtime.provenance;
derived_identity = ttbi.build_generation_identity( ...
    campaign, state_design, runtime.provenance);
if ~strcmp(derived_identity.gen_schema, runtime.provenance.gen_schema) || ...
        ~strcmp(derived_identity.gen_fingerprint, ...
            runtime.provenance.gen_fingerprint)
    error('ttbi:ExecutionIdentity', ...
        'Runtime provenance differs from the recomputed generation identity.');
end
context.identity = struct( ...
    'gen_schema', derived_identity.gen_schema, ...
    'generation_behavior_version', ...
        derived_identity.generation_behavior_version, ...
    'channel_schema_id', derived_identity.channel_schema_id, ...
    'state_design_kind', derived_identity.state_design_kind, ...
    'generation_config_json', derived_identity.generation_config_json, ...
    'gen_fingerprint', derived_identity.gen_fingerprint);
if ~isequal(context.identity, derived_identity)
    error('ttbi:ExecutionIdentityProjection', ...
        'Worker identity projection is incomplete or reordered.');
end
end
