function execute_generation_state(state_index, context, worker_attestation)
%EXECUTE_GENERATION_STATE Simulate and publish one semantic damage state.
%
% This is the only per-state worker entry point used by A00_Run. Its inputs
% are explicit, grouped by responsibility in CONTEXT, and immutable for the
% duration of a state. Nuisance draws live in separate package functions so a
% reviewer can inspect each random mechanism without navigating the driver.

% Defense in depth: the runner consumes the Constant before this call, and the
% executor independently requires the same proof before touching solver state.
ttbi.require_generation_worker_attestation( ...
    worker_attestation, context.provenance);
ttbi.assert_generation_output_directory( ...
    context.run_folder, context.run_folder_observation);

state = context.state;
model = context.model;
provenance = context.provenance;
Npass = context.Npass;

Damage = struct();
Damage.desvio = context.noise_std * context.use_signal_noise;
data = struct();
data2save = struct();

scour_vector = state.DamageStates(state_index, :);
bearing_vector = state.BearingStates(state_index, :);
bearing_fixity = state.BearingFixity(state_index, :);
Damage.scour_rates = scour_vector;
Damage.bearing_left = bearing_vector(1);
Damage.bearing_right = bearing_vector(2);

crack_log = zeros(Npass, 3);
profile_log = ones(Npass, 1);
track_log = cell(Npass, 1);
oor_log = cell(Npass, 1);
% [bridge_tension_flag, track_tension_flag, positive_path_fraction,
%  signed_max_reaction_N]. Compression is negative; only positive reactions
% are the bilateral-contact tensile artifact controlled by the gate.
contact_log = zeros(Npass, 4);

state_fra_class = context.profile.profile_fra_classes(1);
track_state = struct();
beam_f1 = NaN;

operations = ttbi.sample_state_operations( ...
    context.operations, state.StateNamedStreamSeedID(state_index, 1));
speed_mps = operations.speed_mps;
temperature_C = operations.temperature_C;
vehicle_properties = operations.vehicle_properties;

for passage_index = 1:Npass
    Train = A01_Train( ...
        speed_mps(passage_index), vehicle_properties(:, :, passage_index));
    Track = A02_Track();
    Beam_seed = struct();
    Beam_seed.Prop.L = model.L_bridge;
    Beam_seed.Prop.num_spans = model.num_spans;
    Beam = A03_Bridge(Beam_seed);

    % Temperature-dependent deck modulus used by the established generator.
    Beam.Prop.E = Beam.Prop.E - Beam.Prop.E * 0.003 * ...
        (temperature_C(passage_index) - 15);

    [Damage, crack_log(passage_index, :)] = ttbi.sample_crack_damage( ...
        Damage, context.crack, ...
        state.StateNamedStreamSeedID(state_index, 2), ...
        state.CrackOn(state_index), passage_index);

    [profile_config, profile_log(passage_index), state_fra_class] = ...
        ttbi.build_profile_config( ...
            context.profile, state_fra_class, ...
            state.StateNamedStreamSeedID(state_index, 3), ...
            state.StateNamedStreamSeedID(state_index, 5), ...
            state.PassageNamedStreamSeedID(state_index, passage_index, 1), ...
            passage_index);
    if strcmp(context.profile.profile_mode, 'fixed_scaled')
        Damage.profile_intensity = profile_log(passage_index);
    end

    [Damage, track_state, track_log{passage_index}] = ...
        ttbi.sample_track_damage( ...
            Damage, track_state, Track, context.track, ...
            state.StateNamedStreamSeedID(state_index, 4), passage_index);

    [Damage, oor_log{passage_index}] = ttbi.sample_wheel_oor( ...
        Damage, context.oor, ...
        state.PassageNamedStreamSeedID(state_index, passage_index, 2));

    [Calc, Beam, Track] = A04_Options(Beam, Track, profile_config);
    [Sol, Calc, Train, Beam, ~] = B00_Calculations( ...
        Calc, Train, Track, Beam, Damage);
    expected_clearance_m = context.profile.rail_end_clearance_m;
    expected_decision_id = context.profile.rail_end_clearance_decision_id;
    clearance_fields = { ...
        'rail_end_clearance_requested_m', ...
        'rail_end_clearance_realized_m'};
    for clearance_field_index = 1:numel(clearance_fields)
        clearance_field = clearance_fields{clearance_field_index};
        if ~isfield(Calc.Profile,clearance_field) || ...
                Calc.Profile.(clearance_field) ~= expected_clearance_m
            error('ttbi:ProductionRailEndClearanceNotRealized', ...
                ['Production passage did not realize its explicit reviewed ' ...
                 '6 m rail-end clearance (%s).'],clearance_field);
        end
    end
    if ~isfield(Calc.Profile,'rail_end_clearance_decision_id') || ...
            ~strcmp(Calc.Profile.rail_end_clearance_decision_id, ...
                expected_decision_id)
        error('ttbi:ProductionRailEndClearanceDecisionLost', ...
            'Production passage lost its rail-clearance decision identity.');
    end

    % Record and gate the first elastic deck frequency. The broad range
    % applies to every state; healthy targets also use a geometry-specific
    % diagnostic range.
    if passage_index == 1
        if ~isfield(Beam, 'Modal') || ...
                ~isfield(Beam.Modal, 'f') || isempty(Beam.Modal.f)
            error('A00: Beam.Modal.f is missing; deck-frequency attestation failed.');
        end
        beam_f1 = Beam.Modal.f(1);
        if ~isfinite(beam_f1) || beam_f1 < 0.2 || beam_f1 > 15
            error(['A00: implausible deck f1 %.6g Hz at state %d. ' ...
                'Check A03 rho, B43 area and the modal assembly.'], ...
                beam_f1, state_index);
        end
        if strcmp(state.StateFamily{state_index}, 'target_healthy')
            if model.L_bridge < 80
                healthy_f1_bounds = [3, 6];
            else
                healthy_f1_bounds = [2, 4];
            end
            if beam_f1 < healthy_f1_bounds(1) || ...
                    beam_f1 > healthy_f1_bounds(2)
                error(['A00: healthy deck f1 %.6g Hz outside [%g,%g] Hz ' ...
                    'for L=%.3g m. Refusing to authenticate a likely ' ...
                    'mass/stiffness regression.'], beam_f1, ...
                    healthy_f1_bounds(1), healthy_f1_bounds(2), ...
                    model.L_bridge);
            end
        end
        if state_index == 1
            fprintf(['[CHECK] deck f1 = %.2f Hz ' ...
                '(healthy state; sanity gate passed)\n'], beam_f1);
        end
    end

    contact_log(passage_index, :) = [double(Sol.contactLost), ...
        Sol.contactLost_track, Sol.tension_frac_max, Sol.F_tension_max];
    peak_tension = Sol.F_tension_max;
    tension_fraction = Sol.tension_frac_max;
    if ~isfinite(peak_tension) || ~isfinite(tension_fraction) || ...
            peak_tension > context.contact.max_tension_N || ...
            tension_fraction > context.contact.max_tension_fraction
        ttbi.assert_generation_output_directory( ...
            context.run_folder, context.run_folder_observation);
        diagnostic_path = fullfile(context.run_folder, ...
            sprintf('contact_violation_state%04d.txt', state_index));
        diagnostic_file = fopen(diagnostic_path, 'w');
        if diagnostic_file >= 0
            fprintf(diagnostic_file, ...
                ['state %d  passage %d/%d\nscour_vec %s\n' ...
                 'tol_N %g  tol_frac %g\n'], ...
                state_index, passage_index, Npass, ...
                mat2str(scour_vector), context.contact.max_tension_N, ...
                context.contact.max_tension_fraction);
            fprintf(diagnostic_file, ...
                ['F_tension_max_N %g  contactLost_track %g  ' ...
                 'tension_frac_max %g\n'], ...
                peak_tension, Sol.contactLost_track, tension_fraction);
            fclose(diagnostic_file);
        end
        ttbi.assert_generation_output_directory( ...
            context.run_folder, context.run_folder_observation);
        error(['A00 ABORT (contact): state %d passage %d exceeds the ' ...
            'two-tier contact gate (tension %.4g N vs tol %g N; path ' ...
            'fraction %.3g vs tol %g; non-finite also fatal). This is ' ...
            'outside the prospectively source-locked bilateral-model ' ...
            'admissibility ' ...
            'envelope; investigate the solver/time step without raising ' ...
            'the threshold. See contact_violation_state%04d.txt'], ...
            state_index, passage_index, peak_tension, ...
            context.contact.max_tension_N, tension_fraction, ...
            context.contact.max_tension_fraction, state_index);
    end

    data = D01_DataProcessing( ...
        1, passage_index, Sol, Train, Calc, Damage, data);
    fprintf('--- State %d/%d: scour=[%s], Pass %d/%d ---\n', ...
        state_index, context.n_states, ...
        num2str(scour_vector, '%.2f '), passage_index, Npass);
end

% RAW time-domain channels and exact space/crop reconstruction metadata.
data2save.AcelPrimVag = data.AceleracaoPrimVag;
data2save.AcelRodaPrimVag = data.AcelRodaPrimVag;
data2save.PitchPrimVag = data.PitchPrimVag;
% Channel schema `physical8_v1` (2026-08-06): AcelWheelsetPrimVag carries the
% idealized constrained-wheelset acceleration; AcelRodaPrimVag remains the
% Eulerian rail-field diagnostic under its legacy name. The authoritative
% schema is the run's fingerprinted case_info value; every state repeats it so
% readers can reject a missing, foreign, or mixed payload before loading signals.
data2save.AcelWheelsetPrimVag = data.AcelWheelsetPrimVag;
data2save.channel_schema_id = context.identity.channel_schema_id;
data2save.DimAcel = data.DimAcel;
data2save.DimSpace = data.DimSpace;
data2save.crop_start = data.crop_start;
data2save.crop_end = data.crop_end;
data2save.bridge_samp = data.bridge_samp;
data2save.L_bridge_eff = data.L_bridge_eff;

% Scientific targets and semantic state identity.
data2save.scour_vector = scour_vector;
data2save.scour_supports = state.scour_supports;
data2save.Dano = max(scour_vector);
data2save.state_family = state.StateFamily{state_index};
data2save.state_uid = state.StateUID{state_index};
data2save.state_seed_id = state.StateSeedID(state_index);
data2save.random_stream_schedule_version = ...
    state.random_stream_schedule_version;
data2save.state_named_stream_seed_id = ...
    state.StateNamedStreamSeedID(state_index, :);
data2save.passage_named_stream_seed_id = reshape( ...
    state.PassageNamedStreamSeedID(state_index, :, :), ...
    Npass, numel(state.passage_stream_names));
data2save.latent_bearing_fixity = ...
    state.LatentBearingFixity(state_index, :);
data2save.latent_crack_on = state.LatentCrackOn(state_index);
data2save.crack_on = state.CrackOn(state_index);
data2save.beam_f1_Hz = beam_f1;
data2save.bearing_vector = bearing_vector;
data2save.bearing_fixity = bearing_fixity;

% Nuisance-EOV and numerical-admissibility traceability.
data2save.crack_log = crack_log;
data2save.profile_mode = context.profile.profile_mode;
data2save.profile_log = profile_log;
data2save.track_log = track_log;
data2save.oor_log = oor_log;
data2save.contact_log = contact_log;

% Source, configuration, environment, and qualification provenance.
data2save.gen_schema = provenance.gen_schema;
data2save.gen_fingerprint = provenance.gen_fingerprint;
data2save.matlab_release = provenance.matlab_release;
data2save.campaign_matlab_release = ...
    provenance.campaign_matlab_release;
data2save.actual_matlab_environment_descriptor = ...
    provenance.actual_matlab_environment_descriptor;
data2save.actual_matlab_environment_sha256 = ...
    provenance.actual_matlab_environment_sha256;
data2save.campaign_matlab_environment_descriptor = ...
    provenance.campaign_matlab_environment_descriptor;
data2save.campaign_matlab_environment_sha256 = ...
    provenance.campaign_matlab_environment_sha256;
data2save.generator_source_root_sha256 = ...
    provenance.generator_source_root_sha256;
data2save.generator_source_digest_lines = ...
    provenance.generator_source_digest_lines;
data2save.generator_source_file_count = ...
    provenance.generator_source_file_count;
data2save.qualification_source_sha256 = ...
    provenance.qualification_source_sha256;
data2save.release_qualification_run = ...
    provenance.release_qualification_run;

grey_tier = (contact_log(:,4) > 0) & ...
    (contact_log(:,4) <= context.contact.max_tension_N);
if any(grey_tier)
    fprintf(['[NOTE] state %d: %d/%d passages in the bounded tensile-' ...
        'artifact tier (0 < F <= %g N, frac <= %g; worst F %.4g N).\n'], ...
        state_index, sum(grey_tier), Npass, ...
        context.contact.max_tension_N, ...
        context.contact.max_tension_fraction, max(contact_log(:,4)));
end

data2save.Temperatura = temperature_C;
data2save.Velocidade = speed_mps;
data2save.VehiclesProps = vehicle_properties;

% Fresh computation and resumed computation share one complete contract. This
% prevents a newly generated but malformed state from being atomically stamped
% and only failing much later on another machine.
candidate_name = sprintf('%04d.mat (fresh payload)', state_index);
ttbi.validate_resumed_state_payload( ...
    data2save, state_index, candidate_name, context);

save_progress(data2save, state_index, context.run_folder, ...
    provenance.gen_schema, provenance.gen_fingerprint, ...
    provenance.matlab_release, provenance.campaign_matlab_release, ...
    provenance.release_qualification_run, ...
    provenance.actual_matlab_environment_sha256, ...
    provenance.campaign_matlab_environment_sha256, ...
    provenance.generator_source_root_sha256, ...
    provenance.qualification_source_sha256, ...
    context.run_folder_observation);
end
