function expected = expected_state_metadata(state_index, context)
%EXPECTED_STATE_METADATA Reproduce all inexpensive named-stream metadata.
%
% This deliberately replays only nuisance/EOV samplers, never the expensive
% vehicle-bridge solver. The caller can therefore authenticate saved logs and
% operational variables exactly during resume and publication.

old_rng = rng;
restore_rng = onCleanup(@() rng(old_rng));

state = context.state;
Npass = context.Npass;
operations = ttbi.sample_state_operations( ...
    context.operations, state.StateNamedStreamSeedID(state_index, 1));

Damage = struct();
track_state = struct();
state_fra_class = context.profile.profile_fra_classes(1);
crack_log = zeros(Npass, 3);
profile_log = ones(Npass, 1);
track_log = cell(Npass, 1);
oor_log = cell(Npass, 1);
for passage_index = 1:Npass
    Track = A02_Track();
    [Damage, crack_log(passage_index, :)] = ttbi.sample_crack_damage( ...
        Damage, context.crack, ...
        state.StateNamedStreamSeedID(state_index, 2), ...
        state.CrackOn(state_index), passage_index);
    [~, profile_log(passage_index), state_fra_class] = ...
        ttbi.build_profile_config( ...
            context.profile, state_fra_class, ...
            state.StateNamedStreamSeedID(state_index, 3), ...
            state.StateNamedStreamSeedID(state_index, 5), ...
            state.PassageNamedStreamSeedID(state_index, passage_index, 1), ...
            passage_index);
    [Damage, track_state, track_log{passage_index}] = ...
        ttbi.sample_track_damage( ...
            Damage, track_state, Track, context.track, ...
            state.StateNamedStreamSeedID(state_index, 4), passage_index);
    [Damage, oor_log{passage_index}] = ttbi.sample_wheel_oor( ...
        Damage, context.oor, ...
        state.PassageNamedStreamSeedID(state_index, passage_index, 2));
end

expected = struct( ...
    'Dano', max(state.DamageStates(state_index, :)), ...
    'Temperatura', operations.temperature_C, ...
    'Velocidade', operations.speed_mps, ...
    'VehiclesProps', operations.vehicle_properties, ...
    'crack_log', crack_log, ...
    'profile_mode', context.profile.profile_mode, ...
    'profile_log', profile_log, ...
    'track_log', {track_log}, ...
    'oor_log', {oor_log});

clear restore_rng
end
