function f25_execute_generation_state(state_index, context, worker_attestation)
%F25_EXECUTE_GENERATION_STATE Run and atomically save one F25 damage class.
%
% This is an isolated consumer of the same A01..D01 coupled solver used by
% A00_Run.  F25 damage, operational draws, stored Type-2 profile, and output
% window are supplied by the F25 contract and never enter the main campaign.

if nargin < 3
    worker_attestation = [];
end
if ~isstruct(context) || ~isscalar(context) || ...
        ~isfield(context, 'config') || ~isfield(context, 'state') || ...
        ~isfield(context, 'provenance') || ~isfield(context, 'identity') || ...
        ~isfield(context, 'run_folder') || ...
        ~isfield(context, 'run_folder_observation')
    error('ttbi:f25_execute_generation_state:Context', ...
        'F25 execution requires one complete immutable context.');
end
if isempty(getCurrentTask())
    % Solver/capacity smokes run without a process pool.  Re-hash the complete
    % reviewed source boundary instead of pretending to hold a worker proof.
    ttbi.build_generator_source_attestation(context.provenance);
else
    ttbi.require_generation_worker_attestation( ...
        worker_attestation, context.provenance);
end
ttbi.assert_generation_output_directory( ...
    context.run_folder, context.run_folder_observation);

config = context.config;
state = context.state;
provenance = context.provenance;
identity = context.identity;
validateattributes(state_index, {'numeric'}, ...
    {'real','finite','scalar','integer','>=',1,'<=',state.n_states}, ...
    mfilename, 'state_index');

final_path = fullfile(context.run_folder, sprintf('%04d.mat', state_index));
if isfile(final_path)
    error('ttbi:f25_execute_generation_state:Collision', ...
        'F25 state already exists; resume must classify it first: %s', ...
        final_path);
end

operations = ttbi.f25_sample_operations( ...
    config, state.StateNamedStreamSeedID(state_index, 1));
fixed_damage = ttbi.f25_damage_for_state(state, state_index);
fixed_damage.desvio = 0;
fixed_damage.track = [];

data = struct();
contact_log = zeros(config.Npass, 4);
beam_f1_Hz = NaN;
for passage_index = 1:config.Npass
    Train = A01_Train(operations.speed_mps(passage_index), ...
        operations.a01_vehicle_inputs(:,:,passage_index));
    local_verify_vehicle_mapping(Train, operations, passage_index, config);

    Track = A02_Track();
    Beam = A03_Bridge(struct('Prop', struct( ...
        'L', config.L_bridge, 'num_spans', config.num_spans)));
    Beam.Prop.E = Beam.Prop.E - Beam.Prop.E*0.003* ...
        (operations.temperature_C(passage_index)-15);
    Damage = fixed_damage;
    [Calc, Beam, Track] = A04_Options( ...
        Beam, Track, config.profile_config);
    [Sol, Calc, Train, Beam, ~] = B00_Calculations( ...
        Calc, Train, Track, Beam, Damage);

    if passage_index == 1
        if ~isfield(Beam, 'Modal') || ~isfield(Beam.Modal, 'f') || ...
                isempty(Beam.Modal.f)
            error('ttbi:f25_execute_generation_state:Frequency', ...
                'The coupled solve did not expose Beam.Modal.f.');
        end
        beam_f1_Hz = Beam.Modal.f(1);
        if ~isfinite(beam_f1_Hz) || beam_f1_Hz < 0.2 || beam_f1_Hz > 15
            error('ttbi:f25_execute_generation_state:Frequency', ...
                'F25 deck f1 %.6g Hz is outside the solver sanity range.', ...
                beam_f1_Hz);
        end
        if state_index == 1 && (beam_f1_Hz < 3 || beam_f1_Hz > 6)
            error('ttbi:f25_execute_generation_state:HealthyFrequency', ...
                'Healthy F25 deck f1 %.6g Hz is outside [3,6] Hz.', ...
                beam_f1_Hz);
        end
    end

    contact_log(passage_index,:) = [double(Sol.contactLost), ...
        Sol.contactLost_track, Sol.tension_frac_max, Sol.F_tension_max];
    if any(~isfinite(contact_log(passage_index,:))) || ...
            Sol.F_tension_max > config.contact_max_tension_N || ...
            Sol.tension_frac_max > config.contact_max_tension_fraction
        error('ttbi:f25_execute_generation_state:ContactGate', ...
            ['F25 state %d passage %d violates the registered bilateral ' ...
             'contact envelope (F=%.6g N, fraction=%.6g).'], ...
            state_index, passage_index, Sol.F_tension_max, ...
            Sol.tension_frac_max);
    end
    data = D01_DataProcessing( ...
        1, passage_index, Sol, Train, Calc, Damage, data);
    fprintf('[F25] class %d/%d passage %d/%d\n', ...
        state_index, state.n_states, passage_index, config.Npass);
end

monitoring = ttbi.f25_extract_monitoring_signals(data, config);
f25_data = struct();
f25_data.schema = 'f25-saved-state-v1';
f25_data.generation_schema = identity.gen_schema;
f25_data.gen_fingerprint = identity.gen_fingerprint;
f25_data.python_contract_sha256 = identity.python_contract_sha256;
f25_data.shared_data_contract_id = config.shared_data_contract_id;
f25_data.dataset_id = config.dataset_id;
f25_data.channel_schema_id = identity.channel_schema_id;
f25_data.class_index_zero_based = ...
    state.class_index_zero_based(state_index);
f25_data.scenario_label = state.scenario_labels{state_index};
f25_data.axis_names = state.axis_names;
f25_data.axis_codes = state.axis_codes(state_index,:);
f25_data.state_uid = state.StateUID{state_index};
f25_data.state_seed_id = state.StateSeedID(state_index);
f25_data.random_stream_schedule_version = ...
    state.random_stream_schedule_version;
f25_data.state_named_stream_seed_id = ...
    state.StateNamedStreamSeedID(state_index,:);
f25_data.passage_named_stream_seed_id = reshape( ...
    state.PassageNamedStreamSeedID(state_index,:,:), ...
    config.Npass, numel(state.passage_stream_names));
f25_data.scour_vector = state.DamageStates(state_index,:);
f25_data.bearing_vector_Nm_per_rad = state.BearingStates(state_index,:);
f25_data.crack_active = state.CrackOn(state_index);
f25_data.crack_location_m = state.CrackLocation(state_index);
f25_data.crack_ei_loss = state.CrackIntensity(state_index);
f25_data.crack_half_length_m = state.CrackHalfLength(state_index);
f25_data.clean_trimmed = monitoring.clean_trimmed;
f25_data.monitoring_tail_sample = monitoring.monitoring_tail_sample;
f25_data.monitoring_window_schema = monitoring.schema;
f25_data.source_window_samples = monitoring.source_window_samples;
f25_data.trimmed_window_samples = monitoring.trimmed_window_samples;
f25_data.tail_samples_trimmed = monitoring.tail_samples_trimmed;
f25_data.crop_start_one_based = monitoring.crop_start_one_based;
f25_data.crop_end_untrimmed_one_based = ...
    monitoring.crop_end_untrimmed_one_based;
f25_data.crop_end_trimmed_one_based = ...
    monitoring.crop_end_trimmed_one_based;
f25_data.samples_per_m = monitoring.samples_per_m;
f25_data.measurement_noise_applied = false;
f25_data.load_time_measurement_noise_fraction = ...
    config.load_time_measurement_noise_fraction;
f25_data.noise_master_seed = config.noise_master_seed;
f25_data.partition_seed = config.partition_seed;
f25_data.operations_schema = operations.schema;
f25_data.operations_seed_id = operations.seed_id;
f25_data.speed_km_h = operations.speed_km_h;
f25_data.temperature_C = operations.temperature_C;
f25_data.body_mass_kg = operations.body_mass_kg;
f25_data.primary_suspension_N_per_m = ...
    operations.primary_suspension_N_per_m;
f25_data.secondary_suspension_N_per_m = ...
    operations.secondary_suspension_N_per_m;
f25_data.contact_log = contact_log;
f25_data.beam_f1_Hz = beam_f1_Hz;
f25_data.profile_asset_sha256 = config.profile_asset_sha256;
f25_data.matlab_environment_sha256 = ...
    provenance.actual_matlab_environment_sha256;
f25_data.generator_source_root_sha256 = ...
    provenance.generator_source_root_sha256;
f25_data.release_qualification_run = false;

local_validate_payload(f25_data, config, state, state_index, identity);
file_f25_schema = f25_data.schema;
file_gen_fingerprint = identity.gen_fingerprint;
file_python_contract_sha256 = identity.python_contract_sha256;
file_state_uid = f25_data.state_uid;
file_state_seed_id = f25_data.state_seed_id;
file_clean_trimmed_shape = uint32(size(f25_data.clean_trimmed));
tmp_path = fullfile(context.run_folder, ...
    sprintf('.%04d.mat.tmp', state_index));
if isfile(tmp_path)
    error('ttbi:f25_execute_generation_state:TemporaryCollision', ...
        'Stale F25 temporary state exists: %s', tmp_path);
end
ttbi.assert_generation_output_directory( ...
    context.run_folder, context.run_folder_observation);
save(tmp_path, 'f25_data', 'file_f25_schema', ...
    'file_gen_fingerprint', 'file_python_contract_sha256', ...
    'file_state_uid', 'file_state_seed_id', ...
    'file_clean_trimmed_shape', '-v7');
ttbi.assert_generation_output_directory( ...
    context.run_folder, context.run_folder_observation);
if isfile(final_path)
    error('ttbi:f25_execute_generation_state:Collision', ...
        'Another worker published the same F25 state: %s', final_path);
end
[moved, message] = movefile(tmp_path, final_path);
if ~moved
    error('ttbi:f25_execute_generation_state:AtomicMove', ...
        'Could not publish F25 state %d: %s', state_index, message);
end
ttbi.assert_generation_output_directory( ...
    context.run_folder, context.run_folder_observation);
end

function local_verify_vehicle_mapping(Train, operations, passage_index, config)
for vehicle_index = 1:config.Nveh
    expected = [ ...
        operations.body_mass_kg(vehicle_index,1,passage_index), ...
        operations.primary_suspension_N_per_m(vehicle_index,1,passage_index), ...
        operations.secondary_suspension_N_per_m(vehicle_index,1,passage_index)];
    observed = [Train.Veh(vehicle_index).Body.m, ...
        Train.Veh(vehicle_index).Susp.Prim.k(1), ...
        Train.Veh(vehicle_index).Susp.Sec.k(1)];
    if any(abs(observed-expected) > 64*eps(max(abs(expected),1)))
        error('ttbi:f25_execute_generation_state:VehicleMap', ...
            'A01 vehicle %d does not reproduce the F25 physical draw.', ...
            vehicle_index);
    end
end
end

function local_validate_payload(data, config, state, state_index, identity)
expected_shape = [config.Npass, 8, config.trimmed_window_samples];
if ~strcmp(data.schema, 'f25-saved-state-v1') || ...
        ~strcmp(data.gen_fingerprint, identity.gen_fingerprint) || ...
        ~strcmp(data.python_contract_sha256, ...
            config.python_contract_sha256) || ...
        ~strcmp(data.channel_schema_id, 'physical8_v1') || ...
        ~strcmp(data.state_uid, state.StateUID{state_index}) || ...
        ~isequal(data.state_seed_id, state.StateSeedID(state_index)) || ...
        ~isequal(size(data.clean_trimmed), expected_shape) || ...
        ~isequal(size(data.monitoring_tail_sample), [config.Npass 8]) || ...
        any(~isfinite(data.clean_trimmed), 'all') || ...
        any(~isfinite(data.monitoring_tail_sample), 'all') || ...
        data.source_window_samples ~= 5831 || ...
        data.trimmed_window_samples ~= 5830 || ...
        data.tail_samples_trimmed ~= 1 || ...
        data.measurement_noise_applied ~= false || ...
        ~isequal(size(data.contact_log), [config.Npass 4])
    error('ttbi:f25_execute_generation_state:Payload', ...
        'F25 state %d failed its pre-publication payload contract.', ...
        state_index);
end
end
