function catalog = f25_scenario_catalog()
%F25_SCENARIO_CATALOG Exact Fernandes (2025) ten-class damage catalogue.
%
% The publication labels its undamaged row ``Healthy`` (not DC1).  Crack
% percentages in Table 2 are crack-depth ratios, not EI-loss percentages.  The
% source reports their equivalent 30 cm element stiffness losses as 22 and
% 14 percent; those are the values consumed by this repository's uniform-EI
% damaged-block surrogate.  The 0.30 m source element 100 occupies
% [29.70, 30.00] m and is represented by two 0.15 m elements here.

labels = {'Healthy'; 'DC2'; 'DC3'; 'DC4'; 'DC5'; ...
    'DC6'; 'DC7'; 'DC8'; 'DC9'; 'DC10'};
descriptions = { ...
    'No damage condition'; ...
    'Crack at 10 percent depth ratio'; ...
    'Central-support scour at 5 percent'; ...
    'Entrance bearing damage only'; ...
    'Central-support scour at 10 percent plus entrance bearing damage'; ...
    'Crack at 10 percent depth ratio plus central-support scour at 10 percent'; ...
    'Crack at 10 percent depth ratio plus entrance bearing damage'; ...
    ['Crack at 10 percent depth ratio plus central-support scour at ' ...
     '10 percent plus entrance bearing damage']; ...
    ['Crack at 10 percent depth ratio plus central-support scour at ' ...
     '5 percent plus entrance bearing damage']; ...
    ['Crack at 5 percent depth ratio plus central-support scour at ' ...
     '5 percent plus entrance bearing damage']};

% Source class axes.  The crack-depth ratio is retained for traceability;
% crack_ei_loss is the executable damaged-block value.
crack_depth_ratio = [0; .10; 0; 0; 0; .10; .10; .10; .10; .05];
crack_ei_loss = [0; .22; 0; 0; 0; .22; .22; .22; .22; .14];
central_scour_loss = [0; 0; .05; 0; .10; .10; 0; .10; .05; .05];
entrance_bearing_stiffness = ...
    [0; 0; 0; 1e9; 1e9; 0; 1e9; 1e9; 1e9; 1e9];

n_scenarios = numel(labels);
scour_vectors = zeros(n_scenarios, 3);
scour_vectors(:, 2) = central_scour_loss;
bearing_vectors = zeros(n_scenarios, 2);
bearing_vectors(:, 1) = entrance_bearing_stiffness;
crack_active = crack_ei_loss > 0;
crack_zone_m = nan(n_scenarios, 2);
crack_zone_m(crack_active, :) = repmat([29.70 30.00], ...
    sum(crack_active), 1);

% Axis codes reproduce the paper's three-way decomposition.  They are not a
% scalar severity ordering: the ten classes form a partial product space.
axis_codes = [round(100*crack_depth_ratio), ...
    round(100*central_scour_loss), ...
    double(entrance_bearing_stiffness > 0)];

if n_scenarios ~= 10 || numel(unique(labels)) ~= 10 || ...
        ~isequal(size(scour_vectors), [10 3]) || ...
        ~isequal(size(bearing_vectors), [10 2]) || ...
        ~isequal(size(axis_codes), [10 3])
    error('ttbi:f25_scenario_catalog:Shape', ...
        'The Fernandes scenario catalogue must contain ten unique classes.');
end
if any(scour_vectors(:, [1 3]) ~= 0, 'all') || ...
        any(bearing_vectors(:, 2) ~= 0) || ...
        any(~ismember(crack_ei_loss, [0 .14 .22]))
    error('ttbi:f25_scenario_catalog:Physics', ...
        'The source-backed damage-axis catalogue drifted.');
end

catalog = struct();
catalog.schema = 'f25-scenario-catalog-v1';
catalog.labels = labels;
catalog.descriptions = descriptions;
catalog.class_index_zero_based = (0:n_scenarios-1)';
catalog.crack_depth_ratio = crack_depth_ratio;
catalog.crack_ei_loss = crack_ei_loss;
catalog.central_scour_loss = central_scour_loss;
catalog.entrance_bearing_stiffness_Nm_per_rad = ...
    entrance_bearing_stiffness;
catalog.scour_vectors = scour_vectors;
catalog.bearing_vectors_Nm_per_rad = bearing_vectors;
catalog.crack_active = crack_active;
catalog.crack_zone_m = crack_zone_m;
catalog.crack_block_centre_m = 29.85;
catalog.crack_block_half_length_m = 0.15;
catalog.axis_names = {'crack_depth_percent', ...
    'central_scour_percent', 'entrance_bearing_present'};
catalog.axis_codes = axis_codes;
catalog.passages_per_scenario = 200;
catalog.n_scenarios = n_scenarios;
end
