function binding = f25_bundle_source_binding( ...
        repository_root, generator_root_sha256, generator_digest_lines, ...
        generator_file_count, config)
%F25_BUNDLE_SOURCE_BINDING Authenticate the paired F25 source bundle in place.
%
% The external ZIP digests remain the operator trust anchors.  This check
% prevents an extracted workspace from silently mixing bundle manifests,
% reviewed source bytes, the fixed Fernandes profile, or generated plans.

if ~isstruct(config) || ~isscalar(config) || ...
        ~strcmp(config.schema, 'f25-experiment-config-v1') || ...
        ~local_hex(generator_root_sha256, 64) || ...
        ~ischar(generator_digest_lines) || ~isrow(generator_digest_lines) || ...
        ~isnumeric(generator_file_count) || ~isscalar(generator_file_count) || ...
        ~isfinite(generator_file_count) || generator_file_count < 1 || ...
        generator_file_count ~= floor(generator_file_count)
    error('ttbi:f25_bundle_source_binding:Inputs', ...
        'F25 bundle binding requires reviewed source/config identities.');
end

[reviewed_root, entries] = ttbi.reviewed_source_entries();
if ~strcmp(ttbi.canonical_execution_path(reviewed_root), ...
        ttbi.canonical_execution_path(repository_root))
    error('ttbi:f25_bundle_source_binding:RepositoryRoot', ...
        'F25 source manifest resolves outside the supplied repository root.');
end
source_manifest_path = fullfile(reviewed_root, 'bundle_source_files.txt');
source_manifest_sha256 = ttbi.stable_file_sha256(source_manifest_path);

experiments = {'F25-R','F25-X'};
manifests = cell(2,1);
manifest_file_sha256 = cell(2,1);
for experiment_index = 1:2
    experiment = experiments{experiment_index};
    manifest_name = sprintf('f25_bundle_manifest.%s.json', experiment);
    manifest_path = fullfile(reviewed_root, manifest_name);
    [manifest, manifest_file_sha256{experiment_index}] = ...
        local_stable_json(manifest_path, experiment);
    expected_fields = sort({ ...
        'schema'; 'experiment_id'; 'bundle_name'; 'source_commit'; ...
        'source_manifest_sha256'; 'source_file_count'; 'source_files'; ...
        'source_root_sha256'; 'f25_contract_sha256'; ...
        'training_plan_sha256'; 'generated_artifacts'; ...
        'shared_generation_root'; 'artifact_roots'; ...
        'bundle_manifest_sha256'});
    expected_config = ttbi.f25_experiment_config(experiment);
    expected_shared_root = [expected_config.generation_results_root '/' ...
        expected_config.dataset_id];
    if ~isstruct(manifest) || ~isscalar(manifest) || ...
            ~isequal(sort(fieldnames(manifest)), expected_fields) || ...
            ~strcmp(manifest.schema, 'f25-dispatch-bundle-v2') || ...
            ~strcmp(manifest.experiment_id, experiment) || ...
            ~strcmp(manifest.bundle_name, ...
                sprintf('bundle_%s.zip', experiment)) || ...
            ~local_hex(manifest.source_commit, 40) || ...
            ~strcmp(manifest.source_manifest_sha256, ...
                source_manifest_sha256) || ...
            ~isequal(double(manifest.source_file_count), ...
                double(numel(entries))) || ...
            ~local_hex(manifest.source_root_sha256, 64) || ...
            ~strcmp(manifest.f25_contract_sha256, ...
                config.python_contract_sha256) || ...
            ~local_hex(manifest.training_plan_sha256, 64) || ...
            ~local_hex(manifest.bundle_manifest_sha256, 64) || ...
            ~strcmp(manifest.shared_generation_root, expected_shared_root)
        error('ttbi:f25_bundle_source_binding:Manifest', ...
            '%s bundle manifest header/identity is stale.', experiment);
    end

    rows = manifest.source_files;
    if ~isstruct(rows) || numel(rows) ~= numel(entries)
        error('ttbi:f25_bundle_source_binding:SourceInventory', ...
            '%s source inventory has the wrong size.', experiment);
    end
    generator_lines = cell(0,1);
    profile_found = false;
    for source_index = 1:numel(entries)
        row = rows(source_index);
        if ~isequal(sort(fieldnames(row)), {'path';'sha256'}) || ...
                ~ischar(row.path) || ~isrow(row.path) || ...
                ~strcmp(row.path, entries{source_index}) || ...
                ~local_hex(row.sha256, 64)
            error('ttbi:f25_bundle_source_binding:SourceRow', ...
                '%s source row %d is malformed.', ...
                experiment, source_index);
        end
        native_parts = strsplit(row.path, '/');
        source_path = fullfile(reviewed_root, native_parts{:});
        if ~strcmp(ttbi.stable_file_sha256(source_path), row.sha256)
            error('ttbi:f25_bundle_source_binding:SourceBytes', ...
                '%s source bytes differ from the bundle: %s', ...
                experiment, row.path);
        end
        if startsWith(row.path, 'scour_MATLAB/')
            generator_lines{end+1,1} = sprintf( ... %#ok<AGROW>
                '%s:%s', row.path, row.sha256);
        end
        if strcmp(row.path, 'scour_MATLAB/Calc.ProfileData15_05.mat')
            profile_found = strcmp(row.sha256, config.profile_asset_sha256);
        end
    end
    manifest_generator_lines = strjoin(generator_lines, newline);
    if ~strcmp(manifest_generator_lines, generator_digest_lines) || ...
            numel(generator_lines) ~= generator_file_count || ...
            ~strcmp(ttbi.sha256(manifest_generator_lines), ...
                generator_root_sha256) || ~profile_found
        error('ttbi:f25_bundle_source_binding:GeneratorIdentity', ...
            '%s does not bind the live MATLAB generator/profile.', experiment);
    end

    local_validate_generated_artifacts( ...
        manifest.generated_artifacts, reviewed_root, experiment);
    roots = manifest.artifact_roots;
    if ~isstruct(roots) || ~isscalar(roots) || ...
            ~isequal(sort(fieldnames(roots)), {'cache';'manifest';'results'}) || ...
            ~strcmp(roots.cache, expected_config.cache_root) || ...
            ~strcmp(roots.manifest, expected_config.training_manifest_root) || ...
            ~strcmp(roots.results, expected_config.training_results_root)
        error('ttbi:f25_bundle_source_binding:ArtifactRoots', ...
            '%s artifact roots differ from the reviewed config.', experiment);
    end
    manifests{experiment_index} = manifest;
end

shared_fields = {'source_commit','source_manifest_sha256', ...
    'source_file_count','source_files','source_root_sha256', ...
    'f25_contract_sha256','shared_generation_root'};
for field_index = 1:numel(shared_fields)
    field = shared_fields{field_index};
    if ~isequaln(manifests{1}.(field), manifests{2}.(field))
        error('ttbi:f25_bundle_source_binding:PairMismatch', ...
            'F25-R/F25-X differ at shared field %s.', field);
    end
end

[confirmed_root, confirmed_lines, confirmed_count] = generator_source_root();
if ~strcmp(confirmed_root, generator_root_sha256) || ...
        ~strcmp(confirmed_lines, generator_digest_lines) || ...
        confirmed_count ~= generator_file_count || ...
        ~strcmp(ttbi.stable_file_sha256(source_manifest_path), ...
            source_manifest_sha256)
    error('ttbi:f25_bundle_source_binding:AuthenticationRace', ...
        'F25 source changed while its paired bundle was authenticated.');
end

binding = struct();
binding.schema = 'f25-bundle-source-binding-v1';
binding.source_commit = manifests{1}.source_commit;
binding.source_manifest_sha256 = source_manifest_sha256;
binding.bundle_source_root_sha256 = manifests{1}.source_root_sha256;
binding.generator_source_root_sha256 = generator_root_sha256;
binding.generator_source_file_count = generator_file_count;
binding.f25_contract_sha256 = config.python_contract_sha256;
binding.profile_asset_sha256 = config.profile_asset_sha256;
binding.f25_r_bundle_manifest_file_sha256 = manifest_file_sha256{1};
binding.f25_x_bundle_manifest_file_sha256 = manifest_file_sha256{2};
binding.descriptor = sprintf([ ...
    'schema=%s\nsource_commit=%s\nsource_manifest_sha256=%s\n' ...
    'bundle_source_root_sha256=%s\n' ...
    'generator_source_root_sha256=%s\n' ...
    'generator_source_file_count=%.0f\nf25_contract_sha256=%s\n' ...
    'profile_asset_sha256=%s\n' ...
    'f25_r_bundle_manifest_file_sha256=%s\n' ...
    'f25_x_bundle_manifest_file_sha256=%s'], ...
    binding.schema, binding.source_commit, ...
    binding.source_manifest_sha256, binding.bundle_source_root_sha256, ...
    binding.generator_source_root_sha256, ...
    binding.generator_source_file_count, binding.f25_contract_sha256, ...
    binding.profile_asset_sha256, ...
    binding.f25_r_bundle_manifest_file_sha256, ...
    binding.f25_x_bundle_manifest_file_sha256);
binding.sha256 = ttbi.sha256(binding.descriptor);
end


function local_validate_generated_artifacts(artifacts, root, experiment)
if ~isstruct(artifacts) || ~isscalar(artifacts) || ...
        ~isequal(sort(fieldnames(artifacts)), ...
            {'operator_readme';'training_plan'})
    error('ttbi:f25_bundle_source_binding:GeneratedArtifacts', ...
        '%s generated artifact inventory is malformed.', experiment);
end
expected = { ...
    'training_plan', sprintf('f25_training_plan.%s.json', experiment); ...
    'operator_readme', sprintf('README_%s.md', experiment)};
for index = 1:size(expected,1)
    row = artifacts.(expected{index,1});
    if ~isstruct(row) || ~isscalar(row) || ...
            ~isequal(sort(fieldnames(row)), {'path';'sha256'}) || ...
            ~strcmp(row.path, expected{index,2}) || ...
            ~local_hex(row.sha256, 64) || ...
            ~strcmp(ttbi.stable_file_sha256( ...
                fullfile(root, row.path)), row.sha256)
        error('ttbi:f25_bundle_source_binding:GeneratedArtifact', ...
            '%s generated artifact %s differs from its bundle.', ...
            experiment, expected{index,1});
    end
end
end


function [value, digest] = local_stable_json(path, label)
if ~ttbi.regular_nonsymlink_file(path)
    error('ttbi:f25_bundle_source_binding:ManifestPath', ...
        '%s bundle manifest is missing or linked.', label);
end
before = ttbi.file_observation(path);
digest = ttbi.stable_file_sha256(path);
try
    value = jsondecode(fileread(path));
catch decode_error
    error('ttbi:f25_bundle_source_binding:ManifestJSON', ...
        '%s bundle manifest is not JSON: %s', label, decode_error.message);
end
after = ttbi.file_observation(path);
if ~isequal(before, after) || ...
        ~strcmp(digest, ttbi.stable_file_sha256(path))
    error('ttbi:f25_bundle_source_binding:ManifestRace', ...
        '%s bundle manifest changed during authentication.', label);
end
end


function yes = local_hex(value, width)
yes = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, sprintf('^[0-9a-f]{%d}$', width), 'once'));
end
