function names = generation_publication_credential_names()
%GENERATION_PUBLICATION_CREDENTIAL_NAMES Complete final/temporary credential set.

names = { ...
    '_GENERATION_COMPLETE'; ...
    'file_digests.mat'; ...
    '._GENERATION_COMPLETE.tmp'; ...
    '.file_digests.mat.tmp'};
end
