function selection = load_generation_bundle_manifest( ...
        repository_root, generator_source_root_sha256, ...
        generator_source_file_count)
%LOAD_GENERATION_BUNDLE_MANIFEST Authenticate the immutable bundle selector.
%
% Production A00 source is identical in every dispatch ZIP.  This helper
% accepts only one of the four exact source-derived generation manifests and
% binds it to paper1_bundle_identity.json plus the live generator source root.
% The external ZIP SHA-256 remains the operator's trust anchor; these checks
% prevent accidental mixing or post-extraction drift inside that verified ZIP.

root = char(string(repository_root));
if isempty(root) || ~isfolder(root) || ...
        ~strcmp(ttbi.canonical_execution_path(root), ...
            ttbi.canonical_execution_path(repository_root))
    error('ttbi:GenerationBundleRoot', ...
        'Generation bundle repository root is unavailable/noncanonical.');
end
if ~local_hex(generator_source_root_sha256, 64) || ...
        ~isnumeric(generator_source_file_count) || ...
        ~isscalar(generator_source_file_count) || ...
        ~isfinite(generator_source_file_count) || ...
        generator_source_file_count < 1 || ...
        generator_source_file_count ~= floor(generator_source_file_count)
    error('ttbi:GenerationBundleSourceIdentity', ...
        'Live generator source identity is malformed.');
end

manifest_path = fullfile(root, 'generation_bundle_manifest.json');
identity_path = fullfile(root, 'paper1_bundle_identity.json');
[manifest, manifest_file_sha256] = local_stable_json( ...
    manifest_path, 'generation bundle manifest');
[identity, ~] = local_stable_json( ...
    identity_path, 'Paper-1 bundle identity');

identity_fields = sort({ ...
    'schema'; 'source_commit'; 'bundle_kind'; 'target'; ...
    'source_manifest_name'; 'source_manifest_sha256'; ...
    'source_manifest_entry_count'; 'reviewed_source_root_sha256'; ...
    'reviewed_source_file_count'; 'generator_source_root_sha256'; ...
    'generator_source_file_count'; 'python_runtime_source_root_sha256'; ...
    'python_runtime_source_file_count'; 'bundle_manifest_name'; ...
    'bundle_manifest_sha256'});
if ~isstruct(identity) || ~isscalar(identity) || ...
        ~isequal(sort(fieldnames(identity)), identity_fields) || ...
        ~strcmp(identity.schema, 'ttbi-paper1-bundle-identity-v1') || ...
        ~strcmp(identity.bundle_kind, 'generation') || ...
        ~strcmp(identity.source_manifest_name, 'bundle_source_files.txt') || ...
        ~strcmp(identity.bundle_manifest_name, ...
            'generation_bundle_manifest.json') || ...
        ~local_hex(identity.source_commit, 40) || ...
        ~local_hex(identity.source_manifest_sha256, 64) || ...
        ~local_hex(identity.reviewed_source_root_sha256, 64) || ...
        ~local_hex(identity.python_runtime_source_root_sha256, 64) || ...
        ~local_hex(identity.bundle_manifest_sha256, 64) || ...
        ~strcmp(identity.generator_source_root_sha256, ...
            generator_source_root_sha256) || ...
        ~isequal(double(identity.generator_source_file_count), ...
            double(generator_source_file_count)) || ...
        ~strcmp(identity.bundle_manifest_sha256, manifest_file_sha256)
    error('ttbi:GenerationBundleIdentity', ...
        ['paper1_bundle_identity.json does not authenticate this generation ' ...
         'manifest and live generator source root.']);
end

manifest_fields = sort({ ...
    'schema'; 'bundle_name'; 'stage'; 'dataset'; 'n_states'; ...
    'passages_per_state'; 'channel_schema_id'; ...
    'campaign_contract_sha256'; 'campaign_contract'; 'manifest_sha256'});
if ~isstruct(manifest) || ~isscalar(manifest) || ...
        ~isequal(sort(fieldnames(manifest)), manifest_fields) || ...
        ~strcmp(manifest.schema, 'paper1-generation-bundle-manifest-v1') || ...
        ~strcmp(manifest.channel_schema_id, 'physical8_v1') || ...
        ~isstruct(manifest.campaign_contract) || ...
        ~isscalar(manifest.campaign_contract)
    error('ttbi:GenerationBundleManifest', ...
        'Generation bundle manifest header/field inventory drifted.');
end

stages = {'F40-S', 'F40-M', 'L99-S', 'L99-M'};
bundle_names = { ...
    'bundle_f40s_generate.zip', 'bundle_f40m_generate.zip', ...
    'bundle_l99s_generate.zip', 'bundle_l99m_generate.zip'};
datasets = { ...
    'F40-S_L40_st305', 'F40-M_L40_st425', ...
    'L99-S_L99.6_st475', 'L99-M_L99.6_st475'};
state_counts = [305 425 475 475];
driver_counts = [ ...
      0   5 60 5  0; ...
    250  50  5 5 50; ...
    250  50  5 5 50; ...
    250  50  5 5 50];
manifest_hashes = { ...
    '84c39121435ba6719e21b2f5683ce8777464a943f29dba6c4597c953674d85b9', ...
    '422cb898416453f36a13a4b1a3ee8cd68fff82499af302b78c09a8aae10ab2d6', ...
    '675c821cd919ec17fb003a211ee325c12ca9b4682fd672ef579c8330044d975c', ...
    '07c9e5aa041484f7f3f53d70a020f96b32a02bb8733bdb407229031e255c301f'};
file_hashes = { ...
    '31306a5364541b7123c5194b48e60968579c5c9f0316f6feab4aa637d46535c6', ...
    '6e62e45538b76bfdbae2952a3b57bccd93ecdc1a3ddd5f7adaf1eb200300cfec', ...
    '0af4e2b0c32a425920bb1b9c25e88f0d8bb90c8961c24efaa9956ece1e3f17a1', ...
    '4ab4e26da562a3d61976dcb90e2da59a4bf47f7ede0cb0ae4bc01845af54002b'};

index = find(strcmp(stages, manifest.stage));
if numel(index) ~= 1
    error('ttbi:GenerationBundleStage', ...
        'Generation bundle manifest selects an unregistered stage.');
end
counts = double(manifest.campaign_contract.sampling.driver_count_tuple(:)');
if ~strcmp(identity.target, stages{index}) || ...
        ~strcmp(manifest.bundle_name, bundle_names{index}) || ...
        ~strcmp(manifest.dataset, datasets{index}) || ...
        ~isequal(double(manifest.n_states), state_counts(index)) || ...
        ~isequal(double(manifest.passages_per_state), 50) || ...
        ~strcmp(manifest.manifest_sha256, manifest_hashes{index}) || ...
        ~strcmp(manifest_file_sha256, file_hashes{index}) || ...
        ~strcmp(manifest.campaign_contract.stage, stages{index}) || ...
        ~strcmp(manifest.campaign_contract.dataset, datasets{index}) || ...
        ~isequal(counts, driver_counts(index, :)) || ...
        ~isequal(double(manifest.campaign_contract.sampling.n_states), ...
            state_counts(index)) || ...
        ~isequal(double( ...
            manifest.campaign_contract.sampling.passages_per_state), 50)
    error('ttbi:GenerationBundlePreset', ...
        ['Generation manifest bytes, stage, dataset, and exact driver count ' ...
         'tuple do not match one registered source-derived preset.']);
end

selection = struct( ...
    'STAGE', stages{index}, ...
    'n_states_multi', counts(1), ...
    'Npass', double(manifest.passages_per_state), ...
    'n_healthy_states', counts(2), ...
    'n_anchor_levels', counts(3), ...
    'n_anchor_reps', counts(4), ...
    'n_nuisance_states', counts(5), ...
    'manifest_file_sha256', manifest_file_sha256, ...
    'source_commit', identity.source_commit);
end


function [value, digest] = local_stable_json(path, label)
before = ttbi.file_observation(path);
digest = ttbi.stable_file_sha256(path);
try
    value = jsondecode(fileread(path));
catch decode_error
    error('ttbi:GenerationBundleJSON', ...
        '%s is unreadable/non-JSON: %s', label, decode_error.message);
end
after = ttbi.file_observation(path);
if ~isequal(before, after) || ...
        ~strcmp(digest, ttbi.stable_file_sha256(path))
    error('ttbi:GenerationBundleJSONRace', ...
        '%s changed while being authenticated.', label);
end
end


function yes = local_hex(value, width)
yes = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, sprintf('^[0-9a-f]{%d}$', width), 'once'));
end
