function preserve_qualification_evidence( ...
        run_folder, qualification, provenance, run_folder_observation)
%PRESERVE_QUALIFICATION_EVIDENCE Copy and attest the executable micro script.
%
% Qualification output is never campaign data.  When this mode is active, the
% exact executing script and a self-attested host receipt are durable members
% of the endpoint inventory.

if ~provenance.release_qualification_run
    return;
end

ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);
evidence_path = fullfile(run_folder, 'qualification_executed.m');
if isfile(evidence_path)
    if ~strcmp(ttbi.file_sha256(evidence_path), ...
            qualification.executed_file_sha256)
        error('A00:QualificationEvidenceCollision', ...
            ['Existing qualification_executed.m is not the exact script ' ...
             'being executed. Use a fresh output folder.']);
    end
else
    ttbi.assert_generation_output_directory( ...
        run_folder, run_folder_observation);
    [copied, copy_message] = copyfile( ...
        qualification.script_path, evidence_path, 'f');
    if ~copied
        error('A00:QualificationEvidenceCopy', ...
            'Could not preserve executing script bytes: %s', copy_message);
    end
end
if ~strcmp(ttbi.file_sha256(evidence_path), ...
        qualification.executed_file_sha256)
    error('A00:QualificationEvidenceCopy', ...
        'qualification_executed.m is not a byte-exact executable copy.');
end

receipt = ttbi.qualification_host_receipt( ...
    provenance.actual_matlab_environment_sha256, ...
    provenance.qualification_source_sha256, ...
    qualification.executed_file_sha256);
ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);
ttbi.write_qualification_host_receipt( ...
    fullfile(run_folder, 'qualification_host_receipt.json'), receipt);
ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);
end
