function [canonical_sha, raw_sha] = qualification_script_identity( ...
        fpath, stamped_sha, stamped_folder, sha_placeholder, folder_placeholder)
%QUALIFICATION_SCRIPT_IDENTITY Canonical and raw SHA-256 of the executed qualification script.
    % Authenticate exact executing bytes while canonicalising only the two
    % generated self-reference tokens used by make_micro_smoke.py.
    fid = fopen(fpath, 'rb');
    if fid < 0
        error('A00:QualificationExecutableMissing', ...
            'Cannot open qualification executable: %s', fpath);
    end
    cleaner = onCleanup(@() fclose(fid));
    bytes = reshape(fread(fid, Inf, '*uint8'), 1, []);
    raw_sha = ttbi.sha256_bytes(bytes);
    canonical = ttbi.replace_unique_bytes(bytes, ...
        reshape(unicode2native(stamped_sha, 'UTF-8'), 1, []), ...
        reshape(unicode2native(sha_placeholder, 'UTF-8'), 1, []), ...
        'full qualification SHA');
    canonical = ttbi.replace_unique_bytes(canonical, ...
        reshape(unicode2native(stamped_folder, 'UTF-8'), 1, []), ...
        reshape(unicode2native(folder_placeholder, 'UTF-8'), 1, []), ...
        'qualification folder token');
    canonical_sha = ttbi.sha256_bytes(canonical);
end
