function receipt = qualification_host_receipt( ...
        actual_environment_sha256, qualification_source_sha256, ...
        qualification_executed_file_sha256)
%QUALIFICATION_HOST_RECEIPT Self-attested host diagnostics for a qualification run.
    % Qualification-only operational provenance. Host identity is intentionally
    % absent from gen_schema/gen_fingerprint: it proves where a micro response
    % was produced without requiring equal CPUs for the scientific campaign.
    declared_host_id_ = strtrim(getenv('TTBI_QUALIFICATION_HOST_ID'));
    if isempty(regexp(declared_host_id_, ...
            '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$', 'once'))
        error('A00:QualificationHostID', ...
            ['Qualification requires TTBI_QUALIFICATION_HOST_ID to be an ' ...
             'explicit stable host label (1-64 ASCII letters/digits/._-). ' ...
             'Use a different label for every independently qualified PC.']);
    end

    hostname_ = strtrim(getenv('COMPUTERNAME'));
    if isempty(hostname_)
        hostname_ = strtrim(getenv('HOSTNAME'));
    end
    if isempty(hostname_)
        try
            address_ = javaMethod('getLocalHost', 'java.net.InetAddress');
            hostname_ = char(address_.getHostName());
        catch
            hostname_ = 'unavailable';
        end
    end
    cpu_identifier_ = strtrim(getenv('PROCESSOR_IDENTIFIER'));
    if isempty(cpu_identifier_)
        cpu_identifier_ = computer('arch');
    end
    computer_arch_ = computer('arch');

    logical_processors_ = str2double(strtrim(getenv('NUMBER_OF_PROCESSORS')));
    if ~isfinite(logical_processors_) || logical_processors_ < 1 || ...
            logical_processors_ ~= round(logical_processors_)
        try
            runtime_ = javaMethod('getRuntime', 'java.lang.Runtime');
            logical_processors_ = double(runtime_.availableProcessors());
        catch
            logical_processors_ = 1;
        end
    end
    try
        matlab_max_threads_ = double(maxNumCompThreads);
    catch
        % Diagnostic only: retain an explicit, conservative available value if
        % this MATLAB release removes the legacy query.
        matlab_max_threads_ = logical_processors_;
    end
    if ~isfinite(matlab_max_threads_) || matlab_max_threads_ < 1 || ...
            matlab_max_threads_ ~= round(matlab_max_threads_)
        error('A00:QualificationThreadDiagnostic', ...
            'MATLAB thread diagnostic must be one positive integer.');
    end

    hostname_ = ttbi.qualification_host_text(hostname_, 'hostname');
    cpu_identifier_ = ttbi.qualification_host_text( ...
        cpu_identifier_, 'cpu_identifier');
    computer_arch_ = ttbi.qualification_host_text( ...
        computer_arch_, 'computer_arch');
    descriptor_ = strjoin({ ...
        'schema=ttbi-matlab-qualification-host-v1', ...
        ['declared_host_id=' declared_host_id_], ...
        ['hostname=' hostname_], ...
        ['cpu_identifier=' cpu_identifier_], ...
        sprintf('logical_processors=%d', logical_processors_), ...
        sprintf('matlab_max_threads=%d', matlab_max_threads_), ...
        ['computer_arch=' computer_arch_], ...
        ['actual_matlab_environment_sha256=' actual_environment_sha256], ...
        ['qualification_source_sha256=' qualification_source_sha256], ...
        ['qualification_executed_file_sha256=' ...
            qualification_executed_file_sha256]}, newline);
    receipt = struct( ...
        'schema', 'ttbi-matlab-qualification-host-v1', ...
        'declared_host_id', declared_host_id_, ...
        'hostname', hostname_, ...
        'cpu_identifier', cpu_identifier_, ...
        'logical_processors', logical_processors_, ...
        'matlab_max_threads', matlab_max_threads_, ...
        'computer_arch', computer_arch_, ...
        'actual_matlab_environment_sha256', actual_environment_sha256, ...
        'qualification_source_sha256', qualification_source_sha256, ...
        'qualification_executed_file_sha256', ...
            qualification_executed_file_sha256, ...
        'canonical_descriptor', descriptor_, ...
        'host_diagnostic_sha256', ttbi.sha256(descriptor_));
end
