function require_generation_worker_attestation(attestation, provenance)
%REQUIRE_GENERATION_WORKER_ATTESTATION Validate the cached worker proof cheaply.
%
% File hashing occurs once in the Constant constructor. Each state iteration
% still accesses and validates this immutable struct before entering the solver.

expected_fields = sort({ ...
    'schema'; 'gen_schema'; 'gen_fingerprint'; ...
    'generator_source_root_sha256'; ...
    'generator_source_digest_lines'; ...
    'generator_source_file_count'; ...
    'worker_context_authenticated'});
if isempty(getCurrentTask())
    error('ttbi:WorkerAttestationUseContext', ...
        'Worker source attestation can be consumed only inside a pool task.');
end
if ~isstruct(attestation) || ~isscalar(attestation) || ...
        ~isequal(sort(fieldnames(attestation)), expected_fields)
    error('ttbi:WorkerAttestationShape', ...
        'Generation worker returned a malformed source attestation.');
end

line_count = sum(attestation.generator_source_digest_lines == newline) + 1;
matches = ...
    strcmp(attestation.schema, 'ttbi-generator-worker-source-v1') && ...
    isequal(attestation.worker_context_authenticated, true) && ...
    strcmp(attestation.gen_schema, provenance.gen_schema) && ...
    strcmp(attestation.gen_fingerprint, provenance.gen_fingerprint) && ...
    strcmp(attestation.generator_source_root_sha256, ...
        provenance.generator_source_root_sha256) && ...
    strcmp(attestation.generator_source_digest_lines, ...
        provenance.generator_source_digest_lines) && ...
    isequal(attestation.generator_source_file_count, ...
        provenance.generator_source_file_count) && ...
    strcmp(ttbi.sha256(attestation.generator_source_digest_lines), ...
        attestation.generator_source_root_sha256) && ...
    line_count == attestation.generator_source_file_count;
if ~matches
    error('ttbi:WorkerAttestationMismatch', ...
        'Generation worker source attestation differs from run provenance.');
end
end
