function fields = state_file_fields()
%STATE_FILE_FIELDS Exact top-level variable inventory of one state MAT file.
%
% Keeping this contract in one small function prevents the writer, resume
% validator, and mutation tests from maintaining subtly different lists.

fields = { ...
    'data'; ...
    'file_actual_matlab_environment_sha256'; ...
    'file_campaign_matlab_environment_sha256'; ...
    'file_campaign_matlab_release'; ...
    'file_gen_fingerprint'; ...
    'file_gen_schema'; ...
    'file_generator_source_root_sha256'; ...
    'file_matlab_release'; ...
    'file_qualification_source_sha256'; ...
    'file_random_stream_schedule_version'; ...
    'file_release_qualification_run'; ...
    'file_state_seed_id'; ...
    'file_state_uid'};
end
