function fields = state_payload_fields()
%STATE_PAYLOAD_FIELDS Exact scientific/provenance fields of DATA in each state.
%
% The inventory is intentionally closed. An unexpected field is as suspicious
% as a missing field because it can indicate a mixed generator version.

fields = { ...
    'AcelPrimVag'; ...
    'AcelRodaPrimVag'; ...
    'AcelWheelsetPrimVag'; ...
    'Dano'; ...
    'DimAcel'; ...
    'DimSpace'; ...
    'L_bridge_eff'; ...
    'PitchPrimVag'; ...
    'Temperatura'; ...
    'VehiclesProps'; ...
    'Velocidade'; ...
    'actual_matlab_environment_descriptor'; ...
    'actual_matlab_environment_sha256'; ...
    'beam_f1_Hz'; ...
    'bearing_fixity'; ...
    'bearing_vector'; ...
    'bridge_samp'; ...
    'campaign_matlab_environment_descriptor'; ...
    'campaign_matlab_environment_sha256'; ...
    'campaign_matlab_release'; ...
    'channel_schema_id'; ...
    'contact_log'; ...
    'crack_log'; ...
    'crack_on'; ...
    'crop_end'; ...
    'crop_start'; ...
    'gen_fingerprint'; ...
    'gen_schema'; ...
    'generator_source_digest_lines'; ...
    'generator_source_file_count'; ...
    'generator_source_root_sha256'; ...
    'latent_bearing_fixity'; ...
    'latent_crack_on'; ...
    'matlab_release'; ...
    'oor_log'; ...
    'passage_named_stream_seed_id'; ...
    'profile_log'; ...
    'profile_mode'; ...
    'qualification_source_sha256'; ...
    'random_stream_schedule_version'; ...
    'release_qualification_run'; ...
    'scour_supports'; ...
    'scour_vector'; ...
    'state_family'; ...
    'state_named_stream_seed_id'; ...
    'state_seed_id'; ...
    'state_uid'; ...
    'track_log'};
end
