function arms = track_model_form_arms()
%TRACK_MODEL_FORM_ARMS Predeclared Paper-1 parameter-level sensitivities.

arms = struct( ...
    'id', { ...
        'baseline-hybrid-v1', ...
        'consistent-one-seat-v1', ...
        'consistent-two-rail-v1', ...
        'spacing-consistent-0p600-v1', ...
        'rail-damping-0p050pct-v1', ...
        'rail-damping-0p200pct-v1'}, ...
    'family', { ...
        'baseline', ...
        'rail-seat-scaling', ...
        'rail-seat-scaling', ...
        'spacing-transfer', ...
        'rail-damping', ...
        'rail-damping'}, ...
    'description', { ...
        ['Inherited hybrid: two rails and a full sleeper, with the ' ...
         'remaining Zhai properties retained at one rail seat.'], ...
        'Consistent one-rail-seat convention for every tabulated quantity.', ...
        'Consistent two-rail convention for every tabulated quantity.', ...
        ['Inherited scaling convention with Mb, Kb, and Kf recomputed at ' ...
         '0.600 m using Zhai''s equations.'], ...
        'Inherited baseline with a 0.050 percent rail Rayleigh target.', ...
        'Inherited baseline with a 0.200 percent rail Rayleigh target.'}, ...
    'production_candidate', {true,false,false,false,false,false});
end
