function completed = validate_resume_states(run_folder, context)
%VALIDATE_RESUME_STATES Authenticate every existing numbered state file.
%
% A numbered file is complete only when its exact top-level inventory, cheap
% stamps, and full payload all match the immutable execution context. Numeric
% aliases and out-of-range files abort through INSPECT_NUMBERED_STATE_INVENTORY
% instead of being silently skipped or overwritten.

state = context.state;
provenance = context.provenance;
n_states = context.n_states;
completed = false(n_states, 1);
ttbi.assert_generation_output_directory( ...
    run_folder, context.run_folder_observation);
state_paths = ttbi.inspect_numbered_state_inventory(run_folder, n_states);

expected_variables = sort(ttbi.state_file_fields());
stamp_fields = setdiff(expected_variables, {'data'}, 'stable');
for state_index = 1:n_states
    state_path = state_paths{state_index};
    if isempty(state_path)
        continue;
    end
    [~, file_stem, file_extension] = fileparts(state_path);
    file_name = [file_stem file_extension];

    variable_info = whos('-file', state_path);
    variable_names = sort({variable_info.name}');
    if ~isequal(variable_names, expected_variables)
        missing = setdiff(expected_variables, variable_names);
        unexpected = setdiff(variable_names, expected_variables);
        error('ttbi:ResumeFileFields', ...
            ['A00 RESUME ABORTED: state %d file "%s" has a noncanonical ' ...
             'top-level inventory (missing={%s}; unexpected={%s}).'], ...
            state_index, file_name, strjoin(missing, ', '), ...
            strjoin(unexpected, ', '));
    end

    stamps = load(state_path, stamp_fields{:});
    stamps_match = ...
        isequal(stamps.file_gen_schema, provenance.gen_schema) && ...
        isequal(stamps.file_gen_fingerprint, ...
            provenance.gen_fingerprint) && ...
        isequal(stamps.file_state_uid, state.StateUID{state_index}) && ...
        isequal(stamps.file_state_seed_id, ...
            state.StateSeedID(state_index)) && ...
        isequal(stamps.file_random_stream_schedule_version, ...
            state.random_stream_schedule_version) && ...
        isequal(stamps.file_matlab_release, provenance.matlab_release) && ...
        isequal(stamps.file_campaign_matlab_release, ...
            provenance.campaign_matlab_release) && ...
        isequal(stamps.file_release_qualification_run, ...
            provenance.release_qualification_run) && ...
        isequal(stamps.file_actual_matlab_environment_sha256, ...
            provenance.actual_matlab_environment_sha256) && ...
        isequal(stamps.file_campaign_matlab_environment_sha256, ...
            provenance.campaign_matlab_environment_sha256) && ...
        isequal(stamps.file_generator_source_root_sha256, ...
            provenance.generator_source_root_sha256) && ...
        isequal(stamps.file_qualification_source_sha256, ...
            provenance.qualification_source_sha256);
    if ~stamps_match
        error('ttbi:ResumeFileStamps', ...
            ['A00 RESUME ABORTED: state %d file "%s" has a DIFFERENT ' ...
             'schema/fingerprint/release/mode/identity than this run. ' ...
             'Use a FRESH folder.'], state_index, file_name);
    end

    loaded = load(state_path, 'data');
    ttbi.assert_generation_output_directory( ...
        run_folder, context.run_folder_observation);
    ttbi.validate_resumed_state_payload( ...
        loaded.data, state_index, file_name, context);
    completed(state_index) = true;
end

if any(completed)
    fprintf(['Resume: %d/%d states already complete and ' ...
        'provenance/semantics-validated.\n'], sum(completed), n_states);
end
ttbi.assert_generation_output_directory( ...
    run_folder, context.run_folder_observation);
end
