function validate_state_raw_metadata(data, state_index, file_name, context)
%VALIDATE_STATE_RAW_METADATA Enforce the exact registered RAW crop contract.

Npass = context.Npass;
integer_fields = { ...
    'DimAcel', 'DimSpace', 'crop_start', 'crop_end', 'bridge_samp'};
for field_index = 1:numel(integer_fields)
    field_name = integer_fields{field_index};
    value = data.(field_name);
    if ~isnumeric(value) || ~isreal(value) || issparse(value) || ...
            ~isequal(size(value), [1, Npass]) || ...
            ~all(isfinite(value)) || any(value ~= round(value)) || ...
            any(value <= 0)
        error('ttbi:ResumePayloadRawField', ...
            ['A00 RESUME ABORTED: state %d file "%s" RAW field %s must ' ...
             'be one finite, positive, integer-valued 1x%d numeric row.'], ...
            state_index, file_name, field_name, Npass);
    end
end
if ~isnumeric(data.L_bridge_eff) || ~isreal(data.L_bridge_eff) || ...
        issparse(data.L_bridge_eff) || ...
        ~isequal(size(data.L_bridge_eff), [1, Npass]) || ...
        ~all(isfinite(data.L_bridge_eff)) || any(data.L_bridge_eff <= 0)
    error('ttbi:ResumePayloadBridgeLength', ...
        ['A00 RESUME ABORTED: state %d file "%s" L_bridge_eff is not a ' ...
         'finite positive 1x%d numeric row.'], ...
        state_index, file_name, Npass);
end

expected_length = repmat(context.model.L_bridge, 1, Npass);
expected_bridge_samples = repmat(round(100 * context.model.L_bridge), ...
    1, Npass);
expected_crop_start = repmat(1001, 1, Npass);
expected_crop_end = min(expected_crop_start - 1 + ...
    expected_bridge_samples + 1831, data.DimSpace);
expected_dim_space = round(data.Velocidade .* data.DimAcel / 10);
crop_length = data.crop_end - data.crop_start + 1;

if ~isequal(data.L_bridge_eff, expected_length) || ...
        ~isequal(data.bridge_samp, expected_bridge_samples) || ...
        ~isequal(data.crop_start, expected_crop_start) || ...
        ~isequal(data.crop_end, expected_crop_end) || ...
        ~isequal(data.DimSpace, expected_dim_space) || ...
        any(data.DimAcel < 2) || ...
        any(data.crop_start > data.crop_end) || ...
        any(data.crop_end > data.DimSpace) || ...
        any(crop_length < data.bridge_samp)
    error('ttbi:ResumePayloadRawContract', ...
        ['A00 RESUME ABORTED: state %d file "%s" does not reproduce the ' ...
         'registered RAW geometry/crop equations.'], ...
        state_index, file_name);
end
end
