function validate_state_provenance(data, state_index, file_name, context)
%VALIDATE_STATE_PROVENANCE Match all internal provenance to this execution.

provenance = context.provenance;
matches = ...
    isequal(data.gen_schema, provenance.gen_schema) && ...
    isequal(data.gen_fingerprint, provenance.gen_fingerprint) && ...
    isequal(data.channel_schema_id, context.identity.channel_schema_id) && ...
    isequal(data.matlab_release, provenance.matlab_release) && ...
    isequal(data.campaign_matlab_release, ...
        provenance.campaign_matlab_release) && ...
    isequal(data.release_qualification_run, ...
        provenance.release_qualification_run) && ...
    isequal(data.actual_matlab_environment_descriptor, ...
        provenance.actual_matlab_environment_descriptor) && ...
    isequal(data.actual_matlab_environment_sha256, ...
        provenance.actual_matlab_environment_sha256) && ...
    isequal(data.campaign_matlab_environment_descriptor, ...
        provenance.campaign_matlab_environment_descriptor) && ...
    isequal(data.campaign_matlab_environment_sha256, ...
        provenance.campaign_matlab_environment_sha256) && ...
    isequal(data.generator_source_root_sha256, ...
        provenance.generator_source_root_sha256) && ...
    isequal(data.generator_source_digest_lines, ...
        provenance.generator_source_digest_lines) && ...
    isequal(data.generator_source_file_count, ...
        provenance.generator_source_file_count) && ...
    isequal(data.qualification_source_sha256, ...
        provenance.qualification_source_sha256);
if ~matches
    error('ttbi:ResumePayloadProvenance', ...
        ['A00 RESUME ABORTED: state %d file "%s" has internal provenance ' ...
         'different from this run. Use a FRESH folder.'], ...
        state_index, file_name);
end

actual_descriptor_sha256 = ttbi.sha256_bytes(unicode2native( ...
    data.actual_matlab_environment_descriptor, 'UTF-8'));
campaign_descriptor_sha256 = ttbi.sha256_bytes(unicode2native( ...
    data.campaign_matlab_environment_descriptor, 'UTF-8'));
source_descriptor_sha256 = ttbi.sha256_bytes(unicode2native( ...
    data.generator_source_digest_lines, 'UTF-8'));
if ~strcmp(actual_descriptor_sha256, ...
        data.actual_matlab_environment_sha256) || ...
        ~strcmp(campaign_descriptor_sha256, ...
            data.campaign_matlab_environment_sha256) || ...
        ~strcmp(source_descriptor_sha256, ...
            data.generator_source_root_sha256)
    error('ttbi:ResumePayloadDescriptorDigest', ...
        ['A00 RESUME ABORTED: state %d file "%s" contains a provenance ' ...
         'descriptor that does not reproduce its SHA-256 stamp.'], ...
        state_index, file_name);
end

line_count = sum(data.generator_source_digest_lines == newline) + 1;
if ~isnumeric(data.generator_source_file_count) || ...
        ~isreal(data.generator_source_file_count) || ...
        ~isscalar(data.generator_source_file_count) || ...
        ~isfinite(data.generator_source_file_count) || ...
        data.generator_source_file_count ~= line_count
    error('ttbi:ResumePayloadSourceCount', ...
        ['A00 RESUME ABORTED: state %d file "%s" has an invalid generator ' ...
         'source-file count.'], state_index, file_name);
end
end
