function validate_state_signals(data, state_index, file_name, Npass)
%VALIDATE_STATE_SIGNALS Validate exact channel inventories and dimensions.

signal_fields = { ...
    'AcelPrimVag', 'AcelRodaPrimVag', 'AcelWheelsetPrimVag', ...
    'PitchPrimVag'};
expected_rows = [3, 4, 4, 3];
for field_index = 1:numel(signal_fields)
    field_name = signal_fields{field_index};
    cells = data.(field_name);
    if ~iscell(cells) || ~isequal(size(cells), [1, Npass])
        error('ttbi:ResumePayloadSignalCells', ...
            ['A00 RESUME ABORTED: state %d file "%s" %s must be exactly ' ...
             'one 1x%d signal-cell row.'], ...
            state_index, file_name, field_name, Npass);
    end
    for passage_index = 1:Npass
        signal = cells{1, passage_index};
        if ~isa(signal, 'double') || ~isreal(signal) || issparse(signal) || ...
                ~ismatrix(signal) || ...
                size(signal, 1) ~= expected_rows(field_index) || ...
                size(signal, 2) ~= data.DimAcel(passage_index) || ...
                ~all(isfinite(signal(:))) || ~any(signal(:) ~= 0)
            error('ttbi:ResumePayloadSignal', ...
                ['A00 RESUME ABORTED: state %d file "%s" %s passage %d ' ...
                 'is not a finite, nonzero, full double %dxDimAcel matrix.'], ...
                state_index, file_name, field_name, passage_index, ...
                expected_rows(field_index));
        end
    end
end
end
