function validate_state_identity(data, state_index, file_name, context)
%VALIDATE_STATE_IDENTITY Match labels, semantic UID, and named RNG streams.

state = context.state;
Npass = context.Npass;
expected_passage_seeds = reshape( ...
    state.PassageNamedStreamSeedID(state_index, :, :), ...
    Npass, numel(state.passage_stream_names));

matches = ...
    isequal(data.scour_vector, state.DamageStates(state_index, :)) && ...
    isequal(data.bearing_fixity, state.BearingFixity(state_index, :)) && ...
    isequal(data.bearing_vector, state.BearingStates(state_index, :)) && ...
    isequal(data.scour_supports, state.scour_supports) && ...
    isequal(data.state_family, state.StateFamily{state_index}) && ...
    isequal(data.state_uid, state.StateUID{state_index}) && ...
    isequal(data.state_seed_id, state.StateSeedID(state_index)) && ...
    isequal(data.random_stream_schedule_version, ...
        state.random_stream_schedule_version) && ...
    isequal(data.state_named_stream_seed_id, ...
        state.StateNamedStreamSeedID(state_index, :)) && ...
    isequal(data.passage_named_stream_seed_id, expected_passage_seeds) && ...
    isequal(data.latent_bearing_fixity, ...
        state.LatentBearingFixity(state_index, :)) && ...
    isequal(data.latent_crack_on, state.LatentCrackOn(state_index)) && ...
    isequal(data.crack_on, state.CrackOn(state_index));
if ~matches
    error('ttbi:ResumePayloadIdentity', ...
        ['A00 RESUME ABORTED: state %d file "%s" has labels, semantic ' ...
         'identity, latent state, or named streams from another state.'], ...
        state_index, file_name);
end

if ~isnumeric(data.scour_vector) || ~isreal(data.scour_vector) || ...
        ~all(isfinite(data.scour_vector)) || ...
        any(data.scour_vector < 0) || ...
        any(data.scour_vector > context.dano_max + 1e-9) || ...
        ~isnumeric(data.bearing_fixity) || ...
        ~isreal(data.bearing_fixity) || ...
        ~all(isfinite(data.bearing_fixity)) || ...
        any(data.bearing_fixity < 0) || any(data.bearing_fixity >= 1)
    error('ttbi:ResumePayloadTargetRange', ...
        ['A00 RESUME ABORTED: state %d file "%s" has a target outside ' ...
         'the registered physical-coordinate range.'], ...
        state_index, file_name);
end
end
