function validate_repository_relative_path(entry)
%VALIDATE_REPOSITORY_RELATIVE_PATH Require canonical POSIX manifest syntax.

if ~(ischar(entry) && isrow(entry)) || contains(entry, '\') || ...
        startsWith(entry, '/') || ...
        ~isempty(regexp(entry, '^[A-Za-z]:', 'once')) || ...
        contains(entry, '//') || ...
        ~isempty(regexp(entry, '[<>:"|?*\x00-\x1F\x7F]', 'once'))
    error('generator_source_root:UnsafePath', ...
        'Manifest path is not repository-relative POSIX form: "%s".', entry);
end
components = strsplit(entry, '/');
if any(cellfun(@isempty, components)) || ...
        any(strcmp(components, '.')) || any(strcmp(components, '..'))
    error('generator_source_root:UnsafePath', ...
        'Manifest path contains an unsafe component: "%s".', entry);
end
for component_index = 1:numel(components)
    component = components{component_index};
    stem = upper(strtok(component, '.'));
    reserved = any(strcmp(stem, {'CON', 'PRN', 'AUX', 'NUL'})) || ...
        ~isempty(regexp(stem, '^(COM|LPT)[1-9]$', 'once'));
    if endsWith(component, '.') || reserved
        error('generator_source_root:UnsafePath', ...
            'Manifest path has a non-portable component: "%s".', entry);
    end
end
end
