function validate_generation_sidecars(run_folder, context)
%VALIDATE_GENERATION_SIDECARS Bind both MAT sidecars to the worker context.
%
% The completion marker must never authenticate a coherently hashed but
% scientifically foreign case manifest or state catalogue. The detailed
% campaign configuration is already bound by gen_fingerprint; this function
% rechecks its critical readable projection and every state-design array.

case_path = fullfile(run_folder, 'case_info.mat');
damage_path = fullfile(run_folder, 'damage_states.mat');
if ~ttbi.regular_nonsymlink_file(case_path) || ...
        ~ttbi.regular_nonsymlink_file(damage_path)
    error('ttbi:GenerationSidecarPath', ...
        ['Generation sidecars must be regular files without symlink, ' ...
         'junction, or hard-link aliases.']);
end

case_variables = whos('-file', case_path);
if ~isequal({case_variables.name}', {'case_info'})
    error('ttbi:GenerationCaseInventory', ...
        'case_info.mat must contain exactly one case_info variable.');
end
loaded_case = load(case_path, 'case_info');
case_info = loaded_case.case_info;
if ~isstruct(case_info) || ~isscalar(case_info)
    error('ttbi:GenerationCaseShape', ...
        'case_info.mat does not contain one scalar case_info struct.');
end

identity = struct( ...
    'gen_schema', context.identity.gen_schema, ...
    'gen_fingerprint', context.identity.gen_fingerprint);
ttbi.assert_resume_case_identity( ...
    run_folder, case_info, identity, context.provenance);
required_case_fields = { ...
    'generation_behavior_version', 'channel_schema_id', ...
    'state_design_kind', ...
    'generation_config_json', ...
    'n_states', 'passages_per_state', 'L_bridge_m', 'num_spans', ...
    'scour_supports', 'random_stream_schedule_version', ...
    'state_stream_names', 'passage_stream_names', ...
    'bearing_k_ref_Nm_rad', 'n_target_healthy', 'n_scour_only', ...
    'n_bearing_only', 'n_nuisance_only', 'n_joint'};
if ~all(isfield(case_info, required_case_fields))
    error('ttbi:GenerationCaseFields', ...
        'case_info.mat lacks a critical readable scientific field.');
end
state = context.state;
expected_family_counts = [ ...
    sum(strcmp(state.StateFamily, 'target_healthy')), ...
    sum(strcmp(state.StateFamily, 'scour_only')), ...
    sum(strcmp(state.StateFamily, 'bearing_only')), ...
    sum(strcmp(state.StateFamily, 'nuisance_only')), ...
    sum(strcmp(state.StateFamily, 'joint'))];
case_matches = ...
    isequal(case_info.generation_behavior_version, ...
        context.identity.generation_behavior_version) && ...
    isequal(case_info.channel_schema_id, ...
        context.identity.channel_schema_id) && ...
    isequal(case_info.state_design_kind, ...
        context.identity.state_design_kind) && ...
    isequal(case_info.generation_config_json, ...
        context.identity.generation_config_json) && ...
    strcmp(ttbi.sha256(case_info.generation_config_json), ...
        context.identity.gen_fingerprint) && ...
    isequal(case_info.n_states, context.n_states) && ...
    isequal(case_info.passages_per_state, context.Npass) && ...
    isequal(case_info.L_bridge_m, context.model.L_bridge) && ...
    isequal(case_info.num_spans, context.model.num_spans) && ...
    isequal(case_info.scour_supports, mat2str(state.scour_supports)) && ...
    isequal(case_info.random_stream_schedule_version, ...
        state.random_stream_schedule_version) && ...
    isequal(case_info.state_stream_names, ...
        strjoin(state.state_stream_names, ',')) && ...
    isequal(case_info.passage_stream_names, ...
        strjoin(state.passage_stream_names, ',')) && ...
    isequal(case_info.bearing_k_ref_Nm_rad, state.k_ref_bear) && ...
    isequal([case_info.n_target_healthy, case_info.n_scour_only, ...
        case_info.n_bearing_only, case_info.n_nuisance_only, ...
        case_info.n_joint], expected_family_counts);
if ~case_matches
    error('ttbi:GenerationCaseIdentity', ...
        'case_info.mat differs from the current scientific execution context.');
end

expected_damage_fields = sort({ ...
    'AnchorLevel'; 'AnchorTarget'; 'BearingFixity'; 'BearingStates'; ...
    'CrackOn'; 'DamageStates'; 'LatentBearingFixity'; 'LatentCrackOn'; ...
    'PassageNamedStreamSeedID'; 'PassageNamedStreamSeedIDFlat'; ...
    'StateFamily'; 'StateNamedStreamSeedID'; 'StateSeedID'; 'StateUID'; ...
    'k_ref_bear'; 'passage_stream_names'; ...
    'random_stream_schedule_version'; 'scour_supports'; ...
    'state_stream_names'});
damage_variable_info = whos('-file', damage_path);
damage_variables = sort({damage_variable_info.name}');
if ~isequal(damage_variables, expected_damage_fields)
    error('ttbi:GenerationDamageInventory', ...
        'damage_states.mat has a missing or unexpected top-level variable.');
end
catalogue = load(damage_path);
damage_matches = ...
    isequaln(catalogue.DamageStates, state.DamageStates) && ...
    isequaln(catalogue.BearingStates, state.BearingStates) && ...
    isequaln(catalogue.BearingFixity, state.BearingFixity) && ...
    isequaln(catalogue.LatentBearingFixity, ...
        state.LatentBearingFixity) && ...
    isequaln(catalogue.k_ref_bear, state.k_ref_bear) && ...
    isequaln(catalogue.scour_supports, state.scour_supports) && ...
    isequaln(catalogue.StateFamily, state.StateFamily) && ...
    isequaln(catalogue.AnchorTarget, state.AnchorTarget) && ...
    isequaln(catalogue.AnchorLevel, state.AnchorLevel) && ...
    isequaln(catalogue.StateUID, state.StateUID) && ...
    isequaln(catalogue.StateSeedID, state.StateSeedID) && ...
    isequaln(catalogue.StateNamedStreamSeedID, ...
        state.StateNamedStreamSeedID) && ...
    isequaln(catalogue.PassageNamedStreamSeedID, ...
        state.PassageNamedStreamSeedID) && ...
    isequaln(catalogue.PassageNamedStreamSeedIDFlat, ...
        state.PassageNamedStreamSeedIDFlat) && ...
    isequaln(catalogue.random_stream_schedule_version, ...
        state.random_stream_schedule_version) && ...
    isequaln(catalogue.state_stream_names, state.state_stream_names) && ...
    isequaln(catalogue.passage_stream_names, ...
        state.passage_stream_names) && ...
    isequaln(catalogue.LatentCrackOn, state.LatentCrackOn) && ...
    isequaln(catalogue.CrackOn, state.CrackOn);
if ~damage_matches
    error('ttbi:GenerationDamageIdentity', ...
        'damage_states.mat differs from the current semantic state catalogue.');
end
end
