function validate_state_contact(data, state_index, file_name, context)
%VALIDATE_STATE_CONTACT Enforce the signed bilateral-contact diagnostic.
%
% Column 4 is the maximum signed wheel-rail reaction under the solver's
% convention: compression is negative and tensile artifact is positive.

contact_log = data.contact_log;
Npass = context.Npass;
if ~isa(contact_log, 'double') || ~isreal(contact_log) || ...
        issparse(contact_log) || ...
        ~isequal(size(contact_log), [Npass, 4]) || ...
        ~all(isfinite(contact_log(:)))
    error('ttbi:ResumePayloadContactShape', ...
        ['A00 RESUME ABORTED: state %d file "%s" contact_log must be a ' ...
         'finite full double %dx4 matrix.'], ...
        state_index, file_name, Npass);
end

bridge_flag = contact_log(:, 1);
track_flag = contact_log(:, 2);
tension_fraction = contact_log(:, 3);
signed_max_force = contact_log(:, 4);
flags_are_binary = all(bridge_flag == 0 | bridge_flag == 1) && ...
    all(track_flag == 0 | track_flag == 1);
flag_force_consistent = all(track_flag == double(signed_max_force > 0));
flag_fraction_consistent = all(track_flag == double(tension_fraction > 0));

if ~flags_are_binary || any(bridge_flag > track_flag) || ...
        ~flag_force_consistent || ~flag_fraction_consistent || ...
        any(tension_fraction < 0) || any(tension_fraction > 1) || ...
        any(signed_max_force > context.contact.max_tension_N) || ...
        any(tension_fraction > context.contact.max_tension_fraction)
    error('ttbi:ResumePayloadContactContract', ...
        ['A00 RESUME ABORTED: state %d file "%s" has inconsistent contact ' ...
         'flags or exceeds the registered signed two-tier gate.'], ...
        state_index, file_name);
end
end
