function properties = zhai_ballast_properties(rail_seat_spacing_m)
%ZHAI_BALLAST_PROPERTIES Re-evaluate Zhai et al. (2004), Table 1.
%
% The source equations define the effective ballast mass, ballast stiffness,
% and subgrade stiffness per rail seat.  This helper makes the inherited
% 0.545-to-0.600 m spacing transfer executable and independently testable.
% Damping is deliberately absent: Zhai's tabulated Cb/Cf values are not
% defined by these three spacing-dependent equations.

if nargin ~= 1 || ~isscalar(rail_seat_spacing_m) || ...
        ~isfinite(rail_seat_spacing_m) || rail_seat_spacing_m <= 0
    error('ttbi:zhai_ballast_properties:Spacing', ...
        'rail_seat_spacing_m must be one finite positive scalar.');
end

% Zhai et al. (2004), Table 1 / equations immediately preceding it.
ls = double(rail_seat_spacing_m); % longitudinal sleeper spacing [m]
le = 0.95;                        % effective sleeper length [m]
lb = 0.273;                       % sleeper bottom width [m]
rho_b = 1800;                     % ballast density [kg/m^3]
hb = 0.45;                        % ballast depth [m]
alpha_rad = deg2rad(35);          % stress-distribution angle [rad]
Eb = 1.1e8;                       % ballast modulus [Pa]
Ef = 9.0e7;                       % subgrade modulus [Pa]
t = tan(alpha_rad);

h0 = hb - (ls-lb)/(2*t);
if h0 < 0 || ~isfinite(h0)
    error('ttbi:zhai_ballast_properties:Geometry', ...
        'Spacing %.17g m is outside the valid overlapping-cone geometry.',ls);
end

Mb = rho_b * ( ...
    lb*hb*(le + hb*t) + ...
    le*(hb^2-h0^2)*t + ...
    (4/3)*(hb^3-h0^3)*t^2);
Kb1 = 2*(le-lb)*t / log((le*ls)/(lb*(le+ls-lb))) * Eb;
Kb2 = ls*(ls-lb+2*le+2*hb*t)*t / ...
    (lb-ls+2*hb*t) * Eb;
Kb = Kb1*Kb2/(Kb1+Kb2);
Kf = ls*(le+2*hb*t)*Ef;

values = [Mb Kb1 Kb2 Kb Kf h0];
if ~isreal(values) || any(~isfinite(values)) || any(values(1:5) <= 0)
    error('ttbi:zhai_ballast_properties:Result', ...
        'Zhai equations returned nonphysical values at spacing %.17g m.',ls);
end

properties = struct( ...
    'schema','zhai-2004-per-rail-seat-v1', ...
    'rail_seat_spacing_m',ls, ...
    'effective_ballast_mass_kg',Mb, ...
    'ballast_stiffness_component_1_n_m',Kb1, ...
    'ballast_stiffness_component_2_n_m',Kb2, ...
    'effective_ballast_stiffness_n_m',Kb, ...
    'effective_subgrade_stiffness_n_m',Kf, ...
    'overlap_height_m',h0, ...
    'effective_sleeper_length_m',le, ...
    'sleeper_bottom_width_m',lb, ...
    'ballast_density_kg_m3',rho_b, ...
    'ballast_depth_m',hb, ...
    'stress_distribution_angle_deg',35, ...
    'ballast_modulus_pa',Eb, ...
    'subgrade_modulus_pa',Ef, ...
    'source_doi','10.1016/S0022-460X(03)00186-X');
end
