"""Byte-level Python runtime and installed-wheel authentication.

This module keeps filesystem-heavy provenance separate from the small
campaign-lock schema in :mod:`core.environment`.
"""

from __future__ import annotations

import base64
import csv
import hashlib
from importlib import metadata
import io
import os
import platform
from pathlib import Path, PurePosixPath
import re
import site
import sys
import sysconfig

from campaign_import_guard import enforce_import_boundary


_SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
_RECORD_SHA256_RE = re.compile(r"^sha256=([A-Za-z0-9_-]{43})$")
_REPARSE_POINT = 0x0400
_PYVENV_CONFIG_FIELDS = (
    "home",
    "implementation",
    "uv",
    "version_info",
    "include-system-site-packages",
    "seed",
)


def _is_reparse_path(path: Path) -> bool:
    """Return whether ``path`` itself is a link, junction, or reparse point."""
    try:
        info = path.lstat()
    except OSError:
        return False
    junction_check = getattr(path, "is_junction", None)
    try:
        is_junction = bool(junction_check and junction_check())
    except OSError:
        is_junction = True
    attributes = int(getattr(info, "st_file_attributes", 0))
    return (
        path.is_symlink()
        or is_junction
        or bool(attributes & _REPARSE_POINT)
    )


def _is_canonical_path(path: Path) -> bool:
    """Return whether neither ``path`` nor one of its ancestors is aliased."""
    absolute = os.path.normcase(os.path.abspath(path))
    canonical = os.path.normcase(os.path.realpath(path))
    return absolute == canonical


def canonical_distribution_name(name: str) -> str:
    """Return the PEP 503 comparison key used by installers and metadata."""
    if not isinstance(name, str) or not name.strip():
        raise RuntimeError("installed distribution has no usable name")
    return re.sub(r"[-_.]+", "-", name).lower()


def is_sha256(value: object) -> bool:
    """Return whether ``value`` is one lowercase hexadecimal SHA-256."""
    return isinstance(value, str) and _SHA256_RE.fullmatch(value) is not None


def file_sha256(path: Path) -> str:
    """Hash one regular, canonical file without loading it into memory."""
    if (
        not path.is_file()
        or _is_reparse_path(path)
        or not _is_canonical_path(path)
    ):
        raise RuntimeError(
            f"campaign environment file is not regular: {path}"
        )
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def python_base_runtime_root(
    base_prefix: Path | None = None,
) -> tuple[str, int]:
    """Hash the immutable CPython base tree, excluding generated bytecode.

    The uv-managed interpreter is shared by virtual environments. Its standard
    library, extension DLLs, launchers, headers, and bundled support files are
    executable provenance just as much as ``python.exe``. ``__pycache__`` and
    ``*.py[co]`` are the only exclusions because they are mutable derivatives
    of the authenticated source files.
    """
    configured_root = Path(
        sys.base_prefix if base_prefix is None else base_prefix
    )
    if (
        not configured_root.is_dir()
        or _is_reparse_path(configured_root)
        or not _is_canonical_path(configured_root)
    ):
        raise RuntimeError(
            f"invalid CPython base runtime directory: {configured_root}"
        )
    root = Path(os.path.abspath(configured_root))
    entries: list[str] = []
    for path in root.rglob("*"):
        relative = path.relative_to(root)
        if _is_reparse_path(path) or not _is_canonical_path(path):
            raise RuntimeError(
                "CPython base runtime contains a reparse/aliased path: "
                f"{relative}"
            )
        if not path.is_file():
            continue
        if (
            "__pycache__" in relative.parts
            or path.suffix.lower() in {".pyc", ".pyo"}
        ):
            continue
        entries.append(
            f"{relative.as_posix()}\0{path.stat().st_size}\0"
            f"{file_sha256(path)}"
        )
    if not entries or len(entries) != len(set(entries)):
        raise RuntimeError("CPython base runtime inventory is empty or duplicate")
    descriptor = "\n".join(sorted(entries)).encode("utf-8")
    return hashlib.sha256(descriptor).hexdigest(), len(entries)


def sys_path_roles() -> list[str]:
    """Reject every import path outside the source, CPython, and venv roots."""
    source_root = Path(__file__).resolve().parents[1]
    base = Path(sys.base_prefix).resolve()
    venv = Path(sys.prefix).resolve()
    python_tag = f"python{sys.version_info.major}{sys.version_info.minor}.zip"
    expected = [
        ("source_root", source_root),
        ("base_zip", Path(base, python_tag)),
        ("base_dlls", Path(base, "DLLs")),
        ("base_lib", Path(base, "Lib")),
        ("base_prefix", base),
        ("venv_prefix", venv),
        ("venv_site_packages", Path(sysconfig.get_path("purelib"))),
    ]

    def key(path: Path) -> str:
        return os.path.normcase(str(path.resolve()))

    expected_by_path = {key(path): role for role, path in expected}
    expected_roles = [role for role, _path in expected]
    roles: list[str] = []
    for raw_path in sys.path:
        if not isinstance(raw_path, str):
            raise RuntimeError("sys.path contains a non-text entry")
        resolved = Path(raw_path if raw_path else os.getcwd())
        role = expected_by_path.get(key(resolved))
        if role is None:
            raise RuntimeError(
                f"unregistered Python import path: {raw_path!r}"
            )
        roles.append(role)
    if roles != expected_roles:
        raise RuntimeError(
            "Python import-path order differs from the campaign contract: "
            f"{roles!r}"
        )
    for _role, search_root in expected:
        if not search_root.is_dir():
            continue
        for module in ("sitecustomize", "usercustomize"):
            candidates = (
                Path(search_root, f"{module}.py"),
                Path(search_root, f"{module}.pyc"),
                Path(search_root, module),
            )
            if any(candidate.exists() for candidate in candidates):
                raise RuntimeError(
                    f"external Python startup customizer is forbidden: "
                    f"{module!r} below {search_root}"
                )
    return roles


def _same_path(left: Path, right: Path) -> bool:
    return os.path.normcase(str(left.resolve())) == os.path.normcase(
        str(right.resolve())
    )


def parse_pyvenv_config() -> tuple[dict[str, str], str]:
    """Validate uv config and return its portable semantic SHA-256."""
    if Path(sys.prefix).resolve() == Path(sys.base_prefix).resolve():
        raise RuntimeError("campaign Python must run inside a virtual environment")
    path = Path(sys.prefix, "pyvenv.cfg")
    if not path.is_file() or path.is_symlink():
        raise RuntimeError(f"missing regular virtual-environment config: {path}")
    raw = path.read_bytes()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise RuntimeError(
            f"virtual-environment config is not UTF-8: {path}"
        ) from exc
    values: dict[str, str] = {}
    for raw_line in text.splitlines():
        key, separator, value = raw_line.partition("=")
        key = key.strip().lower()
        if separator != "=" or not key or key in values:
            raise RuntimeError(f"malformed virtual-environment config: {path}")
        values[key] = value.strip()
    if set(values) != set(_PYVENV_CONFIG_FIELDS):
        raise RuntimeError(
            "virtual-environment config fields differ from the campaign "
            f"contract: {sorted(values)!r}"
        )
    if (
        values["implementation"] != "CPython"
        or values["include-system-site-packages"] != "false"
        or values["seed"] != "true"
    ):
        raise RuntimeError(
            "campaign virtual environment must be a seeded, isolated CPython "
            "environment"
        )
    configured_home = Path(values["home"])
    if (
        not configured_home.is_absolute()
        or not _same_path(configured_home, Path(sys.base_prefix))
    ):
        raise RuntimeError(
            "virtual-environment home differs from sys.base_prefix"
        )
    if values["version_info"] != platform.python_version():
        raise RuntimeError(
            "virtual-environment version_info differs from the running Python"
        )
    # The absolute account/install path is not a scientific variable. Its value
    # was validated above; replace only that value before hashing so equivalent
    # uv environments remain portable across hosts.
    semantic_values = {
        **values,
        "home": "<validated-sys.base_prefix>",
    }
    descriptor = "\n".join(
        f"{field}={semantic_values[field]}"
        for field in _PYVENV_CONFIG_FIELDS
    ).encode("utf-8")
    return values, hashlib.sha256(descriptor).hexdigest()


def startup_file_paths() -> dict[str, Path]:
    """Return every active top-level site startup hook."""
    purelib = Path(sysconfig.get_path("purelib"))
    if not purelib.is_dir() or purelib.is_symlink():
        raise RuntimeError(f"invalid Python purelib directory: {purelib}")
    names = {
        path.name
        for path in purelib.glob("*.pth")
        if path.is_file()
    }
    names.update(
        name
        for name in ("sitecustomize.py", "usercustomize.py", "_virtualenv.py")
        if Path(purelib, name).exists()
    )
    return {
        name: Path(purelib, name)
        for name in sorted(names)
    }


def startup_file_hashes() -> dict[str, str]:
    """Authenticate every active top-level site startup hook."""
    return {
        name: file_sha256(path)
        for name, path in startup_file_paths().items()
    }


def venv_executable_sha256() -> str:
    """Authenticate the active virtual-environment launcher."""
    executable = Path(sys.executable)
    expected = Path(sys.prefix, "Scripts", "python.exe")
    if os.path.normcase(os.path.abspath(executable)) != os.path.normcase(
        os.path.abspath(expected)
    ):
        raise RuntimeError(
            "active Python executable is not the uv environment launcher"
        )
    return file_sha256(executable)


def current_python_runtime_descriptor() -> dict:
    """Return the exact CPython/ABI/build identity used by this process."""
    for variable in ("PYTHONPATH", "PYTHONHOME"):
        if variable in os.environ:
            raise RuntimeError(
                f"{variable} must be absent in the campaign process"
            )
    enforce_import_boundary()
    config, pyvenv_semantic_sha256 = parse_pyvenv_config()
    path_roles = sys_path_roles()
    base_sha256, base_file_count = python_base_runtime_root()
    version = platform.python_version()
    implementation_version = ".".join(
        str(part) for part in sys.implementation.version[:3]
    )
    runtime_dll = Path(
        sys.base_prefix,
        f"python{sys.version_info.major}{sys.version_info.minor}.dll",
    )
    gil_probe = getattr(sys, "_is_gil_enabled", None)
    gil_enabled = (
        bool(gil_probe())
        if gil_probe is not None
        else sysconfig.get_config_var("Py_GIL_DISABLED") != 1
    )
    return {
        "version": version,
        "implementation": platform.python_implementation(),
        "implementation_version": implementation_version,
        "machine": platform.machine(),
        "architecture": platform.architecture()[0],
        "cache_tag": sys.implementation.cache_tag,
        "soabi": sysconfig.get_config_var("SOABI"),
        "abiflags": getattr(sys, "abiflags", ""),
        "gil_enabled": gil_enabled,
        "build": list(platform.python_build()),
        "compiler": platform.python_compiler(),
        "base_executable_sha256": file_sha256(Path(sys._base_executable)),
        "venv_executable_sha256": venv_executable_sha256(),
        "runtime_dll_sha256": file_sha256(runtime_dll),
        "base_runtime_sha256": base_sha256,
        "base_runtime_file_count": base_file_count,
        "pyvenv_config_semantic_sha256": pyvenv_semantic_sha256,
        "virtual_environment_manager": "uv",
        "virtual_environment_manager_version": config["uv"],
        "include_system_site_packages": False,
        "user_site_enabled": bool(site.ENABLE_USER_SITE),
        "pythonpath_environment": None,
        "pythonhome_environment": None,
        "sys_path_roles": path_roles,
        "startup_files_sha256": startup_file_hashes(),
    }


def installed_distribution_versions() -> dict[str, str]:
    """Inventory every installed distribution, rejecting ambiguous metadata."""
    installed: dict[str, str] = {}
    for distribution in metadata.distributions():
        name = canonical_distribution_name(distribution.metadata.get("Name"))
        if name in installed:
            raise RuntimeError(
                f"duplicate installed distribution metadata for {name!r}"
            )
        installed[name] = distribution.version
    return dict(sorted(installed.items()))


def normalise_record_path(path: str) -> str:
    """Canonicalize and constrain one installed-wheel RECORD path."""
    if (
        not isinstance(path, str)
        or not path
        or "\x00" in path
        or "\n" in path
        or "\r" in path
    ):
        raise RuntimeError("wheel RECORD contains an invalid path")
    value = PurePosixPath(path.replace("\\", "/")).as_posix()
    if PurePosixPath(value).is_absolute():
        raise RuntimeError(f"wheel RECORD path is absolute: {path!r}")
    parts = PurePosixPath(value).parts
    if ".." in parts and not (
        len(parts) >= 4
        and parts[:2] == ("..", "..")
        and parts[2] in {"Scripts", "include", "share"}
        and ".." not in parts[2:]
    ):
        raise RuntimeError(
            f"wheel RECORD path uses an unsafe parent traversal: {path!r}"
        )
    return value


def _record_digest_bytes(value: str, owner: str) -> bytes:
    match = _RECORD_SHA256_RE.fullmatch(value)
    if match is None:
        raise RuntimeError(
            f"{owner}: wheel RECORD entry is not one SHA-256 digest"
        )
    try:
        digest = base64.urlsafe_b64decode(match.group(1) + "=")
    except (ValueError, TypeError) as exc:
        raise RuntimeError(
            f"{owner}: malformed wheel RECORD SHA-256"
        ) from exc
    if len(digest) != hashlib.sha256().digest_size:
        raise RuntimeError(f"{owner}: malformed wheel RECORD SHA-256")
    return digest


def _located_record_path(
    distribution: metadata.Distribution,
    raw_path: str,
    prefix: Path,
    owner: str,
) -> tuple[Path, Path]:
    located = Path(distribution.locate_file(raw_path))
    if _is_reparse_path(located) or not _is_canonical_path(located):
        raise RuntimeError(
            f"{owner}: installed wheel path uses a reparse/aliased path: "
            f"{raw_path!r}"
        )
    installed = located.resolve()
    try:
        installed.relative_to(prefix)
    except ValueError as exc:
        raise RuntimeError(
            f"{owner}: wheel file escapes the virtual environment: "
            f"{raw_path!r}"
        ) from exc
    return located, installed


def _distribution_record_inventory(
    distribution: metadata.Distribution,
    *,
    verify_files: bool,
    allowed_prefix: Path | None = None,
) -> tuple[str, set[Path], set[Path]]:
    """Authenticate one installed wheel's runtime-owned files.

    The root excludes only installer-created ``RECORD``, ``INSTALLER``,
    ``REQUESTED``, and console-launcher rows. Those bytes differ between pip
    and uv but are not imported by the campaign. Every wheel-owned module,
    native library, metadata file, and data file remains covered. Re-hashing
    installed bytes protects runtime semantics even if an index serves another
    archive carrying the same distribution version.
    """
    owner = canonical_distribution_name(distribution.metadata.get("Name"))
    record_text = distribution.read_text("RECORD")
    if not isinstance(record_text, str):
        raise RuntimeError(f"{owner}: installed wheel has no RECORD")
    try:
        rows = list(csv.reader(io.StringIO(record_text), strict=True))
    except (csv.Error, UnicodeError) as exc:
        raise RuntimeError(f"{owner}: malformed wheel RECORD") from exc

    own_records = []
    for row in rows:
        if len(row) != 3:
            raise RuntimeError(f"{owner}: malformed wheel RECORD row")
        path = normalise_record_path(row[0])
        if (
            path.endswith(".dist-info/RECORD")
            and len(PurePosixPath(path).parts) == 2
        ):
            own_records.append(path)
    if len(own_records) != 1:
        raise RuntimeError(
            f"{owner}: wheel RECORD does not identify one metadata directory"
        )
    metadata_root = own_records[0][:-len("/RECORD")]
    installer_rows = {
        f"{metadata_root}/INSTALLER",
        f"{metadata_root}/REQUESTED",
    }

    prefix = Path(
        sys.prefix if allowed_prefix is None else allowed_prefix
    ).resolve()
    canonical_rows: list[str] = []
    covered_paths: set[Path] = set()
    installer_paths: set[Path] = set()
    seen_paths: set[str] = set()
    for raw_path, record_digest, record_size in rows:
        path = normalise_record_path(raw_path)
        if path in seen_paths:
            raise RuntimeError(f"{owner}: duplicate wheel RECORD path {path!r}")
        seen_paths.add(path)
        located_path = None
        installed_path = None
        if verify_files:
            located_path, installed_path = _located_record_path(
                distribution,
                raw_path,
                prefix,
                owner,
            )
        if path == own_records[0]:
            if record_digest or record_size:
                raise RuntimeError(
                    f"{owner}: wheel RECORD must not self-authenticate"
                )
            if verify_files:
                if not installed_path.is_file():
                    raise RuntimeError(
                        f"{owner}: installed wheel RECORD is missing"
                    )
                installer_paths.add(installed_path)
            continue
        if path in installer_rows:
            if verify_files and located_path.exists():
                if not installed_path.is_file():
                    raise RuntimeError(
                        f"{owner}: installer artifact is not a file: "
                        f"{raw_path!r}"
                    )
                installer_paths.add(installed_path)
            continue
        if path.startswith("../../Scripts/"):
            continue
        expected_digest = _record_digest_bytes(record_digest, owner)
        if not record_size.isdigit():
            raise RuntimeError(
                f"{owner}: wheel RECORD size is not a nonnegative integer"
            )
        canonical_rows.append(
            f"{path}\0{record_digest}\0{record_size}"
        )
        if not verify_files:
            continue
        if (
            not installed_path.is_file()
            or installed_path.stat().st_size != int(record_size)
        ):
            raise RuntimeError(
                f"{owner}: installed wheel file is missing or has the wrong "
                f"size: {raw_path!r}"
            )
        actual_digest = bytes.fromhex(file_sha256(installed_path))
        if actual_digest != expected_digest:
            raise RuntimeError(
                f"{owner}: installed wheel file hash mismatch: {raw_path!r}"
            )
        covered_paths.add(installed_path)
    if not canonical_rows:
        raise RuntimeError(f"{owner}: wheel RECORD authenticates no files")
    if len(canonical_rows) != len(set(canonical_rows)):
        raise RuntimeError(f"{owner}: duplicate canonical wheel RECORD row")
    descriptor = "\n".join(sorted(canonical_rows)).encode("utf-8")
    return (
        hashlib.sha256(descriptor).hexdigest(),
        covered_paths,
        installer_paths,
    )


def distribution_record_root(
    distribution: metadata.Distribution,
    *,
    verify_files: bool,
    allowed_prefix: Path | None = None,
) -> str:
    """Return one wheel's authenticated post-install content root."""
    root, _covered_paths, _installer_paths = (
        _distribution_record_inventory(
            distribution,
            verify_files=verify_files,
            allowed_prefix=allowed_prefix,
        )
    )
    return root


def validate_site_package_inventory(
    covered_paths: set[Path],
    installer_paths: set[Path],
    startup_paths: set[Path],
    *,
    library_roots: tuple[Path, ...] | None = None,
) -> int:
    """Reject unowned executable/data files below purelib and platlib."""
    configured_roots = library_roots
    if configured_roots is None:
        configured_roots = tuple(
            Path(sysconfig.get_path(name))
            for name in ("purelib", "platlib")
        )
    roots: list[Path] = []
    root_keys: set[str] = set()
    for configured_root in configured_roots:
        if (
            not configured_root.is_dir()
            or _is_reparse_path(configured_root)
            or not _is_canonical_path(configured_root)
        ):
            raise RuntimeError(
                f"invalid Python package directory: {configured_root}"
            )
        root = Path(os.path.abspath(configured_root))
        key = os.path.normcase(str(root))
        if key not in root_keys:
            roots.append(root)
            root_keys.add(key)

    allowed_paths = {
        path.resolve()
        for path in covered_paths | installer_paths | startup_paths
    }
    file_count = 0
    for root in roots:
        for path in root.rglob("*"):
            relative = path.relative_to(root)
            if _is_reparse_path(path) or not _is_canonical_path(path):
                raise RuntimeError(
                    "Python package directory contains a reparse/aliased "
                    f"path: {relative}"
                )
            if not path.is_file() or "__pycache__" in relative.parts:
                continue
            file_count += 1
            if path.resolve() not in allowed_paths:
                raise RuntimeError(
                    "unowned file in Python package directory: "
                    f"{relative}"
                )
    if file_count == 0:
        raise RuntimeError("Python package inventory is empty")
    return file_count


def installed_distribution_record_roots() -> dict[str, str]:
    """Verify RECORD-owned runtime bytes and reject unowned non-cache files."""
    roots: dict[str, str] = {}
    covered_paths: set[Path] = set()
    installer_paths: set[Path] = set()
    for distribution in metadata.distributions():
        name = canonical_distribution_name(distribution.metadata.get("Name"))
        if name in roots:
            raise RuntimeError(
                f"duplicate installed distribution metadata for {name!r}"
            )
        root, distribution_paths, distribution_installer_paths = (
            _distribution_record_inventory(
                distribution,
                verify_files=True,
            )
        )
        duplicate_paths = (
            (covered_paths | installer_paths)
            & (distribution_paths | distribution_installer_paths)
        )
        if duplicate_paths:
            duplicate = sorted(str(path) for path in duplicate_paths)[0]
            raise RuntimeError(
                f"multiple distributions claim installed path: {duplicate}"
            )
        roots[name] = root
        covered_paths.update(distribution_paths)
        installer_paths.update(distribution_installer_paths)
    validate_site_package_inventory(
        covered_paths,
        installer_paths,
        set(startup_file_paths().values()),
    )
    return dict(sorted(roots.items()))
