% Main script to run TTB-2D model

% *************************************************************************
% *** Script part of TTB-2D tool for Matlab environment.                ***
% *** Licensed under the GNU General Public License v3.0                ***
% *************************************************************************
clear; clc; close all
% process_results;

% Portable campaign environment policy: the reviewed descriptor below is a
% known-good reference, while current_matlab_environment qualifies the required
% toolboxes/licenses/APIs on this host.  Exact release, Update, BLAS/LAPACK and
% toolbox versions are recorded in every output but do not decide eligibility.
% The physics/numerical smoke suite and smoke_generation_worker are the local
% qualification.  make_micro_smoke.py remains available as an optional release
% diagnostic; its marked output can never enter production training.
script_dir_ = fileparts(mfilename('fullpath'));
current_working_dir_ = ttbi.canonical_execution_path(pwd);
expected_working_dir_ = ttbi.canonical_execution_path(script_dir_);
if ~strcmp(current_working_dir_, expected_working_dir_)
    error('A00:WorkingDirectory', ...
        ['A00_Run must execute with the MATLAB current folder equal to its ' ...
         'own scour_MATLAB directory. Current: %s; expected: %s. Change ' ...
         'folder explicitly before running; A00 will not silently cd.'], ...
        current_working_dir_, expected_working_dir_);
end
repository_root_ = fileparts(script_dir_);
environment_lock_path_ = fullfile(repository_root_, 'environment', ...
    'campaign-py313-cu128.json');
if ~isfile(environment_lock_path_)
    error('A00:EnvironmentLockMissing', ...
        'Campaign environment lock is missing: %s', environment_lock_path_);
end
environment_lock_ = jsondecode(fileread(environment_lock_path_));
if ~isstruct(environment_lock_) || ~isscalar(environment_lock_) || ...
        ~isfield(environment_lock_, 'schema') || ...
        ~strcmp(environment_lock_.schema, 'ttbi-campaign-environment-v3') || ...
        ~isfield(environment_lock_, 'matlab_environment') || ...
        ~isfield(environment_lock_, 'matlab_environment_sha256')
    error('A00:EnvironmentLockFormat', ...
        'Campaign environment reference lacks the reviewed v3 MATLAB identity.');
end
campaign_matlab_environment = environment_lock_.matlab_environment;
[campaign_matlab_environment_sha256, ...
    campaign_matlab_environment_descriptor] = ...
    matlab_environment_identity(campaign_matlab_environment);
locked_matlab_environment_sha256_ = ...
    environment_lock_.matlab_environment_sha256;
if ~ischar(locked_matlab_environment_sha256_) || ...
        isempty(regexp(locked_matlab_environment_sha256_, ...
            '^[0-9a-f]{64}$', 'once')) || ...
        ~strcmp(locked_matlab_environment_sha256_, ...
            campaign_matlab_environment_sha256)
    error('A00:EnvironmentLockDigest', ...
        ['matlab_environment_sha256 does not authenticate the canonical ' ...
         'matlab_environment descriptor in the campaign lock.']);
end
actual_matlab_environment = current_matlab_environment();
[actual_matlab_environment_sha256, ...
    actual_matlab_environment_descriptor] = ...
    matlab_environment_identity(actual_matlab_environment);
if isempty(regexp(actual_matlab_environment.release, '^R[^[:space:]]+$', 'once')) || ...
        isempty(regexp(campaign_matlab_environment.release, ...
            '^R[^[:space:]]+$', 'once'))
    error('A00:MATLABReleaseFormat', ...
        'Actual and campaign MATLAB releases must use canonical R####a/R####b form.');
end
% Retain legacy no-leading-R local variables because run-folder formatting and
% older human-readable diagnostics use ['R' matlab_release].
matlab_release = actual_matlab_environment.release(2:end);
campaign_matlab_release = campaign_matlab_environment.release(2:end);
% Production is deliberately immutable/fail-closed. Only the generated MICRO
% qualification script patches this literal to true; there is no environment
% variable that can accidentally turn a full campaign into qualification data.
qualification_run = false;
% make_micro_smoke.py replaces this second immutable literal with the canonical
% SHA-256 identity of the generated qualification source. Production must retain
% the sentinel exactly; it can never masquerade as qualification output.
qualification_source_sha256 = 'PRODUCTION';
qualification_script_path_ = '';
qualification_executed_file_sha256_ = 'PRODUCTION';
if qualification_run
    if isempty(regexp(qualification_source_sha256, ...
            '^[0-9a-f]{64}$', 'once')) %#ok<UNRCH>
        error('A00:QualificationSource', ...
            ['Qualification mode requires make_micro_smoke.py to stamp its ' ...
             'canonical lowercase source SHA-256.']);
    end
    qualification_script_path_ = mfilename('fullpath');
    if ~endsWith(qualification_script_path_, '.m')
        qualification_script_path_ = [qualification_script_path_ '.m'];
    end
    if ~isfile(qualification_script_path_)
        error('A00:QualificationExecutableMissing', ...
            'Cannot read the executing qualification script: %s', ...
            qualification_script_path_);
    end
    % The generated script hashes the exact bytes it is executing after
    % canonicalising ONLY its two unavoidable self-references (the full stamped
    % SHA and the derived 16-character result-folder token).  The placeholder
    % strings are assembled from fragments so they do not themselves create
    % additional canonicalisation matches in the hashed template.
    qualification_sha_placeholder_ = ...
        ['<QUALIFICATION_' 'SOURCE_SHA256>'];
    qualification_folder_placeholder_ = ...
        ['<QUALIFICATION_' 'SOURCE_FOLDER>'];
    [executed_qualification_source_sha256_, ...
        qualification_executed_file_sha256_] = ...
        ttbi.qualification_script_identity(qualification_script_path_, ...
            qualification_source_sha256, qualification_source_sha256(1:16), ...
            qualification_sha_placeholder_, ...
            qualification_folder_placeholder_);
    if ~strcmp(executed_qualification_source_sha256_, ...
            qualification_source_sha256)
        error('A00:QualificationExecutableMutated', ...
            ['The executable qualification script bytes do not authenticate ' ...
             'their embedded qualification_source_sha256 (%s ~= %s).'], ...
            executed_qualification_source_sha256_, ...
            qualification_source_sha256);
    end
    fprintf(2, ['[A00] *** RELEASE-QUALIFICATION RUN on ' ...
                'R%s (environment %s) ***\n      Output is NOT campaign data. Use it only ' ...
                'for compare_generation_releases.py.\n'], ...
            matlab_release, actual_matlab_environment_sha256);
elseif ~strcmp(actual_matlab_environment_sha256, ...
        campaign_matlab_environment_sha256)
    warning('A00:ReferenceMATLABEnvironmentDiffers', ...
        ['This host differs from the known-good MATLAB reference %s (%s): ' ...
         'actual %s (%s). Continuing under capability-and-smoke qualification; ' ...
         'the actual descriptor is recorded in the dataset.'], ...
        campaign_matlab_environment_sha256, ...
        campaign_matlab_environment.release, ...
        actual_matlab_environment_sha256, actual_matlab_environment.release);
else
    fprintf('[A00] MATLAB environment %s (%s; known-good reference).\n', ...
        actual_matlab_environment_sha256, actual_matlab_environment.release);
end
[generator_source_root_sha256, generator_source_digest_lines, ...
    generator_source_file_count] = generator_source_root();
fprintf('[A00] generator source root %s (%d reviewed scour_MATLAB files).\n', ...
    generator_source_root_sha256, generator_source_file_count);

% =========================================================================
% Reviewed campaign configuration
% =========================================================================
% These seven literals are ONLY the generated-micro override boundary.
% make_micro_smoke.py reduces the tuple in a copied driver. Production source
% is byte-identical in all six dispatch ZIPs: its stage and exact count tuple
% come from the authenticated generation_bundle_manifest.json beside the
% repository root, never from a builder rewrite or an environment variable.
STAGE = 'F40-S';
n_states_multi   = 0;       % joint LHS states (zero for dense F40-S)
Npass = 50;                 % passages per semantic state (operational variability)
n_healthy_states  = 5;      % five independent replicas at zero scour
n_anchor_levels  = 60;      % positive integer severities 1..60 percent
n_anchor_reps     = 5;      % each (family,target,level): 3/1/1 train/val/test
n_nuisance_states = 0;      % dense single-mechanism stage has no nuisance rows

if ~qualification_run
    bundle_selection_ = ttbi.load_generation_bundle_manifest( ...
        repository_root_, generator_source_root_sha256, ...
        generator_source_file_count);
    STAGE = bundle_selection_.STAGE;
    n_states_multi = bundle_selection_.n_states_multi;
    Npass = bundle_selection_.Npass;
    n_healthy_states = bundle_selection_.n_healthy_states;
    n_anchor_levels = bundle_selection_.n_anchor_levels;
    n_anchor_reps = bundle_selection_.n_anchor_reps;
    n_nuisance_states = bundle_selection_.n_nuisance_states;
    fprintf('[A00] authenticated generation bundle manifest %s (%s).\n', ...
        bundle_selection_.manifest_file_sha256, STAGE);
end

campaign_setup_inputs = struct( ...
    'STAGE', STAGE, ...
    'qualification_run', qualification_run, ...
    'n_states_multi', n_states_multi, ...
    'Npass', Npass, ...
    'n_healthy_states', n_healthy_states, ...
    'n_anchor_levels', n_anchor_levels, ...
    'n_anchor_reps', n_anchor_reps, ...
    'n_nuisance_states', n_nuisance_states);
campaign_config = ttbi.campaign_setup(campaign_setup_inputs);

% Optional SHM sensitivity run (not a campaign rung).  An absent environment
% variable leaves the production campaign unchanged.  When explicitly set,
% the exact arm is validated, fingerprinted, printed, and routed to a separate
% output root.  Both arms reuse the identical state/passages/RNG schedule.
dry_ballast_sign_request_ = strtrim(getenv( ...
    'TTBI_DRY_BALLAST_STIFFNESS_ARM'));
if ~isempty(dry_ballast_sign_request_)
    assert(~qualification_run, ...
        'A00:DryBallastSensitivityQualification', ...
        'Dry-ballast sign sensitivity is forbidden in qualification runs.');
    if ~campaign_config.use_track_eov
        error('A00:DryBallastSensitivityDeferred', ...
            ['Dry-ballast sign sensitivity is deferred from all four ' ...
             'Paper-1 stages because track EOV is disabled. Use only a ' ...
             'reviewed track-active experiment configuration cut from ' ...
             'commit A.']);
    end
    campaign_config.ballast_dry_stiffness_arm = ...
        ttbi.dry_ballast_stiffness_arm(dry_ballast_sign_request_);
    fprintf(2, ['[A00] DRY-BALLAST STIFFNESS SIGN SENSITIVITY: %s\n' ...
        '      This is a matched-magnitude sensitivity arm, not a campaign rung.\n'], ...
        campaign_config.ballast_dry_stiffness_arm);
end

% Build the immutable state catalogue and named RNG schedule.
state_design = ttbi.build_state_design(campaign_config);
clear campaign_setup_inputs

tempo_inicial = datetime('now');
% `datestr` is retained because the on-disk timestamp is a public legacy
% contract shared by supported MATLAB releases.
tempo_inicial_str = datestr( ...
    tempo_inicial, 'dd_MM_yyyy_HH_mm_ss'); %#ok<DATST>

% Collect source/environment facts once. The fingerprint helper adds the
% canonical schema and configuration identity below.
provenance = struct( ...
    'matlab_release', ['R' matlab_release], ...
    'campaign_matlab_release', ['R' campaign_matlab_release], ...
    'actual_matlab_environment_descriptor', ...
        actual_matlab_environment_descriptor, ...
    'actual_matlab_environment_sha256', ...
        actual_matlab_environment_sha256, ...
    'campaign_matlab_environment_descriptor', ...
        campaign_matlab_environment_descriptor, ...
    'campaign_matlab_environment_sha256', ...
        campaign_matlab_environment_sha256, ...
    'generator_source_root_sha256', generator_source_root_sha256, ...
    'generator_source_digest_lines', generator_source_digest_lines, ...
    'generator_source_file_count', generator_source_file_count, ...
    'qualification_source_sha256', qualification_source_sha256, ...
    'release_qualification_run', qualification_run);
qualification = struct( ...
    'script_path', qualification_script_path_, ...
    'executed_file_sha256', qualification_executed_file_sha256_);

descriptor = ttbi.build_case_descriptor(campaign_config, state_design);
case_name = descriptor.case_name;
if qualification_run && ...
        (state_design.n_states > 64 || campaign_config.Npass > 5)
    error('A00:QualificationMustBeMicro', ...
        ['Release qualification is restricted to <=64 states and <=5 ' ...
         'passages/state (got %d x %d). Use make_micro_smoke.py.'], ...
        state_design.n_states, campaign_config.Npass); %#ok<UNRCH>
end
% This literal is the guarded output-boundary patch used only by generated
% qualification scripts. Production always writes the short case folder.
results_root = 'Results';
relative_run_folder = case_name;
if isfield(campaign_config, 'ballast_dry_stiffness_arm')
    results_root = 'Results_sensitivity';
    relative_run_folder = fullfile('dry_ballast_stiffness_sign', ...
        campaign_config.ballast_dry_stiffness_arm, case_name);
end
if ~isfolder(results_root)
    mkdir(results_root);
end
results_root_observation = ttbi.directory_observation(results_root);
run_folder = fullfile(results_root, relative_run_folder);
% Pin the real output directory before any dataset read, write, rename, or
% credential cleanup.  This rejects a case folder (or ancestor) reached
% through a symlink, junction, or reparse alias and detects later replacement.
run_folder_observation = ttbi.ensure_generation_output_directory( ...
    run_folder, results_root, results_root_observation);

identity = ttbi.build_generation_identity( ...
    campaign_config, state_design, provenance);
provenance.gen_schema = identity.gen_schema;
provenance.gen_fingerprint = identity.gen_fingerprint;

% A folder can be resumed only under the exact same configuration, source,
% executable environment, and qualification mode.
case_info_path = fullfile(run_folder, 'case_info.mat');
ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);
if isfile(case_info_path)
    if ~ttbi.regular_nonsymlink_file(case_info_path)
        error('A00:ResumeCaseInfoPath', ...
            'Existing case_info.mat is not one regular unlinked file.');
    end
    previous_manifest = load(case_info_path, 'case_info');
    ttbi.assert_generation_output_directory( ...
        run_folder, run_folder_observation);
    if ~isfield(previous_manifest, 'case_info')
        error('A00:ResumeCaseInfoFormat', ...
            'Existing case_info.mat has no case_info struct.');
    end
    ttbi.assert_resume_case_identity( ...
        run_folder, previous_manifest.case_info, identity, provenance);
end

% Revoke every publication credential immediately before the first write.
% The revoker reasserts the pinned directory identity before each exact entry;
% it never follows a linked output root or recursively deletes a directory.
% Identity checks
% above are read-only, so an accidental attempt to resume a foreign folder
% leaves its valid marker intact; after this point, any interruption must leave
% the folder visibly incomplete until every sidecar/state is authenticated
% again and a new marker is published.
ttbi.revoke_generation_publication( ...
    run_folder, run_folder_observation);
ttbi.preserve_qualification_evidence( ...
    run_folder, qualification, provenance, run_folder_observation);

case_info = ttbi.build_case_info( ...
    campaign_config, state_design, descriptor, identity, provenance, ...
    tempo_inicial_str);
ttbi.write_run_manifest( ...
    run_folder, case_info, campaign_config, state_design, ...
    run_folder_observation);
fprintf('Run folder: %s  (%d states x %d passages)\n', ...
    run_folder, state_design.n_states, campaign_config.Npass);

% Registered bilateral-contact admissibility envelope. Its exact source bytes
% are authenticated by generator_source_root_sha256.
runtime_context = struct();
% Workers use the already-authenticated absolute spelling, so their output
% boundary does not depend on a process pool's current working directory.
runtime_context.run_folder = run_folder_observation.canonical_path;
runtime_context.run_folder_observation = run_folder_observation;
runtime_context.contact = struct( ...
    'max_tension_N', 24000, ...
    'max_tension_fraction', 0.002);
runtime_context.provenance = provenance;
execution_context = ttbi.build_execution_context( ...
    campaign_config, state_design, runtime_context);
completed = ttbi.validate_resume_states( ...
    run_folder, execution_context);

% =========================================================================
%  Generate missing states and publish an authenticated completion boundary
% =========================================================================
% Re-open the modular source boundary immediately before worker dispatch and
% again after every worker has returned. The runner discards any cached pool,
% creates fresh process workers, and authenticates source/resolution once on
% each used worker before its first state. Publication performs independent
% snapshots around semantic/artifact validation and immediately pre-marker.
ttbi.assert_generator_source_unchanged(provenance);
ttbi.run_generation_states( ...
    execution_context, completed, campaign_config.max_parfor_workers);
ttbi.assert_generator_source_unchanged(provenance);

tempo_final = datetime('now', 'Format', 'dd_MM_yyyy_HH_mm_ss');
ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);
save(fullfile(run_folder, 'tempo_final.mat'), 'tempo_final');
tempo_total = tempo_final - tempo_inicial;
fprintf('Tempo total: %s\n', char(tempo_total));
ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);
save(fullfile(run_folder, 'tempo_total.mat'), 'tempo_total');
ttbi.assert_generation_output_directory( ...
    run_folder, run_folder_observation);

ttbi.publish_generation_completion(run_folder, execution_context);
