function [Calc, Beam, Track] = A04_Options(Beam, Track, Profile_cfg)
% Definition of addition relevant aspects of the model and calculation options

% Function converted from the upstream script. It returns Calc and the updated
% Beam/Track structs explicitly; it does not mutate the caller workspace.

% *************************************************************************
% *** Script part of TTB-2D tool for Matlab environment.                ***
% *** Licensed under the GNU General Public License v3.0                ***
% *** Author: Daniel Cantero (daniel.cantero@ntnu.no)                   ***
% *** For help, modifications, and collaboration contact the author.    ***
% *************************************************************************

% ------------------------- Track irregularity ----------------------------
% The profile MODE is chosen per-run in A00 and passed in as Profile_cfg
% (optional 3rd argument; omitted -> 'fixed'). Registered modes:
%   'fixed'        one fixed-phase FRA-v2 class-4 realization shared by states
%   'fixed_scaled' the same fixed-phase FRA-v2 realization times intensity
%   'psd_fra'      the SAME FRA-v2 spectrum/cutoffs with state-specific phases
%                  (class from Profile_cfg.fra_class; 1 = worst, 6 = best).
%   'f25_stored_type2' the Fernandes (2025) stored Type-2 realization; this
%                  mode is reserved for the isolated F25 experiment.
% Thus fixed -> psd_fra changes the phase-realization distribution only, not
% the spectral law or amplitude. Ref: Berawi (2013), "Improving railway track
% maintenance using PSD".
if nargin < 3 || isempty(Profile_cfg) || ~isfield(Profile_cfg, 'mode')
    Profile_cfg = struct('mode', 'fixed');
end
Calc = struct();

switch Profile_cfg.mode

    case 'fixed'
        % The fixed baseline is generated by the exact same FRA-v2 helper as
        % psd_fra, with one reviewed seed shared across every state.
        if ~isfield(Profile_cfg, 'fra_class')
            Profile_cfg.fra_class = 4;
        end
        if ~isfield(Profile_cfg, 'phase_seed')
            Profile_cfg.phase_seed = 20260728;
        end
        Calc = local_configure_fra_v2(Calc, Profile_cfg);

    case 'fixed_scaled'
        % Legacy/non-registered sensitivity mode: same fixed FRA-v2 phase,
        % multiplied after generation by the requested intensity.
        if ~isfield(Profile_cfg, 'fra_class')
            Profile_cfg.fra_class = 4;
        end
        if ~isfield(Profile_cfg, 'phase_seed')
            Profile_cfg.phase_seed = 20260728;
        end
        Calc = local_configure_fra_v2(Calc, Profile_cfg);
        Calc.Profile.intensity = Profile_cfg.intensity;

    case 'psd_fra'
        Calc = local_configure_fra_v2(Calc, Profile_cfg);

    case 'f25_stored_type2'
        Calc = local_configure_f25_stored_type2(Calc, Profile_cfg);

    otherwise
        error('A04_Options: unknown Profile_cfg.mode "%s"', Profile_cfg.mode);
end

% Main-campaign calls carry both reviewed fields.  A numeric request without a
% decision ID remains available only to nonproduction clearance studies and
% upstream/standalone callers; omission leaves B43's compatibility fallback.
if isfield(Profile_cfg,'rail_end_clearance_m')
    Calc.Profile.rail_end_clearance_m = Profile_cfg.rail_end_clearance_m;
end
if isfield(Profile_cfg,'rail_end_clearance_decision_id')
    expected_decision_id = 'paper1-rail-domain-clearance-c06-v1';
    decision_id = Profile_cfg.rail_end_clearance_decision_id;
    if ~isfield(Profile_cfg,'rail_end_clearance_m') || ...
            ~(ischar(decision_id) || ...
              (isstring(decision_id) && isscalar(decision_id))) || ...
            ~strcmp(char(decision_id),expected_decision_id) || ...
            ~isnumeric(Profile_cfg.rail_end_clearance_m) || ...
            ~isscalar(Profile_cfg.rail_end_clearance_m) || ...
            Profile_cfg.rail_end_clearance_m ~= 6
        error('A04_Options:MainCampaignRailEndClearance', ...
            ['Reviewed main-campaign clearance requires decision %s and ' ...
             'an explicit 6 m request.'],expected_decision_id);
    end
    Calc.Profile.rail_end_clearance_decision_id = char(decision_id);
end

% ---- FRA ---- 
% Reference: Ladislav Fryba. Dynamics of Railway Bridges. Academia Praha, 1996

% Calc.Profile.Type = 1;      % Defined from PSD [m^3]
% Calc.Profile.PSD_Y_fun = @(spaf,inputs) ...
%      inputs(1)*inputs(3)^2*(spaf.^(2)+inputs(2)^2)./(spaf.^(4).*(spaf.^(2)+inputs(3)^2));
% 
% Calc.Profile.inputs(1) = 15.53*1e-8;    % A [m^3] Class 1
% Calc.Profile.inputs(1) = 8.85*1e-8;     % A [m^3] Class 2
% Calc.Profile.inputs(1) = 4.92*1e-8;     % A [m^3] Class 3
% Calc.Profile.inputs(1) = 2.75*1e-8;     % A [m^3] Class 4
% Calc.Profile.inputs(1) = 1.57*1e-8;     % A [m^3] Class 5
% Calc.Profile.inputs(1) = 0.98*1e-8;     % A [m^3] Class 6
% Calc.Profile.inputs(2) = 23.3*1e-3;     % Omega1 [1/m]
%  Calc.Profile.inputs(3) = 13.1*1e-2;     % Omega2 [1/m]
%  Calc.Profile.min_WaveLength = 0.3;    % [m]
%  Calc.Profile.max_WaveLength = 3;    % [m]
 %Calc.Profile.max_WaveLength = 304.8;    % [m]
% Calc.Profile.text = 'FRA';

% % ---- FRA version 2 ----
% % Reference: Abdur Rohim Boy Berawi. Improving railway track maintenance
% %     using power spectral density (PSD). Doctoral thesis.
% %     Link: https://sigarra.up.pt/feup/en/pub_geral.show_file?pi_doc_id=12113
% Calc.Profile.Type = 1;  % Defined from PSD [m^3]
% Calc.Profile.PSD_Y_fun = @(spaf,inputs) (inputs(1)*inputs(2)*inputs(3)^2)./((spaf.^2).*(spaf.^2+inputs(3)^2))*inputs(4);
% Calc.Profile.inputs(1) = 0.25;          % k = Some constant
% %Calc.Profile.inputs(2) = 1.2107;   % A_v [cm^2 rad/m] Class 1
% %Calc.Profile.inputs(2) = 1.0181;   % A_v [cm^2 rad/m] Class 2
% %Calc.Profile.inputs(2) = 0.6816;   % A_v [cm^2 rad/m] Class 3
% %Calc.Profile.inputs(2) = 0.5376;   % A_v [cm^2 rad/m] Class 4
% %Calc.Profile.inputs(2) = 0.2095;   % A_v [cm^2 rad/m] Class 5
% Calc.Profile.inputs(2) = 0.0339;   % A_v [cm^2 rad/m] Class 6
% Calc.Profile.inputs(3) = 0.8245;   % Omega_c [rad/m]
% Calc.Profile.inputs(4) = 1e-4/(2*pi);   % Unit conversion [cm^2 = 10^(-4) m^2] and [rad = 1/(2*pi) cycles]
% Calc.Profile.min_WaveLength = 1.524;    % [m]
% Calc.Profile.max_WaveLength = 304.8;    % [m]
% Calc.Profile.text = 'FRAv2';

% % ---- German spectra for high-speed ----
% % Reference: W.W. Guo, H. Xia, G. De Roeck, K. Liu, Integral model for 
% %     train-track-bridge interaction on the Sesia viaduct: Dynamic simulation 
% %     and critical assessment, Computers & Structures, Volumes 112–113,
% %     2012, Pages 205-216, ISSN 0045-7949,
% %     https://doi.org/10.1016/j.compstruc.2012.09.001.
% Calc.Profile.Type = 1;  % Defined from PSD [m^3]
% Calc.Profile.PSD_Y_fun = @(spaf,inputs) (inputs(1)*inputs(2)^2)./((spaf.^2+inputs(3)^2).*(spaf.^2+inputs(2)^2))*inputs(4);
% Calc.Profile.inputs(1) = 4.032e-7*1/(2*pi)*(0.4/0.9843)^2;  % A_v [m^2 rad/m]
% Calc.Profile.inputs(2) = 0.8246*1/(2*pi);                   % Omega_c [rad/m]
% Calc.Profile.inputs(3) = 0.0206*1/(2*pi);                   % Omega_T [rad/m]
% Calc.Profile.inputs(4) = 1;                         % Unit conversion [rad = 1/(2*pi) cycles]
% Calc.Profile.min_WaveLength = 3;                    % [m]
% Calc.Profile.max_WaveLength = 150;                  % [m]
% Calc.Profile.text = 'German high-speed';

% % ---- SNCF ----
% % Reference: Abdur Rohim Boy Berawi. Improving railway track maintenance
% %     using power spectral density (PSD). Doctoral thesis.
% %     Link: https://sigarra.up.pt/feup/en/pub_geral.show_file?pi_doc_id=12113
% Calc.Profile.Type = 1;  % Defined from PSD [m^3]
% Calc.Profile.PSD_Y_fun = @(spaf,inputs) inputs(1)./(1+spaf/inputs(2)).^3;
% Calc.Profile.inputs(1) = 0.509*308*10^-6;       % A for good track
% %Calc.Profile.inputs(1) = 1.790*308*10^-6;      % A for poor track
% Calc.Profile.inputs(2) = 0.0489;                % n0 [1/m]
% Calc.Profile.min_WaveLength = 2;                % [m]
% Calc.Profile.max_WaveLength = 40;               % [m]
% Calc.Profile.text = 'SNCF';

% % ---- Load existing profile ----
% Calc.Profile.Type = 5;
% Calc.Profile.Load.file_name = '20171207_FRA_Class6_500m';
% Calc.Profile.Load.path_name = 'Results\Profiles\';

% --------------------------- Mesh Properties -----------------------------

% -- Element size for Bridge model --
% Use at least two elements per sleeper bay, then increase only when needed
% to put every equal-span support on a bridge node.  This keeps the existing
% 0.30 m mesh for L99.6/4 spans, while L60/3 spans uses 0.20 m elements
% instead of silently snapping its 20 and 40 m supports to 20.1 and 39.9 m.
Beam.Mesh.Ele.num_per_spacing = bridge_mesh_elements_per_sleeper( ...
    Beam.Prop.L, Beam.Prop.num_spans, Track.Sleeper.spacing, 2);

% -- Element size for rail in Track model --
Track.Rail.Mesh.Ele.num_per_spacing = 2;

% -- Approach distance --
Calc.Profile.minL_Approach = 16;    % Approach distance [m]

% -- Distance after crossing -- (To allow for free vibration)
Calc.Profile.minL_After = 10;   % [m] (Default value = 10)

% ----------------- Calculation options and variables ---------------------

% Results at particular bridge sections
Calc.Options.calc_beam_sections = Beam.Prop.L/2;      % (Default = [])

% Time step
Calc.Solver.max_accurate_frq = 500;     % [Hz]

% Consider VBI
Calc.Options.VBI = 1;        % VBI is considered (default)
%Calc.Options.VBI = 0;        % No VBI considered = Moving force solution 

% Redux model option
Calc.Options.redux = 0;         % Original script. Track under the vehicle
%Calc.Options.redux = 1;         % No track under vehicle at start and end of simulation (Default)

% Other
Calc.Options.calc_beam_modes = 0;   % In modal analysis, no modes are calculated

% -------------------------------------------------------------------------
% ------------------------- Plotting Options ------------------------------

% Note: Comment/uncomment to switch off/on the corresponding plot

% ---- Vehicle ----
%Calc.Plot.Veh.P01_VertDisp = 1;         % Vehicle vertical diplacements
%Calc.Plot.Veh.P02_VertVel = 1;          % Vehicle vertical velocities
%Calc.Plot.Veh.P03_VertAcc = 1;      % Vehicle vertical accelerations
%Calc.Plot.Veh.P04_ContactForce_t = 1;    % Vehicle vertical contact force in time (1 = Values; 2 = With 0 limit)
%Calc.Plot.Veh.P05_ContactForce_x = 2;    % Vehicle vertical contact force in space (1 = Values; 2 = With 0 limit)

% ---- Model ----
% NOTE (batch safety): C03_TTB_2D_Plots runs after EVERY passage and never
% closes its figures. With these flags ON, a dataset run (states x passages)
% accumulates thousands of figures until MATLAB runs out of memory/crashes.
% Keep them OFF for data generation; uncomment only for single-run debugging.

%Calc.Plot.Model.P00_ModelVisualization = 1;% Sketch of model before performing simulation
%Calc.Plot.Model.P01_ModelDef = 50;        % Model vertical deformation at X% of the total simulated time
%Calc.Plot.Model.P02_ModelRot = 10;        % Model rotation values at X% of the total simulated time

% ---- Beam ----
%Calc.Plot.Beam.P01_DispContour = 1;          % Beam displacement contour plot
%Calc.Plot.Beam.P02_StaticDispContour = 1;    % Beam static displacment contour plot
%Calc.Plot.Beam.P03_BMContour = 1;            % Beam Bending moment contour plot
%Calc.Plot.Beam.P04_StaticBMContour = 1;      % Beam Static Bending moment contour plot
%Calc.Plot.Beam.P05_ShearContour = 1;         % Beam Shear contour plot
%Calc.Plot.Beam.P06_StaticShearContour = 1;   % Beam Static Shear contour plot
%Calc.Plot.Beam.P07_VertAccContour = 1;       % Beam Vertical Acceleration contour plot
%Calc.Plot.Beam.P08_Sections_BeamVertDisp = 1;% Beam vertical displacement at selected sections
%Calc.Plot.Beam.P09_Sections_BeamBM = 1;      % Beam Bending Moment at selected sections
%Calc.Plot.Beam.P10_Sections_BeamShear = 1;   % Beam Shear at selected sections
%Calc.Plot.Beam.P11_Sections_BeamAcc = 1;     % Beam Acceleration at selected sections

% ---- Others ----
%Calc.Plot.Profile_original = 1;         % Generated Profile
%Calc.Plot.P3_VehPos = 1;                % Vehicle position in time

% ---- End of script ----
end

function Calc = local_configure_f25_stored_type2(Calc, Profile_cfg)
% Source-locked F25 realization. B19 loads elevation only and preserves the
% live geometry; generator_source_root authenticates the asset bytes.
expected_contract = 'fernandes-2025-stored-type2-v1';
expected_asset = 'Calc.ProfileData15_05.mat';
expected_sha256 = ...
    '71c69d9923bdc184a2c8448e0e0e6debb1670302908e093b758f57c36147465d';
required = {'profile_contract','asset_name','asset_sha256'};
missing = setdiff(required, fieldnames(Profile_cfg));
if ~isempty(missing) || ...
        ~strcmp(Profile_cfg.profile_contract, expected_contract) || ...
        ~strcmp(Profile_cfg.asset_name, expected_asset) || ...
        ~strcmp(Profile_cfg.asset_sha256, expected_sha256)
    error('A04_Options:F25ProfileContract', ...
        ['f25_stored_type2 requires the reviewed contract, asset name, and ' ...
         'SHA-256 supplied by ttbi.f25_experiment_config.']);
end
Calc.Profile.Type = 2;
Calc.Profile.text = 'Fernandes 2025 stored Type-2 realization';
Calc.Profile.profile_contract = expected_contract;
Calc.Profile.source_asset_name = expected_asset;
Calc.Profile.source_asset_sha256 = expected_sha256;
Calc.Profile.intensity = 1;
end

function Calc = local_configure_fra_v2(Calc, Profile_cfg)
% One executable spectral contract shared by fixed and per-state profiles.
expected_contract = 'fra-v2-class4-cycles-per-m-v1';
if ~isfield(Profile_cfg, 'spectrum_contract')
    Profile_cfg.spectrum_contract = expected_contract;
elseif ~strcmp(Profile_cfg.spectrum_contract, expected_contract)
    error('A04_Options: unexpected FRA-v2 spectrum contract "%s".', ...
        Profile_cfg.spectrum_contract);
end
A_v_classes = [1.2107, 1.0181, 0.6816, 0.5376, 0.2095, 0.0339];
if ~isfield(Profile_cfg, 'fra_class') || ...
        ~isscalar(Profile_cfg.fra_class) || ...
        Profile_cfg.fra_class ~= round(Profile_cfg.fra_class) || ...
        Profile_cfg.fra_class < 1 || Profile_cfg.fra_class > 6
    error('A04_Options: fra_class must be one integer in 1..6.');
end
Calc.Profile.Type = 1;
Calc.Profile.PSD_Y_fun = @(spaf,inputs) ...
    (inputs(1)*inputs(2)*inputs(3)^2) ./ ...
    ((spaf.^2).*(spaf.^2+inputs(3)^2))*inputs(4);
Calc.Profile.inputs(1) = 0.25;
Calc.Profile.inputs(2) = A_v_classes(Profile_cfg.fra_class);
% B19's axis is cycles/m. Convert Omega_c from rad/m and A_v from
% cm^2*rad/m consistently; see smoke_audit.m.
Calc.Profile.inputs(3) = 0.8245/(2*pi);
Calc.Profile.inputs(4) = 1e-4/(2*pi);
Calc.Profile.min_WaveLength = 1.524;
Calc.Profile.max_WaveLength = 304.8;
Calc.Profile.text = sprintf('FRA-v2 class %d', Profile_cfg.fra_class);
Calc.Profile.fra_class = Profile_cfg.fra_class;
Calc.Profile.spectrum_contract = expected_contract;
if isfield(Profile_cfg, 'phase_seed')
    Calc.Profile.phase_seed = Profile_cfg.phase_seed;
end
if isfield(Profile_cfg, 'jitter_sd_m')
    Calc.Profile.jitter_sd_m = Profile_cfg.jitter_sd_m;
end
end
