function contact_assert_manifest_snapshot(manifest, snapshot)
%CONTACT_ASSERT_MANIFEST_SNAPSHOT Bind one captured member to digest_lines.

if ~isstruct(manifest) || ~isscalar(manifest) || ...
        ~isfield(manifest, 'names') || ~isfield(manifest, 'sha256') || ...
        ~isstruct(snapshot) || ~isscalar(snapshot) || ...
        ~all(isfield(snapshot, {'name', 'sha256'}))
    error('dataset_digest_manifest:BadSnapshotBinding', ...
        'Manifest/member snapshot binding received malformed inputs.');
end
index = find(strcmp(manifest.names, snapshot.name));
if ~isscalar(index) || ...
        ~strcmp(manifest.sha256{index}, snapshot.sha256)
    error('dataset_digest_manifest:DigestMismatch', ...
        'Captured bytes differ from the manifest digest for %s.', ...
        snapshot.name);
end
end
