function channel_table = contact_channel_metric_table( ...
        dt_ms, channel_names, nrmse, nmax, correlation)
%CONTACT_CHANNEL_METRIC_TABLE Build long-format waveform-error evidence.

n_dt = numel(dt_ms);
n_channels = numel(channel_names);
expected_size = [n_dt, n_channels];
if ~isequal(size(nrmse), expected_size) || ...
        ~isequal(size(nmax), expected_size) || ...
        ~isequal(size(correlation), expected_size)
    error('contact_closure:MetricShape', ...
        'Channel metric arrays must be n_dt x n_channels.');
end
row_count = n_dt * n_channels;
dt_column = repelem(dt_ms(:), n_channels, 1);
channel_column = repmat(channel_names(:), n_dt, 1);
channel_table = table(dt_column, channel_column, ...
    reshape(nrmse', row_count, 1), reshape(nmax', row_count, 1), ...
    reshape(correlation', row_count, 1), ...
    'VariableNames', {'requested_dt_ms', 'channel', 'nrmse_vs_finest', ...
    'nmax_vs_finest', 'correlation_vs_finest'});
end
