function descriptor = contact_selection_descriptor(selection, datasets)
%CONTACT_SELECTION_DESCRIPTOR Render the canonical frozen selection text.

header = ['ordinal	stage	state_index	passage_index	state_uid	state_family	' ...
    'state_file_sha256	saved_bridge_flag	saved_track_flag	' ...
    'saved_fraction	saved_signed_peak_N'];
lines = cell(height(selection), 1);
for row = 1:height(selection)
    lines{row} = sprintf('%d\t%s\t%d\t%d\t%s\t%s\t%s\t%.17g\t%.17g\t%.17g\t%.17g', ...
        selection.ordinal(row), selection.stage{row}, ...
        selection.state_index(row), selection.passage_index(row), ...
        selection.state_uid{row}, selection.state_family{row}, ...
        selection.state_file_sha256{row}, ...
        selection.saved_contact_lost_bridge(row), ...
        selection.saved_contact_lost_track(row), ...
        selection.saved_tension_fraction(row), ...
        selection.saved_peak_signed_N(row));
end
dataset_lines = cell(numel(datasets), 1);
for k = 1:numel(datasets)
    d = datasets(k);
    dataset_lines{k} = sprintf( ...
        ['#dataset\t%s\tdataset_dir_sha256=%s\tcontent_root=%s\t' ...
         'case_info=%s\tdamage_states=%s\tfile_digests=%s\t' ...
         'complete=%s\thost_receipt=%s\tfingerprint=%s\tqual_source=%s\t' ...
         'qual_executed=%s\thost_diagnostic=%s'], ...
        d.stage, d.dataset_dir_sha256, d.dataset_content_root_sha256, ...
        d.case_info_sha256, d.damage_states_sha256, ...
        d.file_digests_sha256, d.completion_marker_sha256, ...
        d.qualification_host_receipt_sha256, d.gen_fingerprint, ...
        d.qualification_source_sha256, ...
        d.qualification_executed_file_sha256, ...
        d.qualification_host_diagnostic_sha256);
end
descriptor = sprintf('%s\n%s\n%s\n', ...
    strjoin(dataset_lines, newline), header, strjoin(lines, newline));
end
