function [selection, datasets] = contact_gate_build_selection( ...
        dataset_dirs, policy, host_id, source_root, environment_sha)
%CONTACT_GATE_BUILD_SELECTION Authenticate datasets and enumerate gate cases.
%
% MAT and JSON values are parsed only from stable byte snapshots. Every SHA
% published in the selection comes from that same snapshot, and lightweight
% identity/SHA receipts for all four datasets are reasserted together before
% the selection returns. State payload bytes are discarded after each parse
% so the complete gate inventory does not remain duplicated in memory.

common = contact_closure_common();
rows = cell(policy.expected_cases, 12);
datasets = repmat(struct(), numel(dataset_dirs), 1);
all_dataset_snapshots = cell(numel(dataset_dirs), 1);
ordinal = 0;
expected_families = { ...
    [3, 4, 8, 6, 10]; ...
    [3, 4, 8, 6, 10]; ...
    [3, 12, 8, 6, 10]; ...
    [3, 12, 8, 6, 10]};
family_names = {'target_healthy', 'scour_only', 'bearing_only', ...
    'nuisance_only', 'joint'};

for stage_index = 1:numel(dataset_dirs)
    dataset_dir = dataset_dirs{stage_index};
    expected_stage = policy.stages{stage_index};
    expected_states = policy.expected_states(stage_index);
    strict_manifest = validate_dataset_digest_manifest( ...
        dataset_dir, expected_states);
    manifest_snapshot = strict_manifest.file_digests_snapshot;

    case_snapshot = contact_capture_file_snapshot( ...
        fullfile(dataset_dir, 'case_info.mat'));
    contact_assert_manifest_snapshot(strict_manifest, case_snapshot);
    case_blob = contact_load_mat_bytes(case_snapshot.bytes);
    if ~isfield(case_blob, 'case_info') || ...
            ~isstruct(case_blob.case_info) || ...
            ~isscalar(case_blob.case_info)
        error('contact_closure_gate:BadDataset', ...
            '%s has no scalar case_info struct.', dataset_dir);
    end
    ci = case_blob.case_info;
    required = {'stage', 'gen_schema', 'gen_fingerprint', ...
        'generation_behavior_version', 'channel_schema_id', ...
        'release_qualification_run', 'n_states', 'passages_per_state', ...
        'generator_source_root_sha256', ...
        'actual_matlab_environment_sha256', ...
        'qualification_source_sha256'};
    if ~all(isfield(ci, required))
        error('contact_closure_gate:BadDataset', ...
            '%s has incomplete Paper-1 qualification provenance.', dataset_dir);
    end
    if ~strcmp(char(string(ci.stage)), expected_stage) || ...
            ~strcmp(char(string(ci.gen_schema)), 'audit-2026-08-09-r12') || ...
            ~strcmp(char(string(ci.generation_behavior_version)), ...
                'generation-rules-v8') || ...
            ~strcmp(char(string(ci.channel_schema_id)), 'physical8_v1') || ...
            ~isscalar(ci.release_qualification_run) || ...
            ~logical(ci.release_qualification_run) || ...
            double(ci.n_states) ~= expected_states || ...
            double(ci.passages_per_state) ~= policy.expected_passages || ...
            ~strcmp(char(string(ci.generator_source_root_sha256)), source_root) || ...
            ~strcmp(char(string(ci.actual_matlab_environment_sha256)), ...
                environment_sha)
        error('contact_closure_gate:BadDataset', ...
            '%s is not the expected fresh %s qualification micro.', ...
            dataset_dir, expected_stage);
    end
    required_files = {'damage_states.mat', 'file_digests.mat', ...
        '_GENERATION_COMPLETE', 'qualification_host_receipt.json', ...
        'qualification_executed.m'};
    for file_index = 1:numel(required_files)
        if ~isfile(fullfile(dataset_dir, required_files{file_index}))
            error('contact_closure_gate:BadDataset', ...
                '%s is missing %s.', dataset_dir, required_files{file_index});
        end
    end

    states_snapshot = contact_capture_file_snapshot( ...
        fullfile(dataset_dir, 'damage_states.mat'));
    contact_assert_manifest_snapshot(strict_manifest, states_snapshot);
    state_table = contact_load_mat_bytes(states_snapshot.bytes);
    if ~isstruct(state_table) || ~isscalar(state_table) || ...
            ~isfield(state_table, 'StateUID') || ...
            ~isfield(state_table, 'StateFamily') || ...
            numel(state_table.StateUID) ~= expected_states || ...
            numel(unique(cellstr(string(state_table.StateUID)))) ~= ...
                expected_states
        error('contact_closure_gate:BadStateTable', ...
            '%s has a malformed state identity table.', dataset_dir);
    end
    observed_families = cellstr(string(state_table.StateFamily));
    for family_index = 1:numel(family_names)
        if sum(strcmp(observed_families, family_names{family_index})) ~= ...
                expected_families{stage_index}(family_index)
            error('contact_closure_gate:BadStateTable', ...
                '%s family count differs for %s.', ...
                dataset_dir, family_names{family_index});
        end
    end

    marker_path = fullfile(dataset_dir, '_GENERATION_COMPLETE');
    marker_snapshot = contact_validate_completion_marker_snapshot( ...
        marker_path, char(string(ci.gen_schema)), ...
        char(string(ci.gen_fingerprint)), strict_manifest.root);
    receipt_path = fullfile(dataset_dir, 'qualification_host_receipt.json');
    [receipt, executed_sha, receipt_snapshot, executed_snapshot] = ...
        contact_validate_host_receipt( ...
            dataset_dir, receipt_path, expected_stage, ci, host_id, ...
            environment_sha);

    dataset_snapshots = { ...
        contact_snapshot_receipt(manifest_snapshot); ...
        contact_snapshot_receipt(case_snapshot); ...
        contact_snapshot_receipt(states_snapshot); ...
        contact_snapshot_receipt(marker_snapshot); ...
        contact_snapshot_receipt(receipt_snapshot); ...
        contact_snapshot_receipt(executed_snapshot)};
    contact_assert_numbered_state_inventory(dataset_dir, expected_states);
    for state_index = 1:expected_states
        state_path = fullfile(dataset_dir, sprintf('%04d.mat', state_index));
        if ~isfile(state_path)
            error('contact_closure_gate:BadInventory', ...
                '%s is missing state %04d.', dataset_dir, state_index);
        end
        state_snapshot = contact_capture_file_snapshot(state_path);
        contact_assert_manifest_snapshot(strict_manifest, state_snapshot);
        state_blob = contact_load_mat_bytes(state_snapshot.bytes);
        if ~isfield(state_blob, 'data') || ~isstruct(state_blob.data)
            error('contact_closure_gate:BadState', ...
                '%s does not contain data.', state_path);
        end
        data = state_blob.data;
        if ~isfield(data, 'state_uid') || ~isfield(data, 'state_family') || ...
                ~isfield(data, 'channel_schema_id') || ...
                ~strcmp(char(string(data.channel_schema_id)), 'physical8_v1') || ...
                ~strcmp(char(string(data.state_uid)), ...
                    char(string(state_table.StateUID{state_index}))) || ...
                ~strcmp(char(string(data.state_family)), ...
                    char(string(state_table.StateFamily{state_index}))) || ...
                ~isfield(data, 'contact_log') || ...
                ~isequal(size(data.contact_log), ...
                    [policy.expected_passages, 4]) || ...
                any(~isfinite(double(data.contact_log(:))))
            error('contact_closure_gate:BadState', ...
                '%s has malformed identity/contact data.', state_path);
        end
        state_sha = state_snapshot.sha256;
        for passage_index = 1:policy.expected_passages
            ordinal = ordinal + 1;
            contact = double(data.contact_log(passage_index, :));
            rows(ordinal, :) = {ordinal, expected_stage, dataset_dir, ...
                state_index, passage_index, char(string(data.state_uid)), ...
                char(string(data.state_family)), state_sha, ...
                contact(1), contact(2), contact(3), contact(4)};
        end
        dataset_snapshots{end + 1, 1} = ...
            contact_snapshot_receipt(state_snapshot); %#ok<AGROW>
        clear state_blob state_snapshot data
    end
    datasets(stage_index).stage = expected_stage;
    datasets(stage_index).dataset_dir = dataset_dir;
    datasets(stage_index).dataset_dir_sha256 = ...
        common.text_sha256(dataset_dir);
    datasets(stage_index).dataset_content_root_sha256 = ...
        strict_manifest.root;
    datasets(stage_index).case_info_sha256 = case_snapshot.sha256;
    datasets(stage_index).damage_states_sha256 = states_snapshot.sha256;
    datasets(stage_index).file_digests_sha256 = manifest_snapshot.sha256;
    datasets(stage_index).completion_marker_sha256 = marker_snapshot.sha256;
    datasets(stage_index).qualification_host_receipt_sha256 = ...
        receipt_snapshot.sha256;
    datasets(stage_index).gen_fingerprint = char(string(ci.gen_fingerprint));
    datasets(stage_index).qualification_source_sha256 = ...
        char(string(ci.qualification_source_sha256));
    datasets(stage_index).qualification_executed_file_sha256 = ...
        executed_sha;
    datasets(stage_index).qualification_host_diagnostic_sha256 = ...
        char(string(receipt.host_diagnostic_sha256));
    datasets(stage_index).qualification_hostname = ...
        char(string(receipt.hostname));
    datasets(stage_index).qualification_cpu_identifier = ...
        char(string(receipt.cpu_identifier));
    datasets(stage_index).qualification_logical_processors = ...
        double(receipt.logical_processors);
    datasets(stage_index).qualification_matlab_max_threads = ...
        double(receipt.matlab_max_threads);
    datasets(stage_index).qualification_computer_arch = ...
        char(string(receipt.computer_arch));
    contact_assert_snapshot_set_unchanged(dataset_snapshots);
    all_dataset_snapshots{stage_index} = dataset_snapshots;
end

fingerprints = {datasets.gen_fingerprint};
qualification_sources = {datasets.qualification_source_sha256};
if numel(unique(fingerprints)) ~= numel(datasets) || ...
        any(cellfun(@(v) isempty(regexp(v, '^[0-9a-f]{64}$', 'once')), ...
            fingerprints)) || ...
        numel(unique(qualification_sources)) ~= numel(datasets)
    error('contact_closure_gate:DatasetIdentity', ...
        ['Stage fingerprints/source identities must be lowercase SHA-256 ' ...
         'values and distinct across F40-S/F40-M/L99-S/L99-M.']);
end
host_tuple_fields = {'qualification_hostname', ...
    'qualification_cpu_identifier', 'qualification_logical_processors', ...
    'qualification_matlab_max_threads', 'qualification_computer_arch'};
for field_index = 1:numel(host_tuple_fields)
    field = host_tuple_fields{field_index};
    reference = datasets(1).(field);
    for stage_index = 2:numel(datasets)
        if ~isequal(datasets(stage_index).(field), reference)
            error('contact_closure_gate:HostDrift', ...
                ['Qualification micros do not carry one identical physical-' ...
                 'host diagnostic tuple (%s differs).'], field);
        end
    end
end

selection = cell2table(rows, 'VariableNames', { ...
    'ordinal', 'stage', 'dataset_dir', 'state_index', 'passage_index', ...
    'state_uid', 'state_family', 'state_file_sha256', ...
    'saved_contact_lost_bridge', 'saved_contact_lost_track', ...
    'saved_tension_fraction', 'saved_peak_signed_N'});
if height(selection) ~= policy.expected_cases || ...
        ~isequal(selection.ordinal, (1:policy.expected_cases)')
    error('contact_closure_gate:BadInventory', ...
        'Complete Cartesian inventory has %d cases; expected %d.', ...
        height(selection), policy.expected_cases);
end
for stage_index = 1:numel(dataset_dirs)
    contact_assert_numbered_state_inventory( ...
        dataset_dirs{stage_index}, policy.expected_states(stage_index));
    contact_assert_snapshot_set_unchanged( ...
        all_dataset_snapshots{stage_index});
end
end
