function n_states = contact_case_state_count(case_info)
%CONTACT_CASE_STATE_COUNT Validate and return case_info.n_states.

if ~isfield(case_info, 'n_states') || ...
        ~isnumeric(case_info.n_states) || ~isscalar(case_info.n_states) || ...
        ~isfinite(case_info.n_states) || case_info.n_states < 1 || ...
        case_info.n_states ~= round(case_info.n_states)
    error('contact_closure:BadCaseInfo', ...
        'case_info.n_states must be one positive integer.');
end
n_states = double(case_info.n_states);
end
