function snapshot = contact_capture_file_snapshot(path)
%CONTACT_CAPTURE_FILE_SNAPSHOT Capture bytes, identity and SHA in one record.

path = char(path);
[bytes, observation] = contact_stable_file_bytes(path);
[~, base, extension] = fileparts(path);
snapshot = struct( ...
    'name', [base, extension], ...
    'path', path, ...
    'bytes', bytes, ...
    'observation', observation, ...
    'sha256', contact_bytes_sha256(bytes));
end
