function contact_gate_validate_publication( ...
        existing, recomputed_summary, selection_descriptor, selection_sha)
%CONTACT_GATE_VALIDATE_PUBLICATION Reauthenticate a finalized summary.
%
% Run timestamps are the only values preserved from the original publication;
% every scientific and provenance field must equal freshly recomputed evidence.

if ~isstruct(existing) || ...
        ~isequal(fieldnames(existing), {'publication'}) || ...
        ~isstruct(existing.publication) || ...
        ~isscalar(existing.publication) || ...
        ~isequal(sort(fieldnames(existing.publication)), ...
            sort({'summary'; 'selection_descriptor'; 'selection_sha256'})) || ...
        ~strcmp(existing.publication.selection_descriptor, ...
            selection_descriptor) || ...
        ~strcmp(existing.publication.selection_sha256, selection_sha)
    error('contact_closure_gate:ImmutableSummary', ...
        'Existing publication does not contain the exact frozen inputs/cases.');
end
observed = existing.publication.summary;
if ~isstruct(observed) || ~isscalar(observed) || ...
        ~isequal(sort(fieldnames(observed)), ...
            sort(fieldnames(recomputed_summary))) || ...
        ~isfield(observed, 'started_utc') || ...
        ~isfield(observed, 'completed_utc') || ...
        isempty(regexp(observed.started_utc, ...
            '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(Z|\+00:00)$', 'once')) || ...
        isempty(regexp(observed.completed_utc, ...
            '^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(Z|\+00:00)$', 'once'))
    error('contact_closure_gate:ImmutableSummary', ...
        'Existing publication summary has a malformed exact schema/timestamp.');
end
observed_comparable = rmfield(observed, {'started_utc', 'completed_utc'});
recomputed_comparable = rmfield( ...
    recomputed_summary, {'started_utc', 'completed_utc'});
if ~isequaln(observed_comparable, recomputed_comparable)
    error('contact_closure_gate:ImmutableSummary', ...
        'Existing immutable summary disagrees with recomputed evidence.');
end
end
