function [accepted, acceptance, reasons] = ...
        contact_gate_accept_report(report, policy)
%CONTACT_GATE_ACCEPT_REPORT Apply every per-case closure acceptance rule.

reasons = cell(0, 1);
if ~strcmp(report.study_schema, 'contact-closure-v3') || ...
        ~strcmp(report.generation_behavior_version, 'generation-rules-v8') || ...
        ~strcmp(report.channel_schema_id, policy.channel_schema_id) || ...
        ~strcmp(report.status, 'COMPLETED')
    reasons{end + 1, 1} = 'wrong study schema/status';
end
if ~isequal(report.dt_requested_ms, policy.dt_ms) || ...
        ~isequal(report.gates_n, policy.gates_n) || ...
        report.fraction_gate ~= policy.fraction_gate || ...
        report.common_dx_m ~= policy.common_dx_m || ...
        report.reconstruction_rtol ~= policy.reconstruction_rtol || ...
        report.reconstruction_atol ~= policy.reconstruction_atol
    reasons{end + 1, 1} = 'study policy mismatch';
end
if ~islogical(report.direct_reconstruction_pass) || ...
        ~isscalar(report.direct_reconstruction_pass) || ...
        ~isequal(report.direct_reconstruction_pass, true) || ...
        ~islogical(report.saved_contact_reconstruction_pass) || ...
        ~isscalar(report.saved_contact_reconstruction_pass) || ...
        ~isequal(report.saved_contact_reconstruction_pass, true) || ...
        ~strcmp(report.saved_baseline_mode, 'direct_raw_samples')
    reasons{end + 1, 1} = '1-ms direct reconstruction failed';
end
reconstruction = report.saved_baseline_table;
reconstruction_fields = {'channel', 'nrmse_rerun_vs_saved', ...
    'nmax_rerun_vs_saved', 'correlation_rerun_vs_saved', ...
    'max_abs_rerun_vs_saved', 'max_rel_rerun_vs_saved', ...
    'max_tolerance_ratio', 'within_tolerance'};
expected_channel_count = numel(policy.expected_channels);
if ~istable(reconstruction) || ...
        height(reconstruction) ~= expected_channel_count || ...
        ~all(ismember(reconstruction_fields, ...
            reconstruction.Properties.VariableNames)) || ...
        ~isequal(reconstruction.channel, policy.expected_channels(:)) || ...
        any(~isfinite([reconstruction.nrmse_rerun_vs_saved; ...
            reconstruction.nmax_rerun_vs_saved; ...
            reconstruction.correlation_rerun_vs_saved; ...
            reconstruction.max_abs_rerun_vs_saved; ...
            reconstruction.max_rel_rerun_vs_saved; ...
            reconstruction.max_tolerance_ratio])) || ...
        any([reconstruction.nrmse_rerun_vs_saved; ...
            reconstruction.nmax_rerun_vs_saved; ...
            reconstruction.max_abs_rerun_vs_saved; ...
            reconstruction.max_rel_rerun_vs_saved; ...
            reconstruction.max_tolerance_ratio] < 0) || ...
        any(reconstruction.correlation_rerun_vs_saved < -1 | ...
            reconstruction.correlation_rerun_vs_saved > 1) || ...
        any(reconstruction.max_tolerance_ratio > 1) || ...
        ~islogical(reconstruction.within_tolerance) || ...
        ~isequal(reconstruction.within_tolerance, ...
            true(expected_channel_count, 1))
    reasons{end + 1, 1} = ...
        'raw reconstruction numerical evidence failed';
end

run = report.run_table;
expected_dt = policy.dt_ms(:);
actual_dt_ms = double(run.actual_dt_ms);
t_end_s = double(run.t_end_s);
n_samples = double(run.n_samples);
reconstructed_dt_ms = 1000 * t_end_s ./ (n_samples - 1);
dt_tolerance = policy.time_grid_ulps * ...
    eps(max(abs(reconstructed_dt_ms), 1));
expected_intervals = ceil(t_end_s ./ (expected_dt * 1e-3));
dt_contract = height(run) == 3 && ...
    isequal(double(run.requested_dt_ms), expected_dt) && ...
    all(isfinite(actual_dt_ms)) && all(actual_dt_ms > 0) && ...
    all(isfinite(t_end_s)) && all(t_end_s > 0) && ...
    all(isfinite(n_samples)) && all(n_samples >= 2) && ...
    all(n_samples == round(n_samples)) && ...
    all(n_samples - 1 == expected_intervals) && ...
    all(abs(actual_dt_ms - reconstructed_dt_ms) <= dt_tolerance) && ...
    all(actual_dt_ms <= expected_dt + policy.time_grid_ulps * ...
        eps(max(abs(expected_dt), 1))) && ...
    all(diff(actual_dt_ms) < 0) && ...
    max(abs(t_end_s - t_end_s(1))) <= ...
        policy.time_grid_ulps * eps(max([1; abs(t_end_s)]));
if ~dt_contract
    reasons{end + 1, 1} = 'requested/actual dt mismatch';
end
signed_peak = double(run.peak_contact_signed_N);
peak = double(run.peak_tension_N);
fraction = double(run.tension_fraction);
flag_types_valid = islogical(run.contact_lost_track) && ...
    islogical(run.contact_lost_bridge) && ...
    isequal(size(run.contact_lost_track), [3, 1]) && ...
    isequal(size(run.contact_lost_bridge), [3, 1]);
track_lost = logical(run.contact_lost_track);
bridge_lost = logical(run.contact_lost_bridge);
finite_contact = all(isfinite(peak)) && all(isfinite(fraction)) && ...
    all(peak >= 0) && all(fraction >= 0 & fraction <= 1);
peak_identity_tolerance = policy.equivalence_atol + ...
    policy.equivalence_rtol * ...
    max([1; abs(signed_peak); abs(peak)]);
contact_flags_consistent = flag_types_valid && ...
    all(isfinite(signed_peak)) && ...
    all(abs(peak - max(0, signed_peak)) <= peak_identity_tolerance) && ...
    isequal(track_lost, signed_peak > 0) && ...
    all(~bridge_lost | track_lost);
if ~contact_flags_consistent
    reasons{end + 1, 1} = ...
        'signed peak/contact-loss flags are inconsistent';
end
within_contact = finite_contact && all(peak <= policy.gates_n(end)) && ...
    all(fraction <= policy.fraction_gate);
if ~within_contact
    reasons{end + 1, 1} = 'registered contact limit exceeded';
end
classes = false(3, 3);
if finite_contact
    for k = 1:3
        classes(k, :) = (peak(k) <= policy.gates_n) & ...
            (fraction(k) <= policy.fraction_gate);
    end
end
classification_stable = finite_contact && ...
    isequal(classes(1, :), classes(2, :)) && ...
    isequal(classes(2, :), classes(3, :));
if ~classification_stable
    reasons{end + 1, 1} = '0/12/24-kN classification changed with dt';
end
peak_contracts = contact_contracts_to_finest( ...
    peak, policy.equivalence_rtol, policy.equivalence_atol);
fraction_contracts = contact_contracts_to_finest( ...
    fraction, policy.equivalence_rtol, policy.equivalence_atol);
if ~peak_contracts || ~fraction_contracts
    reasons{end + 1, 1} = 'contact metric did not contract under refinement';
end
[peak_gci_pass, peak_gci] = contact_gci_bound( ...
    peak, actual_dt_ms * 1e-3, policy.gates_n(end), ...
    policy.gci_safety_factor, policy.equivalence_rtol, ...
    policy.equivalence_atol, policy.gci_p_min, policy.gci_p_max);
[fraction_gci_pass, fraction_gci] = contact_gci_bound( ...
    fraction, actual_dt_ms * 1e-3, policy.fraction_gate, ...
    policy.gci_safety_factor, policy.equivalence_rtol, ...
    policy.equivalence_atol, policy.gci_p_min, policy.gci_p_max);
if ~peak_gci_pass || ~fraction_gci_pass
    reasons{end + 1, 1} = 'contact Richardson/GCI upper bound failed';
end

channel = report.channel_table;
qoi = report.channel_qoi_table;
expected_channels = policy.expected_channels(:);
waveform_pass = true;
[~, gci_template] = contact_gci_bound( ...
    [1; 1; 1], actual_dt_ms * 1e-3, Inf, ...
    policy.gci_safety_factor, policy.equivalence_rtol, ...
    policy.equivalence_atol, policy.gci_p_min, policy.gci_p_max);
qoi_gci = repmat(gci_template, numel(expected_channels), 2);
qoi_gci_pass = false(numel(expected_channels), 2);
expected_channel_rows = numel(expected_channels) * numel(expected_dt);
if height(channel) ~= expected_channel_rows || ...
        height(qoi) ~= expected_channel_rows
    waveform_pass = false;
else
    for channel_index = 1:numel(expected_channels)
        name = expected_channels{channel_index};
        mask = strcmp(channel.channel, name);
        qmask = strcmp(qoi.channel, name);
        rows = channel(mask, :);
        qrows = qoi(qmask, :);
        if height(rows) ~= 3 || height(qrows) ~= 3 || ...
                ~isequal(rows.requested_dt_ms, expected_dt) || ...
                ~isequal(qrows.requested_dt_ms, expected_dt) || ...
                any(~isfinite([rows.nrmse_vs_finest; rows.nmax_vs_finest; ...
                    rows.correlation_vs_finest; qrows.signal_rms; ...
                    qrows.signal_abs_peak])) || ...
                any(rows.nrmse_vs_finest < 0) || ...
                any(rows.nmax_vs_finest < 0) || ...
                any(rows.correlation_vs_finest < -1 | ...
                    rows.correlation_vs_finest > 1) || ...
                any(qrows.signal_rms < 0) || ...
                any(qrows.signal_abs_peak < 0)
            waveform_pass = false;
            continue
        end
        if rows.nrmse_vs_finest(1) > policy.coarse_nrmse_max || ...
                rows.nmax_vs_finest(1) > policy.coarse_nmax_max || ...
                rows.correlation_vs_finest(1) < policy.coarse_corr_min || ...
                rows.nrmse_vs_finest(2) > policy.medium_nrmse_max || ...
                rows.nmax_vs_finest(2) > policy.medium_nmax_max || ...
                rows.correlation_vs_finest(2) < policy.medium_corr_min || ...
                rows.nrmse_vs_finest(2) > rows.nrmse_vs_finest(1) + ...
                    policy.waveform_monotonic_atol || ...
                rows.nmax_vs_finest(2) > rows.nmax_vs_finest(1) + ...
                    policy.waveform_monotonic_atol
            waveform_pass = false;
        end
        if rows.nrmse_vs_finest(3) > policy.finest_identity_atol || ...
                rows.nmax_vs_finest(3) > policy.finest_identity_atol || ...
                abs(rows.correlation_vs_finest(3) - 1) > ...
                    policy.finest_identity_atol
            waveform_pass = false;
        end
        [qoi_gci_pass(channel_index, 1), ...
            qoi_gci(channel_index, 1)] = contact_gci_bound( ...
            qrows.signal_rms, actual_dt_ms * 1e-3, Inf, ...
            policy.gci_safety_factor, policy.equivalence_rtol, ...
            policy.equivalence_atol, policy.gci_p_min, policy.gci_p_max);
        [qoi_gci_pass(channel_index, 2), ...
            qoi_gci(channel_index, 2)] = contact_gci_bound( ...
            qrows.signal_abs_peak, actual_dt_ms * 1e-3, Inf, ...
            policy.gci_safety_factor, policy.equivalence_rtol, ...
            policy.equivalence_atol, policy.gci_p_min, policy.gci_p_max);
    end
end
if ~waveform_pass
    reasons{end + 1, 1} = 'waveform convergence gate failed';
end
qoi_gci_all_pass = all(qoi_gci_pass(:));
if policy.qoi_gci_required && ~qoi_gci_all_pass
    reasons{end + 1, 1} = ...
        'channel QOI GCI convergence gate failed';
end

acceptance = struct();
acceptance.contact_peak_N = peak(:)';
acceptance.contact_fraction = fraction(:)';
acceptance.contact_classification = classes;
acceptance.contact_classification_stable = classification_stable;
acceptance.contact_flags_consistent = contact_flags_consistent;
acceptance.bilateral_tension_present_diagnostic = any(track_lost);
acceptance.contact_peak_contracts = peak_contracts;
acceptance.contact_fraction_contracts = fraction_contracts;
acceptance.peak_gci = peak_gci;
acceptance.fraction_gci = fraction_gci;
acceptance.waveform_pass = waveform_pass;
acceptance.channel_qoi_gci = qoi_gci;
acceptance.channel_qoi_gci_all_pass = qoi_gci_all_pass;
accepted = isempty(reasons);
end
