function text = contact_gate_policy_descriptor(policy)
%CONTACT_GATE_POLICY_DESCRIPTOR Canonical key=value projection of policy.

text = strjoin({ ...
    ['schema=' policy.schema], ...
    ['closure_interpretation=' policy.closure_interpretation], ...
    ['source_commit=' policy.source_commit], ...
    ['stages=' strjoin(policy.stages, ',')], ...
    ['expected_states=' contact_numeric_text(policy.expected_states)], ...
    sprintf('expected_passages=%d', policy.expected_passages), ...
    sprintf('expected_cases=%d', policy.expected_cases), ...
    ['dt_ms=' contact_numeric_text(policy.dt_ms)], ...
    ['gates_n=' contact_numeric_text(policy.gates_n)], ...
    sprintf('fraction_gate=%.17g', policy.fraction_gate), ...
    sprintf('common_dx_m=%.17g', policy.common_dx_m), ...
    sprintf('reconstruction_rtol=%.17g', policy.reconstruction_rtol), ...
    sprintf('reconstruction_atol=%.17g', policy.reconstruction_atol), ...
    sprintf('coarse_nrmse_max=%.17g', policy.coarse_nrmse_max), ...
    sprintf('coarse_nmax_max=%.17g', policy.coarse_nmax_max), ...
    sprintf('coarse_corr_min=%.17g', policy.coarse_corr_min), ...
    sprintf('medium_nrmse_max=%.17g', policy.medium_nrmse_max), ...
    sprintf('medium_nmax_max=%.17g', policy.medium_nmax_max), ...
    sprintf('medium_corr_min=%.17g', policy.medium_corr_min), ...
    sprintf('gci_safety_factor=%.17g', policy.gci_safety_factor), ...
    ['gci_method=' policy.gci_method], ...
    sprintf('equivalence_rtol=%.17g', policy.equivalence_rtol), ...
    sprintf('equivalence_atol=%.17g', policy.equivalence_atol), ...
    sprintf('gci_p_min=%.17g', policy.gci_p_min), ...
    sprintf('gci_p_max=%.17g', policy.gci_p_max), ...
    sprintf('qoi_gci_required=%s', ...
        lower(char(string(policy.qoi_gci_required)))), ...
    sprintf('time_grid_ulps=%d', policy.time_grid_ulps), ...
    sprintf('waveform_monotonic_atol=%.17g', ...
        policy.waveform_monotonic_atol), ...
    sprintf('finest_identity_atol=%.17g', ...
        policy.finest_identity_atol), ...
    ['expected_channels=' strjoin(policy.expected_channels, ',')]; ...
    ['channel_schema_id=' policy.channel_schema_id]}, newline);
end
