function contact_gate_verify_frozen_plan( ...
        policy_mat_path, policy_txt_path, selection_mat_path, ...
        selection_txt_path, policy, policy_descriptor, policy_sha, ...
        selection, datasets, selection_descriptor, selection_sha)
%CONTACT_GATE_VERIFY_FROZEN_PLAN Reauthenticate immutable plan artifacts.
%
% A resumed directory is accepted only when its MAT and text projections are
% exact representations of the newly recomputed policy and selection.

paths = {policy_mat_path, policy_txt_path, ...
    selection_mat_path, selection_txt_path};
if ~all(cellfun(@isfile, paths))
    error('contact_closure_gate:PartialPlan', ...
        'Existing OutputDir lacks one or more immutable plan artifacts.');
end
p = load(policy_mat_path);
s = load(selection_mat_path);
if ~isequal(fieldnames(p), {'frozen_policy'}) || ...
        ~isequal(fieldnames(s), {'frozen_selection'}) || ...
        ~isequal(sort(fieldnames(p.frozen_policy)), ...
            sort({'canonical_policy'; 'descriptor'; 'sha256'})) || ...
        ~isequal(sort(fieldnames(s.frozen_selection)), ...
            sort({'selection_records'; 'datasets'; 'descriptor'; 'sha256'})) || ...
        ~isequaln(p.frozen_policy.canonical_policy, policy) || ...
        ~strcmp(p.frozen_policy.descriptor, policy_descriptor) || ...
        ~strcmp(p.frozen_policy.sha256, policy_sha) || ...
        ~isequaln(s.frozen_selection.selection_records, ...
            contact_gate_plain_table(selection)) || ...
        ~isequaln(s.frozen_selection.datasets, datasets) || ...
        ~strcmp(s.frozen_selection.descriptor, selection_descriptor) || ...
        ~strcmp(s.frozen_selection.sha256, selection_sha) || ...
        ~strcmp(fileread(selection_txt_path), selection_descriptor) || ...
        ~strcmp(fileread(policy_txt_path), ...
            sprintf('%s\nsha256=%s\n', policy_descriptor, policy_sha))
    error('contact_closure_gate:PlanDrift', ...
        'Immutable closure policy/selection differs on resume.');
end
end
