function contact_validate_locked_matlab_environment( ...
        actual_sha, actual_descriptor)
%CONTACT_VALIDATE_LOCKED_MATLAB_ENVIRONMENT Validate reference and live identity.
%   Kept under its historical function name because the closure policy calls
%   it. Exact version equality is intentionally not an eligibility condition.

common = contact_closure_common();
repo_root = fileparts(fileparts(mfilename('fullpath')));
lock_path = fullfile( ...
    repo_root, 'environment', 'campaign-py313-cu128.json');
if ~common.regular_nonsymlink(lock_path)
    error('contact_closure_gate:EnvironmentLock', ...
        'Campaign environment lock is missing/non-regular.');
end
try
    lock = jsondecode(native2unicode(common.file_bytes(lock_path), 'UTF-8'));
catch ME
    error('contact_closure_gate:EnvironmentLock', ...
        'Campaign environment lock is invalid: %s', ME.message);
end
if ~isstruct(lock) || ~isscalar(lock) || ...
        ~isfield(lock, 'schema') || ...
        ~strcmp(char(string(lock.schema)), ...
            'ttbi-campaign-environment-v3') || ...
        ~isfield(lock, 'matlab_environment') || ...
        ~isfield(lock, 'matlab_environment_sha256')
    error('contact_closure_gate:EnvironmentLock', ...
        'Campaign environment reference is not the reviewed v3 descriptor.');
end
[locked_sha, locked_descriptor] = ...
    matlab_environment_identity(lock.matlab_environment);
if ~strcmp(locked_sha, char(string(lock.matlab_environment_sha256))) || ...
        ~strcmp(common.text_sha256(actual_descriptor), actual_sha) || ...
        isempty(locked_descriptor) || ...
        isempty(regexp(actual_sha, '^[0-9a-f]{64}$', 'once'))
    error('contact_closure_gate:EnvironmentLock', ...
        'Reference or actual MATLAB descriptor/SHA is internally inconsistent.');
end
end
