function contact_validate_case(case_info, data, state_index)
%CONTACT_VALIDATE_CASE Validate saved case and passage-array shapes.

required_case = {'L_bridge_m', 'num_spans', 'n_vehicles', ...
    'n_props_varied', 'passages_per_state'};
for k = 1:numel(required_case)
    if ~isfield(case_info, required_case{k})
        error('contact_closure:BadCaseInfo', ...
            'case_info is missing "%s".', required_case{k});
    end
end
if isfield(case_info, 'n_states') && state_index > double(case_info.n_states)
    error('contact_closure:StateOutOfRange', ...
        'State %d exceeds case_info.n_states=%d.', ...
        state_index, double(case_info.n_states));
end
required_data = {'Velocidade', 'Temperatura', 'VehiclesProps', ...
    'scour_vector', 'crack_log', 'profile_mode', 'profile_log', ...
    'track_log', 'oor_log', 'contact_log', 'state_uid', 'state_family', ...
    'state_seed_id', 'random_stream_schedule_version', ...
    'state_named_stream_seed_id'};
for k = 1:numel(required_data)
    if ~isfield(data, required_data{k})
        error('contact_closure:BadState', ...
            'State payload is missing "%s".', required_data{k});
    end
end
n_passages = numel(data.Velocidade);
if n_passages ~= double(case_info.passages_per_state) || ...
        numel(data.Temperatura) ~= n_passages || ...
        any(~isfinite(double(data.Velocidade(:)))) || ...
        any(~isfinite(double(data.Temperatura(:))))
    error('contact_closure:BadOperations', ...
        ['Velocity/temperature arrays must be finite and have exactly the ' ...
         'manifest passage count.']);
end
if size(data.contact_log, 1) ~= n_passages || size(data.contact_log, 2) < 4
    error('contact_closure:BadContactLog', ...
        'contact_log must have one row per passage and at least four columns.');
end
expected_vehicle_shape = [double(case_info.n_vehicles), ...
    double(case_info.n_props_varied), n_passages];
if ~isequal(size(data.VehiclesProps), expected_vehicle_shape) || ...
        any(~isfinite(double(data.VehiclesProps(:))))
    error('contact_closure:BadVehicleProps', ...
        'VehiclesProps must be a finite %s tensor; got %s.', ...
        mat2str(expected_vehicle_shape), mat2str(size(data.VehiclesProps)));
end
if any(~isfinite(double(data.contact_log(:))))
    error('contact_closure:BadContactLog', ...
        'contact_log contains NaN/Inf.');
end
end
