function [receipt, executed_sha, receipt_snapshot, executed_snapshot] = ...
        contact_validate_host_receipt( ...
        dataset_dir, receipt_path, expected_stage, case_info, ...
        host_id, environment_sha)
%CONTACT_VALIDATE_HOST_RECEIPT Authenticate one qualification host receipt.

common = contact_closure_common();
if ~common.regular_nonsymlink(receipt_path) || ...
        ~common.regular_nonsymlink( ...
            fullfile(dataset_dir, 'qualification_executed.m'))
    error('contact_closure_gate:HostReceipt', ...
        'Host receipt/executed qualification must be regular non-symlinks.');
end
receipt_snapshot = contact_capture_file_snapshot(receipt_path);
raw = receipt_snapshot.bytes;
if isempty(raw) || raw(end) ~= 10 || ...
        (numel(raw) >= 2 && raw(end - 1) == 10) || any(raw == 13)
    error('contact_closure_gate:HostReceipt', ...
        'Host receipt must be canonical UTF-8/LF with one terminal LF.');
end
try
    raw_text = native2unicode(raw(:)', 'UTF-8');
    receipt = jsondecode(raw_text);
catch ME
    error('contact_closure_gate:HostReceipt', ...
        'Host receipt is not strict UTF-8 JSON: %s', ME.message);
end
required = sort({'schema'; 'declared_host_id'; 'hostname'; ...
    'cpu_identifier'; 'logical_processors'; 'matlab_max_threads'; ...
    'computer_arch'; 'actual_matlab_environment_sha256'; ...
    'qualification_source_sha256'; ...
    'qualification_executed_file_sha256'; 'canonical_descriptor'; ...
    'host_diagnostic_sha256'});
if ~isstruct(receipt) || ~isscalar(receipt) || ...
        ~isequal(sort(fieldnames(receipt)), required) || ...
        ~strcmp([jsonencode(receipt), newline], raw_text)
    error('contact_closure_gate:HostReceipt', ...
        ['Host receipt has duplicate/missing/extra fields or is not the ' ...
         'canonical A00 JSON projection.']);
end
text_fields = {'schema', 'declared_host_id', 'hostname', ...
    'cpu_identifier', 'computer_arch', ...
    'actual_matlab_environment_sha256', ...
    'qualification_source_sha256', ...
    'qualification_executed_file_sha256', 'canonical_descriptor', ...
    'host_diagnostic_sha256'};
for k = 1:numel(text_fields)
    value = receipt.(text_fields{k});
    if ~ischar(value) || isempty(value) || contains(value, char(0)) || ...
            contains(value, char(13))
        error('contact_closure_gate:HostReceipt', ...
            'Host receipt field %s is not canonical text.', text_fields{k});
    end
end
for field = {'hostname', 'cpu_identifier', 'computer_arch'}
    value = receipt.(field{1});
    if numel(value) > 1024 || contains(value, newline)
        error('contact_closure_gate:HostReceipt', ...
            'Host diagnostic %s is not one bounded line.', field{1});
    end
end
for field = {'logical_processors', 'matlab_max_threads'}
    value = receipt.(field{1});
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value < 1 || value ~= round(value)
        error('contact_closure_gate:HostReceipt', ...
            'Host diagnostic %s must be a positive integer.', field{1});
    end
end
sha_fields = {'actual_matlab_environment_sha256', ...
    'qualification_source_sha256', ...
    'qualification_executed_file_sha256', ...
    'host_diagnostic_sha256'};
for field = sha_fields
    if isempty(regexp(receipt.(field{1}), ...
            '^[0-9a-f]{64}$', 'once'))
        error('contact_closure_gate:HostReceipt', ...
            'Host receipt field %s is not lowercase SHA-256.', field{1});
    end
end
if ~isstruct(case_info) || ~isscalar(case_info) || ...
        ~isfield(case_info, 'qualification_source_sha256')
    error('contact_closure_gate:HostReceipt', ...
        'case_info lacks qualification_source_sha256.');
end
qualification_source = char(string( ...
    case_info.qualification_source_sha256));
if ~strcmp(receipt.schema, 'ttbi-matlab-qualification-host-v1') || ...
        (~isempty(host_id) && ...
            ~strcmp(receipt.declared_host_id, host_id)) || ...
        ~strcmp(receipt.actual_matlab_environment_sha256, environment_sha) || ...
        ~strcmp(receipt.qualification_source_sha256, qualification_source)
    error('contact_closure_gate:HostReceipt', ...
        ['Host receipt is not bound to its environment/qualification ' ...
         'source or to the supplied host ID.']);
end
descriptor = strjoin({ ...
    ['schema=' receipt.schema], ...
    ['declared_host_id=' receipt.declared_host_id], ...
    ['hostname=' receipt.hostname], ...
    ['cpu_identifier=' receipt.cpu_identifier], ...
    sprintf('logical_processors=%d', receipt.logical_processors), ...
    sprintf('matlab_max_threads=%d', receipt.matlab_max_threads), ...
    ['computer_arch=' receipt.computer_arch], ...
    ['actual_matlab_environment_sha256=' ...
        receipt.actual_matlab_environment_sha256], ...
    ['qualification_source_sha256=' ...
        receipt.qualification_source_sha256], ...
    ['qualification_executed_file_sha256=' ...
        receipt.qualification_executed_file_sha256]}, newline);
if ~strcmp(receipt.canonical_descriptor, descriptor) || ...
        ~strcmp(receipt.host_diagnostic_sha256, ...
            common.text_sha256(descriptor))
    error('contact_closure_gate:HostReceipt', ...
        'Host canonical descriptor/diagnostic SHA does not recompute.');
end

script_path = fullfile(dataset_dir, 'qualification_executed.m');
[canonical_sha, executed_sha, script_bytes, executed_snapshot] = ...
    contact_qualification_script_identity( ...
        script_path, qualification_source);
if ~strcmp(canonical_sha, qualification_source) || ...
        ~strcmp(executed_sha, ...
            receipt.qualification_executed_file_sha256)
    error('contact_closure_gate:QualificationExecutable', ...
        ['qualification_executed.m bytes do not authenticate their stamped ' ...
         'source identity and receipt SHA.']);
end
stage_token = unicode2native(sprintf( ...
    'STAGE = ''%s'';               %% RELEASE-QUALIFICATION', ...
    expected_stage), 'UTF-8');
if numel(strfind(script_bytes(:)', stage_token(:)')) ~= 1
    error('contact_closure_gate:QualificationExecutable', ...
        'Qualification executable is not uniquely bound to stage %s.', ...
        expected_stage);
end
contact_assert_snapshot_set_unchanged( ...
    {receipt_snapshot; executed_snapshot});
end
