function summary = contact_closure_gate( ...
        f40s_dir, f40m_dir, l99s_dir, l99m_dir, output_dir, varargin)
%CONTACT_CLOSURE_GATE Exhaustive Paper-1 pre-dispatch time-step closure gate.
%
% Real qualifying invocation (on any capable host after its four local micros
% have passed capability and physics-smoke qualification):
%
%   contact_closure_gate( ...
%       "...\F40-S_L40_st31", ...
%       "...\F40-M_L40_st31", ...
%       "...\L99-S_L99.6_st39", ...
%       "...\L99-M_L99.6_st39", ...
%       "...\contact_closure_paper1", ...
%       "SourceCommit", "<40-lowercase-hex>");
%
% The four inputs must be freshly completed qualification micros produced on
% THIS closure host from one internally coherent Paper-1 source and actual
% MATLAB environment. Different campaign jobs may use other locally qualified
% hosts; only the evidence combined inside this one closure study must remain
% internally homogeneous. Every saved state/passage is selected before any
% refinement solve: 93 + 93 + 117 + 117 =
% 420 cases, each re-run at 1/0.5/0.25 ms. No historical state number and no
% post-hoc "worst" selector is part of this gate.
%
% Interrupted runs are resumable.  The policy and complete case inventory are
% immutable; a completed PASS/FAIL/ERROR case is never overwritten.  A power
% loss before the atomic case publication leaves at most a .tmp file, and only
% that absent case is re-run. Recognized temp files are removed only when
% their final artifact is absent; final+temp is rejected as ambiguous. A
% shutdown during the four-file initial frozen-plan publication is handled by
% abandoning that solver-free output directory and choosing a fresh one.
%
% Options:
%   SourceCommit  required 40-character lowercase Git commit identity.
%                 The independent Python checker proves it equals clean HEAD.
%   PlanOnly      default false.  Validates and freezes the complete inventory
%                 but runs no solver; its status is explicitly nonqualifying.
%
% MODULE LAYOUT: this entry file is a thin orchestrator (argument parsing,
% sequencing and the per-case loop). Cohesive responsibilities live in
% dedicated project functions:
%   contact_gate_policy       frozen policy struct + descriptor + locked
%                             MATLAB-environment validation
%   contact_gate_selection    dataset/selection reconstruction, host
%                             receipt/attestation, selection descriptor
%   contact_gate_acceptance   per-case acceptance metrics (contraction,
%                             Richardson/GCI, waveform and QOI gates)
%   contact_gate_*            one-function-per-file acceptance and publication
%                             helpers, named by their exact responsibility
%   contact_closure_common    shared hashing/path/closeness utilities
%   contact_solver_modules    frozen 39-module solver inventory

arguments
    f40s_dir {mustBeTextScalar}
    f40m_dir {mustBeTextScalar}
    l99s_dir {mustBeTextScalar}
    l99m_dir {mustBeTextScalar}
    output_dir {mustBeTextScalar}
end
arguments (Repeating)
    varargin
end

% Bootstrap the executable-set root without first trusting a shadowable
% project helper. The bootstrap function itself must resolve to this file's
% reviewed directory before it is allowed to check the remaining root chain.
reviewed_dir = fileparts(mfilename('fullpath'));
bootstrap_path = which('contact_assert_reviewed_bootstrap');
bootstrap_expected = fullfile( ...
    reviewed_dir, 'contact_assert_reviewed_bootstrap.m');
bootstrap_resolved_file = java.io.File(bootstrap_path);
bootstrap_expected_file = java.io.File(bootstrap_expected);
bootstrap_resolved_absolute = strrep( ...
    char(bootstrap_resolved_file.getAbsolutePath()), '\', '/');
bootstrap_expected_absolute = strrep( ...
    char(bootstrap_expected_file.getAbsolutePath()), '\', '/');
bootstrap_resolved_canonical = strrep( ...
    char(bootstrap_resolved_file.getCanonicalPath()), '\', '/');
bootstrap_expected_canonical = strrep( ...
    char(bootstrap_expected_file.getCanonicalPath()), '\', '/');
if ispc
    bootstrap_resolved_absolute = lower(bootstrap_resolved_absolute);
    bootstrap_expected_absolute = lower(bootstrap_expected_absolute);
    bootstrap_resolved_canonical = lower(bootstrap_resolved_canonical);
    bootstrap_expected_canonical = lower(bootstrap_expected_canonical);
end
if isempty(bootstrap_path) || ...
        ~strcmp(bootstrap_resolved_absolute, bootstrap_expected_absolute) || ...
        ~strcmp(bootstrap_resolved_absolute, bootstrap_resolved_canonical) || ...
        ~strcmp(bootstrap_expected_absolute, bootstrap_expected_canonical)
    error('contact_closure:GateModuleShadowed', ...
        'Gate bootstrap helper is missing or shadowed.');
end
contact_assert_reviewed_bootstrap(reviewed_dir, { ...
    'contact_absolute_path'; ...
    'contact_bytes_sha256'; ...
    'contact_closure_common'; ...
    'contact_comparison_path'; ...
    'contact_file_bytes'; ...
    'contact_file_observation'; ...
    'contact_file_sha256'; ...
    'contact_filesystem_identity'; ...
    'contact_gate_execution_root'; ...
    'contact_gate_module_files'; ...
    'contact_java_boolean_value'; ...
    'contact_path_component_is_link_alias'; ...
    'contact_regular_nonsymlink'; ...
    'contact_regular_nonsymlink_directory'; ...
    'contact_resolved_module_root'; ...
    'contact_run_small_process'; ...
    'contact_stable_file_bytes'; ...
    'contact_study_harness_files'; ...
    'contact_study_harness_root'; ...
    'contact_text_sha256'; ...
    'contact_unlinked_path_identity'; ...
    'contact_windows_file_identity'}, ...
    'contact_closure:GateModuleShadowed', 'Gate bootstrap module');

common = contact_closure_common();
common.study_harness_root();
common.gate_execution_root();
policy_api = contact_gate_policy();
selection_api = contact_gate_selection();
acceptance_api = contact_gate_acceptance();

parser = inputParser;
parser.FunctionName = mfilename;
addParameter(parser, 'SourceCommit', "", common.text_scalar);
addParameter(parser, 'PlanOnly', false, common.logical_scalar);
parse(parser, varargin{:});
opt = parser.Results;

source_commit = char(string(opt.SourceCommit));
if isempty(regexp(source_commit, '^[0-9a-f]{40}$', 'once'))
    error('contact_closure_gate:SourceCommit', ...
        'SourceCommit must be exactly one 40-character lowercase Git SHA.');
end

policy = policy_api.policy(source_commit);
policy_descriptor = policy_api.policy_descriptor(policy);
policy_sha256 = common.text_sha256(policy_descriptor);

dataset_dirs = {char(f40s_dir); char(f40m_dir); ...
    char(l99s_dir); char(l99m_dir)};
output_dir = common.absolute_path(char(output_dir));
for k = 1:numel(dataset_dirs)
    try
        dataset_identity = contact_unlinked_path_identity(dataset_dirs{k});
    catch dataset_path_error
        error('contact_closure_gate:LinkedDataset', ...
            ['Qualification dataset path is linked or cannot be ' ...
             'authenticated: %s (%s)'], dataset_dirs{k}, ...
            dataset_path_error.message);
    end
    if ~dataset_identity.exists || ~dataset_identity.is_directory
        error('contact_closure_gate:MissingDataset', ...
            'Dataset directory does not exist: %s', dataset_dirs{k});
    end
    dataset_dirs{k} = dataset_identity.canonical_path;
    if common.is_same_or_child(output_dir, dataset_dirs{k}) || ...
            common.is_same_or_child(dataset_dirs{k}, output_dir)
        error('contact_closure_gate:UnsafeOutput', ...
            ['OutputDir and every qualification dataset must be path-disjoint; ' ...
             'neither may equal or contain the other.']);
    end
end

declared_host_id = strtrim(getenv('TTBI_QUALIFICATION_HOST_ID'));
if isempty(regexp(declared_host_id, ...
        '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$', 'once'))
    error('contact_closure_gate:HostID', ...
        ['Set TTBI_QUALIFICATION_HOST_ID to the same stable 1-64 character ' ...
         'host label used to generate these micros.']);
end

[source_root, source_lines, source_count] = generator_source_root();
[environment_sha, environment_descriptor] = ...
    matlab_environment_identity(current_matlab_environment());
policy_api.validate_locked_matlab_environment( ...
    environment_sha, environment_descriptor);
closure_host_start = selection_api.closure_host_attestation( ...
    declared_host_id, environment_sha);

[selection, datasets] = selection_api.build_selection(dataset_dirs, policy, ...
    declared_host_id, source_root, environment_sha);
selection_api.assert_closure_host_matches_datasets(closure_host_start, datasets);
selection_descriptor = selection_api.selection_descriptor(selection, datasets);
selection_sha256 = common.text_sha256(selection_descriptor);

is_resume = isfolder(output_dir);
policy_mat_path = fullfile(output_dir, 'closure_policy.mat');
policy_txt_path = fullfile(output_dir, 'closure_policy.txt');
selection_mat_path = fullfile(output_dir, 'selection_manifest.mat');
selection_txt_path = fullfile(output_dir, 'selection_manifest.tsv');
cases_dir = fullfile(output_dir, 'cases');
if is_resume
    contact_gate_recover_interrupted_temps( ...
        output_dir, policy.expected_cases);
    contact_gate_validate_output_inventory( ...
        output_dir, policy.expected_cases, false);
    contact_gate_verify_frozen_plan(policy_mat_path, policy_txt_path, ...
        selection_mat_path, selection_txt_path, policy, ...
        policy_descriptor, policy_sha256, selection, datasets, ...
        selection_descriptor, selection_sha256);
else
    [ok, msg] = mkdir(output_dir);
    if ~ok
        error('contact_closure_gate:OutputCreate', ...
            'Could not create OutputDir: %s', msg);
    end
    mkdir(cases_dir);
    frozen_policy = struct('canonical_policy', policy, ...
        'descriptor', policy_descriptor, 'sha256', policy_sha256);
    frozen_selection = struct( ...
        'selection_records', contact_gate_plain_table(selection), ...
        'datasets', datasets, 'descriptor', selection_descriptor, ...
        'sha256', selection_sha256);
    contact_gate_save_atomic( ...
        policy_mat_path, 'frozen_policy', frozen_policy);
    contact_gate_write_text_atomic(policy_txt_path, ...
        sprintf('%s\nsha256=%s\n', policy_descriptor, policy_sha256));
    contact_gate_save_atomic(selection_mat_path, ...
        'frozen_selection', frozen_selection);
    contact_gate_write_text_atomic(selection_txt_path, selection_descriptor);
end
if ~isfolder(cases_dir)
    mkdir(cases_dir);
end

summary = contact_gate_summary_skeleton(policy, policy_sha256, ...
    selection_sha256, source_root, source_lines, source_count, ...
    environment_sha, environment_descriptor, declared_host_id, ...
    closure_host_start, datasets);
if logical(opt.PlanOnly)
    if isfile(fullfile(output_dir, 'gate_summary.mat'))
        error('contact_closure_gate:PlanAfterFinal', ...
            'A finalized gate cannot be mutated by a later PlanOnly request.');
    end
    summary.status = 'PLAN_ONLY_NONQUALIFYING';
    summary.completed_cases = contact_gate_count_case_files(cases_dir);
    summary.pass_cases = 0;
    summary.fail_cases = 0;
    summary.error_cases = 0;
    summary.case_artifact_root_sha256 = '';
    summary.completed_utc = common.utc_now();
    % A plan can later resume into the real run. Do not publish any final
    % gate_summary/GATE_STATUS artifact here: that would either require an
    % unsafe overwrite or permanently poison the legitimate PLAN->PASS/FAIL
    % transition. The marker is explicitly nonqualifying and create-once.
    plan_marker_path = fullfile(output_dir, ...
        'PLAN_ONLY_NONQUALIFYING.json');
    plan_marker = struct( ...
        'schema', 'contact-closure-plan-v2', ...
        'status', 'PLAN_ONLY_NONQUALIFYING', ...
        'source_commit', policy.source_commit, ...
        'policy_sha256', policy_sha256, ...
        'selection_sha256', selection_sha256, ...
        'expected_cases', policy.expected_cases);
    plan_text = [jsonencode(plan_marker, PrettyPrint=true), newline];
    if isfile(plan_marker_path)
        if ~strcmp(fileread(plan_marker_path), plan_text)
            error('contact_closure_gate:PlanDrift', ...
                'Existing nonqualifying plan marker differs.');
        end
    else
        contact_gate_write_text_atomic(plan_marker_path, plan_text);
    end
    fprintf(['CONTACT CLOSURE PLAN ONLY: %d immutable cases; ' ...
        'NO dispatch evidence produced.\n'], height(selection));
    return
end

case_results = cell(height(selection), 1);
for row = 1:height(selection)
    case_path = fullfile(cases_dir, sprintf('%04d_case.mat', row));
    case_json_path = fullfile(cases_dir, sprintf('%04d_case.json', row));
    if isfile(case_path)
        blob = load(case_path);
        if ~isequal(fieldnames(blob), {'canonical_case'})
            error('contact_closure_gate:BadResumeCase', ...
                'Existing case MAT lacks the exact canonical_case root: %s', ...
                case_path);
        end
        canonical_case = blob.canonical_case;
        contact_gate_validate_canonical_case(canonical_case, ...
            selection(row, :), policy_sha256, selection_sha256, ...
            source_root, environment_sha, datasets);
        expected_json = [jsonencode(canonical_case, ...
            PrettyPrint=true), newline];
        if isfile(case_json_path)
            if ~strcmp(fileread(case_json_path), expected_json)
                error('contact_closure_gate:BadResumeCase', ...
                    'Case %d JSON sidecar was modified.', row);
            end
        else
            % A crash may occur after the immutable MAT rename but before its
            % deterministic JSON projection. Recreate only the missing
            % projection; never rerun or replace the completed case.
            contact_gate_write_text_atomic(case_json_path, expected_json);
        end
        case_results{row} = canonical_case;
        fprintf('[closure] resume %d/%d %s\n', ...
            row, height(selection), canonical_case.status);
        continue
    end

    case_result = contact_gate_case_result_skeleton(selection(row, :), ...
        policy_sha256, selection_sha256, source_root, environment_sha);
    try
        report = contact_closure_study( ...
            selection.dataset_dir{row}, selection.state_index(row), ...
            selection.passage_index(row), ...
            'DtMs', policy.dt_ms, 'GatesN', policy.gates_n, ...
            'FractionGate', policy.fraction_gate, ...
            'CommonDxM', policy.common_dx_m, ...
            'ReconstructionRtol', policy.reconstruction_rtol, ...
            'ReconstructionAtol', policy.reconstruction_atol, ...
            'VerifyIntegrity', true, 'DryRun', false);
        contact_gate_validate_report_binding(report, selection(row, :), ...
            source_root, environment_sha, datasets, policy);
        [accepted, acceptance, failure_reasons] = ...
            acceptance_api.accept_report(report, policy);
        case_result.report = report;
        case_result.acceptance = acceptance;
        case_result.failure_reasons = failure_reasons;
        if accepted
            case_result.status = 'PASS';
        else
            case_result.status = 'FAIL';
        end
    catch ME
        case_result.status = 'ERROR';
        case_result.error_identifier = ME.identifier;
        case_result.error_message = ME.message;
    end
    case_result.completed_utc = common.utc_now();
    canonical_case = contact_gate_public_case(case_result);
    contact_gate_save_atomic(case_path, 'canonical_case', canonical_case);
    contact_gate_write_text_atomic(case_json_path, ...
        [jsonencode(canonical_case, PrettyPrint=true), newline]);
    case_results{row} = canonical_case;
    fprintf('[closure] case %d/%d %s\n', ...
        row, height(selection), case_result.status);
end

[source_root_end, source_lines_end, source_count_end] = ...
    generator_source_root();
[environment_sha_end, environment_descriptor_end] = ...
    matlab_environment_identity(current_matlab_environment());
[selection_end, datasets_end] = selection_api.build_selection( ...
    dataset_dirs, policy, declared_host_id, source_root_end, ...
    environment_sha_end);
closure_host_end = selection_api.closure_host_attestation( ...
    declared_host_id, environment_sha_end);
selection_api.assert_closure_host_matches_datasets(closure_host_end, datasets_end);
selection_descriptor_end = selection_api.selection_descriptor( ...
    selection_end, datasets_end);
if ~strcmp(source_root_end, source_root) || ...
        ~strcmp(source_lines_end, source_lines) || ...
        source_count_end ~= source_count || ...
        ~strcmp(environment_sha_end, environment_sha) || ...
        ~strcmp(environment_descriptor_end, environment_descriptor) || ...
        ~isequaln(closure_host_end, closure_host_start) || ...
        ~isequaln(selection_end, selection) || ...
        ~isequaln(datasets_end, datasets) || ...
        ~strcmp(selection_descriptor_end, selection_descriptor) || ...
        ~strcmp(common.text_sha256(selection_descriptor_end), ...
            selection_sha256)
    error('contact_closure_gate:RuntimeDrift', ...
        ['Source, environment, qualification datasets or authenticated ' ...
         'sidecars changed during the gate.']);
end

statuses = cellfun(@(r) r.status, case_results, 'UniformOutput', false);
summary.completed_cases = numel(statuses);
summary.pass_cases = sum(strcmp(statuses, 'PASS'));
summary.fail_cases = sum(strcmp(statuses, 'FAIL'));
summary.error_cases = sum(strcmp(statuses, 'ERROR'));
summary.case_artifact_root_sha256 = contact_gate_case_artifact_root( ...
    cases_dir, policy.expected_cases);
if summary.completed_cases == policy.expected_cases && ...
        summary.pass_cases == policy.expected_cases
    summary.status = 'PASS';
else
    summary.status = 'FAIL';
end
summary.completed_utc = common.utc_now();
existing_summary_path = fullfile(output_dir, 'gate_summary.mat');
if isfile(existing_summary_path)
    existing = load(existing_summary_path);
    contact_gate_validate_publication( ...
        existing, summary, selection_descriptor, selection_sha256);
    summary = existing.publication.summary;
else
    if isfile(fullfile(output_dir, 'gate_summary.json')) || ...
            isfile(fullfile(output_dir, 'GATE_STATUS.txt'))
        error('contact_closure_gate:PartialSummary', ...
            'Summary sidecar exists without the immutable MAT source of truth.');
    end
    contact_gate_publish_summary_mat( ...
        output_dir, summary, selection_descriptor, selection_sha256);
end
contact_gate_publish_or_validate_summary_sidecars(output_dir, summary);
contact_gate_validate_output_inventory(output_dir, policy.expected_cases, true);
fprintf('CONTACT CLOSURE GATE: %s (%d PASS, %d FAIL, %d ERROR / %d)\n', ...
    summary.status, summary.pass_cases, summary.fail_cases, ...
    summary.error_cases, policy.expected_cases);
end
