function attestation = ...
        contact_closure_host_attestation(host_id, environment_sha)
%CONTACT_CLOSURE_HOST_ATTESTATION Capture the executing host diagnostics.

common = contact_closure_common();
hostname = strtrim(getenv('COMPUTERNAME'));
if isempty(hostname)
    hostname = strtrim(getenv('HOSTNAME'));
end
if isempty(hostname)
    try
        address = javaMethod('getLocalHost', 'java.net.InetAddress');
        hostname = char(address.getHostName());
    catch
        hostname = 'unavailable';
    end
end
cpu_identifier = strtrim(getenv('PROCESSOR_IDENTIFIER'));
if isempty(cpu_identifier)
    cpu_identifier = computer('arch');
end
computer_arch = computer('arch');
logical_processors = str2double(strtrim(getenv('NUMBER_OF_PROCESSORS')));
if ~isfinite(logical_processors) || logical_processors < 1 || ...
        logical_processors ~= round(logical_processors)
    try
        runtime = javaMethod('getRuntime', 'java.lang.Runtime');
        logical_processors = double(runtime.availableProcessors());
    catch
        logical_processors = 1;
    end
end
try
    matlab_max_threads = double(maxNumCompThreads);
catch
    matlab_max_threads = logical_processors;
end
if ~isfinite(matlab_max_threads) || matlab_max_threads < 1 || ...
        matlab_max_threads ~= round(matlab_max_threads)
    error('contact_closure_gate:HostAttestation', ...
        'MATLAB thread diagnostic must be one positive integer.');
end
hostname = contact_closure_host_text(hostname, 'hostname');
cpu_identifier = contact_closure_host_text( ...
    cpu_identifier, 'cpu_identifier');
computer_arch = contact_closure_host_text(computer_arch, 'computer_arch');
descriptor = strjoin({ ...
    'schema=contact-closure-host-attestation-v1', ...
    ['declared_host_id=' host_id], ...
    ['hostname=' hostname], ...
    ['cpu_identifier=' cpu_identifier], ...
    sprintf('logical_processors=%d', logical_processors), ...
    sprintf('matlab_max_threads=%d', matlab_max_threads), ...
    ['computer_arch=' computer_arch], ...
    ['matlab_environment_sha256=' environment_sha]}, newline);
attestation = struct( ...
    'schema', 'contact-closure-host-attestation-v1', ...
    'declared_host_id', host_id, ...
    'hostname', hostname, ...
    'cpu_identifier', cpu_identifier, ...
    'logical_processors', logical_processors, ...
    'matlab_max_threads', matlab_max_threads, ...
    'computer_arch', computer_arch, ...
    'matlab_environment_sha256', environment_sha, ...
    'canonical_descriptor', descriptor, ...
    'sha256', common.text_sha256(descriptor));
end
