function contract = contact_validate_r11_descriptor( ...
        case_info, data, state_table, state_index, verify_integrity)
%CONTACT_VALIDATE_R11_DESCRIPTOR Authenticate current named-stream reconstruction.
% Historical function name retained so older callers fail at content checks,
% not at an ambiguous MATLAB name-resolution fallback.

required_case = {'gen_schema', 'generator_source_root_sha256', ...
    'actual_matlab_environment_sha256', 'random_stream_schedule_version', ...
    'state_stream_names', 'profile_jitter_sd_mm', 'use_signal_noise', ...
    'generation_behavior_version', 'channel_schema_id'};
for k = 1:numel(required_case)
    if ~isfield(case_info, required_case{k})
        error('contact_closure:BadR11Descriptor', ...
            'case_info is missing current field "%s".', required_case{k});
    end
end
if ~strcmp(char(string(case_info.gen_schema)), 'audit-2026-08-09-r12') || ...
        ~strcmp(char(string(case_info.generation_behavior_version)), ...
            'generation-rules-v8') || ...
        ~strcmp(char(string(case_info.channel_schema_id)), 'physical8_v1')
    error('contact_closure:BadR11Descriptor', ...
        ['Only the R12/v8/physical8_v1 Paper-1 inputs qualify for this ' ...
         'closure study.']);
end
if ~isfield(data, 'gen_schema') || ...
        ~isfield(data, 'generation_behavior_version') || ...
        ~isfield(data, 'channel_schema_id') || ...
        ~strcmp(char(string(data.gen_schema)), char(string(case_info.gen_schema))) || ...
        ~strcmp(char(string(data.generation_behavior_version)), ...
            char(string(case_info.generation_behavior_version))) || ...
        ~strcmp(char(string(data.channel_schema_id)), ...
            char(string(case_info.channel_schema_id)))
    error('contact_closure:BadR11Descriptor', ...
        'State payload R12/v8/channel identity does not match case_info.');
end
if logical(case_info.use_signal_noise) || ...
        double(case_info.profile_jitter_sd_mm) ~= 0
    error('contact_closure:NonDeterministicInput', ...
        ['Paper-1 closure requires noise-free saved signals and zero physical ' ...
         'profile jitter.']);
end

schedule = char(string(case_info.random_stream_schedule_version));
if ~strcmp(schedule, 'uid-named-substreams-v2') || ...
        ~strcmp(char(string(data.random_stream_schedule_version)), schedule)
    error('contact_closure:BadNamedStreams', ...
        'Paper-1 named-stream schedule is missing or inconsistent.');
end
raw_names = char(string(case_info.state_stream_names));
state_names = strsplit(raw_names, ',');
if isempty(state_names) || any(cellfun(@isempty, state_names)) || ...
        any(~strcmp(state_names, cellfun(@strtrim, state_names, ...
            'UniformOutput', false))) || ...
        numel(unique(state_names)) ~= numel(state_names)
    error('contact_closure:BadNamedStreams', ...
        'case_info.state_stream_names is empty, duplicated or non-canonical.');
end
phase_indices = find(strcmp(state_names, 'profile-phase'));
if ~isscalar(phase_indices)
    error('contact_closure:BadNamedStreams', ...
        'Named streams must contain "profile-phase" exactly once.');
end

seed_row = data.state_named_stream_seed_id;
if ~isa(seed_row, 'uint32') || ...
        ~isequal(size(seed_row), [1, numel(state_names)]) || ...
        any(seed_row == 0)
    error('contact_closure:BadNamedStreams', ...
        ['data.state_named_stream_seed_id must be a nonzero uint32 row ' ...
         'aligned with case_info.state_stream_names.']);
end
if ~isa(data.state_seed_id, 'uint32') || ~isscalar(data.state_seed_id) || ...
        data.state_seed_id == 0
    error('contact_closure:BadNamedStreams', ...
        'data.state_seed_id must be one nonzero uint32.');
end

if ~isstruct(state_table) || ~isscalar(state_table)
    error('contact_closure:BadStateTable', ...
        'damage_states.mat must parse as one scalar struct.');
end
required_state_table = {'StateUID', 'StateFamily', 'StateSeedID', ...
    'StateNamedStreamSeedID', 'state_stream_names', ...
    'random_stream_schedule_version'};
for k = 1:numel(required_state_table)
    if ~isfield(state_table, required_state_table{k})
        error('contact_closure:BadStateTable', ...
            'damage_states.mat is missing "%s".', required_state_table{k});
    end
end
table_names = reshape(cellstr(string(state_table.state_stream_names)), 1, []);
if ~isequal(table_names, state_names) || ...
        ~strcmp(char(string(state_table.random_stream_schedule_version)), schedule)
    error('contact_closure:BadNamedStreams', ...
        'damage_states named-stream metadata disagrees with case_info.');
end
if state_index > numel(state_table.StateUID) || ...
        state_index > numel(state_table.StateFamily) || ...
        state_index > numel(state_table.StateSeedID) || ...
        state_index > size(state_table.StateNamedStreamSeedID, 1)
    error('contact_closure:StateOutOfRange', ...
        'State %d is absent from the current identity tables.', state_index);
end
table_uid = char(string(state_table.StateUID{state_index}));
table_family = char(string(state_table.StateFamily{state_index}));
data_uid = char(string(data.state_uid));
data_family = char(string(data.state_family));
if ~strcmp(data_uid, table_uid) || ~strcmp(data_family, table_family) || ...
        ~isa(state_table.StateSeedID, 'uint32') || ...
        state_table.StateSeedID(state_index) ~= data.state_seed_id || ...
        ~isa(state_table.StateNamedStreamSeedID, 'uint32') || ...
        ~isequal(state_table.StateNamedStreamSeedID(state_index, :), seed_row)
    error('contact_closure:StateIdentityMismatch', ...
        ['State UID/family/root seed/named-seed row does not match ' ...
         'damage_states.mat row %d.'], state_index);
end

[current_source_root, current_source_lines, current_source_count] = ...
    generator_source_root();
[current_environment_sha, current_environment_descriptor] = ...
    matlab_environment_identity(current_matlab_environment());
if verify_integrity
    if ~strcmp(current_source_root, ...
            char(string(case_info.generator_source_root_sha256)))
        error('contact_closure:SourceRootMismatch', ...
            ['Current reviewed MATLAB source root differs from the one that ' ...
             'generated this dataset. Regenerate the qualification micro.']);
    end
    if ~strcmp(current_environment_sha, ...
            char(string(case_info.actual_matlab_environment_sha256)))
        error('contact_closure:EnvironmentMismatch', ...
            ['Current MATLAB numerical environment differs from the one that ' ...
             'generated this dataset.']);
    end
end

contract = struct();
contract.state_uid = data_uid;
contract.state_family = data_family;
contract.state_seed_id = data.state_seed_id;
contract.state_stream_names = state_names;
contract.profile_phase_stream_index = phase_indices;
contract.profile_phase_seed_uint32 = seed_row(phase_indices);
contract.profile_phase_seed = double(seed_row(phase_indices));
contract.current_generator_source_root_sha256 = current_source_root;
contract.current_generator_source_digest_lines = current_source_lines;
contract.current_generator_source_file_count = current_source_count;
contract.current_matlab_environment_sha256 = current_environment_sha;
contract.current_matlab_environment_descriptor = current_environment_descriptor;
end
