function [canonical_sha, raw_sha, bytes, snapshot] = ...
        contact_qualification_script_identity(path, stamped_sha)
%CONTACT_QUALIFICATION_SCRIPT_IDENTITY Hash one stable qualification script.

snapshot = contact_capture_file_snapshot(path);
bytes = snapshot.bytes;
raw_sha = snapshot.sha256;
canonical = contact_replace_unique_bytes(bytes(:)', ...
    unicode2native(stamped_sha, 'UTF-8'), ...
    unicode2native('<QUALIFICATION_SOURCE_SHA256>', 'UTF-8'), ...
    'full qualification SHA');
canonical = contact_replace_unique_bytes(canonical, ...
    unicode2native(stamped_sha(1:16), 'UTF-8'), ...
    unicode2native('<QUALIFICATION_SOURCE_FOLDER>', 'UTF-8'), ...
    'qualification folder token');
canonical_sha = contact_bytes_sha256(canonical);
contact_assert_file_snapshot_unchanged( ...
    snapshot.path, snapshot.observation, snapshot.sha256);
end
