function contact_gate_validate_canonical_case(result, row, policy_sha, ...
        selection_sha, source_root, environment_sha, datasets)
%CONTACT_GATE_VALIDATE_CANONICAL_CASE Authenticate a resumed case artifact.
%
% Resume is fail-closed: both the exact outer schema and the report identity
% must still agree with the frozen selection and qualification datasets.

common = contact_closure_common();
identity_fields = {'schema', 'status', 'ordinal', 'stage', 'state_index', ...
    'passage_index', 'state_uid', 'state_file_sha256', 'policy_sha256', ...
    'selection_sha256', 'generator_source_root_sha256', ...
    'matlab_environment_sha256', 'started_utc', 'completed_utc', ...
    'failure_reasons', 'error_identifier', 'error_message'};
report_fields = {'study_schema', 'report_status', 'report_stage', ...
    'report_state_index', 'report_passage_index', 'report_state_uid', ...
    'report_state_family', 'report_state_file_sha256', ...
    'report_gen_fingerprint', 'report_dataset_dir_sha256', ...
    'report_generator_source_root_sha256', ...
    'report_matlab_environment_sha256', 'report_harness_sha256', ...
    'report_b66_sha256', 'report_solver_execution_root_sha256', ...
    'report_dataset_manifest_root', 'report_case_info_sha256', ...
    'report_damage_states_sha256', 'report_file_digests_sha256', ...
    'report_completion_marker_sha256', 'report_host_receipt_sha256', ...
    'profile_phase_stream_index', 'profile_phase_seed', ...
    'dt_requested_ms', 'gates_n', 'fraction_gate', 'common_dx_m', ...
    'reconstruction_rtol', 'reconstruction_atol', ...
    'saved_baseline_mode', 'direct_reconstruction_pass', ...
    'saved_contact_reconstruction_pass', 'requested_dt_ms', ...
    'actual_dt_ms', 't_end_s', 'n_samples', ...
    'peak_contact_signed_N', 'peak_tension_N', 'tension_fraction', ...
    'contact_lost_track', 'contact_lost_bridge', 'saved_contact_log', ...
    'rerun_contact_log_1ms', 'channel_metrics', 'channel_qoi', ...
    'saved_reconstruction', 'report_plain', 'acceptance'};
if ~isstruct(result) || ~isscalar(result) || ~isfield(result, 'status')
    error('contact_closure_gate:BadResumeCase', ...
        'Completed case %d is not one canonical scalar struct.', row.ordinal);
end
expected_fields = identity_fields;
if any(strcmp(result.status, {'PASS', 'FAIL'}))
    expected_fields = [identity_fields, report_fields];
end
stage_index = find(strcmp({datasets.stage}, row.stage{1}));
if ~isscalar(stage_index) || ...
        ~isequal(sort(fieldnames(result)), sort(expected_fields(:))) || ...
        ~strcmp(result.schema, 'contact-closure-case-v1') || ...
        ~any(strcmp(result.status, {'PASS', 'FAIL', 'ERROR'})) || ...
        result.ordinal ~= row.ordinal || ~strcmp(result.stage, row.stage{1}) || ...
        result.state_index ~= row.state_index || ...
        result.passage_index ~= row.passage_index || ...
        ~strcmp(result.state_uid, row.state_uid{1}) || ...
        ~strcmp(result.state_file_sha256, row.state_file_sha256{1}) || ...
        ~strcmp(result.policy_sha256, policy_sha) || ...
        ~strcmp(result.selection_sha256, selection_sha) || ...
        ~strcmp(result.generator_source_root_sha256, source_root) || ...
        ~strcmp(result.matlab_environment_sha256, environment_sha)
    error('contact_closure_gate:BadResumeCase', ...
        'Completed case %d is foreign, mutated or inconsistent.', row.ordinal);
end
if any(strcmp(result.status, {'PASS', 'FAIL'}))
    dataset = datasets(stage_index);
    if ~strcmp(result.report_status, 'COMPLETED') || ...
            ~strcmp(result.report_stage, row.stage{1}) || ...
            result.report_state_index ~= row.state_index || ...
            result.report_passage_index ~= row.passage_index || ...
            ~strcmp(result.report_state_uid, row.state_uid{1}) || ...
            ~strcmp(result.report_state_family, row.state_family{1}) || ...
            ~strcmp(result.report_state_file_sha256, ...
                row.state_file_sha256{1}) || ...
            ~strcmp(result.report_gen_fingerprint, dataset.gen_fingerprint) || ...
            ~strcmp(result.report_dataset_dir_sha256, ...
                common.text_sha256(row.dataset_dir{1})) || ...
            ~isstruct(result.report_plain) || ~isscalar(result.report_plain)
        error('contact_closure_gate:BadResumeCase', ...
            'Completed canonical case %d report identity differs.', row.ordinal);
    end
end
end
