function contact_validate_locked_matlab_environment( ...
        actual_sha, actual_descriptor)
%CONTACT_VALIDATE_LOCKED_MATLAB_ENVIRONMENT Enforce the reviewed MATLAB lock.

common = contact_closure_common();
expected_sha = ...
    '958e7fe28f70577e9cb77aba0443c127d0a99726042a4618f7cce88d557fce79';
repo_root = fileparts(fileparts(mfilename('fullpath')));
lock_path = fullfile( ...
    repo_root, 'environment', 'campaign-py313-cu128.json');
if ~common.regular_nonsymlink(lock_path)
    error('contact_closure_gate:EnvironmentLock', ...
        'Campaign environment lock is missing/non-regular.');
end
try
    lock = jsondecode(native2unicode(common.file_bytes(lock_path), 'UTF-8'));
catch ME
    error('contact_closure_gate:EnvironmentLock', ...
        'Campaign environment lock is invalid: %s', ME.message);
end
if ~isstruct(lock) || ~isscalar(lock) || ...
        ~isfield(lock, 'schema') || ...
        ~strcmp(char(string(lock.schema)), ...
            'ttbi-campaign-environment-v2') || ...
        ~isfield(lock, 'matlab_environment') || ...
        ~isfield(lock, 'matlab_environment_sha256') || ...
        ~strcmp(char(string(lock.matlab_environment_sha256)), expected_sha)
    error('contact_closure_gate:EnvironmentLock', ...
        'Campaign environment lock is not the exact reviewed v2 lock.');
end
[locked_sha, locked_descriptor] = ...
    matlab_environment_identity(lock.matlab_environment);
locked = lock.matlab_environment;
if ~strcmp(locked_sha, expected_sha) || ...
        ~strcmp(locked_descriptor, actual_descriptor) || ...
        ~strcmp(actual_sha, expected_sha) || ...
        ~strcmp(char(string(locked.release)), 'R2025b') || ...
        ~strcmp(char(string(locked.version)), ...
            '25.2.0.3177638 (R2025b) Update 5') || ...
        ~strcmp(version('-release'), '2025b')
    error('contact_closure_gate:EnvironmentLock', ...
        ['Closure qualification requires the exact locked MATLAB R2025b ' ...
         'Update 5 numerical stack.']);
end
end
