function run = contact_run_one( ...
        case_info, data, state_index, passage_index, ...
        descriptor_contract, requested_dt_ms)
%CONTACT_RUN_ONE Rebuild and execute one passage at one requested time step.

recon = contact_study_reconstruction();
velocity = double(data.Velocidade(passage_index));
temperature = double(data.Temperatura(passage_index));
n_vehicles = double(case_info.n_vehicles);
n_properties = double(case_info.n_props_varied);
vehicle_draw = reshape(double(data.VehiclesProps(:, :, passage_index)), ...
    [n_vehicles, n_properties]);

Train = A01_Train(velocity, vehicle_draw);
Track = A02_Track();
Beam_seed = struct();
Beam_seed.Prop.L = double(case_info.L_bridge_m);
Beam_seed.Prop.num_spans = double(case_info.num_spans);
Beam = A03_Bridge(Beam_seed);
Beam.Prop.E = Beam.Prop.E - Beam.Prop.E * 0.003 * (temperature - 15);

Damage = recon.damage_descriptor( ...
    case_info, data, state_index, passage_index, descriptor_contract);
Profile_cfg = recon.profile_descriptor( ...
    case_info, data, passage_index, descriptor_contract);
[Calc, Beam, Track] = A04_Options(Beam, Track, Profile_cfg);

% B11 derives samples/s as 2*max_accurate_frq. This override changes only
% integration resolution; no production constant or contact gate is touched.
Calc.Solver.max_accurate_frq = 1 / (2 * requested_dt_ms * 1e-3);
[Sol, Calc, Train] = B00_Calculations(Calc, Train, Track, Beam, Damage);

run = struct();
run.requested_dt_ms = requested_dt_ms;
run.actual_dt_ms = Calc.Solver.dt * 1000;
run.n_samples = Calc.Solver.num_t;
run.t_end_s = double(Calc.Solver.t(end));
run.contact_peak_signed_n = double(Sol.F_tension_max);
run.tension_fraction = double(Sol.tension_frac_max);
run.contact_lost_track = logical(Sol.contactLost_track);
run.contact_lost_bridge = logical(Sol.contactLost);
run.x_rel_m = double(Train.vel * Calc.Solver.t);
[helper_path, helper_expected] = deal( ...
    which('ttbi.wheel_contact_kinematics'), ...
    fullfile(fileparts(mfilename('fullpath')), '+ttbi', ...
        'wheel_contact_kinematics.m'));
if isempty(helper_path) || ...
        ~strcmpi(contact_absolute_path(helper_path), ...
            contact_absolute_path(helper_expected))
    error('contact_closure:WheelsetHelperShadowed', ...
        ['ttbi.wheel_contact_kinematics is missing or shadowed outside ' ...
         'the reviewed source tree.']);
end
[wheelset_acceleration, ~] = ttbi.wheel_contact_kinematics( ...
    Sol.Veh(1), Calc.Veh(1), Train.vel);
% physical8_v1 deploys the first two idealized constrained-wheelset proxy
% channels, not the Eulerian rail-field acceleration formerly used here.
run.signal = double([Sol.Veh(1).A(1:3, :); ...
    wheelset_acceleration(1:2, :); Sol.Veh(1).V(4:6, :)]);
run.channel_names = { ...
    'carbody_vertical_acceleration'; ...
    'front_bogie_vertical_acceleration'; ...
    'rear_bogie_vertical_acceleration'; ...
    'wheelset_1_constrained_vertical_acceleration_proxy'; ...
    'wheelset_2_constrained_vertical_acceleration_proxy'; ...
    'carbody_pitch_rate'; ...
    'front_bogie_pitch_rate'; ...
    'rear_bogie_pitch_rate'};
end
