function plain = contact_gate_plain_report(report)
%CONTACT_GATE_PLAIN_REPORT Convert a completed report to canonical MAT data.
%
% The exact field inventory is intentional. Any added, missing or renamed
% field must be reviewed before it can become durable gate evidence.

expected = { ...
    'study_schema'; 'created_utc'; 'matlab_release'; 'dataset_dir'; ...
    'state_file'; 'state_file_sha256'; 'dataset_integrity'; 'stage'; ...
    'case_name'; 'gen_schema'; 'generation_behavior_version'; ...
    'channel_schema_id'; 'gen_fingerprint'; 'state_index'; ...
    'passage_index'; 'passage_selector'; 'state_uid'; 'state_family'; ...
    'profile_phase_stream_index'; 'profile_phase_seed'; ...
    'dt_requested_ms'; 'gates_n'; 'fraction_gate'; 'common_dx_m'; ...
    'reconstruction_rtol'; 'reconstruction_atol'; 'saved_contact_log'; ...
    'saved_gate_pass'; 'harness_sha256'; 'b66_sha256'; ...
    'solver_source_sha256'; 'solver_execution_root_sha256'; ...
    'current_generator_source_root_sha256'; ...
    'current_matlab_environment_sha256'; 'dry_run'; ...
    'numeric_hash_selfcheck'; 'status'; 'reference_dt_ms'; ...
    'comparison_window_m'; 'descriptor'; 'run_table'; 'channel_table'; ...
    'channel_qoi_table'; 'saved_baseline_table'; ...
    'saved_baseline_note'; 'saved_baseline_mode'; ...
    'direct_reconstruction_pass'; 'rerun_contact_log_1ms'; ...
    'saved_contact_reconstruction_pass'; 'signal_common_sha256'; ...
    'contact_peak_delta_vs_finest_N'; ...
    'tension_fraction_delta_vs_finest'};
if ~isstruct(report) || ~isscalar(report) || ...
        ~isequal(sort(fieldnames(report)), sort(expected))
    error('contact_closure_gate:ReportProjection', ...
        'Completed report field inventory differs from canonical projection.');
end
plain = report;
for field = {'solver_source_sha256', 'run_table', 'channel_table', ...
        'channel_qoi_table', 'saved_baseline_table'}
    plain.(field{1}) = contact_gate_plain_table(report.(field{1}));
end
end
