function names = contact_study_harness_files()
%CONTACT_STUDY_HARNESS_FILES Frozen executable inventory for the study.
%
% Production solver modules have their own root. This set contains every
% harness/helper file whose bytes determine reconstruction and reporting.

names = { ...
    'contact_absolute_path.m'; ...
    'contact_allclose.m'; ...
    'contact_assert_file_snapshot_unchanged.m'; ...
    'contact_assert_manifest_snapshot.m'; ...
    'contact_assert_reviewed_bootstrap.m'; ...
    'contact_assert_snapshot_set_unchanged.m'; ...
    'contact_bytes_sha256.m'; ...
    'contact_capture_file_snapshot.m'; ...
    'contact_case_info_from_snapshot.m'; ...
    'contact_case_state_count.m'; ...
    'contact_case_text.m'; ...
    'contact_channel_metric_table.m'; ...
    'contact_channel_qoi_table.m'; ...
    'contact_closure_common.m'; ...
    'contact_closure_study.m'; ...
    'contact_comparison_path.m'; ...
    'contact_damage_descriptor.m'; ...
    'contact_delete_file_entry_if_present.m'; ...
    'contact_descriptor_summary.m'; ...
    'contact_exact_manifest_text.m'; ...
    'contact_file_bytes.m'; ...
    'contact_file_observation.m'; ...
    'contact_file_sha256.m'; ...
    'contact_filesystem_identity.m'; ...
    'contact_gate_pass.m'; ...
    'contact_indexed_value.m'; ...
    'contact_is_same_or_child.m'; ...
    'contact_java_boolean_value.m'; ...
    'contact_load_mat_bytes.m'; ...
    'contact_load_study_dataset_snapshots.m'; ...
    'contact_logical_scalar.m'; ...
    'contact_maybe_write_report.m'; ...
    'contact_named_file_snapshot.m'; ...
    'contact_nearest_dt_index.m'; ...
    'contact_nonnegative_scalar.m'; ...
    'contact_nonnegative_vector.m'; ...
    'contact_numeric_sha256.m'; ...
    'contact_path_component_is_link_alias.m'; ...
    'contact_positive_scalar.m'; ...
    'contact_positive_vector.m'; ...
    'contact_profile_descriptor.m'; ...
    'contact_qualification_script_identity.m'; ...
    'contact_regular_nonsymlink.m'; ...
    'contact_regular_nonsymlink_directory.m'; ...
    'contact_replace_unique_bytes.m'; ...
    'contact_resolved_module_root.m'; ...
    'contact_run_one.m'; ...
    'contact_run_small_process.m'; ...
    'contact_saved_baseline_comparison.m'; ...
    'contact_select_passage.m'; ...
    'contact_solver_modules.m'; ...
    'contact_solver_source_manifest.m'; ...
    'contact_stable_file_bytes.m'; ...
    'contact_state_text.m'; ...
    'contact_study_harness_files.m'; ...
    'contact_study_harness_root.m'; ...
    'contact_study_metrics.m'; ...
    'contact_study_reconstruction.m'; ...
    'contact_study_report.m'; ...
    'contact_study_solver.m'; ...
    'contact_text_scalar.m'; ...
    'contact_text_sha256.m'; ...
    'contact_unlinked_path_identity.m'; ...
    'contact_utc_now.m'; ...
    'contact_validate_case.m'; ...
    'contact_validate_completion_marker_snapshot.m'; ...
    'contact_validate_host_receipt.m'; ...
    'contact_validate_r11_descriptor.m'; ...
    'contact_verify_dataset_integrity.m'; ...
    'contact_windows_file_identity.m'; ...
    'contact_write_markdown.m'; ...
    'current_matlab_environment.m'; ...
    'generator_source_root.m'; ...
    'matlab_environment_identity.m'; ...
    'validate_dataset_digest_manifest.m'};
end
