function qoi_table = contact_channel_qoi_table( ...
        dt_ms, channel_names, signal_common)
%CONTACT_CHANNEL_QOI_TABLE Build long-format RMS and peak evidence.

n_dt = numel(dt_ms);
n_channels = numel(channel_names);
if size(signal_common, 1) ~= n_channels || ...
        size(signal_common, 3) ~= n_dt
    error('contact_closure:MetricShape', ...
        'Signal cube does not match dt/channel metadata.');
end
rms_value = zeros(n_dt, n_channels);
absolute_peak = zeros(n_dt, n_channels);
for k = 1:n_dt
    values = signal_common(:, :, k);
    rms_value(k, :) = sqrt(mean(values.^2, 2))';
    absolute_peak(k, :) = max(abs(values), [], 2)';
end
row_count = n_dt * n_channels;
qoi_table = table( ...
    repelem(dt_ms(:), n_channels, 1), ...
    repmat(channel_names(:), n_dt, 1), ...
    reshape(rms_value', row_count, 1), ...
    reshape(absolute_peak', row_count, 1), ...
    'VariableNames', {'requested_dt_ms', 'channel', ...
    'signal_rms', 'signal_abs_peak'});
end
