function contact_gate_validate_report_binding(report, row, source_root, ...
        environment_sha, datasets, policy)
%CONTACT_GATE_VALIDATE_REPORT_BINDING Bind a fresh report to the frozen case.
%
% This validation reconnects the inner study evidence to the gate selection,
% exact source/environment identities, dataset manifest and solver execution
% inventory before an acceptance decision is allowed.

common = contact_closure_common();
stage_index = find(strcmp({datasets.stage}, row.stage{1}));
if ~isscalar(stage_index)
    error('contact_closure_gate:ReportIdentity', ...
        'No unique frozen dataset descriptor exists for %s.', row.stage{1});
end
dataset = datasets(stage_index);
required_report = {'study_schema', 'status', 'dataset_dir', 'stage', ...
    'gen_schema', 'generation_behavior_version', 'channel_schema_id', ...
    'gen_fingerprint', 'state_index', 'passage_index', ...
    'state_uid', 'state_family', 'state_file_sha256', ...
    'current_generator_source_root_sha256', ...
    'current_matlab_environment_sha256', 'dataset_integrity', ...
    'saved_contact_log', 'rerun_contact_log_1ms', 'run_table', ...
    'harness_sha256', 'b66_sha256', 'solver_source_sha256', ...
    'solver_execution_root_sha256'};
if ~isstruct(report) || ~isscalar(report) || ...
        ~all(isfield(report, required_report)) || ...
        ~strcmp(report.study_schema, 'contact-closure-v3') || ...
        ~strcmp(report.status, 'COMPLETED') || ...
        ~strcmp(report.dataset_dir, row.dataset_dir{1}) || ...
        ~strcmp(report.stage, row.stage{1}) || ...
        ~strcmp(report.gen_schema, 'audit-2026-08-09-r12') || ...
        ~strcmp(report.generation_behavior_version, 'generation-rules-v8') || ...
        ~strcmp(report.channel_schema_id, 'physical8_v1') || ...
        ~strcmp(report.gen_fingerprint, dataset.gen_fingerprint) || ...
        report.state_index ~= row.state_index || ...
        report.passage_index ~= row.passage_index || ...
        ~strcmp(report.state_uid, row.state_uid{1}) || ...
        ~strcmp(report.state_family, row.state_family{1}) || ...
        ~strcmp(report.state_file_sha256, row.state_file_sha256{1}) || ...
        ~strcmp(report.current_generator_source_root_sha256, source_root) || ...
        ~strcmp(report.current_matlab_environment_sha256, environment_sha) || ...
        ~strcmp(report.harness_sha256, common.study_harness_root()) || ...
        ~strcmp(report.b66_sha256, common.file_sha256( ...
            fullfile(fileparts(mfilename('fullpath')), ...
                'B66_ContactForce.m'))) || ...
        ~strcmp(report.solver_execution_root_sha256, ...
            contact_gate_validate_solver_execution_manifest( ...
                report.solver_source_sha256))
    error('contact_closure_gate:ReportIdentity', ...
        ['Inner closure report does not match the frozen outer ' ...
         'stage/state/passage/source/environment identity.']);
end
integrity = report.dataset_integrity;
required_integrity = {'status', 'manifest_root', ...
    'state_digest_match', 'marker_match', 'state_table_match', ...
    'identity_table_match', 'case_info_sha256', ...
    'damage_states_sha256', 'completion_marker_sha256', ...
    'file_digests_sha256', 'qualification_host_receipt_sha256'};
if ~isstruct(integrity) || ~isscalar(integrity) || ...
        ~all(isfield(integrity, required_integrity)) || ...
        ~strcmp(integrity.status, 'VERIFIED') || ...
        ~strcmp(integrity.manifest_root, ...
            dataset.dataset_content_root_sha256) || ...
        ~all([integrity.state_digest_match, integrity.marker_match, ...
            integrity.state_table_match, integrity.identity_table_match]) || ...
        ~strcmp(integrity.case_info_sha256, dataset.case_info_sha256) || ...
        ~strcmp(integrity.damage_states_sha256, ...
            dataset.damage_states_sha256) || ...
        ~strcmp(integrity.completion_marker_sha256, ...
            dataset.completion_marker_sha256) || ...
        ~strcmp(integrity.file_digests_sha256, ...
            dataset.file_digests_sha256) || ...
        ~strcmp(integrity.qualification_host_receipt_sha256, ...
            dataset.qualification_host_receipt_sha256)
    error('contact_closure_gate:ReportIdentity', ...
        'Inner closure report is not bound to the frozen dataset artifacts.');
end
saved = double(report.saved_contact_log(:)');
rerun = double(report.rerun_contact_log_1ms(:)');
frozen = [row.saved_contact_lost_bridge, ...
    row.saved_contact_lost_track, row.saved_tension_fraction, ...
    row.saved_peak_signed_N];
if numel(saved) ~= 4 || numel(rerun) ~= 4 || ...
        ~isequal(saved(1:2), frozen(1:2)) || ...
        ~isequal(rerun(1:2), frozen(1:2)) || ...
        ~common.allclose(saved(3:4), frozen(3:4), ...
            policy.reconstruction_rtol, policy.reconstruction_atol) || ...
        ~common.allclose(rerun(3:4), frozen(3:4), ...
            policy.reconstruction_rtol, policy.reconstruction_atol)
    error('contact_closure_gate:ReportIdentity', ...
        ['Saved/1-ms reconstructed contact vector does not match the frozen ' ...
         'selection row.']);
end
run = report.run_table;
if height(run) ~= 3 || ...
        ~isequal(double(run.contact_lost_bridge(1)), rerun(1)) || ...
        ~isequal(double(run.contact_lost_track(1)), rerun(2)) || ...
        ~common.allclose( ...
            [double(run.tension_fraction(1)), ...
             double(run.peak_contact_signed_N(1))], ...
            rerun(3:4), policy.reconstruction_rtol, ...
            policy.reconstruction_atol)
    error('contact_closure_gate:ReportIdentity', ...
        'The report 1-ms row disagrees with its reconstruction record.');
end
end
