function contact_write_markdown(path, report)
%CONTACT_WRITE_MARKDOWN Render the appendix view of a completed study report.

fid = fopen(path, 'w');
if fid < 0
    error('contact_closure:OutputOpenFailed', ...
        'Could not open report for writing: %s', path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Wheel-rail contact closure: %s state %d, passage %d\n\n', ...
    report.stage, report.state_index, report.passage_index);
fprintf(fid, '- Status: `%s`\n', report.status);
fprintf(fid, '- Generated UTC: `%s`\n', report.created_utc);
fprintf(fid, '- MATLAB: `%s`\n', report.matlab_release);
fprintf(fid, '- Generator schema: `%s`\n', report.gen_schema);
fprintf(fid, '- Generator fingerprint: `%s`\n', report.gen_fingerprint);
fprintf(fid, '- State UID/family: `%s` / `%s`\n', ...
    report.state_uid, report.state_family);
fprintf(fid, '- State-file SHA-256: `%s`\n', report.state_file_sha256);
fprintf(fid, '- Dataset integrity: `%s`\n', report.dataset_integrity.status);
if strcmp(report.dataset_integrity.status, 'VERIFIED')
    fprintf(fid, '- Dataset manifest root: `%s`\n', ...
        report.dataset_integrity.manifest_root);
end
fprintf(fid, '- Harness SHA-256 (study executable set root): `%s`\n', ...
    report.harness_sha256);
fprintf(fid, '- B66 SHA-256: `%s`\n\n', report.b66_sha256);
fprintf(fid, '- Current generator source root: `%s`\n', ...
    report.current_generator_source_root_sha256);
fprintf(fid, '- Current MATLAB environment: `%s`\n\n', ...
    report.current_matlab_environment_sha256);
fprintf(fid, '## Reconstructed passage\n\n');
fprintf(fid, '- Velocity: `%.8g km/h`\n', ...
    report.descriptor.velocity_kmh);
fprintf(fid, '- Temperature: `%.8g C`\n', ...
    report.descriptor.temperature_C);
fprintf(fid, '- Scour vector: `%s`\n', ...
    mat2str(report.descriptor.scour_vector, 8));
fprintf(fid, '- Bearing vector: `%s Nm/rad`\n', ...
    mat2str(report.descriptor.bearing_vector_Nm_rad, 8));
fprintf(fid, '- Crack row: `%s`\n', ...
    mat2str(report.descriptor.crack_row, 8));
fprintf(fid, '- Profile: `%s`, value `%.8g`, phase seed `%.0f`\n', ...
    report.descriptor.profile_mode, report.descriptor.profile_value, ...
    report.descriptor.profile_phase_seed);
fprintf(fid, '- Track EOV present: `%s`\n', ...
    string(report.descriptor.has_track_eov));
fprintf(fid, '- Wheel flats/polygonization rows: `%d/%d`\n\n', ...
    report.descriptor.n_flats, report.descriptor.n_polygonization);
fprintf(fid, '## Solver source manifest\n\n');
fprintf(fid, '| module | SHA-256 |\n|---|---|\n');
for source_index = 1:height(report.solver_source_sha256)
    fprintf(fid, '| %s | `%s` |\n', ...
        report.solver_source_sha256.module{source_index}, ...
        report.solver_source_sha256.sha256{source_index});
end
fprintf(fid, '\n');
fprintf(fid, ['Diagnostic acceptance requires peak tension <= the indicated ' ...
    'gate and tension fraction <= %.6g. These gates do not alter the solver.\n\n'], ...
    report.fraction_gate);
fprintf(fid, ['Saved contact row `[bridge_lost, track_lost, fraction, ' ...
    'signed_peak_N]`: `%s`.\n\n'], mat2str(report.saved_contact_log, 8));

if report.dry_run
    fprintf(fid, 'Dry run only: descriptors validated; no solver was invoked.\n');
    return
end

fprintf(fid, '| requested dt (ms) | actual dt (ms) | samples | peak tension (N) | fraction |');
for g = report.gates_n
    fprintf(fid, ' gate %.0f N |', g);
end
fprintf(fid, '\n|---:|---:|---:|---:|---:|');
fprintf(fid, '%s', repmat('---:|', 1, numel(report.gates_n)));
fprintf(fid, '\n');
for r = 1:height(report.run_table)
    fprintf(fid, '| %.6g | %.6g | %d | %.8g | %.8g |', ...
        report.run_table.requested_dt_ms(r), ...
        report.run_table.actual_dt_ms(r), report.run_table.n_samples(r), ...
        report.run_table.peak_tension_N(r), ...
        report.run_table.tension_fraction(r));
    for g = 1:numel(report.gates_n)
        gate_name = matlab.lang.makeValidName( ...
            sprintf('pass_gate_%g_N', report.gates_n(g)));
        fprintf(fid, ' %s |', string(report.run_table.(gate_name)(r)));
    end
    fprintf(fid, '\n');
end

fprintf(fid, '\n## Signal convergence against finest dt\n\n');
fprintf(fid, '| dt (ms) | channel | NRMSE | normalized max error | correlation |\n');
fprintf(fid, '|---:|---|---:|---:|---:|\n');
for r = 1:height(report.channel_table)
    fprintf(fid, '| %.6g | %s | %.8g | %.8g | %.8g |\n', ...
        report.channel_table.requested_dt_ms(r), ...
        report.channel_table.channel{r}, ...
        report.channel_table.nrmse_vs_finest(r), ...
        report.channel_table.nmax_vs_finest(r), ...
        report.channel_table.correlation_vs_finest(r));
end

if ~isempty(report.saved_baseline_table)
    fprintf(fid, '\n## Current 1 ms rerun versus saved raw passage\n\n');
    fprintf(fid, '- Comparison mode: `%s`\n', report.saved_baseline_mode);
    fprintf(fid, '- Direct reconstruction PASS: `%s`\n', ...
        string(report.direct_reconstruction_pass));
    fprintf(fid, '- Saved-contact reconstruction PASS: `%s`\n\n', ...
        string(report.saved_contact_reconstruction_pass));
    fprintf(fid, ['| channel | NRMSE | normalized max error | correlation | ' ...
        'max abs | max rel | max tolerance ratio | within tolerance |\n']);
    fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|\n');
    for r = 1:height(report.saved_baseline_table)
        fprintf(fid, ...
            '| %s | %.8g | %.8g | %.8g | %.8g | %.8g | %.8g | %s |\n', ...
            report.saved_baseline_table.channel{r}, ...
            report.saved_baseline_table.nrmse_rerun_vs_saved(r), ...
            report.saved_baseline_table.nmax_rerun_vs_saved(r), ...
            report.saved_baseline_table.correlation_rerun_vs_saved(r), ...
            report.saved_baseline_table.max_abs_rerun_vs_saved(r), ...
            report.saved_baseline_table.max_rel_rerun_vs_saved(r), ...
            report.saved_baseline_table.max_tolerance_ratio(r), ...
            string(report.saved_baseline_table.within_tolerance(r)));
    end
    fprintf(fid, '\n%s\n', report.saved_baseline_note);
end
end
