function names = contact_solver_modules()
%CONTACT_SOLVER_MODULES Frozen 37-module production solver inventory.
%
% CONTRACT: this file is the single source of truth for the exact set of
% production solver modules that a contact-closure refinement run executes.
% The study's solver-source manifest (contact_study_solver) hashes exactly
% these modules and requires each to appear exactly once in the generator
% source digest; contact_gate_validate_solver_execution_manifest re-resolves
% and re-hashes the same inventory before the gate accepts a study report.
% The independent Python checker pins the identical list as SOLVER_MODULES
% in check_contact_closure_gate.py.
%
% RATIONALE: the two MATLAB consumers previously duplicated this list
% verbatim inside their monoliths, so an edit could silently desynchronise
% what the study hashed from what the gate revalidated.  Keeping one frozen
% list makes any inventory change a single reviewable diff on all sides.
%
% Order is significant: the solver execution root is the SHA-256 of the
% LF-joined "<module>:<sha256>" lines in exactly this order.
%
% THE LAST TWO ENTRIES exist because the A0x definition files are not leaves.
% Both are reached unconditionally from contact_study_solver (A01_Train and
% A02_Track are called for every case of every gate stage):
%
%   * A01_Train calls TrainProp_ObrienCalibrate once per vehicle;
%   * A02_Track executes TrackProp_Zhai_et_al_WithBallastOnBridge.
%
% Their canonical bytes were always inside the broad generator source root,
% but until R11 they were absent from the executed-module path/hash/shadow
% checks, so a same-named file earlier on the MATLAB path could execute while
% the evidence kept quoting the reviewed repository blob.
%
% Both property dependencies are now ordinary function calls. MATLAB's static
% dependency analysis must therefore discover all 37 entries; the completeness
% smoke rejects any future source that reintroduces run/eval-style dispatch.

names = { ...
    'A01_Train'; ...
    'A02_Track'; ...
    'A03_Bridge'; ...
    'A04_Options'; ...
    'B00_Calculations'; ...
    'B01_ElementsAndCoordinates'; ...
    'B02_BoundaryConditions'; ...
    'B03_BeamMatrices'; ...
    'B07_OptionsProcessing'; ...
    'B08_VehFreq'; ...
    'B09_BeamFrq'; ...
    'B10_EndTime'; ...
    'B11_TimeSpaceDiscretization'; ...
    'B14_EqVertNodalForce'; ...
    'B17_CalcUat'; ...
    'B18_TrainVehEq'; ...
    'B19_GenerateProfile'; ...
    'B24_BeamDamping'; ...
    'B25_WheelProfiles'; ...
    'B31_BeamBM'; ...
    'B33_BeamShear'; ...
    'B43_ModelGeometry'; ...
    'B47_VehStaticLoads'; ...
    'B49_BeamDeformation'; ...
    'B50_ElementNumOfForce'; ...
    'B51_RailVariables'; ...
    'B53_BeamAcceleration'; ...
    'B54_ModelMatrices'; ...
    'B54_TrackVectors'; ...
    'B55_ModelBC'; ...
    'B56_ModelFrq'; ...
    'B58_ResultsBeamSections'; ...
    'B64_Coupled_InitialStatic'; ...
    'B65_DynamicCalcCoupledFaster'; ...
    'B66_ContactForce'; ...
    'TrackProp_Zhai_et_al_WithBallastOnBridge'; ...
    'TrainProp_ObrienCalibrate'};
end
