function environment = current_matlab_environment()
%CURRENT_MATLAB_ENVIRONMENT Capture the executable MATLAB numerical stack.
%   The returned scalar struct deliberately contains only the fields consumed
%   by matlab_environment_identity.  Release equality alone is insufficient:
%   Update level, architecture, BLAS/LAPACK, and the two stochastic/parallel
%   toolboxes can all affect generated samples or floating-point trajectories.

    release_info = matlabRelease;
    full_version = char(version);
    matlab_product_version = regexp(full_version, '^\d+\.\d+', ...
        'match', 'once');
    statistics_info = ver('stats');
    parallel_info = ver('parallel');
    if isempty(matlab_product_version) || numel(statistics_info) ~= 1 || ...
            numel(parallel_info) ~= 1
        error('current_matlab_environment:Products', ...
            ['MATLAB, Statistics and Machine Learning Toolbox, and Parallel ' ...
             'Computing Toolbox must each be installed exactly once.']);
    end

    environment = struct( ...
        'release', char(release_info.Release), ...
        'version', full_version, ...
        'arch', char(computer('arch')), ...
        'blas', strtrim(char(version('-blas'))), ...
        'lapack', strtrim(char(version('-lapack'))), ...
        'matlab_product_version', matlab_product_version, ...
        'statistics_toolbox_version', char(statistics_info.Version), ...
        'parallel_toolbox_version', char(parallel_info.Version));

    % Validate field set and types immediately, not only when A00 hashes it.
    matlab_environment_identity(environment);
end
