function environment = current_matlab_environment()
%CURRENT_MATLAB_ENVIRONMENT Qualify capabilities and record the MATLAB stack.
%   Exact release/build/toolbox versions are provenance, not eligibility.
%   Production eligibility depends on the functions and licenses actually used
%   by the generator; numerical/physical smokes provide the end-to-end check.

    full_version = char(version);
    matlab_product_version = regexp(full_version, '^\d+\.\d+', ...
        'match', 'once');
    statistics_info = ver('stats');
    parallel_info = ver('parallel');
    if isempty(matlab_product_version) || isempty(statistics_info) || ...
            isempty(parallel_info)
        error('current_matlab_environment:Products', ...
            ['MATLAB, Statistics and Machine Learning Toolbox, and Parallel ' ...
             'Computing Toolbox must be installed.']);
    end
    if ~license('test', 'Statistics_Toolbox') || ...
            ~license('test', 'Distrib_Computing_Toolbox')
        error('current_matlab_environment:Licenses', ...
            ['Statistics and Machine Learning Toolbox and Parallel Computing ' ...
             'Toolbox licenses must be available on this host.']);
    end
    required_functions = {'lhsdesign', 'poissrnd', 'wblrnd', 'RandStream', ...
        'jsonencode', 'jsondecode', 'matfile', 'parpool'};
    missing_functions = required_functions(cellfun( ...
        @(name) exist(name, 'file') == 0 && exist(name, 'class') == 0 && ...
            exist(name, 'builtin') == 0, ...
        required_functions));
    if ~isempty(missing_functions)
        error('current_matlab_environment:Capabilities', ...
            'Required MATLAB APIs are unavailable: %s.', ...
            strjoin(missing_functions, ', '));
    end

    environment = struct( ...
        'release', ['R' char(version('-release'))], ...
        'version', full_version, ...
        'arch', char(computer('arch')), ...
        'blas', strtrim(char(version('-blas'))), ...
        'lapack', strtrim(char(version('-lapack'))), ...
        'matlab_product_version', matlab_product_version, ...
        'statistics_toolbox_version', char(statistics_info(1).Version), ...
        'parallel_toolbox_version', char(parallel_info(1).Version));

    % Validate field set and types immediately, not only when A00 hashes it.
    matlab_environment_identity(environment);
end
