function rows = numerical_vv_support_alignment(geometries, mesh_sequences)
%NUMERICAL_VV_SUPPORT_ALIGNMENT Audit internal supports on bridge meshes.
%
% Mesh resolution is geometry-specific because the 60 m bridge needs three
% bridge elements per 0.6 m sleeper bay to place its 20 m internal supports
% on nodes, whereas the 99.6 m bridge is aligned with two.  Bridge and rail
% spacings are therefore retained separately; only the bridge grid controls
% support realization in this audit.

required_geometry = {'id', 'bridge_length_m', 'num_spans'};
required_sequence = {'geometry_id', 'level_id', ...
    'bridge_elements_per_sleeper_bay', ...
    'rail_elements_per_sleeper_bay', ...
    'bridge_nominal_h_m', 'rail_nominal_h_m'};
if ~isstruct(geometries) || ~all(isfield(geometries, required_geometry)) || ...
        ~isstruct(mesh_sequences) || ...
        ~all(isfield(mesh_sequences, required_sequence))
    error('numerical_vv:BadSupportAlignmentContract', ...
        'Geometry and geometry-specific mesh structures do not match the schema.');
end

row_count = 0;
for m = 1:numel(mesh_sequences)
    geometry_index = strcmp({geometries.id}, ...
        mesh_sequences(m).geometry_id);
    if nnz(geometry_index) ~= 1
        error('numerical_vv:UnknownMeshGeometry', ...
            'Mesh sequence %s/%s has no unique registered geometry.', ...
            mesh_sequences(m).geometry_id, mesh_sequences(m).level_id);
    end
    row_count = row_count+geometries(geometry_index).num_spans+1;
end

template = struct( ...
    'geometry_id', '', 'mesh_level', '', ...
    'bridge_elements_per_sleeper_bay', 0, ...
    'rail_elements_per_sleeper_bay', 0, ...
    'bridge_nominal_h_m', 0, 'rail_nominal_h_m', 0, ...
    'bridge_actual_h_m', 0, 'support_number', 0, ...
    'nominal_coordinate_m', 0, 'realized_node_number', 0, ...
    'realized_coordinate_m', 0, 'signed_offset_m', 0, ...
    'absolute_offset_m', 0, 'alignment_tolerance_m', 0, ...
    'exactly_aligned_for_qualification', false);
rows = repmat(template, row_count, 1);
row = 0;
identities = strings(numel(mesh_sequences), 1);
for m = 1:numel(mesh_sequences)
    sequence = mesh_sequences(m);
    identities(m) = string(sequence.geometry_id)+"/"+string(sequence.level_id);
    geometry_index = strcmp({geometries.id}, sequence.geometry_id);
    geometry = geometries(geometry_index);
    L = double(geometry.bridge_length_m);
    n_spans = double(geometry.num_spans);
    h_requested = double(sequence.bridge_nominal_h_m);
    rail_h_requested = double(sequence.rail_nominal_h_m);
    bridge_per_bay = double(sequence.bridge_elements_per_sleeper_bay);
    rail_per_bay = double(sequence.rail_elements_per_sleeper_bay);
    if any(~isfinite([L, n_spans, h_requested, rail_h_requested, ...
            bridge_per_bay, rail_per_bay])) || ...
            any([L, n_spans, h_requested, rail_h_requested, ...
                bridge_per_bay, rail_per_bay] <= 0) || ...
            any([n_spans, bridge_per_bay, rail_per_bay] ~= ...
                floor([n_spans, bridge_per_bay, rail_per_bay]))
        error('numerical_vv:InvalidMeshSequence', ...
            'Mesh sequence %s has invalid geometry or spacing values.', ...
            identities(m));
    end
    spacing_tolerance = 256*eps(1);
    if abs(h_requested-0.6/bridge_per_bay) > spacing_tolerance || ...
            abs(rail_h_requested-0.6/rail_per_bay) > spacing_tolerance
        error('numerical_vv:MeshSpacingCountMismatch', ...
            'Mesh sequence %s is inconsistent with the 0.6 m sleeper bay.', ...
            identities(m));
    end
    n_elements_real = L/h_requested;
    n_elements = round(n_elements_real);
    if abs(n_elements_real-n_elements) > 256*eps(max(n_elements_real, 1))
        error('numerical_vv:BridgeLengthNotNested', ...
            '%s is not divisible by the bridge spacing for %s.', ...
            geometry.id, sequence.level_id);
    end
    h_actual = L/n_elements;
    % B01 forms its coordinates using cumulative element lengths.
    nodes = [0, cumsum(ones(1, n_elements)*h_actual)];
    nominal_supports = linspace(0, L, n_spans+1);
    summation_roundoff_factor = max(256, 2*n_elements);
    tolerance = summation_roundoff_factor*eps(max(L, 1));
    for s = 1:numel(nominal_supports)
        [~, node_index] = min(abs(nodes-nominal_supports(s)));
        realized = nodes(node_index);
        offset = realized-nominal_supports(s);
        row = row+1;
        rows(row) = struct( ...
            'geometry_id', geometry.id, ...
            'mesh_level', sequence.level_id, ...
            'bridge_elements_per_sleeper_bay', bridge_per_bay, ...
            'rail_elements_per_sleeper_bay', rail_per_bay, ...
            'bridge_nominal_h_m', h_requested, ...
            'rail_nominal_h_m', rail_h_requested, ...
            'bridge_actual_h_m', h_actual, ...
            'support_number', s, ...
            'nominal_coordinate_m', nominal_supports(s), ...
            'realized_node_number', node_index, ...
            'realized_coordinate_m', realized, ...
            'signed_offset_m', offset, ...
            'absolute_offset_m', abs(offset), ...
            'alignment_tolerance_m', tolerance, ...
            'exactly_aligned_for_qualification', abs(offset) <= tolerance);
    end
end
if numel(unique(identities)) ~= numel(identities)
    error('numerical_vv:DuplicateMeshSequence', ...
        'Each geometry/mesh-level identity must be unique.');
end
if row ~= row_count
    error('numerical_vv:SupportAlignmentRowCount', ...
        'Internal support-alignment row-count mismatch.');
end
end
