function receipt = numerical_vv_validate_package(package_dir, varargin)
%NUMERICAL_VV_VALIDATE_PACKAGE Verify one numerical-V&V artifact package.
%
% This validator is intentionally limited to nonqualifying micro-package
% integrity.  RequireQualification always fails: no independent, source-bound
% scientific qualification verifier has been implemented yet.

parser = inputParser;
addRequired(parser, 'package_dir', @(v) ischar(v) || ...
    (isstring(v) && isscalar(v)));
addParameter(parser, 'AllowNonqualifyingMicro', false, @local_logical_scalar);
addParameter(parser, 'RequireQualification', false, @local_logical_scalar);
parse(parser, package_dir, varargin{:});
opt = parser.Results;
if logical(opt.RequireQualification)
    error('numerical_vv:QualificationVerifierNotImplemented', ...
        ['Qualification verification is not implemented. This validator ' ...
         'can authenticate only an explicitly nonqualifying micro package.']);
end
package_file = java.io.File(char(package_dir));
package_absolute = char(package_file.getAbsolutePath());
package_canonical = char(package_file.getCanonicalPath());
if ~local_same_path(package_absolute, package_canonical)
    error('numerical_vv:AliasedPackageRoot', ...
        'Package root must not traverse a symlink, junction, or alias.');
end
package_dir = package_canonical;
if exist(package_dir, 'dir') ~= 7
    error('numerical_vv:MissingPackage', ...
        'Package directory does not exist: %s', package_dir);
end
if exist(fullfile(package_dir, '_RUN_INCOMPLETE'), 'file') == 2
    error('numerical_vv:IncompleteRun', ...
        'Package retains _RUN_INCOMPLETE and is invalid.');
end
manifest_path = fullfile(package_dir, 'manifest.json');
verdict_path = fullfile(package_dir, 'vv_verdict.json');
complete_path = fullfile(package_dir, '_RUN_COMPLETE');
local_require_file(manifest_path);
local_require_file(verdict_path);
local_require_file(complete_path);
manifest = jsondecode(fileread(manifest_path));
verdict = jsondecode(fileread(verdict_path));
if ~strcmp(manifest.schema, 'numerical-vv-manifest-v1') || ...
        ~strcmp(verdict.schema, 'numerical-vv-verdict-v1')
    error('numerical_vv:BadSchema', 'Manifest or verdict schema mismatch.');
end
if ~isfield(manifest, 'run_kind') || ...
        ~strcmp(manifest.run_kind, 'nonqualifying_micro')
    error('numerical_vv:UnsupportedRunKind', ...
        ['This validator accepts only run_kind=nonqualifying_micro; it ' ...
         'cannot authenticate or qualify a scientific V&V run.']);
end
marker = fileread(complete_path);
expected_manifest_sha = numerical_vv_file_sha256(manifest_path);
if ~contains(marker, ['manifest_sha256=', expected_manifest_sha])
    error('numerical_vv:CompletionMarkerMismatch', ...
        'Completion marker does not authenticate manifest.json.');
end

inventory_names = cell(numel(manifest.artifacts), 1);
for k = 1:numel(manifest.artifacts)
    relative = manifest.artifacts(k).path;
    if contains(relative, '/') || contains(relative, '\') || ...
            any(strcmp(relative, {'.', '..'}))
        error('numerical_vv:UnsafeArtifactPath', ...
            'Artifact inventory contains a non-flat/unsafe path.');
    end
    inventory_names{k} = relative;
    path = fullfile(package_dir, relative);
    local_require_file(path);
    info = dir(path);
    if info.bytes ~= manifest.artifacts(k).bytes || ...
            ~strcmp(numerical_vv_file_sha256(path), ...
                manifest.artifacts(k).sha256)
        error('numerical_vv:ArtifactDigestMismatch', ...
            'Artifact digest/size mismatch: %s', relative);
    end
end
if numel(unique(inventory_names)) ~= numel(inventory_names)
    error('numerical_vv:DuplicateArtifact', ...
        'Manifest artifact paths must be unique.');
end
actual_entries = dir(package_dir);
actual_entries = actual_entries(~ismember( ...
    {actual_entries.name}, {'.', '..'}));
extra_directories = actual_entries([actual_entries.isdir]);
if ~isempty(extra_directories)
    error('numerical_vv:UnexpectedDirectory', ...
        'Package must be flat and contain no nested directories.');
end
actual = sort(reshape({actual_entries.name}, [], 1));
expected = sort([inventory_names; {'manifest.json'; '_RUN_COMPLETE'}]);
if ~isequal(actual, expected)
    error('numerical_vv:ArtifactInventoryMismatch', ...
        'Package has missing or extra files relative to manifest inventory.');
end

core_micro = { ...
    'case_table.csv'; 'descriptor_hashes.csv'; ...
    'static_equilibrium_checks.csv'; 'modal_matching.csv'; ...
    'mesh_scalar_qoi.csv'; 'time_grid_realization.csv'; ...
    'support_alignment.csv'; 'tolerance_rationale.csv'; ...
    'raw_bridge_fixture.mat'; 'protocol_snapshot.json'; ...
    'input_descriptor.json'; 'vv_verdict.json'};
if any(~ismember(core_micro, inventory_names))
    error('numerical_vv:MissingMicroArtifact', ...
        'Nonqualifying micro package lacks a required foundation artifact.');
end
P = numerical_vv_protocol_definition();
protocol_snapshot = jsondecode(fileread( ...
    fullfile(package_dir, 'protocol_snapshot.json')));
local_validate_protocol_snapshot(protocol_snapshot, P);
support_table = readtable(fullfile(package_dir, 'support_alignment.csv'), ...
    'Delimiter', ',', 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
local_validate_support_table(support_table, P);

case_table = readtable(fullfile(package_dir, 'case_table.csv'), ...
    'Delimiter', ',', 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
required_case_columns = { ...
    'case_id', 'geometry_id', 'study_kind', 'mesh_level', ...
    'bridge_length_m', ...
    'bridge_elements_per_sleeper_bay', ...
    'rail_elements_per_sleeper_bay', ...
    'bridge_nominal_h_m', 'rail_nominal_h_m', ...
    'bridge_actual_h_m', 'rail_actual_h_m', ...
    'bridge_mesh_executed', 'rail_mesh_executed', ...
    'bridge_n_elements', 'bridge_n_nodes', ...
    'max_support_offset_m', 'support_alignment_pass', ...
    'source_commit', 'input_hash'};
if ~all(ismember(required_case_columns, ...
        case_table.Properties.VariableNames))
    error('numerical_vv:BadMicroCaseSchema', ...
        'Case table does not retain separate bridge/rail mesh fields.');
end
if height(case_table) ~= manifest.completed_mesh_case_count || ...
        numel(unique(case_table.case_id)) ~= height(case_table)
    error('numerical_vv:CaseInventoryMismatch', ...
        'Case table count/identity does not match the manifest.');
end
counts = [case_table.bridge_elements_per_sleeper_bay, ...
    case_table.rail_elements_per_sleeper_bay];
spacings = [case_table.bridge_nominal_h_m, ...
    case_table.rail_nominal_h_m, case_table.bridge_actual_h_m];
if any(~isfinite(counts), 'all') || any(counts <= 0, 'all') || ...
        any(counts ~= floor(counts), 'all') || ...
        any(~isfinite(spacings), 'all') || any(spacings <= 0, 'all')
    error('numerical_vv:BadRealizedMesh', ...
        'Case table contains an invalid bridge/rail count or spacing.');
end
bridge_executed = double(case_table.bridge_mesh_executed);
rail_executed = double(case_table.rail_mesh_executed);
if any(~ismember(bridge_executed, [0, 1])) || ...
        any(~ismember(rail_executed, [0, 1])) || ...
        any(bridge_executed ~= 1) || any(rail_executed ~= 0) || ...
        any(~isnan(case_table.rail_actual_h_m))
    error('numerical_vv:MicroRailExecutionMismatch', ...
        ['The bridge-only micro must record a realized bridge mesh and an ' ...
         'explicitly unexecuted rail mesh with rail_actual_h_m=NaN.']);
end
if any(case_table.source_commit ~= string(manifest.source_commit)) || ...
        any(case_table.input_hash ~= string(manifest.input_hash))
    error('numerical_vv:CaseIdentityMismatch', ...
        'Case source/input identity does not match the manifest.');
end
local_validate_source_locked_cases(case_table, P);

input_descriptor = jsondecode(fileread( ...
    fullfile(package_dir, 'input_descriptor.json')));
local_validate_input_descriptor(input_descriptor, manifest, case_table, P);

descriptor_table = readtable( ...
    fullfile(package_dir, 'descriptor_hashes.csv'), ...
    'Delimiter', ',', 'TextType', 'string', ...
    'VariableNamingRule', 'preserve');
required_descriptor_columns = { ...
    'case_id', 'geometry_id', 'mesh_level', 'descriptor_schema', ...
    'descriptor_json', 'descriptor_hash', ...
    'source_commit', 'input_hash'};
if ~all(ismember(required_descriptor_columns, ...
        descriptor_table.Properties.VariableNames)) || ...
        height(descriptor_table) ~= height(case_table) || ...
        numel(unique(descriptor_table.case_id)) ~= height(descriptor_table) || ...
        ~isequal(sort(descriptor_table.case_id), sort(case_table.case_id))
    error('numerical_vv:DescriptorInventoryMismatch', ...
        'Descriptor preimages do not match the case inventory.');
end
descriptors = cell(height(descriptor_table), 1);
for k = 1:height(descriptor_table)
    computed = numerical_vv_sha256_bytes(unicode2native( ...
        char(descriptor_table.descriptor_json(k)), 'UTF-8'));
    if ~strcmp(computed, descriptor_table.descriptor_hash(k))
        error('numerical_vv:DescriptorDigestMismatch', ...
            'Descriptor SHA-256 does not match its retained preimage.');
    end
    case_index = find(case_table.case_id == descriptor_table.case_id(k));
    if numel(case_index) ~= 1 || ...
            descriptor_table.source_commit(k) ~= ...
                case_table.source_commit(case_index) || ...
            descriptor_table.input_hash(k) ~= case_table.input_hash(case_index)
        error('numerical_vv:DescriptorIdentityMismatch', ...
            'Descriptor source/input identity differs from its case row.');
    end
    try
        descriptor = jsondecode(char(descriptor_table.descriptor_json(k)));
    catch ME
        error('numerical_vv:DescriptorSemanticMismatch', ...
            'Descriptor preimage is not valid JSON: %s', ME.message);
    end
    local_validate_descriptor(descriptor, descriptor_table(k, :), ...
        case_table(case_index, :));
    descriptors{k} = descriptor;
end

raw = load(fullfile(package_dir, 'raw_bridge_fixture.mat'), 'runs');
if ~isfield(raw, 'runs')
    error('numerical_vv:RawFixtureMismatch', ...
        'raw_bridge_fixture.mat does not contain runs.');
end
local_validate_raw_fixture(raw.runs, case_table, descriptor_table, ...
    descriptors, input_descriptor, P);

if ~logical(opt.AllowNonqualifyingMicro)
    error('numerical_vv:NonqualifyingMicro', ...
        ['Package is an integrity-checkable nonqualifying micro. ' ...
         'Explicit opt-in is required.']);
end
if manifest.numerical_verification_claim_authorized || ...
        manifest.physical_validation_claim_authorized || ...
        verdict.numerical_verification_claim_authorized || ...
        verdict.physical_validation_claim_authorized || ...
        verdict.production_resolution_qualified || ...
        ~strcmp(verdict.overall_status, 'UNVERIFIED')
    error('numerical_vv:MicroClaimEscalation', ...
        'Nonqualifying micro contains an unauthorized qualification claim.');
end

receipt = struct();
receipt.schema = 'numerical-vv-package-receipt-v1';
receipt.package_dir = package_dir;
receipt.manifest_sha256 = expected_manifest_sha;
receipt.run_kind = manifest.run_kind;
receipt.integrity_pass = true;
receipt.qualification_pass = false;
receipt.status = 'NONQUALIFYING_INTEGRITY_PASS';
receipt.numerical_verification_claim_authorized = false;
receipt.physical_validation_claim_authorized = false;
end

function local_validate_protocol_snapshot(snapshot, P)
required = {'schema', 'sleeper_spacing_m', 'mesh_levels', 'geometries', ...
    'geometry_mesh_sequences', 'registered_support_alignment', ...
    'support_alignment_policy', 'micro_run_kind', ...
    'max_gci_observed_order', 'qualification_verifier_implemented', ...
    'qualification_ready'};
local_require_struct_fields(snapshot, required, ...
    'numerical_vv:ProtocolSnapshotMismatch', 'protocol snapshot');
if ~strcmp(snapshot.schema, P.schema) || ...
        ~local_close(snapshot.sleeper_spacing_m, P.sleeper_spacing_m) || ...
        ~strcmp(snapshot.micro_run_kind, P.micro_run_kind) || ...
        snapshot.max_gci_observed_order ~= P.max_gci_observed_order || ...
        logical(snapshot.qualification_verifier_implemented) || ...
        logical(snapshot.qualification_ready)
    error('numerical_vv:ProtocolSnapshotMismatch', ...
        'Protocol snapshot escalates or differs from the source-locked contract.');
end
if numel(snapshot.mesh_levels) ~= numel(P.mesh_levels) || ...
        numel(snapshot.geometries) ~= numel(P.geometries) || ...
        numel(snapshot.geometry_mesh_sequences) ~= ...
            numel(P.geometry_mesh_sequences) || ...
        numel(snapshot.registered_support_alignment) ~= ...
            numel(P.registered_support_alignment)
    error('numerical_vv:ProtocolSnapshotMismatch', ...
        'Protocol snapshot inventory differs from the source-locked contract.');
end
for k = 1:numel(P.mesh_levels)
    if ~strcmp(snapshot.mesh_levels(k).id, P.mesh_levels(k).id) || ...
            ~strcmp(snapshot.mesh_levels(k).role, P.mesh_levels(k).role)
        error('numerical_vv:ProtocolSnapshotMismatch', ...
            'Protocol snapshot mesh-level roles are not source locked.');
    end
end
for k = 1:numel(P.geometries)
    source = P.geometries(k);
    match = strcmp({snapshot.geometries.id}, source.id);
    if nnz(match) ~= 1 || ...
            ~local_close(snapshot.geometries(match).bridge_length_m, ...
                source.bridge_length_m) || ...
            snapshot.geometries(match).num_spans ~= source.num_spans
        error('numerical_vv:ProtocolSnapshotMismatch', ...
            'Protocol snapshot geometry differs from source-locked geometry.');
    end
end
for k = 1:numel(P.geometry_mesh_sequences)
    source = P.geometry_mesh_sequences(k);
    match = strcmp({snapshot.geometry_mesh_sequences.geometry_id}, ...
        source.geometry_id) & strcmp( ...
        {snapshot.geometry_mesh_sequences.level_id}, source.level_id);
    if nnz(match) ~= 1
        error('numerical_vv:ProtocolSnapshotMismatch', ...
            'Protocol snapshot mesh sequence is missing or duplicated.');
    end
    candidate = snapshot.geometry_mesh_sequences(match);
    if candidate.bridge_elements_per_sleeper_bay ~= ...
            source.bridge_elements_per_sleeper_bay || ...
            candidate.rail_elements_per_sleeper_bay ~= ...
                source.rail_elements_per_sleeper_bay || ...
            ~local_close(candidate.bridge_nominal_h_m, ...
                source.bridge_nominal_h_m) || ...
            ~local_close(candidate.rail_nominal_h_m, ...
                source.rail_nominal_h_m)
        error('numerical_vv:ProtocolSnapshotMismatch', ...
            'Protocol snapshot mesh values differ from the source lock.');
    end
end
for k = 1:numel(P.registered_support_alignment)
    source = P.registered_support_alignment(k);
    match = strcmp({snapshot.registered_support_alignment.geometry_id}, ...
        source.geometry_id) & strcmp( ...
        {snapshot.registered_support_alignment.mesh_level}, ...
        source.mesh_level) & ...
        [snapshot.registered_support_alignment.support_number] == ...
            source.support_number;
    if nnz(match) ~= 1 || ~local_alignment_struct_matches( ...
            snapshot.registered_support_alignment(match), source)
        error('numerical_vv:ProtocolSnapshotMismatch', ...
            'Protocol snapshot support alignment differs from the source lock.');
    end
end
if ~strcmp(snapshot.support_alignment_policy.current_policy_status, ...
        P.support_alignment_policy.current_policy_status)
    error('numerical_vv:ProtocolSnapshotMismatch', ...
        'Protocol snapshot support policy status differs from the source lock.');
end
end

function local_validate_support_table(T, P)
required = {'geometry_id', 'mesh_level', ...
    'bridge_elements_per_sleeper_bay', ...
    'rail_elements_per_sleeper_bay', 'bridge_nominal_h_m', ...
    'rail_nominal_h_m', 'bridge_actual_h_m', 'support_number', ...
    'nominal_coordinate_m', 'realized_node_number', ...
    'realized_coordinate_m', 'signed_offset_m', 'absolute_offset_m', ...
    'alignment_tolerance_m', 'exactly_aligned_for_qualification'};
if ~all(ismember(required, T.Properties.VariableNames)) || ...
        height(T) ~= numel(P.registered_support_alignment)
    error('numerical_vv:SupportAlignmentMismatch', ...
        'support_alignment.csv has the wrong schema or row count.');
end
for k = 1:numel(P.registered_support_alignment)
    source = P.registered_support_alignment(k);
    match = T.geometry_id == string(source.geometry_id) & ...
        T.mesh_level == string(source.mesh_level) & ...
        T.support_number == source.support_number;
    if nnz(match) ~= 1
        error('numerical_vv:SupportAlignmentMismatch', ...
            'support_alignment.csv key is missing or duplicated.');
    end
    row = T(match, :);
    if row.bridge_elements_per_sleeper_bay ~= ...
            source.bridge_elements_per_sleeper_bay || ...
            row.rail_elements_per_sleeper_bay ~= ...
                source.rail_elements_per_sleeper_bay || ...
            row.support_number ~= source.support_number || ...
            row.realized_node_number ~= source.realized_node_number || ...
            ~local_close(row.bridge_nominal_h_m, ...
                source.bridge_nominal_h_m) || ...
            ~local_close(row.rail_nominal_h_m, source.rail_nominal_h_m) || ...
            ~local_close(row.bridge_actual_h_m, source.bridge_actual_h_m) || ...
            ~local_close(row.nominal_coordinate_m, ...
                source.nominal_coordinate_m) || ...
            ~local_close(row.realized_coordinate_m, ...
                source.realized_coordinate_m) || ...
            ~local_close(row.signed_offset_m, source.signed_offset_m) || ...
            ~local_close(row.absolute_offset_m, source.absolute_offset_m) || ...
            ~local_close(row.alignment_tolerance_m, ...
                source.alignment_tolerance_m) || ...
            logical(row.exactly_aligned_for_qualification) ~= ...
                logical(source.exactly_aligned_for_qualification)
        error('numerical_vv:SupportAlignmentMismatch', ...
            'support_alignment.csv differs from source-locked values.');
    end
end
end

function local_validate_source_locked_cases(T, P)
for k = 1:height(T)
    geometry_id = char(T.geometry_id(k));
    mesh_level = char(T.mesh_level(k));
    geometry_match = strcmp({P.geometries.id}, geometry_id);
    sequence_match = strcmp({P.geometry_mesh_sequences.geometry_id}, ...
        geometry_id) & strcmp({P.geometry_mesh_sequences.level_id}, ...
        mesh_level);
    if nnz(geometry_match) ~= 1 || nnz(sequence_match) ~= 1
        error('numerical_vv:SourceLockedMeshMismatch', ...
            'Case %s uses an unregistered geometry/mesh pair.', T.case_id(k));
    end
    geometry = P.geometries(geometry_match);
    sequence = P.geometry_mesh_sequences(sequence_match);
    expected_bridge_h = P.sleeper_spacing_m / ...
        sequence.bridge_elements_per_sleeper_bay;
    expected_rail_h = P.sleeper_spacing_m / ...
        sequence.rail_elements_per_sleeper_bay;
    expected_n_elements = round(geometry.bridge_length_m / expected_bridge_h);
    expected_case_id = sprintf('%s_%s_ss_micro', geometry_id, mesh_level);
    alignment_tolerance = max(256, 2*expected_n_elements) * ...
        eps(max(geometry.bridge_length_m, 1));
    if T.case_id(k) ~= string(expected_case_id) || ...
            T.study_kind(k) ~= "simply_supported_bridge_fixture" || ...
            ~local_close(T.bridge_length_m(k), geometry.bridge_length_m) || ...
            T.bridge_elements_per_sleeper_bay(k) ~= ...
                sequence.bridge_elements_per_sleeper_bay || ...
            T.rail_elements_per_sleeper_bay(k) ~= ...
                sequence.rail_elements_per_sleeper_bay || ...
            ~local_close(T.bridge_nominal_h_m(k), expected_bridge_h) || ...
            ~local_close(T.rail_nominal_h_m(k), expected_rail_h) || ...
            ~local_close(T.bridge_actual_h_m(k), expected_bridge_h) || ...
            T.bridge_n_elements(k) ~= expected_n_elements || ...
            T.bridge_n_nodes(k) ~= expected_n_elements+1 || ...
            ~isfinite(T.max_support_offset_m(k)) || ...
            T.max_support_offset_m(k) < 0 || ...
            T.max_support_offset_m(k) > alignment_tolerance || ...
            ~logical(T.support_alignment_pass(k))
        error('numerical_vv:SourceLockedMeshMismatch', ...
            ['Case %s bridge/rail mesh metadata does not match the ' ...
             'source-locked %s/%s contract.'], ...
            T.case_id(k), geometry_id, mesh_level);
    end
end
end

function local_validate_input_descriptor(input_descriptor, manifest, T, P)
required = {'schema', 'bridge_lengths_m', 'mesh_level_ids', ...
    'time_level_ids', 'point_load_N', 'synthetic_time_window_s', ...
    'dynamic_solver_executed', 'qualification_requested'};
local_require_struct_fields(input_descriptor, required, ...
    'numerical_vv:InputDescriptorMismatch', 'input descriptor');
if ~strcmp(input_descriptor.schema, 'numerical-vv-micro-input-v1') || ...
        logical(input_descriptor.dynamic_solver_executed) || ...
        logical(input_descriptor.qualification_requested) || ...
        ~isfinite(input_descriptor.point_load_N) || ...
        input_descriptor.point_load_N <= 0
    error('numerical_vv:InputDescriptorMismatch', ...
        'Input descriptor scope or values are invalid for a micro package.');
end
if ~isfield(manifest, 'input_descriptor') || ...
        ~isequaln(input_descriptor, manifest.input_descriptor)
    error('numerical_vv:InputDescriptorMismatch', ...
        'Manifest input descriptor differs from input_descriptor.json.');
end
computed_hash = numerical_vv_sha256_bytes(unicode2native( ...
    jsonencode(input_descriptor), 'UTF-8'));
if ~strcmp(computed_hash, manifest.input_hash)
    error('numerical_vv:InputDescriptorMismatch', ...
        'Manifest input_hash does not match the canonical input descriptor.');
end
lengths = double(input_descriptor.bridge_lengths_m(:)');
mesh_ids = local_text_list(input_descriptor.mesh_level_ids);
if numel(unique(lengths)) ~= numel(lengths) || ...
        numel(unique(mesh_ids)) ~= numel(mesh_ids) || ...
        any(~ismember(lengths, [P.geometries.bridge_length_m])) || ...
        any(~ismember(mesh_ids, {P.mesh_levels.id})) || ...
        height(T) ~= numel(lengths)*numel(mesh_ids)
    error('numerical_vv:InputDescriptorMismatch', ...
        'Input descriptor case inventory is not a registered Cartesian set.');
end
for g = 1:numel(lengths)
    geometry = P.geometries(abs([P.geometries.bridge_length_m]- ...
        lengths(g)) < 1e-12);
    for m = 1:numel(mesh_ids)
        match = T.geometry_id == string(geometry.id) & ...
            T.mesh_level == string(mesh_ids{m});
        if nnz(match) ~= 1
            error('numerical_vv:InputDescriptorMismatch', ...
                'Input descriptor and case table inventories differ.');
        end
    end
end
end

function local_validate_descriptor(descriptor, descriptor_row, case_row)
expected_fields = { ...
    'case_id'; 'geometry_id'; 'mesh_level'; 'bridge_length_m'; ...
    'bridge_elements_per_sleeper_bay'; ...
    'rail_elements_per_sleeper_bay'; 'bridge_nominal_h_m'; ...
    'rail_nominal_h_m'; 'rail_mesh_executed'; 'point_load_N'; 'scope'};
if ~isstruct(descriptor) || ~isscalar(descriptor) || ...
        ~isequal(sort(fieldnames(descriptor)), sort(expected_fields)) || ...
        descriptor_row.descriptor_schema ~= ...
            "numerical-vv-bridge-fixture-v1" || ...
        descriptor_row.geometry_id ~= case_row.geometry_id || ...
        descriptor_row.mesh_level ~= case_row.mesh_level
    error('numerical_vv:DescriptorSemanticMismatch', ...
        'Descriptor schema or table identity is invalid.');
end
if ~strcmp(descriptor.case_id, char(case_row.case_id)) || ...
        ~strcmp(descriptor.geometry_id, char(case_row.geometry_id)) || ...
        ~strcmp(descriptor.mesh_level, char(case_row.mesh_level)) || ...
        ~local_close(descriptor.bridge_length_m, ...
            case_row.bridge_length_m) || ...
        descriptor.bridge_elements_per_sleeper_bay ~= ...
            case_row.bridge_elements_per_sleeper_bay || ...
        descriptor.rail_elements_per_sleeper_bay ~= ...
            case_row.rail_elements_per_sleeper_bay || ...
        ~local_close(descriptor.bridge_nominal_h_m, ...
            case_row.bridge_nominal_h_m) || ...
        ~local_close(descriptor.rail_nominal_h_m, ...
            case_row.rail_nominal_h_m) || ...
        ~islogical(descriptor.rail_mesh_executed) || ...
        descriptor.rail_mesh_executed || ...
        ~isfinite(descriptor.point_load_N) || descriptor.point_load_N <= 0 || ...
        ~strcmp(descriptor.scope, ...
            'nonqualifying-simply-supported-production-matrix-micro')
    error('numerical_vv:DescriptorSemanticMismatch', ...
        'Descriptor fields do not match their case row and micro scope.');
end
end

function local_validate_raw_fixture(runs, T, descriptor_table, ...
        descriptors, input_descriptor, P)
required = {'schema', 'scope', 'case_id', 'geometry_id', 'mesh_level', ...
    'bridge_length_m', 'bridge_elements_per_sleeper_bay', ...
    'rail_elements_per_sleeper_bay', 'bridge_nominal_h_m', ...
    'rail_nominal_h_m', 'bridge_actual_h_m', 'rail_actual_h_m', ...
    'bridge_mesh_executed', 'rail_mesh_executed', 'bridge_n_elements', ...
    'bridge_n_nodes', 'node_coordinates_m', ...
    'nominal_support_coordinates_m', 'realized_support_coordinates_m', ...
    'support_signed_offsets_m', 'support_alignment_pass', 'point_load_N'};
if ~isstruct(runs) || numel(runs) ~= height(T) || ...
        ~all(isfield(runs, required)) || ...
        numel(unique(string({runs.case_id}))) ~= numel(runs)
    error('numerical_vv:RawFixtureMismatch', ...
        'Raw fixture inventory/schema differs from the case table.');
end
for k = 1:height(T)
    raw_index = find(string({runs.case_id}) == T.case_id(k));
    descriptor_index = find(descriptor_table.case_id == T.case_id(k));
    if numel(raw_index) ~= 1 || numel(descriptor_index) ~= 1
        error('numerical_vv:RawFixtureMismatch', ...
            'Raw fixture case identity is missing or duplicated.');
    end
    run = runs(raw_index);
    descriptor = descriptors{descriptor_index};
    geometry_match = strcmp({P.geometries.id}, char(T.geometry_id(k)));
    sequence_match = strcmp({P.geometry_mesh_sequences.geometry_id}, ...
        char(T.geometry_id(k))) & strcmp( ...
        {P.geometry_mesh_sequences.level_id}, char(T.mesh_level(k)));
    geometry = P.geometries(geometry_match);
    sequence = P.geometry_mesh_sequences(sequence_match);
    expected_h = P.sleeper_spacing_m / ...
        sequence.bridge_elements_per_sleeper_bay;
    expected_n = round(geometry.bridge_length_m/expected_h);
    tolerance = max(256, 2*expected_n) * ...
        eps(max(geometry.bridge_length_m, 1));
    nodes = double(run.node_coordinates_m(:)');
    if ~strcmp(run.schema, 'numerical-vv-bridge-fixture-v1') || ...
            ~strcmp(run.scope, descriptor.scope) || ...
            ~strcmp(run.geometry_id, char(T.geometry_id(k))) || ...
            ~strcmp(run.mesh_level, char(T.mesh_level(k))) || ...
            ~local_close(run.bridge_length_m, T.bridge_length_m(k)) || ...
            run.bridge_elements_per_sleeper_bay ~= ...
                T.bridge_elements_per_sleeper_bay(k) || ...
            run.rail_elements_per_sleeper_bay ~= ...
                T.rail_elements_per_sleeper_bay(k) || ...
            ~local_close(run.bridge_nominal_h_m, ...
                T.bridge_nominal_h_m(k)) || ...
            ~local_close(run.rail_nominal_h_m, T.rail_nominal_h_m(k)) || ...
            ~local_close(run.bridge_actual_h_m, T.bridge_actual_h_m(k)) || ...
            ~isnan(run.rail_actual_h_m) || ...
            ~logical(run.bridge_mesh_executed) || ...
            logical(run.rail_mesh_executed) || ...
            run.bridge_n_elements ~= expected_n || ...
            run.bridge_n_nodes ~= expected_n+1 || ...
            numel(nodes) ~= expected_n+1 || ...
            ~local_close(nodes(1), 0) || ...
            ~local_close(nodes(end), geometry.bridge_length_m, tolerance) || ...
            any(abs(diff(nodes)-expected_h) > tolerance) || ...
            max(abs(run.support_signed_offsets_m)) > tolerance || ...
            ~logical(run.support_alignment_pass) || ...
            ~local_close(max(abs(run.support_signed_offsets_m)), ...
                T.max_support_offset_m(k), tolerance) || ...
            ~local_close(run.point_load_N, descriptor.point_load_N) || ...
            ~local_close(run.point_load_N, input_descriptor.point_load_N)
        error('numerical_vv:RawFixtureMismatch', ...
            'Raw fixture values differ from case/descriptor/source contract.');
    end
end
end

function tf = local_alignment_struct_matches(candidate, source)
tf = candidate.bridge_elements_per_sleeper_bay == ...
        source.bridge_elements_per_sleeper_bay && ...
    candidate.rail_elements_per_sleeper_bay == ...
        source.rail_elements_per_sleeper_bay && ...
    candidate.support_number == source.support_number && ...
    candidate.realized_node_number == source.realized_node_number && ...
    local_close(candidate.bridge_nominal_h_m, source.bridge_nominal_h_m) && ...
    local_close(candidate.rail_nominal_h_m, source.rail_nominal_h_m) && ...
    local_close(candidate.bridge_actual_h_m, source.bridge_actual_h_m) && ...
    local_close(candidate.nominal_coordinate_m, source.nominal_coordinate_m) && ...
    local_close(candidate.realized_coordinate_m, source.realized_coordinate_m) && ...
    local_close(candidate.signed_offset_m, source.signed_offset_m) && ...
    local_close(candidate.absolute_offset_m, source.absolute_offset_m) && ...
    local_close(candidate.alignment_tolerance_m, ...
        source.alignment_tolerance_m) && ...
    logical(candidate.exactly_aligned_for_qualification) == ...
        logical(source.exactly_aligned_for_qualification);
end

function local_require_struct_fields(value, fields, identifier, label)
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, fields))
    error(identifier, '%s is missing required source-bound fields.', label);
end
end

function values = local_text_list(value)
if ischar(value)
    values = {value};
else
    values = cellstr(string(value(:)));
end
end

function tf = local_close(left, right, varargin)
left = double(left);
right = double(right);
if ~isscalar(left) || ~isscalar(right) || ...
        ~isfinite(left) || ~isfinite(right)
    tf = false;
    return
end
if isempty(varargin)
    tolerance = 64*eps(max([abs(left), abs(right), 1]));
else
    tolerance = double(varargin{1});
end
tf = abs(left-right) <= tolerance;
end

function local_require_file(path)
file = java.io.File(path);
if ~local_same_path(char(file.getAbsolutePath()), ...
        char(file.getCanonicalPath()))
    error('numerical_vv:AliasedArtifact', ...
        'Artifact must not be a symlink, junction, or aliased path: %s', path);
end
info = dir(path);
if numel(info) ~= 1 || info.isdir
    error('numerical_vv:MissingRegularFile', ...
        'Expected one regular file: %s', path);
end
end

function tf = local_same_path(left, right)
if ispc
    tf = strcmpi(left, right);
else
    tf = strcmp(left, right);
end
end

function tf = local_logical_scalar(value)
tf = (islogical(value) || isnumeric(value)) && isscalar(value) && ...
    isfinite(double(value)) && any(double(value) == [0, 1]);
end
