function P = numerical_vv_protocol_definition()
%NUMERICAL_VV_PROTOCOL_DEFINITION Machine-readable numerical V&V contract.
%
% This function mirrors docs/numerical_vv_protocol.md.  It deliberately
% separates facts already fixed by that protocol from unresolved choices.  A
% caller must not turn an unresolved choice into a qualifying default.
%
% The returned contract is data only.  Calling this function does not execute
% or qualify a mesh/time-refinement study.

P = struct();
P.schema = 'numerical-vv-protocol-v1';
P.protocol_document = 'docs/numerical_vv_protocol.md';
P.evidence_scope = 'numerical-solution-verification';
P.numerical_verification_claim_authorized = false;
P.physical_validation_claim_authorized = false;
P.qualification_verifier_implemented = false;

P.mesh_levels = struct( ...
    'id', {'M0', 'M1', 'M2', 'M3'}, ...
    'role', { ...
        'current-production', ...
        'primary-finer-comparison', ...
        'second-primary-finer-comparison', ...
        'conditional-resolution'});
P.primary_mesh_level_ids = {'M0', 'M1', 'M2'};
P.conditional_mesh_level_id = 'M3';
P.mesh_refinement = [ ...
    'geometry-specific joint bridge-and-rail refinement; each level ' ...
    'doubles both element counts per sleeper bay'];
P.mesh_refinement_factor = 2;
P.sleeper_spacing_m = 0.6;
P.refine_lumped_sleeper_ballast_dofs = false;

P.time_levels = struct( ...
    'id', {'dt1', 'dt0p5', 'dt0p25', 'dt0p125'}, ...
    'requested_dt_ms', {1.0, 0.5, 0.25, 0.125}, ...
    'role', { ...
        'primary-coarse', ...
        'primary-medium', ...
        'primary-fine', ...
        'conditional-resolution'});
P.primary_time_level_ids = {'dt1', 'dt0p5', 'dt0p25'};
P.conditional_time_level_id = 'dt0p125';
P.common_distance_dx_m = 0.01;
P.analysis_band_hz = [0.2, 15.0];

P.geometries = struct( ...
    'id', {'L60_3span', 'L99p6_4span'}, ...
    'bridge_length_m', {60.0, 99.6}, ...
    'num_spans', {3, 4});
P.geometry_mesh_sequences = struct( ...
    'geometry_id', { ...
        'L60_3span', 'L60_3span', 'L60_3span', 'L60_3span', ...
        'L99p6_4span', 'L99p6_4span', 'L99p6_4span', 'L99p6_4span'}, ...
    'level_id', {'M0', 'M1', 'M2', 'M3', 'M0', 'M1', 'M2', 'M3'}, ...
    'bridge_elements_per_sleeper_bay', {3, 6, 12, 24, 2, 4, 8, 16}, ...
    'rail_elements_per_sleeper_bay', {2, 4, 8, 16, 2, 4, 8, 16}, ...
    'bridge_nominal_h_m', { ...
        0.2, 0.1, 0.05, 0.025, 0.3, 0.15, 0.075, 0.0375}, ...
    'rail_nominal_h_m', { ...
        0.3, 0.15, 0.075, 0.0375, 0.3, 0.15, 0.075, 0.0375});
P.registered_support_alignment = numerical_vv_support_alignment( ...
    P.geometries, P.geometry_mesh_sequences);
P.rejected_legacy_mesh_sequences = local_legacy_mesh_sequences(P.geometries);
P.rejected_legacy_support_alignment = numerical_vv_support_alignment( ...
    P.geometries, P.rejected_legacy_mesh_sequences);
P.support_alignment_policy = struct( ...
    'qualification_rule', ...
        ['FAIL when any realized support coordinate differs materially from ' ...
         'its nominal coordinate'], ...
    'materiality_rule', ...
        'max(256,2*n_bridge_elements)*eps(max(bridge_length_m,1))', ...
    'current_policy_status', 'SOURCE_LOCKED_GEOMETRY_SPECIFIC_ALIGNED', ...
    'sequence_field', 'geometry_mesh_sequences', ...
    'primary_level_count', 3, ...
    'conditional_level_count', 1, ...
    'production_role', 'M0', ...
    'rejected_legacy_universal_sequence', struct( ...
        'status', 'REJECTED_SUPPORT_GEOMETRY_CHANGES_WITH_LEVEL', ...
        'reason', ...
            ['universal h=[0.6,0.3,0.15,0.075] m snaps nominal internal ' ...
             'supports by mesh level for one or both registered bridges'], ...
        'nonproduction_alternative', ...
            ['a separately verified coordinate-consistent spring ' ...
             'interpolation/distribution would be a production-method ' ...
             'change and is not authorized by this harness']));
P.healthy_operating_points = struct( ...
    'id', {'V70_T3', 'V80_T18', 'V90_T33'}, ...
    'speed_kmh', {70.0, 80.0, 90.0}, ...
    'temperature_degC', {3.0, 18.0, 33.0});

P.active_mechanisms = { ...
    'scour_support_loss'; ...
    'nominal_bearing_fixity'; ...
    'local_crack'; ...
    'ballast_patch'; ...
    'unsupported_sleepers'; ...
    'rail_pad_service_change'; ...
    'rail_pad_failure'; ...
    'wheel_polygonization'};

P.qois = local_qois();
P.required_artifacts = local_required_artifacts();
P.required_table_identity_columns = { ...
    'case_id', 'geometry_id', 'source_commit', 'input_hash'};
P.verdict_statuses = {'PASS', 'FAIL', 'UNVERIFIED'};
P.qualifying_run_kind = 'qualification';
P.micro_run_kind = 'nonqualifying_micro';

P.contact_policy = struct( ...
    'coarse_to_fine_nrmse', 0.05, ...
    'coarse_to_fine_nmax', 0.10, ...
    'coarse_to_fine_correlation', 0.995, ...
    'medium_to_fine_nrmse', 0.02, ...
    'medium_to_fine_nmax', 0.05, ...
    'medium_to_fine_correlation', 0.999, ...
    'positive_tensile_peak_N', 24000.0, ...
    'on_track_tensile_fraction', 0.002, ...
    'evidence_class', 'author-chosen-engineering-closure');

% Dedicated finite-rail-domain model-form gate. This is deliberately
% separate from the incomplete general mesh/time qualification contract:
% executing it may select a production rail margin, but cannot authorize a
% physical-validation or general numerical-verification claim.
P.rail_domain_clearance = local_rail_domain_clearance_contract( ...
    P.healthy_operating_points,P.contact_policy);
P.gci_safety_factor = 1.25;
P.max_gci_observed_order = 10;

% These items are intentionally not defaulted by executable code.  Each must
% be resolved prospectively and source-locked before a qualifying execution.
P.unresolved_contract_items = { ...
    ['operating point for each maximum-mechanism coupled stress case is ' ...
     'not stated']; ...
    ['fixed PSD estimator, window, overlap, sample-rate/binning policy is ' ...
     'not yet encoded']; ...
    ['per-QoI zero floors and mesh/time acceptance thresholds require the ' ...
     'prospective tolerance ledger']; ...
    ['physical-interval mapping for crack convergence is not yet an ' ...
     'executable contract']; ...
    ['Zhai Table 1 quantities are stated per rail seat, whereas the ' ...
     'inherited equivalent-plane track-property function doubles rail ' ...
     'and sleeper terms but not pad, ballast, or sub-ballast terms; the ' ...
     'intended one-seat versus two-rail scaling requires a source-bound ' ...
     'benchmark or prospective sensitivity decision']; ...
    ['Zhai Table 1 uses 0.545 m rail-support spacing, whereas the ' ...
     'generator retains the source Mb, Kb, and Kf values at 0.600 m; ' ...
     'this hybrid transfer requires an upstream ' ...
     'benchmark or a prospective spacing-consistency sensitivity']; ...
    ['bridge/full-state dynamic residual extraction is not yet available ' ...
     'for every production solve']; ...
    ['immutable upstream raw-array oracle and compatibility mapping are ' ...
     'not yet available']};
P.qualification_ready = P.qualification_verifier_implemented && ...
    isempty(P.unresolved_contract_items);
end

function C = local_rail_domain_clearance_contract(operating_points,contact)
C = struct();
C.schema = 'rail-domain-clearance-protocol-v1';
C.full_run_kind = 'rail_domain_clearance_full';
C.smoke_run_kind = 'rail_domain_clearance_smoke';
C.claim_scope = 'finite-rail-domain-model-form-selection-only';
C.numerical_verification_claim_authorized = false;
C.physical_validation_claim_authorized = false;
C.production_decision_id = 'paper1-rail-domain-clearance-c06-v1';
C.reviewed_production_clearance_m = 6;
C.clearance_m = [6,15,30];
C.clearance_roles = { ...
    'current-production-diagnostic'; ...
    'primary-candidate'; ...
    'long-domain-reference'};
C.geometries = struct( ...
    'id', {'F40_2span','L99p6_4span'}, ...
    'bridge_length_m', {40.0,99.6}, ...
    'num_spans', {2,4}, ...
    'minimum_bridge_elements_per_sleeper_bay', {2,2}, ...
    'expected_bridge_elements_per_sleeper_bay', {3,2}, ...
    'rail_elements_per_sleeper_bay', {2,2});
C.operating_points = operating_points;
C.expected_full_solve_count = ...
    numel(C.geometries)*numel(C.operating_points)*numel(C.clearance_m);
C.smoke_case_id = 'F40_2span_V70_T3_C15';
C.vehicle_draw = zeros(5,3);
C.damage_state = 'healthy';
C.profile = struct( ...
    'mode','fixed', ...
    'fra_class',4, ...
    'phase_seed',20260728, ...
    'spectrum_contract','fra-v2-class4-cycles-per-m-v1', ...
    'coordinate_schema','rail-domain-common-coordinate-v1', ...
    'common_x_bounds_m',[-30,390], ...
    'comparison_rule','evaluate live profile at x_global-domain_translation');
C.retained_window = struct( ...
    'coordinate','leading-wheel travel from solve start', ...
    'dx_m',0.01, ...
    'crop_start_m',10.0, ...
    'post_deck_m',18.30, ...
    'length_rule','bridge_length_m + post_deck_m');
C.invariance_tolerance = struct( ...
    'geometry_m',1e-10, ...
    'time_s',1e-12, ...
    'profile_elevation_m',1e-12);
C.wheel_endpoint_policy = struct( ...
    'requested_padding_exact_on_sleeper_lattice',true, ...
    'every_wheel_at_least_requested',true, ...
    'expected_nominal_train_start_surplus_m',0.5, ...
    'expected_leading_exit_surplus_m',0.0);
C.waveform_channels = { ...
    'carbody_vertical_acc'; ...
    'front_bogie_vertical_acc'; ...
    'rear_bogie_vertical_acc'; ...
    'rail_eulerian_vertical_acc_under_wheel_1'; ...
    'rail_eulerian_vertical_acc_under_wheel_2'; ...
    'rail_eulerian_vertical_acc_under_wheel_3'; ...
    'rail_eulerian_vertical_acc_under_wheel_4'; ...
    'carbody_pitch_rate'; ...
    'front_bogie_pitch_rate'; ...
    'rear_bogie_pitch_rate'; ...
    'wheelset_total_vertical_acc_1'; ...
    'wheelset_total_vertical_acc_2'; ...
    'wheelset_total_vertical_acc_3'; ...
    'wheelset_total_vertical_acc_4'; ...
    'bridge_midspan_displacement'; ...
    'bridge_midspan_acceleration'; ...
    'contact_force_wheel_1'; ...
    'contact_force_wheel_2'; ...
    'contact_force_wheel_3'; ...
    'contact_force_wheel_4'};
C.comparisons = struct( ...
    'id', {'C06_vs_C30','C15_vs_C30'}, ...
    'test_clearance_m', {6,15}, ...
    'reference_clearance_m', {30,30}, ...
    'role', {'coarse-production-diagnostic','primary-convergence'}, ...
    'maximum_nrmse', {contact.coarse_to_fine_nrmse, ...
        contact.medium_to_fine_nrmse}, ...
    'maximum_normalized_max_error', {contact.coarse_to_fine_nmax, ...
        contact.medium_to_fine_nmax}, ...
    'minimum_correlation', {contact.coarse_to_fine_correlation, ...
        contact.medium_to_fine_correlation});
C.selection_rule = [ ...
    'select 6 m only when both registered comparisons pass every case/channel; ' ...
    'otherwise select 15 m when C15_vs_C30 passes every case/channel; ' ...
    'otherwise production is unresolved and 30 m remains diagnostic only'];
C.contact_admissibility = contact;
C.required_artifacts = { ...
    'input_descriptor.json'; ...
    'protocol_snapshot.json'; ...
    'source_manifest.txt'; ...
    'case_table.csv'; ...
    'wheel_end_clearances.csv'; ...
    'waveform_metrics.csv'; ...
    'scalar_metrics.csv'; ...
    'comparison_summary.csv'; ...
    'raw_clearance_runs.mat'; ...
    'rail_domain_clearance_report.md'; ...
    'verdict.json'};
end

function sequences = local_legacy_mesh_sequences(geometries)
% Retained only to reproduce and reject the historical universal grid.
level_ids = {'M0', 'M1', 'M2', 'M3'};
per_bay = [1, 2, 4, 8];
h_m = [0.6, 0.3, 0.15, 0.075];
template = struct('geometry_id', '', 'level_id', '', ...
    'bridge_elements_per_sleeper_bay', 0, ...
    'rail_elements_per_sleeper_bay', 0, ...
    'bridge_nominal_h_m', 0, 'rail_nominal_h_m', 0);
sequences = repmat(template, numel(geometries)*numel(level_ids), 1);
row = 0;
for g = 1:numel(geometries)
    for m = 1:numel(level_ids)
        row = row+1;
        sequences(row) = struct('geometry_id', geometries(g).id, ...
            'level_id', level_ids{m}, ...
            'bridge_elements_per_sleeper_bay', per_bay(m), ...
            'rail_elements_per_sleeper_bay', per_bay(m), ...
            'bridge_nominal_h_m', h_m(m), ...
            'rail_nominal_h_m', h_m(m));
    end
end
end

function qois = local_qois()
ids = { ...
    'bridge_frequency_1_to_5'; ...
    'matched_mode_mac_1_to_5'; ...
    'static_midspan_displacement'; ...
    'static_left_support_reaction'; ...
    'static_right_support_reaction'; ...
    'static_force_balance'; ...
    'static_strain_energy'; ...
    'bridge_midspan_displacement_history'; ...
    'bridge_midspan_acceleration_history'; ...
    'bridge_max_abs_bending_moment'; ...
    'bridge_max_abs_shear'; ...
    'bridge_bending_moment_peak_location_time'; ...
    'bridge_shear_peak_location_time'; ...
    'bridge_entry_exit_values'; ...
    'wheel_contact_force_history_1_to_4'; ...
    'wheel_contact_signed_peak'; ...
    'wheel_contact_positive_tensile_peak'; ...
    'wheel_contact_on_track_tensile_fraction'; ...
    'wheel_contact_peak_location'; ...
    'vehicle_waveforms_10_channels'; ...
    'bridge_psd_band_energy_0p2_to_15_hz'; ...
    'polygon_harmonic_response'; ...
    'dynamic_equilibrium_residual'};
families = { ...
    'modal'; 'modal'; 'static'; 'static'; 'static'; 'static'; 'static'; ...
    'waveform'; 'waveform'; 'scalar'; 'scalar'; 'event'; 'event'; 'event'; ...
    'waveform'; 'scalar'; 'scalar'; 'scalar'; 'event'; 'waveform'; ...
    'spectral'; 'spectral'; 'residual'};
units = { ...
    'Hz'; '1'; 'm'; 'N'; 'N'; 'N'; 'J'; 'm'; 'm/s^2'; 'N*m'; 'N'; ...
    'm,s'; 'm,s'; 'response-dependent'; 'N'; 'N'; 'N'; '1'; 'm'; ...
    'channel-dependent'; 'response-unit^2'; 'response-dependent'; '1'};
qois = struct('id', ids, 'family', families, 'unit', units);
end

function artifacts = local_required_artifacts()
artifacts = { ...
    'manifest.json'; ...
    'case_table.csv'; ...
    'descriptor_hashes.csv'; ...
    'element_assembly_checks.csv'; ...
    'bc_checks.csv'; ...
    'static_equilibrium_checks.csv'; ...
    'modal_matching.csv'; ...
    'mesh_scalar_qoi.csv'; ...
    'mesh_waveform_metrics.csv'; ...
    'time_scalar_qoi.csv'; ...
    'time_waveform_metrics.csv'; ...
    'contact_metrics.csv'; ...
    'contact_closure_report.mat'; ...
    'contact_closure_receipt.json'; ...
    'upstream_oracle_manifest.json'; ...
    'compatibility_mapping.json'; ...
    'upstream_array_comparison.csv'; ...
    'mechanism_pair_manifest.csv'; ...
    'tolerance_rationale.csv'; ...
    'vv_verdict.json'};
end
