function run = rail_domain_clearance_run_one(case_definition,contract)
%RAIL_DOMAIN_CLEARANCE_RUN_ONE One source-locked healthy coupled clearance arm.
%
% This is the sole dynamic runner used by rail_domain_clearance_study. It
% executes production B00 with a fixed FRA-v2 excitation, records every
% wheel's realized distance to both finite rail ends, and retains the exact
% D01 distance window on a leading-wheel-travel coordinate. It does not make
% the 6/15/30 m selection decision.

if nargin ~= 2 || ~isstruct(case_definition) || ...
        ~isscalar(case_definition) || ~isstruct(contract) || ...
        ~isscalar(contract)
    error('rail_domain_clearance:RunInput', ...
        'case_definition and contract must be scalar structures.');
end
local_validate_case(case_definition,contract);

geometry = contract.geometries(strcmp( ...
    {contract.geometries.id},case_definition.geometry_id));
operating = contract.operating_points(strcmp( ...
    {contract.operating_points.id},case_definition.operating_point_id));
speed_mps = operating.speed_kmh/3.6;

Train = A01_Train(speed_mps,contract.vehicle_draw);
Track = A02_Track();
Beam = A03_Bridge(struct('Prop',struct( ...
    'L',geometry.bridge_length_m,'num_spans',geometry.num_spans)));
Beam.Prop.E = Beam.Prop.E - Beam.Prop.E*0.003* ...
    (operating.temperature_degC-15);
profile_cfg = struct( ...
    'mode',contract.profile.mode, ...
    'fra_class',contract.profile.fra_class, ...
    'phase_seed',contract.profile.phase_seed, ...
    'spectrum_contract',contract.profile.spectrum_contract);
[Calc,Beam,Track] = A04_Options(Beam,Track,profile_cfg);
Calc.Profile.rail_end_clearance_m = case_definition.clearance_m;
Calc.Profile.rail_domain_common_coordinate = struct( ...
    'schema',contract.profile.coordinate_schema, ...
    'x_bounds_m',contract.profile.common_x_bounds_m);
Calc.Options.calc_beam_frq = 1;
Calc.Options.calc_beam_modes = 1;

Damage = local_healthy_damage(geometry.num_spans+1);
[Sol,Calc,Train,Beam,Track,Model] = ...
    B00_Calculations(Calc,Train,Track,Beam,Damage);

wheel_counts = arrayfun(@(vehicle) vehicle.Wheels.num,Train.Veh);
if numel(Train.Veh) ~= 5 || any(wheel_counts ~= 4)
    error('rail_domain_clearance:VehicleInventory', ...
        'The source-locked case requires five four-wheel vehicles.');
end

[endpoint,minimum_start_m,minimum_end_m] = ...
    local_wheel_end_clearances(Calc,Train,case_definition.clearance_m);
domain_tolerance_m = max(1e-10,512*eps(max(Calc.Profile.L,1)));
if any(endpoint.start_clearance_m < ...
        case_definition.clearance_m-domain_tolerance_m) || ...
        any(endpoint.end_clearance_m < ...
        case_definition.clearance_m-domain_tolerance_m)
    error('rail_domain_clearance:RealizedClearanceBelowRequest', ...
        ['At least one realized per-wheel start/end clearance is below ' ...
         'the requested %.17g m minimum.'],case_definition.clearance_m);
end
if abs(minimum_end_m-case_definition.clearance_m) > domain_tolerance_m
    error('rail_domain_clearance:ExitClearanceNotRealized', ...
        ['The leading exit wheel must realize the requested clearance ' ...
         'exactly (requested %.17g m, realized %.17g m).'], ...
        case_definition.clearance_m,minimum_end_m);
end
expected_start_m = case_definition.clearance_m + ...
    contract.wheel_endpoint_policy.expected_nominal_train_start_surplus_m;
if abs(minimum_start_m-expected_start_m) > domain_tolerance_m
    error('rail_domain_clearance:StartClearanceNotSourceLocked', ...
        ['The nominal five-car train must retain its source-locked %.17g m ' ...
         'start surplus (expected %.17g m, realized %.17g m).'], ...
        contract.wheel_endpoint_policy. ...
            expected_nominal_train_start_surplus_m, ...
        expected_start_m,minimum_start_m);
end

deck_global_x_m = Model.Mesh.XLoc.beam_vert(1);
if abs(deck_global_x_m-Calc.Profile.L_Aw) > domain_tolerance_m
    error('rail_domain_clearance:DeckCoordinateMismatch', ...
        'B54 deck origin disagrees with B43 Calc.Profile.L_Aw.');
end
lead_x_m = double(Calc.Veh(1).x_path(1,:));
lead_travel_m = lead_x_m-lead_x_m(1);
lead_to_deck_m = deck_global_x_m-lead_x_m(1);
expected_lead_to_deck_m = ...
    Calc.Profile.L_Approach-Calc.Profile.rail_end_clearance_default_m;
if abs(lead_to_deck_m-expected_lead_to_deck_m) > domain_tolerance_m
    error('rail_domain_clearance:LeadToDeckChanged', ...
        ['Rail-domain expansion changed leading-wheel-to-deck travel ' ...
         '(expected %.17g m, realized %.17g m).'], ...
        expected_lead_to_deck_m,lead_to_deck_m);
end

window = contract.retained_window;
retained_x_m = window.crop_start_m:window.dx_m: ...
    (window.crop_start_m+geometry.bridge_length_m+window.post_deck_m);
if retained_x_m(1) < lead_travel_m(1) || ...
        retained_x_m(end) > lead_travel_m(end)
    error('rail_domain_clearance:RetainedWindowOutsideSolve', ...
        'The source-locked D01-equivalent window lies outside this solve.');
end

wheelset_acc = ttbi.wheel_contact_kinematics( ...
    Sol.Veh(1),Calc.Veh(1),Train.vel);
legacy = double([ ...
    Sol.Veh(1).A(1:3,:); ...
    Sol.Veh(1).acc_under(1:4,:); ...
    Sol.Veh(1).V(4:6,:)]);
bridge = double([ ...
    Sol.Beam.U.sections_t(1,:); ...
    Sol.Beam.Acc.sections_t(1,:)]);
contact = double(Sol.Veh(1).F_onBeam(1:4,:));
raw_waveforms = [legacy;double(wheelset_acc(1:4,:));bridge;contact];
if size(raw_waveforms,1) ~= numel(contract.waveform_channels) || ...
        size(raw_waveforms,2) ~= numel(lead_travel_m)
    error('rail_domain_clearance:WaveformInventory', ...
        'The coupled solve did not return the registered 20-channel inventory.');
end
retained_waveforms = zeros(size(raw_waveforms,1),numel(retained_x_m));
for channel = 1:size(raw_waveforms,1)
    retained_waveforms(channel,:) = interp1( ...
        lead_travel_m,raw_waveforms(channel,:),retained_x_m,'linear');
end
if any(~isfinite(retained_waveforms(:)))
    error('rail_domain_clearance:NonfiniteWaveform', ...
        'Retained-window interpolation returned nonfinite data.');
end

retained_lead_global_x_m = lead_x_m(1)+retained_x_m;
profile_h_m = interp1(Calc.Profile.x,Calc.Profile.h, ...
    retained_lead_global_x_m,'linear');
if any(~isfinite(profile_h_m))
    error('rail_domain_clearance:NonfiniteProfile', ...
        'Retained common-coordinate profile contains nonfinite data.');
end

[scalar_names,scalar_values,scalar_units] = local_scalar_qois( ...
    Sol,Beam,Calc,lead_travel_m,retained_x_m,contact,bridge);
contact_admissible = isfinite(Sol.F_tension_max) && ...
    isfinite(Sol.tension_frac_max) && ...
    Sol.F_tension_max <= ...
        contract.contact_admissibility.positive_tensile_peak_N && ...
    Sol.tension_frac_max <= ...
        contract.contact_admissibility.on_track_tensile_fraction;

run = struct();
run.schema = 'rail-domain-clearance-run-v1';
run.case_id = case_definition.case_id;
run.geometry_id = geometry.id;
run.operating_point_id = operating.id;
run.clearance_m = double(case_definition.clearance_m);
run.speed_kmh = double(operating.speed_kmh);
run.temperature_degC = double(operating.temperature_degC);
run.bridge_length_m = double(Beam.Prop.L);
run.num_spans = double(geometry.num_spans);
run.bridge_elements_per_sleeper_bay = ...
    double(Beam.Mesh.Ele.num_per_spacing);
run.rail_elements_per_sleeper_bay = ...
    double(Track.Rail.Mesh.Ele.num_per_spacing);
run.rail_length_m = double(Calc.Profile.L);
run.rail_domain_translation_m = ...
    double(Calc.Profile.rail_domain_translation_m);
run.deck_global_x_m = double(deck_global_x_m);
run.lead_start_global_x_m = double(lead_x_m(1));
run.lead_end_global_x_m = double(lead_x_m(end));
run.lead_to_deck_m = double(lead_to_deck_m);
run.lead_travel_m = double(lead_travel_m(end));
run.solve_duration_s = double(Calc.Solver.t(end));
run.actual_dt_s = double(Calc.Solver.dt);
run.solver_sample_count = double(Calc.Solver.num_t);
run.retained_x_m = double(retained_x_m);
run.retained_waveforms = retained_waveforms;
run.waveform_channel_names = contract.waveform_channels;
run.profile_retained_h_m = double(profile_h_m);
run.profile_retained_sha256 = local_numeric_sha256(profile_h_m);
run.wheel_end_clearances = endpoint;
run.minimum_start_clearance_m = double(minimum_start_m);
run.minimum_end_clearance_m = double(minimum_end_m);
run.scalar_names = scalar_names;
run.scalar_values = scalar_values;
run.scalar_units = scalar_units;
run.aggregate_tensile_peak_n = double(Sol.F_tension_max);
run.aggregate_positive_fraction = double(Sol.tension_frac_max);
run.contact_admissible = logical(contact_admissible);
run.contact_lost_track = logical(Sol.contactLost_track);
run.contact_lost_bridge = logical(Sol.contactLost);
run.common_profile_coordinate = ...
    Calc.Profile.rail_domain_common_coordinate;
local_assert_finite(run);
end

function damage = local_healthy_damage(n_supports)
damage = struct( ...
    'desvio',0, ...
    'scour_rates',zeros(1,n_supports), ...
    'bearing_left',0, ...
    'bearing_right',0, ...
    'crack_locs',[], ...
    'crack_intensity',[], ...
    'crack_lc',0, ...
    'track',[], ...
    'oor_flats',zeros(0,5), ...
    'oor_poly',zeros(0,5), ...
    'oor_radius',0.46);
end

function [rows,minimum_start_m,minimum_end_m] = ...
        local_wheel_end_clearances(Calc,Train,requested_m)
n_vehicles = numel(Train.Veh);
n_rows = sum(arrayfun(@(vehicle) vehicle.Wheels.num,Train.Veh));
vehicle_index = zeros(n_rows,1);
wheel_index = zeros(n_rows,1);
start_global_x_m = zeros(n_rows,1);
end_global_x_m = zeros(n_rows,1);
start_clearance_m = zeros(n_rows,1);
end_clearance_m = zeros(n_rows,1);
row = 0;
for vehicle = 1:n_vehicles
    x = double(Calc.Veh(vehicle).x_path);
    for wheel = 1:size(x,1)
        row = row+1;
        vehicle_index(row) = vehicle;
        wheel_index(row) = wheel;
        start_global_x_m(row) = x(wheel,1);
        end_global_x_m(row) = x(wheel,end);
        start_clearance_m(row) = x(wheel,1);
        end_clearance_m(row) = Calc.Profile.L-x(wheel,end);
    end
end
requested_clearance_m = repmat(double(requested_m),n_rows,1);
rows = table(vehicle_index,wheel_index,requested_clearance_m, ...
    start_global_x_m,end_global_x_m,start_clearance_m,end_clearance_m);
minimum_start_m = min(start_clearance_m);
minimum_end_m = min(end_clearance_m);
end

function [names,values,units] = local_scalar_qois( ...
        Sol,Beam,Calc,lead_travel_m,retained_x_m,contact,bridge)
names = cell(0,1); values = zeros(0,1); units = cell(0,1);
for mode = 1:5
    [names,values,units] = local_append(names,values,units, ...
        sprintf('bridge_frequency_%d',mode),Beam.Modal.f(mode),'Hz');
end
[names,values,units] = local_append(names,values,units, ...
    'static_midspan_displacement',Sol.Beam.StaticU.min05,'m');
[bm_abs,bm_index] = max(abs(Sol.Beam.BM.xt),[],'all','linear');
[bm_x,bm_t] = ind2sub(size(Sol.Beam.BM.xt),bm_index);
[sh_abs,sh_index] = max(abs(Sol.Beam.Shear.xt),[],'all','linear');
[sh_x,sh_t] = ind2sub(size(Sol.Beam.Shear.xt),sh_index);
[names,values,units] = local_append(names,values,units, ...
    'bridge_max_abs_bending_moment',bm_abs,'N*m');
[names,values,units] = local_append(names,values,units, ...
    'bridge_bending_peak_x',Beam.Mesh.Nodes.acum(bm_x),'m');
[names,values,units] = local_append(names,values,units, ...
    'bridge_bending_peak_lead_travel',lead_travel_m(bm_t),'m');
[names,values,units] = local_append(names,values,units, ...
    'bridge_max_abs_shear',sh_abs,'N');
[names,values,units] = local_append(names,values,units, ...
    'bridge_shear_peak_x',Beam.Mesh.Nodes.acum(sh_x),'m');
[names,values,units] = local_append(names,values,units, ...
    'bridge_shear_peak_lead_travel',lead_travel_m(sh_t),'m');

deck_entry_travel_m = Calc.Profile.L_Aw-Calc.Veh(1).x_path(1,1);
event_travel_m = [deck_entry_travel_m, ...
    deck_entry_travel_m+Calc.Profile.L_bridge];
for event = 1:2
    [~,index] = min(abs(lead_travel_m-event_travel_m(event)));
    event_name = {'entry','exit'};
    for channel = 1:2
        bridge_name = {'midspan_displacement','midspan_acceleration'};
        bridge_unit = {'m','m/s^2'};
        [names,values,units] = local_append(names,values,units, ...
            sprintf('bridge_%s_at_lead_%s', ...
            bridge_name{channel},event_name{event}), ...
            bridge(channel,index),bridge_unit{channel});
    end
end

retained_mask = lead_travel_m >= retained_x_m(1) & ...
    lead_travel_m <= retained_x_m(end);
for wheel = 1:4
    force = contact(wheel,retained_mask);
    travel = lead_travel_m(retained_mask);
    [absolute_peak,index] = max(abs(force));
    qoi_names = { ...
        sprintf('contact_wheel_%d_signed_tensile_peak',wheel); ...
        sprintf('contact_wheel_%d_compressive_minimum',wheel); ...
        sprintf('contact_wheel_%d_absolute_peak',wheel); ...
        sprintf('contact_wheel_%d_positive_fraction',wheel); ...
        sprintf('contact_wheel_%d_peak_lead_travel',wheel)};
    qoi_values = [max(force);min(force);absolute_peak; ...
        mean(force>0);travel(index)];
    qoi_units = {'N';'N';'N';'1';'m'};
    for qoi = 1:numel(qoi_names)
        [names,values,units] = local_append(names,values,units, ...
            qoi_names{qoi},qoi_values(qoi),qoi_units{qoi});
    end
end
end

function [names,values,units] = local_append( ...
        names,values,units,name,value,unit)
names{end+1,1} = name;
values(end+1,1) = double(value);
units{end+1,1} = unit;
end

function digest = local_numeric_sha256(values)
digest = numerical_vv_sha256_bytes(typecast(double(values(:)),'uint8'));
end

function local_validate_case(case_definition,contract)
required = {'case_id','geometry_id','operating_point_id','clearance_m'};
if ~all(isfield(case_definition,required)) || ...
        ~any(strcmp({contract.geometries.id},case_definition.geometry_id)) || ...
        ~any(strcmp({contract.operating_points.id}, ...
        case_definition.operating_point_id)) || ...
        ~any(abs(contract.clearance_m-case_definition.clearance_m) < 1e-12)
    error('rail_domain_clearance:UnregisteredCase', ...
        'The case is not in the source-locked clearance matrix.');
end
expected_id = sprintf('%s_%s_C%02d',case_definition.geometry_id, ...
    case_definition.operating_point_id,round(case_definition.clearance_m));
if ~strcmp(case_definition.case_id,expected_id)
    error('rail_domain_clearance:CaseIdentity', ...
        'case_id does not match its source-locked descriptor.');
end
end

function local_assert_finite(run)
arrays = {run.retained_x_m,run.retained_waveforms, ...
    run.profile_retained_h_m,run.scalar_values, ...
    run.wheel_end_clearances.start_clearance_m, ...
    run.wheel_end_clearances.end_clearance_m};
for k = 1:numel(arrays)
    if ~isreal(arrays{k}) || any(~isfinite(arrays{k}(:)))
        error('rail_domain_clearance:NonfiniteRun', ...
            'The compact clearance run contains complex or nonfinite data.');
    end
end
end
