function result = rail_domain_clearance_study(output_dir,varargin)
%RAIL_DOMAIN_CLEARANCE_STUDY Coupled 6/15/30 m finite-rail-domain gate.
%
% Default execution is the complete source-locked matrix: F40 and L99.6,
% healthy V70/T3, V80/T18, and V90/T33, at 6/15/30 m (18 solves). Use
% SmokeOnly=true only for the one-solve C15 plumbing smoke; it emits an
% UNVERIFIED verdict and cannot select a production clearance.

parser = inputParser;
addRequired(parser,'output_dir',@local_text_scalar);
addParameter(parser,'SmokeOnly',false,@local_logical_scalar);
addParameter(parser,'Command','',@local_text_scalar);
parse(parser,output_dir,varargin{:});
opt = parser.Results;
output_dir = char(java.io.File(char(output_dir)).getCanonicalPath());

if exist(output_dir,'file') || exist(output_dir,'dir')
    error('rail_domain_clearance:OutputAlreadyExists', ...
        ['Output must be a new path; overwrite and resume are forbidden: ' ...
         '%s'],output_dir);
end
[made,message] = mkdir(output_dir);
if ~made
    error('rail_domain_clearance:OutputCreate', ...
        'Could not create output directory: %s',message);
end
incomplete_path = fullfile(output_dir,'_RUN_INCOMPLETE');
local_write_text(incomplete_path,sprintf( ...
    'schema=rail-domain-clearance-incomplete-v1\nstatus=INCOMPLETE\n'));

P = numerical_vv_protocol_definition();
C = P.rail_domain_clearance;
if opt.SmokeOnly
    run_kind = C.smoke_run_kind;
else
    run_kind = C.full_run_kind;
end
cases = local_cases(C,opt.SmokeOnly);

% Authenticate the complete reviewed MATLAB generator tree before the first
% solve. The digest text is saved verbatim so the independent checker can
% recompute both every file hash and the aggregate root.
[source_root_sha256,source_digest_lines,source_file_count] = ...
    generator_source_root();
local_write_text(fullfile(output_dir,'source_manifest.txt'), ...
    [source_digest_lines,newline]);
source = local_git_identity();

input_descriptor = struct( ...
    'schema','rail-domain-clearance-input-v1', ...
    'run_kind',run_kind, ...
    'case_count',numel(cases), ...
    'cases',cases, ...
    'clearance_m',C.clearance_m, ...
    'production_decision_id',C.production_decision_id, ...
    'reviewed_production_clearance_m', ...
        C.reviewed_production_clearance_m, ...
    'profile',C.profile, ...
    'retained_window',C.retained_window, ...
    'source_root_sha256',source_root_sha256, ...
    'dynamic_solver_executed',true, ...
    'physical_validation_requested',false, ...
    'general_numerical_qualification_requested',false);
input_json = jsonencode(input_descriptor);
input_hash = numerical_vv_sha256_bytes( ...
    unicode2native(input_json,'UTF-8'));
local_write_json(fullfile(output_dir,'input_descriptor.json'), ...
    input_descriptor);
local_write_json(fullfile(output_dir,'protocol_snapshot.json'),C);

start_utc = local_utc_now();
clock_start = tic;
runs_cell = cell(numel(cases),1);
for case_index = 1:numel(cases)
    fprintf('RAIL DOMAIN CLEARANCE: case %d/%d %s\n', ...
        case_index,numel(cases),cases(case_index).case_id);
    runs_cell{case_index} = rail_domain_clearance_run_one( ...
        cases(case_index),C);
end
runs = vertcat(runs_cell{:});

case_table = local_case_table(runs,input_hash,source.commit);
endpoint_table = local_endpoint_table(runs,input_hash,source.commit);
[waveform_metrics,scalar_metrics,comparison_summary] = ...
    local_comparisons(runs,C,input_hash,source.commit,opt.SmokeOnly);
verdict = local_verdict(run_kind,runs,comparison_summary,C, ...
    input_hash,source_root_sha256,opt.SmokeOnly);

writetable(case_table,fullfile(output_dir,'case_table.csv'));
writetable(endpoint_table, ...
    fullfile(output_dir,'wheel_end_clearances.csv'));
writetable(waveform_metrics, ...
    fullfile(output_dir,'waveform_metrics.csv'));
writetable(scalar_metrics,fullfile(output_dir,'scalar_metrics.csv'));
writetable(comparison_summary, ...
    fullfile(output_dir,'comparison_summary.csv'));
save(fullfile(output_dir,'raw_clearance_runs.mat'),'runs','-v7.3');
local_write_json(fullfile(output_dir,'verdict.json'),verdict);
local_write_report(fullfile(output_dir,'rail_domain_clearance_report.md'), ...
    verdict,comparison_summary,C);

required = sort(C.required_artifacts(:));
present = local_file_names(output_dir,{'_RUN_INCOMPLETE'});
if ~isequal(required,present)
    error('rail_domain_clearance:ArtifactInventory', ...
        'Required artifact inventory is missing, extra, or duplicated.');
end
artifact_inventory = local_artifact_inventory(output_dir,present);
elapsed_s = toc(clock_start);
end_utc = local_utc_now();
if isempty(opt.Command)
    command = sprintf('rail_domain_clearance_study("%s","SmokeOnly",%s)', ...
        output_dir,lower(char(string(logical(opt.SmokeOnly)))));
else
    command = char(opt.Command);
end
manifest = struct( ...
    'schema','rail-domain-clearance-manifest-v1', ...
    'protocol_schema',C.schema, ...
    'run_kind',run_kind, ...
    'status','COMPLETE', ...
    'claim_scope',C.claim_scope, ...
    'production_decision_id',C.production_decision_id, ...
    'reviewed_production_clearance_m', ...
        C.reviewed_production_clearance_m, ...
    'numerical_verification_claim_authorized',false, ...
    'physical_validation_claim_authorized',false, ...
    'source_commit',source.commit, ...
    'source_clean',source.clean, ...
    'generator_source_root_sha256',source_root_sha256, ...
    'generator_source_file_count',source_file_count, ...
    'input_hash',input_hash, ...
    'case_count',numel(cases), ...
    'artifacts',artifact_inventory, ...
    'host',getenv('COMPUTERNAME'), ...
    'matlab_release',version('-release'), ...
    'command',command, ...
    'start_utc',start_utc, ...
    'end_utc',end_utc, ...
    'elapsed_s',elapsed_s);
local_write_json(fullfile(output_dir,'manifest.json'),manifest);
manifest_sha256 = numerical_vv_file_sha256( ...
    fullfile(output_dir,'manifest.json'));
delete(incomplete_path);
local_write_text(fullfile(output_dir,'_RUN_COMPLETE'),sprintf([ ...
    'schema=rail-domain-clearance-completion-v1\n' ...
    'run_kind=%s\nstatus=COMPLETE\nmanifest_sha256=%s\n'], ...
    run_kind,manifest_sha256));

result = struct('manifest',manifest,'verdict',verdict, ...
    'output_dir',output_dir,'manifest_sha256',manifest_sha256);
end

function cases = local_cases(C,smoke_only)
template = struct('case_id','','geometry_id','', ...
    'operating_point_id','','clearance_m',0);
all_cases = repmat(template,C.expected_full_solve_count,1);
row = 0;
for geometry = 1:numel(C.geometries)
    for operating = 1:numel(C.operating_points)
        for clearance = 1:numel(C.clearance_m)
            row = row+1;
            all_cases(row) = struct( ...
                'case_id',sprintf('%s_%s_C%02d', ...
                    C.geometries(geometry).id, ...
                    C.operating_points(operating).id, ...
                    round(C.clearance_m(clearance))), ...
                'geometry_id',C.geometries(geometry).id, ...
                'operating_point_id',C.operating_points(operating).id, ...
                'clearance_m',C.clearance_m(clearance));
        end
    end
end
if smoke_only
    selected = strcmp({all_cases.case_id},C.smoke_case_id);
    if nnz(selected) ~= 1
        error('rail_domain_clearance:SmokeCaseContract', ...
            'The source-locked smoke case is absent or duplicated.');
    end
    cases = all_cases(selected);
else
    cases = all_cases;
end
end

function T = local_case_table(runs,input_hash,source_commit)
n = numel(runs);
case_id = strings(n,1); geometry_id = strings(n,1);
operating_point_id = strings(n,1); clearance_m = zeros(n,1);
speed_kmh = zeros(n,1); temperature_degC = zeros(n,1);
bridge_length_m = zeros(n,1); num_spans = zeros(n,1);
bridge_elements_per_sleeper_bay = zeros(n,1);
rail_elements_per_sleeper_bay = zeros(n,1);
rail_length_m = zeros(n,1); rail_domain_translation_m = zeros(n,1);
deck_global_x_m = zeros(n,1); lead_start_global_x_m = zeros(n,1);
lead_end_global_x_m = zeros(n,1); lead_to_deck_m = zeros(n,1);
lead_travel_m = zeros(n,1); solve_duration_s = zeros(n,1);
actual_dt_s = zeros(n,1); solver_sample_count = zeros(n,1);
retained_start_m = zeros(n,1); retained_end_m = zeros(n,1);
retained_dx_m = zeros(n,1); retained_sample_count = zeros(n,1);
minimum_start_clearance_m = zeros(n,1);
minimum_end_clearance_m = zeros(n,1);
profile_retained_sha256 = strings(n,1);
aggregate_tensile_peak_n = zeros(n,1);
aggregate_positive_fraction = zeros(n,1);
contact_admissible = false(n,1); contact_lost_track = false(n,1);
for k = 1:n
    r = runs(k);
    case_id(k)=r.case_id; geometry_id(k)=r.geometry_id;
    operating_point_id(k)=r.operating_point_id;
    clearance_m(k)=r.clearance_m; speed_kmh(k)=r.speed_kmh;
    temperature_degC(k)=r.temperature_degC;
    bridge_length_m(k)=r.bridge_length_m; num_spans(k)=r.num_spans;
    bridge_elements_per_sleeper_bay(k)=r.bridge_elements_per_sleeper_bay;
    rail_elements_per_sleeper_bay(k)=r.rail_elements_per_sleeper_bay;
    rail_length_m(k)=r.rail_length_m;
    rail_domain_translation_m(k)=r.rail_domain_translation_m;
    deck_global_x_m(k)=r.deck_global_x_m;
    lead_start_global_x_m(k)=r.lead_start_global_x_m;
    lead_end_global_x_m(k)=r.lead_end_global_x_m;
    lead_to_deck_m(k)=r.lead_to_deck_m; lead_travel_m(k)=r.lead_travel_m;
    solve_duration_s(k)=r.solve_duration_s; actual_dt_s(k)=r.actual_dt_s;
    solver_sample_count(k)=r.solver_sample_count;
    retained_start_m(k)=r.retained_x_m(1);
    retained_end_m(k)=r.retained_x_m(end);
    retained_dx_m(k)=r.retained_x_m(2)-r.retained_x_m(1);
    retained_sample_count(k)=numel(r.retained_x_m);
    minimum_start_clearance_m(k)=r.minimum_start_clearance_m;
    minimum_end_clearance_m(k)=r.minimum_end_clearance_m;
    profile_retained_sha256(k)=r.profile_retained_sha256;
    aggregate_tensile_peak_n(k)=r.aggregate_tensile_peak_n;
    aggregate_positive_fraction(k)=r.aggregate_positive_fraction;
    contact_admissible(k)=r.contact_admissible;
    contact_lost_track(k)=r.contact_lost_track;
end
source_commit = repmat(string(source_commit),n,1);
input_hash = repmat(string(input_hash),n,1);
T = table(case_id,geometry_id,operating_point_id,clearance_m, ...
    speed_kmh,temperature_degC,bridge_length_m,num_spans, ...
    bridge_elements_per_sleeper_bay,rail_elements_per_sleeper_bay, ...
    rail_length_m,rail_domain_translation_m,deck_global_x_m, ...
    lead_start_global_x_m,lead_end_global_x_m,lead_to_deck_m, ...
    lead_travel_m,solve_duration_s,actual_dt_s,solver_sample_count, ...
    retained_start_m,retained_end_m,retained_dx_m, ...
    retained_sample_count,minimum_start_clearance_m, ...
    minimum_end_clearance_m,profile_retained_sha256, ...
    aggregate_tensile_peak_n,aggregate_positive_fraction, ...
    contact_admissible,contact_lost_track,source_commit,input_hash);
end

function T = local_endpoint_table(runs,input_hash,source_commit)
tables = cell(numel(runs),1);
for k = 1:numel(runs)
    one = runs(k).wheel_end_clearances;
    n = height(one);
    one = addvars(one,repmat(string(runs(k).case_id),n,1), ...
        repmat(string(runs(k).geometry_id),n,1), ...
        repmat(string(runs(k).operating_point_id),n,1), ...
        'Before',1,'NewVariableNames', ...
        {'case_id','geometry_id','operating_point_id'});
    one.source_commit = repmat(string(source_commit),n,1);
    one.input_hash = repmat(string(input_hash),n,1);
    tables{k} = one;
end
T = vertcat(tables{:});
end

function [waveform,scalar,summary] = local_comparisons( ...
        runs,C,input_hash,source_commit,smoke_only)
waveform = local_empty_waveform_table();
scalar = local_empty_scalar_table();
summary = local_empty_summary_table();
if smoke_only
    return
end
for geometry = 1:numel(C.geometries)
    for operating = 1:numel(C.operating_points)
        group = strcmp({runs.geometry_id},C.geometries(geometry).id) & ...
            strcmp({runs.operating_point_id},C.operating_points(operating).id);
        group_runs = runs(group);
        if numel(group_runs) ~= numel(C.clearance_m)
            error('rail_domain_clearance:ComparisonInventory', ...
                'Each geometry/operating group must contain all clearances.');
        end
        for comparison = 1:numel(C.comparisons)
            policy = C.comparisons(comparison);
            test = group_runs(abs([group_runs.clearance_m]- ...
                policy.test_clearance_m)<1e-12);
            reference = group_runs(abs([group_runs.clearance_m]- ...
                policy.reference_clearance_m)<1e-12);
            if numel(test) ~= 1 || numel(reference) ~= 1
                error('rail_domain_clearance:ComparisonInventory', ...
                    'A registered test/reference arm is absent or duplicated.');
            end
            metric = numerical_vv_waveform_metrics( ...
                reference.retained_x_m,reference.retained_waveforms, ...
                test.retained_x_m,test.retained_waveforms, ...
                reference.retained_x_m, ...
                'ChannelNames',C.waveform_channels);
            if any(~isfinite(metric.nrmse)) || ...
                    any(~isfinite(metric.normalized_max_error)) || ...
                    any(~isfinite(metric.correlation))
                error('rail_domain_clearance:NonfiniteMetric', ...
                    'A registered waveform comparison returned nonfinite metrics.');
            end
            channel_pass = metric.nrmse <= policy.maximum_nrmse & ...
                metric.normalized_max_error <= ...
                    policy.maximum_normalized_max_error & ...
                metric.correlation >= policy.minimum_correlation;
            rows = addvars(metric, ...
                repmat(string(test.geometry_id),height(metric),1), ...
                repmat(string(test.operating_point_id),height(metric),1), ...
                repmat(string(policy.id),height(metric),1), ...
                repmat(policy.test_clearance_m,height(metric),1), ...
                repmat(policy.reference_clearance_m,height(metric),1), ...
                repmat(policy.maximum_nrmse,height(metric),1), ...
                repmat(policy.maximum_normalized_max_error,height(metric),1), ...
                repmat(policy.minimum_correlation,height(metric),1), ...
                channel_pass, ...
                'Before',1,'NewVariableNames',{ ...
                'geometry_id','operating_point_id','comparison_id', ...
                'test_clearance_m','reference_clearance_m', ...
                'maximum_nrmse','maximum_normalized_max_error', ...
                'minimum_correlation','channel_pass'});
            rows.source_commit = repmat(string(source_commit),height(rows),1);
            rows.input_hash = repmat(string(input_hash),height(rows),1);
            waveform = [waveform;rows]; %#ok<AGROW>

            if ~isequal(test.scalar_names,reference.scalar_names) || ...
                    ~isequal(test.scalar_units,reference.scalar_units)
                error('rail_domain_clearance:ScalarInventory', ...
                    'Scalar QoI inventories differ between clearance arms.');
            end
            delta = test.scalar_values-reference.scalar_values;
            relative = abs(delta)./max(abs(reference.scalar_values),1e-15);
            scalar_rows = table( ...
                repmat(string(test.geometry_id),numel(delta),1), ...
                repmat(string(test.operating_point_id),numel(delta),1), ...
                repmat(string(policy.id),numel(delta),1), ...
                string(test.scalar_names),string(test.scalar_units), ...
                test.scalar_values,reference.scalar_values,delta,relative, ...
                'VariableNames',{'geometry_id','operating_point_id', ...
                'comparison_id','qoi_id','unit','test_value', ...
                'reference_value','signed_difference','relative_difference'});
            scalar_rows.source_commit = repmat( ...
                string(source_commit),height(scalar_rows),1);
            scalar_rows.input_hash = repmat( ...
                string(input_hash),height(scalar_rows),1);
            scalar = [scalar;scalar_rows]; %#ok<AGROW>

            profile_max_abs_delta_m = max(abs( ...
                test.profile_retained_h_m-reference.profile_retained_h_m));
            geometry_invariant = ...
                abs(test.lead_to_deck_m-reference.lead_to_deck_m) <= ...
                    C.invariance_tolerance.geometry_m && ...
                abs(test.lead_travel_m-reference.lead_travel_m) <= ...
                    C.invariance_tolerance.geometry_m && ...
                abs(test.solve_duration_s-reference.solve_duration_s) <= ...
                    C.invariance_tolerance.time_s && ...
                test.solver_sample_count == reference.solver_sample_count && ...
                isequal(test.retained_x_m,reference.retained_x_m);
            profile_invariant = profile_max_abs_delta_m <= ...
                C.invariance_tolerance.profile_elevation_m;
            clearance_enforced = ...
                test.minimum_start_clearance_m >= ...
                    test.clearance_m-C.invariance_tolerance.geometry_m && ...
                test.minimum_end_clearance_m >= ...
                    test.clearance_m-C.invariance_tolerance.geometry_m && ...
                reference.minimum_start_clearance_m >= ...
                    reference.clearance_m-C.invariance_tolerance.geometry_m && ...
                reference.minimum_end_clearance_m >= ...
                    reference.clearance_m-C.invariance_tolerance.geometry_m;
            contact_admissible = test.contact_admissible && ...
                reference.contact_admissible;
            waveform_pass = all(channel_pass);
            comparison_pass = waveform_pass && geometry_invariant && ...
                profile_invariant && clearance_enforced && contact_admissible;
            summary_row = table(string(test.geometry_id), ...
                string(test.operating_point_id),string(policy.id), ...
                policy.test_clearance_m,policy.reference_clearance_m, ...
                policy.maximum_nrmse, ...
                policy.maximum_normalized_max_error, ...
                policy.minimum_correlation,max(metric.nrmse), ...
                max(metric.normalized_max_error),min(metric.correlation), ...
                profile_max_abs_delta_m,waveform_pass,geometry_invariant, ...
                profile_invariant,clearance_enforced,contact_admissible, ...
                comparison_pass,string(source_commit),string(input_hash), ...
                'VariableNames',summary.Properties.VariableNames);
            summary = [summary;summary_row]; %#ok<AGROW>
        end
    end
end
end

function verdict = local_verdict(run_kind,runs,summary,C,input_hash, ...
        source_root_sha256,smoke_only)
verdict = struct();
verdict.schema = 'rail-domain-clearance-verdict-v1';
verdict.run_kind = run_kind;
verdict.claim_scope = C.claim_scope;
verdict.production_decision_id = C.production_decision_id;
verdict.reviewed_production_clearance_m = ...
    C.reviewed_production_clearance_m;
verdict.numerical_verification_claim_authorized = false;
verdict.physical_validation_claim_authorized = false;
verdict.input_hash = input_hash;
verdict.generator_source_root_sha256 = source_root_sha256;
verdict.completed_case_ids = {runs.case_id};
verdict.completed_case_count = numel(runs);
verdict.diagnostic_clearance_m = 30;
if smoke_only
    verdict.overall_status = 'UNVERIFIED';
    verdict.production_selection_status = 'NOT_EVALUATED';
    verdict.production_clearance_m = [];
    verdict.coarse_comparison_pass = false;
    verdict.primary_comparison_pass = false;
    verdict.reason = [ ...
        'one-case coupled plumbing smoke; the 18-solve selection matrix ' ...
        'was not executed'];
else
    coarse = summary(strcmp(summary.comparison_id,'C06_vs_C30'),:);
    primary = summary(strcmp(summary.comparison_id,'C15_vs_C30'),:);
    expected_groups = numel(C.geometries)*numel(C.operating_points);
    if height(coarse) ~= expected_groups || height(primary) ~= expected_groups
        error('rail_domain_clearance:VerdictInventory', ...
            'Comparison summary is incomplete or duplicated.');
    end
    coarse_pass = all(coarse.comparison_pass);
    primary_pass = all(primary.comparison_pass);
    verdict.coarse_comparison_pass = logical(coarse_pass);
    verdict.primary_comparison_pass = logical(primary_pass);
    if coarse_pass && primary_pass
        verdict.overall_status = 'PASS';
        verdict.production_selection_status = 'SELECTED';
        verdict.production_clearance_m = 6;
        verdict.reason = 'both C06-vs-C30 and primary C15-vs-C30 pass';
    elseif primary_pass
        verdict.overall_status = 'PASS';
        verdict.production_selection_status = 'SELECTED';
        verdict.production_clearance_m = 15;
        verdict.reason = 'primary C15-vs-C30 passes; C06-vs-C30 fails';
    else
        verdict.overall_status = 'UNRESOLVED';
        verdict.production_selection_status = 'UNRESOLVED';
        verdict.production_clearance_m = [];
        verdict.reason = [ ...
            'primary C15-vs-C30 fails; 30 m is diagnostic only and no ' ...
            'production clearance is authorized'];
    end
end
verdict.reviewed_production_decision_confirmed = logical( ...
    ~smoke_only && strcmp(verdict.production_selection_status,'SELECTED') && ...
    isequal(verdict.production_clearance_m, ...
        C.reviewed_production_clearance_m));
verdict.claims_can_support = { ...
    'finite-rail-domain selection for the source-locked case matrix'};
verdict.claims_cannot_support = { ...
    'general mesh/time-step convergence'; ...
    'damage-model validation'; ...
    'physical or field validation'};
end

function T = local_empty_waveform_table()
T = table(strings(0,1),strings(0,1),strings(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),false(0,1), ...
    strings(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'geometry_id','operating_point_id','comparison_id', ...
    'test_clearance_m','reference_clearance_m','maximum_nrmse', ...
    'maximum_normalized_max_error','minimum_correlation','channel_pass', ...
    'channel_id','nrmse','normalized_max_error','correlation', ...
    'reference_rms','test_rms','reference_abs_peak','test_abs_peak', ...
    'peak_amplitude_error','peak_position_error_m','source_commit','input_hash'});
end

function T = local_empty_scalar_table()
T = table(strings(0,1),strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'geometry_id','operating_point_id','comparison_id', ...
    'qoi_id','unit','test_value','reference_value','signed_difference', ...
    'relative_difference','source_commit','input_hash'});
end

function T = local_empty_summary_table()
T = table(strings(0,1),strings(0,1),strings(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),false(0,1),false(0,1), ...
    false(0,1),false(0,1),false(0,1),false(0,1), ...
    strings(0,1),strings(0,1), ...
    'VariableNames',{'geometry_id','operating_point_id','comparison_id', ...
    'test_clearance_m','reference_clearance_m','maximum_nrmse', ...
    'maximum_normalized_max_error','minimum_correlation','worst_nrmse', ...
    'worst_normalized_max_error','worst_correlation', ...
    'profile_max_abs_delta_m','waveform_pass','geometry_invariant', ...
    'profile_invariant','clearance_enforced','contact_admissible', ...
    'comparison_pass','source_commit','input_hash'});
end

function local_write_report(path,verdict,summary,C)
lines = { ...
    '# Rail-domain clearance study';''; ...
    sprintf('- Run kind: `%s`',verdict.run_kind); ...
    sprintf('- Status: **%s**',verdict.overall_status); ...
    sprintf('- Production selection: `%s`', ...
        verdict.production_selection_status); ...
    sprintf('- Diagnostic reference: %.0f m', ...
        verdict.diagnostic_clearance_m); ...
    sprintf('- Reason: %s',verdict.reason);''; ...
    'This verdict is limited to finite-rail-domain model-form selection.'; ...
    'It does not authorize physical validation or general numerical V&V.';''; ...
    '## Frozen rule';'';C.selection_rule;''};
if ~isempty(verdict.production_clearance_m)
    lines{end+1} = sprintf('Selected production clearance: **%.0f m**.', ...
        verdict.production_clearance_m);
    lines{end+1} = '';
end
if ~isempty(summary)
    lines{end+1} = '## Group comparisons';
    lines{end+1} = '';
    lines{end+1} = ['| Geometry | Operating point | Comparison | Worst NRMSE | ' ...
        'Worst NMAX | Min corr. | Pass |'];
    lines{end+1} = '|---|---|---|---:|---:|---:|:---:|';
    comparison_lines = cell(height(summary),1);
    for row = 1:height(summary)
        comparison_lines{row} = sprintf( ...
            '| %s | %s | %s | %.6g | %.6g | %.6g | %d |', ...
            summary.geometry_id(row),summary.operating_point_id(row), ...
            summary.comparison_id(row),summary.worst_nrmse(row), ...
            summary.worst_normalized_max_error(row), ...
            summary.worst_correlation(row),summary.comparison_pass(row));
    end
    lines = [lines;comparison_lines];
end
local_write_text(path,[strjoin(lines,newline),newline]);
end

function source = local_git_identity()
matlab_root = fileparts(mfilename('fullpath'));
repo_root = fileparts(matlab_root);
[commit_status,commit_text] = system(sprintf( ...
    'git -C "%s" rev-parse HEAD',repo_root));
[dirty_status,dirty_text] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=normal',repo_root));
if commit_status == 0
    commit = strtrim(commit_text);
else
    commit = 'UNAVAILABLE';
end
clean = commit_status == 0 && dirty_status == 0 && isempty(strtrim(dirty_text));
source = struct('commit',commit,'clean',logical(clean));
end

function inventory = local_artifact_inventory(root,names)
inventory = repmat(struct('path','','sha256','','bytes',0),numel(names),1);
for k = 1:numel(names)
    path = fullfile(root,names{k}); info = dir(path);
    inventory(k).path = names{k};
    inventory(k).sha256 = numerical_vv_file_sha256(path);
    inventory(k).bytes = info.bytes;
end
end

function names = local_file_names(root,excluded)
entries = dir(root); entries = entries(~[entries.isdir]);
names = sort(reshape({entries.name},[],1));
names = setdiff(names,excluded,'stable');
end

function local_write_json(path,value)
local_write_text(path,[jsonencode(value,'PrettyPrint',true),newline]);
end

function local_write_text(path,value)
bytes = unicode2native(char(value),'UTF-8');
fid = fopen(path,'wb');
if fid < 0
    error('rail_domain_clearance:FileWrite','Could not write %s.',path);
end
cleanup = onCleanup(@() fclose(fid));
written = fwrite(fid,bytes,'uint8');
if written ~= numel(bytes)
    error('rail_domain_clearance:FileWrite','Short write to %s.',path);
end
end

function value = local_utc_now()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSSXXX'));
end

function tf = local_text_scalar(value)
tf = ischar(value) || (isstring(value) && isscalar(value));
end

function tf = local_logical_scalar(value)
tf = (islogical(value) || isnumeric(value)) && isscalar(value) && ...
    isfinite(double(value)) && any(double(value)==[0,1]);
end
