function [healthy, interventions, design] = ...
        response_signature_damage_catalog(design)
%RESPONSE_SIGNATURE_DAMAGE_CATALOG Deterministic one-factor TTBI descriptors.
%
% [healthy, interventions, design] = response_signature_damage_catalog()
% returns the healthy descriptor and one representative, interior intervention
% for every active MATLAB mechanism.  The catalogue contains no random draw:
% it is an executable response-fingerprint fixture, not a replacement for the
% registered 50-passage mechanism-trend study.
%
% The track coordinates use the campaign-local frame
%   [30 m approach, bridge, 30 m exit]
% and x_bridge_local identifies the deck start in that frame.  Nominal
% bearing fixity is an intervention coordinate, not physical bearing damage.

if nargin < 1 || isempty(design)
    design = struct();
end
design = local_design_defaults(design);

n_supports = design.num_spans + 1;
healthy = struct();
healthy.desvio = 0;
healthy.scour_rates = zeros(1,n_supports);
healthy.bearing_left = 0;
healthy.bearing_right = 0;
healthy.crack_locs = [];
healthy.crack_intensity = [];
healthy.crack_lc = 0;
healthy.track = [];
healthy.oor_flats = zeros(0,5); % dormant by production contract
healthy.oor_poly = zeros(0,5);
healthy.oor_radius = design.wheel_radius_m;

interventions = repmat(local_empty_intervention(),0,1);

damage = healthy;
damage.scour_rates(design.scour_support) = design.scour_fraction;
interventions(end+1) = local_item( ...
    'scour','support-stiffness loss', ...
    sprintf('support %d, loss %.3g',design.scour_support, ...
    design.scour_fraction),damage,{'scour_rates'}, ...
    'bridge_stiffness_state_specific_rayleigh_damping');

span_length_m = design.L_bridge_m / design.num_spans;
bearing_reference_nm_per_rad = 4 * design.E15_pa * design.I_m4 / ...
    span_length_m;
bearing_k_nm_per_rad = bearing_reference_nm_per_rad * ...
    design.bearing_fixity / (1 - design.bearing_fixity);
damage = healthy;
damage.bearing_left = bearing_k_nm_per_rad;
interventions(end+1) = local_item( ...
    'bearing_fixity','nominal abutment rotational fixity', ...
    sprintf('left abutment, phi %.3g, k %.9g Nm/rad', ...
    design.bearing_fixity,bearing_k_nm_per_rad),damage, ...
    {'bearing_left'}, ...
    'bridge_stiffness_state_specific_rayleigh_damping');

damage = healthy;
damage.crack_locs = design.crack_location_m;
damage.crack_intensity = design.crack_intensity;
damage.crack_lc = 0;
interventions(end+1) = local_item( ...
    'crack','one-element EI reduction', ...
    sprintf('x %.3g m, EI loss %.3g',design.crack_location_m, ...
    design.crack_intensity),damage, ...
    {'crack_locs','crack_intensity'}, ...
    'bridge_stiffness_state_specific_rayleigh_damping');

track = local_track_identity(design);
track.ballast_patches = design.ballast_patch;
damage = healthy;
damage.track = track;
interventions(end+1) = local_item( ...
    'ballast_patch','paired ballast stiffness/damping patch', ...
    sprintf('[%.3g, %.3g] m, eta_k %.3g, eta_c %.3g', ...
    design.ballast_patch),damage,{'track'},'track_stiffness_damping');

track = local_track_identity(design);
track.hanging_groups = design.hanging_group;
damage = healthy;
damage.track = track;
interventions(end+1) = local_item( ...
    'hanging_sleepers','near-zero sleeper support group', ...
    sprintf('start %.3g m, count %d',design.hanging_group), ...
    damage,{'track'},'track_stiffness_damping');

track = local_track_identity(design);
track.pad_stiff_mult = design.pad_stiffness_multiplier;
damage = healthy;
damage.track = track;
interventions(end+1) = local_item( ...
    'pad_service_stiffness','state-global pad stiffness', ...
    sprintf('eta_k %.3g; damping held at 1', ...
    design.pad_stiffness_multiplier),damage,{'track'},'track_stiffness_only');

track = local_track_identity(design);
track.pad_damp_mult = design.pad_damping_multiplier;
damage = healthy;
damage.track = track;
interventions(end+1) = local_item( ...
    'pad_service_damping','state-global pad damping', ...
    sprintf('eta_c %.3g; stiffness held at 1', ...
    design.pad_damping_multiplier),damage,{'track'},'track_damping_only');

track = local_track_identity(design);
track.pad_failures = design.pad_failure_m;
damage = healthy;
damage.track = track;
interventions(end+1) = local_item( ...
    'pad_failure','one near-zero rail-pad connection', ...
    sprintf('x %.3g m',design.pad_failure_m), ...
    damage,{'track'},'track_stiffness_damping');

damage = healthy;
damage.oor_poly = design.polygon_row;
interventions(end+1) = local_item( ...
    'wheel_polygonization','one wheel harmonic path intervention', ...
    sprintf(['vehicle %d wheel %d order %d amplitude %.9g m ' ...
    'phase %.9g rad'],design.polygon_row), ...
    damage,{'oor_poly'},'wheel_path');

local_validate_catalog(healthy,interventions,design);
end

function design = local_design_defaults(design)
defaults = struct( ...
    'L_bridge_m',60, ...
    'num_spans',3, ...
    'speed_kmh',80, ...
    'temperature_c',18, ...
    'case_label','V80_T18', ...
    'vehicle_draw',zeros(5,3), ...
    'profile_phase_seed',20260728, ...
    'profile_fra_class',4, ...
    'E15_pa',35e9, ...
    'I_m4',0.33, ...
    'wheel_radius_m',0.46, ...
    'scour_support',2, ...
    'scour_fraction',0.30, ...
    'bearing_fixity',0.50, ...
    'crack_location_m',30, ...
    'crack_intensity',0.22, ...
    'track_approach_m',30, ...
    'ballast_patch',[40 52 0.80 2.00], ...
    'hanging_group',[30.6 3], ...
    'pad_stiffness_multiplier',1.80, ...
    'pad_damping_multiplier',1.10, ...
    'pad_failure_m',45.0, ...
    'polygon_row',[1 2 3 50e-6 0.7], ...
    'contact_max_tensile_peak_n',24000, ...
    'contact_max_positive_fraction',0.002, ...
    'psd_bands_hz',[0.2 15], ...
    'psd_band_names',{{'bridge_response_0p2_15_hz'}});
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(design,names{k})
        design.(names{k}) = defaults.(names{k});
    end
end
design.polygon_harmonic_frequency_hz = design.polygon_row(3) * ...
    (design.speed_kmh/3.6) / (2*pi*design.wheel_radius_m);
end

function track = local_track_identity(design)
track = struct();
track.ballast_patches = zeros(0,4);
track.hanging_groups = zeros(0,2);
track.pad_stiff_mult = 1;
track.pad_damp_mult = 1;
track.pad_failures = zeros(1,0);
track.x_bridge_local = design.track_approach_m;
end

function item = local_empty_intervention()
item = struct( ...
    'name','', ...
    'role','', ...
    'mechanism','', ...
    'level_label','', ...
    'damage',struct(), ...
    'changed_damage_fields',{{}}, ...
    'first_changed_quantity','');
end

function item = local_item(name,mechanism,level_label,damage,fields,quantity)
item = local_empty_intervention();
item.name = name;
switch name
    case 'scour'
        item.role = 'active support-loss regression target';
    case 'bearing_fixity'
        item.role = [ ...
            'active structural-design-coordinate target ' ...
            '(not physical bearing damage)'];
    case 'crack'
        item.role = 'bridge-condition nuisance';
    case {'ballast_patch','hanging_sleepers', ...
            'pad_service_stiffness','pad_service_damping','pad_failure'}
        item.role = 'track-condition nuisance/EOV';
    case 'wheel_polygonization'
        item.role = 'wheel-condition nuisance';
    otherwise
        error('response_signature:UnknownRole', ...
            'No canonical analysis role is defined for %s.',name);
end
item.mechanism = mechanism;
item.level_label = level_label;
item.damage = damage;
item.changed_damage_fields = fields;
item.first_changed_quantity = quantity;
end

function local_validate_catalog(healthy,interventions,design)
if ~isscalar(design.num_spans) || design.num_spans < 1 || ...
        design.num_spans ~= fix(design.num_spans)
    error('response_signature:InvalidDesign', ...
        'num_spans must be a positive integer.');
end
if ~isequal(size(design.vehicle_draw),[5 3]) || ...
        any(~isfinite(design.vehicle_draw(:)))
    error('response_signature:InvalidDesign', ...
        'vehicle_draw must be one finite 5-by-3 passage descriptor.');
end
if design.scour_support <= 1 || ...
        design.scour_support >= design.num_spans + 1
    error('response_signature:InvalidDesign', ...
        'scour_support must select one internal bridge support.');
end
if design.bearing_fixity <= 0 || design.bearing_fixity >= 1
    error('response_signature:InvalidDesign', ...
        'bearing_fixity must be strictly between zero and one.');
end
if ~isscalar(design.contact_max_tensile_peak_n) || ...
        ~isfinite(design.contact_max_tensile_peak_n) || ...
        design.contact_max_tensile_peak_n < 0 || ...
        ~isscalar(design.contact_max_positive_fraction) || ...
        ~isfinite(design.contact_max_positive_fraction) || ...
        design.contact_max_positive_fraction < 0 || ...
        design.contact_max_positive_fraction > 1
    error('response_signature:InvalidDesign', ...
        'Contact limits must be finite, with peak >= 0 and fraction in [0,1].');
end
if ~isscalar(design.polygon_harmonic_frequency_hz) || ...
        ~isfinite(design.polygon_harmonic_frequency_hz) || ...
        design.polygon_harmonic_frequency_hz <= 0
    error('response_signature:InvalidDesign', ...
        'The derived polygon forcing frequency must be finite and positive.');
end
if ~isequal(size(design.psd_bands_hz,2),2) || ...
        size(design.psd_bands_hz,1) ~= numel(design.psd_band_names) || ...
        any(~isfinite(design.psd_bands_hz(:))) || ...
        any(design.psd_bands_hz(:,1) < 0) || ...
        any(design.psd_bands_hz(:,2) <= design.psd_bands_hz(:,1))
    error('response_signature:InvalidDesign', ...
        'PSD bands must be finite increasing [low high] rows with names.');
end

expected_names = { ...
    'scour','bearing_fixity','crack','ballast_patch', ...
    'hanging_sleepers','pad_service_stiffness', ...
    'pad_service_damping','pad_failure','wheel_polygonization'};
actual_names = {interventions.name};
assert(isequal(actual_names,expected_names), ...
    'response_signature:CatalogInventory', ...
    'The active intervention inventory changed unexpectedly.');
for k = 1:numel(interventions)
    actual_changed = local_changed_top_fields( ...
        healthy,interventions(k).damage);
    expected_changed = sort(interventions(k).changed_damage_fields(:));
    assert(isequal(actual_changed,expected_changed), ...
        'response_signature:DescriptorIsolation', ...
        '%s changed fields outside its declared intervention: %s', ...
        interventions(k).name,strjoin(actual_changed,', '));
end
end

function changed = local_changed_top_fields(left,right)
names = union(fieldnames(left),fieldnames(right));
changed = cell(0,1);
for k = 1:numel(names)
    name = names{k};
    left_has = isfield(left,name);
    right_has = isfield(right,name);
    if left_has ~= right_has || ...
            (left_has && ~isequaln(left.(name),right.(name)))
        changed{end+1,1} = name; %#ok<AGROW>
    end
end
changed = sort(changed(:));
end
