function report = response_signature_study(requested_names,design)
%RESPONSE_SIGNATURE_STUDY Exploratory paired TTBI mechanism fingerprints.
%
% report = response_signature_study()
% report = response_signature_study({'scour','wheel_polygonization'})
% report = response_signature_study(requested_names,design)
%
% One fixed passage is cloned exactly and one explicit intervention is made
% active at a time.  The report contains exact matrix/path deltas, matched
% bridge modes, vehicle and bridge RMS/peak/PSD-band metrics, all four
% leading-vehicle contact histories, and all-vehicle per-wheel contact
% diagnostics.  It is intentionally marked exploratory/nonqualifying: it
% does not replace the registered 50-passage, multi-level CRN study.

if nargin < 2
    design = struct();
end
[healthy_damage,catalog,design] = ...
    response_signature_damage_catalog(design);
if nargin < 1 || isempty(requested_names)
    requested_names = {catalog.name};
end
requested_names = local_names(requested_names);
catalog = local_select_catalog(catalog,requested_names);

fprintf(['RESPONSE SIGNATURE STUDY: exploratory/nonqualifying; ' ...
    '1 healthy + %d one-factor passage(s)\n'],numel(catalog));
healthy_run = response_signature_run_one(healthy_damage,design);
healthy_vehicle_metrics = local_metrics(healthy_run.vehicle, ...
    healthy_run.controls.time_s,design);
healthy_bridge_metrics = local_metrics(healthy_run.bridge, ...
    healthy_run.controls.time_s,design);

report = struct();
report.schema = 'ttbi-paired-response-signatures-v2';
report.status = 'exploratory/nonqualifying';
report.study_design = design;
report.crn_contract = [ ...
    'Every intervention reuses exactly the same speed, temperature, ' ...
    'vehicle descriptor, FRA-v2 realization, time grid, wheel positions, ' ...
    'and fixed mesh geometry. Damage-induced placement state, including ' ...
    'track-frame offset, is reported separately and is not a CRN control.'];
report.crn_control_fields = fieldnames(healthy_run.controls);
report.rayleigh_damping_contract = [ ...
    'Bridge-stiffness interventions use state-specific Rayleigh damping: ' ...
    'B24 recomputes bridge damping and the rail damping reference follows ' ...
    'the state bridge modes. Beam/model C deltas are retained and these ' ...
    'pairs are not described as fixed-C or K-only counterfactuals.'];
report.contact_admissibility_policy = healthy_run.contact.registered_policy;
report.polygon_harmonic_contract = [ ...
    'Target frequency is n*v/(2*pi*R). Exact-frequency least-squares ' ...
    'amplitude and nearest-Welch-bin density are reported independently ' ...
    'of the 0.2-15 Hz reporting band.'];
report.interpretation_contract = [ ...
    'Physical response directions are reported, never required. Positive ' ...
    'contact force denotes bilateral-solver tensile demand, not simulated ' ...
    'separation or re-contact.'];
report.limitations = { ...
    ['One deterministic representative passage and one representative ' ...
     'level per intervention only.']; ...
    ['Not the registered 50-passage repeated-observation study and not a ' ...
     'basis for confidence intervals or population inference.']; ...
    ['Bridge-only modes are matched here; coupled track-bridge modal ' ...
     'matching remains part of numerical V&V.']; ...
    ['Contact admissibility uses the source-locked 24 kN peak and 0.002 ' ...
     'on-track positive-fraction limits; any positive reaction remains ' ...
     'reported as bilateral-solver tensile demand.']};
report.healthy = local_healthy_report( ...
    healthy_run,healthy_vehicle_metrics,healthy_bridge_metrics);
report.pairs = repmat(local_empty_pair(),numel(catalog),1);

for k = 1:numel(catalog)
    item = catalog(k);
    fprintf('  [%d/%d] %s: %s\n',k,numel(catalog), ...
        item.name,item.level_label);
    damaged_run = response_signature_run_one(item.damage,design);
    if ~isequaln(healthy_run.controls,damaged_run.controls)
        error('response_signature:CrnMismatch', ...
            '%s changed a non-intervention passage control.',item.name);
    end
    delta = local_physics_delta(healthy_run.physics,damaged_run.physics);
    local_assert_mechanism_boundary( ...
        item,healthy_run.physics,damaged_run.physics,delta);

    damaged_vehicle_metrics = local_metrics( ...
        damaged_run.vehicle,damaged_run.controls.time_s,design);
    damaged_bridge_metrics = local_metrics( ...
        damaged_run.bridge,damaged_run.controls.time_s,design);
    pair = local_empty_pair();
    pair.name = item.name;
    pair.role = item.role;
    pair.mechanism = item.mechanism;
    pair.level_label = item.level_label;
    pair.changed_damage_fields = item.changed_damage_fields;
    pair.damage = item.damage;
    pair.crn_controls_exactly_equal = true;
    pair.crn_control_fields = fieldnames(healthy_run.controls);
    pair.state_specific_geometry = struct( ...
        'healthy',healthy_run.geometry, ...
        'intervention',damaged_run.geometry, ...
        'track_frame_offset_delta_m', ...
            damaged_run.geometry.track_frame_offset_m - ...
            healthy_run.geometry.track_frame_offset_m);
    pair.physics_boundary_role = item.first_changed_quantity;
    pair.physics_delta = delta;
    pair.physics_change_counts = local_change_counts(delta);
    pair.rayleigh_damping = local_rayleigh_damping_report(item,delta);
    pair.modal = local_modal_pair(healthy_run.modal,damaged_run.modal);
    pair.vehicle_metric_comparison = local_metric_comparison( ...
        healthy_vehicle_metrics,damaged_vehicle_metrics);
    pair.vehicle_waveform_delta = ...
        damaged_run.vehicle.signal-healthy_run.vehicle.signal;
    pair.bridge_metric_comparison = local_metric_comparison( ...
        healthy_bridge_metrics,damaged_bridge_metrics);
    pair.bridge_waveform_delta = ...
        damaged_run.bridge.signal-healthy_run.bridge.signal;
    pair.bridge_extreme_comparison = local_bridge_extreme_comparison( ...
        healthy_run.bridge,damaged_run.bridge);
    pair.bridge_event_comparison = local_bridge_event_comparison( ...
        healthy_run.bridge,damaged_run.bridge);
    pair.contact = local_contact_pair( ...
        healthy_run.contact,damaged_run.contact);
    pair.bilateral_contact_admissible = ...
        pair.contact.pair_registered_admissible;
    if strcmp(item.name,'wheel_polygonization')
        pair.polygon_harmonic = local_polygon_harmonic_report( ...
            item,design,healthy_vehicle_metrics,damaged_vehicle_metrics, ...
            healthy_bridge_metrics,damaged_bridge_metrics);
    end
    pair.vehicle_response_changed_exactly = ...
        ~isequal(healthy_run.vehicle.signal,damaged_run.vehicle.signal);
    pair.response_direction_gate = 'none: report signed paired differences';
    report.pairs(k) = pair;
end

fprintf(['RESPONSE SIGNATURE STUDY COMPLETE: %d paired fingerprints; ' ...
    'no response-direction threshold applied; contact policy classified\n'], ...
    numel(report.pairs));
end

function metrics = local_metrics(response,time_s,design)
metrics = response_signature_metrics( ...
    time_s,response.signal,response.channel_names,response.channel_units, ...
    design.psd_bands_hz,design.psd_band_names, ...
    design.polygon_harmonic_frequency_hz,{'wheel_polygon_forcing'});
end

function healthy = local_healthy_report(run,vehicle_metrics,bridge_metrics)
healthy = struct();
healthy.damage = run.damage;
healthy.geometry = run.geometry;
healthy.controls = run.controls;
healthy.vehicle_waveforms = run.vehicle;
healthy.vehicle_metrics = vehicle_metrics;
healthy.bridge_waveforms = run.bridge;
healthy.bridge_metrics = bridge_metrics;
healthy.contact = run.contact;
healthy.contact_summary = local_contact_summary(run.contact);
healthy.modal = run.modal;
healthy.physics = run.physics;
end

function pair = local_empty_pair()
pair = struct( ...
    'name','', ...
    'role','', ...
    'mechanism','', ...
    'level_label','', ...
    'changed_damage_fields',{{}}, ...
    'damage',struct(), ...
    'crn_controls_exactly_equal',false, ...
    'crn_control_fields',{{}}, ...
    'state_specific_geometry',struct(), ...
    'physics_boundary_role','', ...
    'physics_delta',struct(), ...
    'physics_change_counts',struct(), ...
    'rayleigh_damping',struct(), ...
    'modal',struct(), ...
    'vehicle_metric_comparison',table(), ...
    'vehicle_waveform_delta',[], ...
    'bridge_metric_comparison',table(), ...
    'bridge_waveform_delta',[], ...
    'bridge_extreme_comparison',table(), ...
    'bridge_event_comparison',table(), ...
    'contact',struct(), ...
    'bilateral_contact_admissible',false, ...
    'polygon_harmonic',struct(), ...
    'vehicle_response_changed_exactly',false, ...
    'response_direction_gate','');
end

function delta = local_physics_delta(healthy,damaged)
delta = struct( ...
    'beam_M',sparse(damaged.beam_M-healthy.beam_M), ...
    'beam_C',sparse(damaged.beam_C-healthy.beam_C), ...
    'beam_K',sparse(damaged.beam_K-healthy.beam_K), ...
    'model_M',sparse(damaged.model_M-healthy.model_M), ...
    'model_C',sparse(damaged.model_C-healthy.model_C), ...
    'model_K',sparse(damaged.model_K-healthy.model_K), ...
    'wheel_h_m',damaged.wheel_h_m-healthy.wheel_h_m, ...
    'wheel_hd_mps',damaged.wheel_hd_mps-healthy.wheel_hd_mps, ...
    'wheel_hdd_mps2',damaged.wheel_hdd_mps2-healthy.wheel_hdd_mps2, ...
    'track_placement',damaged.track_placement);
end

function counts = local_change_counts(delta)
counts = struct( ...
    'beam_M_nnz',nnz(delta.beam_M), ...
    'beam_C_nnz',nnz(delta.beam_C), ...
    'beam_K_nnz',nnz(delta.beam_K), ...
    'model_M_nnz',nnz(delta.model_M), ...
    'model_C_nnz',nnz(delta.model_C), ...
    'model_K_nnz',nnz(delta.model_K), ...
    'wheel_h_count',nnz(delta.wheel_h_m), ...
    'wheel_hd_count',nnz(delta.wheel_hd_mps), ...
    'wheel_hdd_count',nnz(delta.wheel_hdd_mps2));
end

function damping = local_rayleigh_damping_report(item,delta)
is_state_specific = strcmp(item.first_changed_quantity, ...
    'bridge_stiffness_state_specific_rayleigh_damping');
damping = struct( ...
    'state_specific_rayleigh_recomputed',is_state_specific, ...
    'beam_C_delta_nnz',nnz(delta.beam_C), ...
    'model_C_delta_nnz',nnz(delta.model_C), ...
    'beam_C_delta_frobenius_norm',norm(delta.beam_C,'fro'), ...
    'model_C_delta_frobenius_norm',norm(delta.model_C,'fro'));
if is_state_specific
    damping.interpretation = [ ...
        'Bridge K changed and production recomputed state-specific bridge ' ...
        'and rail Rayleigh damping; this is a K+C dynamic intervention, ' ...
        'not a fixed-C K-only counterfactual.'];
else
    damping.interpretation = [ ...
        'Any C delta shown here follows the declared non-structural ' ...
        'mechanism boundary; no bridge-stiffness Rayleigh retuning occurred.'];
end
end

function local_assert_mechanism_boundary(item,healthy,damaged,delta)
assert(isequal(healthy.beam_M,damaged.beam_M) && ...
    isequal(healthy.model_M,damaged.model_M), ...
    'response_signature:MassChanged', ...
    '%s changed mass, outside its documented boundary.',item.name);

path_same = isequal(healthy.wheel_h_m,damaged.wheel_h_m) && ...
    isequal(healthy.wheel_hd_mps,damaged.wheel_hd_mps) && ...
    isequal(healthy.wheel_hdd_mps2,damaged.wheel_hdd_mps2);
switch item.first_changed_quantity
    case 'bridge_stiffness_state_specific_rayleigh_damping'
        assert(nnz(delta.beam_K) > 0 && nnz(delta.model_K) > 0 && ...
            nnz(delta.beam_C) > 0 && nnz(delta.model_C) > 0 && path_same, ...
            'response_signature:PhysicsBoundary', ...
            ['%s did not exhibit the declared bridge-stiffness plus ' ...
             'state-specific Rayleigh-damping boundary.'], ...
            item.name);
    case 'track_stiffness_damping'
        assert(isequal(healthy.beam_K,damaged.beam_K) && ...
            isequal(healthy.beam_C,damaged.beam_C) && ...
            nnz(delta.model_K) > 0 && nnz(delta.model_C) > 0 && path_same, ...
            'response_signature:PhysicsBoundary', ...
            '%s did not remain inside the track K/C boundary.',item.name);
    case 'track_stiffness_only'
        assert(isequal(healthy.beam_K,damaged.beam_K) && ...
            isequal(healthy.beam_C,damaged.beam_C) && ...
            nnz(delta.model_K) > 0 && nnz(delta.model_C) == 0 && path_same, ...
            'response_signature:PhysicsBoundary', ...
            '%s did not remain inside the track-K boundary.',item.name);
    case 'track_damping_only'
        assert(isequal(healthy.beam_K,damaged.beam_K) && ...
            isequal(healthy.beam_C,damaged.beam_C) && ...
            nnz(delta.model_K) == 0 && nnz(delta.model_C) > 0 && path_same, ...
            'response_signature:PhysicsBoundary', ...
            '%s did not remain inside the track-C boundary.',item.name);
    case 'wheel_path'
        assert(isequal(healthy.beam_K,damaged.beam_K) && ...
            isequal(healthy.beam_C,damaged.beam_C) && ...
            isequal(healthy.model_K,damaged.model_K) && ...
            isequal(healthy.model_C,damaged.model_C) && ...
            nnz(delta.wheel_h_m) > 0 && nnz(delta.wheel_hd_mps) > 0 && ...
            nnz(delta.wheel_hdd_mps2) > 0, ...
            'response_signature:PhysicsBoundary', ...
            '%s did not remain inside the wheel-path boundary.',item.name);
    otherwise
        error('response_signature:UnknownBoundary', ...
            'Unknown first-changed quantity %s.',item.first_changed_quantity);
end
end

function modal = local_modal_pair(healthy,damaged)
if ~isequal(healthy.mass_matrix,damaged.mass_matrix)
    error('response_signature:ModalMassMismatch', ...
        'MAC matching requires one common unchanged bridge mass matrix.');
end
if numel(healthy.frequency_hz) < 5 || numel(damaged.frequency_hz) < 5 || ...
        size(healthy.mode_shapes,2) < 5 || size(damaged.mode_shapes,2) < 5
    error('response_signature:MissingModes', ...
        'At least five healthy and five intervention bridge modes are required.');
end
n_reference = 5;
n_candidate = min(10,numel(damaged.frequency_hz));
if n_candidate < n_reference || size(damaged.mode_shapes,2) < n_candidate
    error('response_signature:MissingModes', ...
        'At least five candidate bridge modes are required for matching.');
end
phi_h = healthy.mode_shapes(:,1:n_reference);
phi_d = damaged.mode_shapes(:,1:n_candidate);
mass = healthy.mass_matrix;
cross = phi_h'*mass*phi_d;
norm_h = real(diag(phi_h'*mass*phi_h));
norm_d = real(diag(phi_d'*mass*phi_d));
mac = abs(cross).^2 ./ (norm_h*norm_d');
matched = local_best_assignment(mac);
indices = sub2ind(size(mac),(1:n_reference)',matched(:));
modal = struct();
modal.matching_method = ...
    ['exhaustive maximum summed mass-metric MAC over first 10 candidates; ' ...
     'MAC denominator explicitly normalizes both mode shapes'];
modal.reference_mode = (1:n_reference)';
modal.intervention_mode = matched(:);
modal.mac = mac(indices);
modal.mac_matrix = mac;
modal.healthy_frequency_hz = healthy.frequency_hz(1:n_reference);
modal.intervention_frequency_hz = damaged.frequency_hz(matched);
modal.frequency_delta_hz = modal.intervention_frequency_hz - ...
    modal.healthy_frequency_hz;
end

function assignment = local_best_assignment(mac)
n_reference = size(mac,1);
n_candidate = size(mac,2);
combinations = nchoosek(1:n_candidate,n_reference);
best_score = -Inf;
assignment = zeros(1,n_reference);
for row = 1:size(combinations,1)
    candidates = perms(combinations(row,:));
    for k = 1:size(candidates,1)
        indices = sub2ind(size(mac),(1:n_reference)',candidates(k,:)');
        score = sum(mac(indices));
        if score > best_score
            best_score = score;
            assignment = candidates(k,:);
        end
    end
end
end

function comparison = local_metric_comparison(healthy,damaged)
h = healthy.summary;
d = damaged.summary;
key_names = {'channel','signal_unit','psd_band','band_low_hz','band_high_hz', ...
    'realized_band_low_hz','realized_band_high_hz','realized_bin_count', ...
    'psd_density_unit','psd_band_energy_unit'};
for k = 1:numel(key_names)
    if ~isequal(h.(key_names{k}),d.(key_names{k}))
        error('response_signature:MetricKeyMismatch', ...
            'Healthy/intervention metric rows do not align.');
    end
end
comparison = table( ...
    h.channel,h.signal_unit,h.psd_band,h.band_low_hz,h.band_high_hz, ...
    h.realized_band_low_hz,h.realized_band_high_hz,h.realized_bin_count, ...
    h.psd_density_unit,h.psd_band_energy_unit, ...
    h.signal_rms,d.signal_rms,d.signal_rms-h.signal_rms, ...
    h.signal_abs_peak,d.signal_abs_peak, ...
    d.signal_abs_peak-h.signal_abs_peak, ...
    h.psd_band_energy,d.psd_band_energy, ...
    d.psd_band_energy-h.psd_band_energy, ...
    'VariableNames',{'channel','signal_unit','psd_band', ...
    'band_low_hz','band_high_hz','realized_band_low_hz', ...
    'realized_band_high_hz','realized_bin_count','psd_density_unit', ...
    'psd_band_energy_unit','healthy_rms','intervention_rms','delta_rms', ...
    'healthy_abs_peak','intervention_abs_peak','delta_abs_peak', ...
    'healthy_psd_band_energy', ...
    'intervention_psd_band_energy','delta_psd_band_energy'});
end

function comparison = local_harmonic_comparison(healthy,damaged)
h = healthy.harmonic_summary;
d = damaged.harmonic_summary;
key_names = {'channel','signal_unit','harmonic','target_frequency_hz', ...
    'nearest_welch_bin_hz','nearest_welch_bin_offset_hz','psd_density_unit'};
for k = 1:numel(key_names)
    if ~isequal(h.(key_names{k}),d.(key_names{k}))
        error('response_signature:HarmonicKeyMismatch', ...
            'Healthy/intervention harmonic metric rows do not align.');
    end
end
comparison = table( ...
    h.channel,h.signal_unit,h.harmonic,h.target_frequency_hz, ...
    h.nearest_welch_bin_hz,h.nearest_welch_bin_offset_hz, ...
    h.psd_density_unit, ...
    h.exact_frequency_amplitude,d.exact_frequency_amplitude, ...
    d.exact_frequency_amplitude-h.exact_frequency_amplitude, ...
    h.nearest_welch_psd_density,d.nearest_welch_psd_density, ...
    d.nearest_welch_psd_density-h.nearest_welch_psd_density, ...
    'VariableNames',{'channel','signal_unit','harmonic', ...
    'target_frequency_hz','nearest_welch_bin_hz', ...
    'nearest_welch_bin_offset_hz','psd_density_unit', ...
    'healthy_exact_frequency_amplitude', ...
    'intervention_exact_frequency_amplitude', ...
    'delta_exact_frequency_amplitude','healthy_nearest_welch_psd_density', ...
    'intervention_nearest_welch_psd_density', ...
    'delta_nearest_welch_psd_density'});
end

function polygon = local_polygon_harmonic_report( ...
        item,design,healthy_vehicle,damaged_vehicle,healthy_bridge,damaged_bridge)
row = double(item.damage.oor_poly);
if ~isequal(size(row),[1 5])
    error('response_signature:PolygonDescriptor', ...
        'The polygon response fixture requires one [veh wheel n amp phase] row.');
end
speed_mps = design.speed_kmh/3.6;
target_hz = row(3)*speed_mps/(2*pi*item.damage.oor_radius);
if abs(target_hz-design.polygon_harmonic_frequency_hz) > ...
        10*eps(max(1,target_hz))
    error('response_signature:PolygonFrequencyMismatch', ...
        'Catalog and response metric disagree on polygon forcing frequency.');
end
polygon = struct( ...
    'vehicle_index',row(1), ...
    'wheel_index',row(2), ...
    'harmonic_order',row(3), ...
    'path_amplitude_m',row(4), ...
    'phase_rad',row(5), ...
    'wheel_radius_m',double(item.damage.oor_radius), ...
    'speed_mps',speed_mps, ...
    'target_frequency_hz',target_hz, ...
    'frequency_definition','harmonic_order*speed_mps/(2*pi*wheel_radius_m)', ...
    'metric_definition',[ ...
        'exact-frequency least-squares sinusoidal amplitude plus nearest ' ...
        'fixed-Welch-bin PSD density; independent of reporting bands'], ...
    'vehicle_response',local_harmonic_comparison( ...
        healthy_vehicle,damaged_vehicle), ...
    'bridge_response',local_harmonic_comparison( ...
        healthy_bridge,damaged_bridge));
end

function comparison = local_bridge_extreme_comparison(healthy,damaged)
h = {healthy.bending_moment_extreme;healthy.shear_extreme};
d = {damaged.bending_moment_extreme;damaged.shear_extreme};
healthy_signed = cellfun(@(x) x.signed_value,h);
intervention_signed = cellfun(@(x) x.signed_value,d);
healthy_absolute = cellfun(@(x) x.absolute_value,h);
intervention_absolute = cellfun(@(x) x.absolute_value,d);
comparison = table( ...
    {'bending_moment_extreme';'shear_extreme'}, ...
    {'N m';'N'}, ...
    healthy_signed,intervention_signed, ...
    intervention_signed-healthy_signed, ...
    healthy_absolute,intervention_absolute, ...
    intervention_absolute-healthy_absolute, ...
    cellfun(@(x) x.bridge_x_m,h),cellfun(@(x) x.bridge_x_m,d), ...
    cellfun(@(x) x.time_s,h),cellfun(@(x) x.time_s,d), ...
    'VariableNames',{'quantity','unit','healthy_signed_value', ...
    'intervention_signed_value','delta_signed_value','healthy_absolute_value', ...
    'intervention_absolute_value','delta_absolute_value','healthy_bridge_x_m', ...
    'intervention_bridge_x_m','healthy_time_s','intervention_time_s'});
end

function comparison = local_bridge_event_comparison(healthy,damaged)
h = healthy.leading_wheel_bridge_events;
d = damaged.leading_wheel_bridge_events;
if ~isequal(h.event,d.event) || ...
        ~isequal(h.target_global_x_m,d.target_global_x_m) || ...
        ~isequal(h.sample_index,d.sample_index)
    error('response_signature:BridgeEventCrnMismatch', ...
        'Healthy/intervention bridge entry/exit event grids do not align.');
end
required_lengths = [numel(h.event),numel(h.target_global_x_m), ...
    numel(h.realized_global_x_m),numel(d.realized_global_x_m), ...
    numel(h.time_s),numel(d.time_s),numel(h.midspan_displacement_m), ...
    numel(d.midspan_displacement_m),numel(h.midspan_acceleration_mps2), ...
    numel(d.midspan_acceleration_mps2)];
if any(required_lengths ~= 2)
    error('response_signature:BridgeEventShape', ...
        'Bridge event report requires exactly one entry and one exit value.');
end
event = {h.event{1};h.event{1};h.event{2};h.event{2}};
quantity = {'midspan_displacement';'midspan_acceleration'; ...
    'midspan_displacement';'midspan_acceleration'};
unit = {'m';'m/s^2';'m';'m/s^2'};
target_global_x_m = [h.target_global_x_m(1);h.target_global_x_m(1); ...
    h.target_global_x_m(2);h.target_global_x_m(2)];
healthy_realized_global_x_m = [h.realized_global_x_m(1); ...
    h.realized_global_x_m(1);h.realized_global_x_m(2); ...
    h.realized_global_x_m(2)];
intervention_realized_global_x_m = [d.realized_global_x_m(1); ...
    d.realized_global_x_m(1);d.realized_global_x_m(2); ...
    d.realized_global_x_m(2)];
healthy_time_s = [h.time_s(1);h.time_s(1);h.time_s(2);h.time_s(2)];
intervention_time_s = [d.time_s(1);d.time_s(1);d.time_s(2);d.time_s(2)];
healthy_value = [h.midspan_displacement_m(1); ...
    h.midspan_acceleration_mps2(1);h.midspan_displacement_m(2); ...
    h.midspan_acceleration_mps2(2)];
intervention_value = [d.midspan_displacement_m(1); ...
    d.midspan_acceleration_mps2(1);d.midspan_displacement_m(2); ...
    d.midspan_acceleration_mps2(2)];
comparison = table(event,quantity,unit, ...
    target_global_x_m,healthy_realized_global_x_m, ...
    intervention_realized_global_x_m,healthy_time_s,intervention_time_s, ...
    healthy_value,intervention_value,intervention_value-healthy_value, ...
    'VariableNames',{'event','quantity','unit','target_global_x_m', ...
    'healthy_realized_global_x_m','intervention_realized_global_x_m', ...
    'healthy_time_s','intervention_time_s','healthy_value', ...
    'intervention_value','delta'});
end

function contact = local_contact_pair(healthy,damaged)
if ~isequal(healthy.x_m,damaged.x_m) || ...
        ~isequal(healthy.on_track_mask,damaged.on_track_mask)
    error('response_signature:ContactCrnMismatch', ...
        'Healthy/intervention contact paths do not share one exact grid.');
end
contact = struct();
contact.x_m = healthy.x_m;
contact.on_track_mask = healthy.on_track_mask;
contact.healthy_force_n = healthy.force_n;
contact.intervention_force_n = damaged.force_n;
contact.force_delta_n = damaged.force_n-healthy.force_n;
contact.history_scope = 'all four wheels of the leading vehicle';
contact.healthy_per_wheel = healthy.per_wheel;
contact.intervention_per_wheel = damaged.per_wheel;
contact.healthy_per_vehicle = healthy.per_vehicle;
contact.intervention_per_vehicle = damaged.per_vehicle;
contact.summary = local_contact_comparison(healthy,damaged);
if ~isequaln(healthy.registered_policy,damaged.registered_policy)
    error('response_signature:ContactPolicyMismatch', ...
        'Healthy/intervention runs must use one identical contact policy.');
end
contact.registered_policy = healthy.registered_policy;
contact.healthy_aggregate_tensile_peak_n = ...
    healthy.aggregate_tensile_peak_n;
contact.intervention_aggregate_tensile_peak_n = ...
    damaged.aggregate_tensile_peak_n;
contact.healthy_aggregate_positive_fraction = ...
    healthy.aggregate_positive_fraction;
contact.intervention_aggregate_positive_fraction = ...
    damaged.aggregate_positive_fraction;
contact.healthy_registered_admissible = healthy.registered_admissible;
contact.intervention_registered_admissible = damaged.registered_admissible;
contact.pair_registered_admissible = ...
    healthy.registered_admissible && damaged.registered_admissible;
contact.healthy_lost_track = healthy.lost_track;
contact.intervention_lost_track = damaged.lost_track;
contact.healthy_lost_bridge = healthy.lost_bridge;
contact.intervention_lost_bridge = damaged.lost_bridge;
end

function summary = local_contact_summary(contact)
summary = contact.per_wheel;
end

function comparison = local_contact_comparison(healthy,damaged)
h = healthy.per_wheel;
d = damaged.per_wheel;
key_names = {'vehicle_index','wheel_index','wheel','on_track_sample_count'};
for k = 1:numel(key_names)
    if ~isequal(h.(key_names{k}),d.(key_names{k}))
        error('response_signature:ContactKeyMismatch', ...
            'Healthy/intervention per-wheel contact rows do not align.');
    end
end
comparison = table( ...
    h.vehicle_index,h.wheel_index,h.wheel,h.on_track_sample_count, ...
    h.signed_tensile_peak_n,d.signed_tensile_peak_n, ...
    d.signed_tensile_peak_n-h.signed_tensile_peak_n, ...
    h.compressive_minimum_n,d.compressive_minimum_n, ...
    d.compressive_minimum_n-h.compressive_minimum_n, ...
    h.absolute_peak_n,d.absolute_peak_n, ...
    d.absolute_peak_n-h.absolute_peak_n, ...
    h.positive_fraction,d.positive_fraction, ...
    d.positive_fraction-h.positive_fraction, ...
    'VariableNames',{'vehicle_index','wheel_index','wheel', ...
    'on_track_sample_count','healthy_signed_tensile_peak_n', ...
    'intervention_signed_tensile_peak_n','delta_signed_tensile_peak_n', ...
    'healthy_compressive_minimum_n','intervention_compressive_minimum_n', ...
    'delta_compressive_minimum_n','healthy_absolute_peak_n', ...
    'intervention_absolute_peak_n','delta_absolute_peak_n', ...
    'healthy_positive_fraction','intervention_positive_fraction', ...
    'delta_positive_fraction'});
end

function selected = local_select_catalog(catalog,names)
available = {catalog.name};
indices = zeros(1,numel(names));
for k = 1:numel(names)
    found = find(strcmp(available,names{k}));
    if numel(found) ~= 1
        error('response_signature:UnknownIntervention', ...
            'Unknown intervention "%s". Available: %s.', ...
            names{k},strjoin(available,', '));
    end
    indices(k) = found;
end
if numel(unique(indices)) ~= numel(indices)
    error('response_signature:DuplicateIntervention', ...
        'requested_names must not contain duplicate interventions.');
end
selected = catalog(indices);
end

function names = local_names(names)
if ischar(names)
    names = {names};
elseif isstring(names)
    names = cellstr(names(:));
elseif iscell(names)
    names = names(:)';
else
    error('response_signature:InterventionNames', ...
        'requested_names must be text or a cell array of text.');
end
if any(~cellfun(@(x) ischar(x) && isrow(x) && ~isempty(x),names))
    error('response_signature:InterventionNames', ...
        'Every requested intervention name must be nonempty text.');
end
end
