function run = response_signature_run_one(damage,design)
%RESPONSE_SIGNATURE_RUN_ONE Execute one deterministic production TTBI passage.
%
% The caller supplies an explicit Damage descriptor and a complete study
% design from response_signature_damage_catalog.  No random value is drawn in
% this function: the fixed FRA-v2 phase, speed, temperature, and vehicle
% descriptor are identical in every paired call.

if nargin ~= 2 || ~isstruct(damage) || ~isscalar(damage) || ...
        ~isstruct(design) || ~isscalar(design)
    error('response_signature:RunInput', ...
        'damage and design must be scalar structs.');
end

speed_mps = design.speed_kmh/3.6;
Train = A01_Train(speed_mps,design.vehicle_draw);
Track = A02_Track();
if isfield(design,'track_model_form_arm')
    track_model_form_arm = design.track_model_form_arm;
else
    track_model_form_arm = 'baseline-hybrid-v1';
end
Track = ttbi.apply_track_model_form_arm(Track,track_model_form_arm);
Beam_seed = struct('Prop',struct( ...
    'L',design.L_bridge_m,'num_spans',design.num_spans));
Beam = A03_Bridge(Beam_seed);
Beam.Prop.E = Beam.Prop.E - Beam.Prop.E*0.003*(design.temperature_c-15);
profile_cfg = struct( ...
    'mode','fixed', ...
    'fra_class',design.profile_fra_class, ...
    'phase_seed',design.profile_phase_seed);
[Calc,Beam,Track] = A04_Options(Beam,Track,profile_cfg);

% Sensitivity-only fixed Rayleigh closure. Ordinary production designs omit
% this field and B24 recalibrates independently for the current state/grid.
% The explicit four-coefficient payload prevents a bridge-only override from
% silently leaving the rail damping on a different policy.
if isfield(design,'fixed_rayleigh')
    fixed = local_fixed_rayleigh(design.fixed_rayleigh);
    Beam.Damping.fixed_rayleigh_coefficients = ...
        [fixed.bridge_alpha,fixed.bridge_beta];
    Beam.Damping.fixed_rayleigh_source_id = fixed.source_id;
    Track.Rail.Damping.fixed_rayleigh_coefficients = ...
        [fixed.rail_alpha,fixed.rail_beta];
    Track.Rail.Damping.fixed_rayleigh_source_id = fixed.source_id;
end

% B09 needs mode shapes, rather than frequencies alone, for MAC matching.
% This changes post-assembly modal output only; the dynamic solver settings
% and the production 1 ms integration step remain untouched.
Calc.Options.calc_beam_frq = 1;
Calc.Options.calc_beam_modes = 1;
[Sol,Calc,~,Beam,Track,Model] = ...
    B00_Calculations(Calc,Train,Track,Beam,damage);

vehicle_signal = double([ ...
    Sol.Veh(1).A(1:3,:); ...
    Sol.Veh(1).acc_under(1:4,:); ...
    Sol.Veh(1).V(4:6,:)]);
vehicle_names = { ...
    'carbody_vertical_acc'; ...
    'front_bogie_vertical_acc'; ...
    'rear_bogie_vertical_acc'; ...
    'rail_eulerian_vertical_acc_under_wheel_1'; ...
    'rail_eulerian_vertical_acc_under_wheel_2'; ...
    'rail_eulerian_vertical_acc_under_wheel_3'; ...
    'rail_eulerian_vertical_acc_under_wheel_4'; ...
    'carbody_pitch_rate'; ...
    'front_bogie_pitch_rate'; ...
    'rear_bogie_pitch_rate'};
vehicle_units = { ...
    'm/s^2';'m/s^2';'m/s^2';'m/s^2';'m/s^2';'m/s^2';'m/s^2'; ...
    'rad/s';'rad/s';'rad/s'};

[wheelset_acceleration,wheelset_active_mask] = ...
    ttbi.wheel_contact_kinematics(Sol.Veh(1),Calc.Veh(1),Train.vel);
physical8_signal = double([ ...
    Sol.Veh(1).A(1:3,:); ...
    wheelset_acceleration(1:2,:); ...
    Sol.Veh(1).V(4:6,:)]);

if ~isfield(Sol.Beam.U,'sections_t') || ...
        ~isfield(Sol.Beam.Acc,'sections_t') || ...
        size(Sol.Beam.U.sections_t,1) ~= 1 || ...
        size(Sol.Beam.Acc.sections_t,1) ~= 1
    error('response_signature:MissingMidspan', ...
        'The production solve did not return the configured midspan signals.');
end
bridge_signal = double([ ...
    Sol.Beam.U.sections_t(1,:); ...
    Sol.Beam.Acc.sections_t(1,:)]);

[contact_force_n,contact_x_m,contact_on_track,contact_per_wheel, ...
    contact_per_vehicle] = local_contact_diagnostics( ...
    Sol.Veh,Calc.Veh,Calc.Profile.L);

[wheel_h_m,wheel_hd_mps,wheel_hdd_mps2,wheel_x_m] = ...
    local_wheel_paths(Calc.Veh);

realized_support_x_m = double( ...
    Beam.Mesh.Nodes.acum(Beam.BC.loc_ind));
support_coordinate_error_m = double(Beam.BC.loc_offset);
support_coordinate_tolerance_m = double(Beam.BC.loc_tolerance);
geometry = struct( ...
    'bridge_length_m',double(Beam.Prop.L), ...
    'bridge_element_length_m',double(Beam.Mesh.Ele.L), ...
    'bridge_elements_per_sleeper_spacing', ...
        double(Beam.Mesh.Ele.num_per_spacing), ...
    'rail_elements_per_sleeper_spacing', ...
        double(Track.Rail.Mesh.Ele.num_per_spacing), ...
    'requested_support_x_m',double(Beam.BC.loc), ...
    'realized_support_x_m',realized_support_x_m, ...
    'support_coordinate_error_m',support_coordinate_error_m, ...
    'max_abs_support_coordinate_error_m', ...
        max(abs(support_coordinate_error_m)), ...
    'support_coordinate_tolerance_m',support_coordinate_tolerance_m, ...
    'support_on_node_within_tolerance', ...
        abs(support_coordinate_error_m) <= support_coordinate_tolerance_m, ...
    'all_supports_on_nodes_within_tolerance', ...
        all(abs(support_coordinate_error_m) <= ...
        support_coordinate_tolerance_m), ...
    'track_frame_offset_m',double(Model.TrackDmgDbg.frame_offset), ...
    'deck_global_x_m',double(Model.TrackDmgDbg.x_deck_global), ...
    'bridge_entry_global_x_m',double(Model.TrackDmgDbg.x_deck_global(1)), ...
    'bridge_exit_global_x_m', ...
        double(Model.TrackDmgDbg.x_deck_global(1)+Beam.Prop.L), ...
    'last_on_bridge_sleeper_global_x_m', ...
        double(Model.TrackDmgDbg.x_deck_global(2)));
fixed_geometry_controls = rmfield(geometry,'track_frame_offset_m');

bending_extreme = local_spatiotemporal_extreme( ...
    Sol.Beam.BM.xt,Beam.Mesh.Nodes.acum,Calc.Solver.t);
shear_extreme = local_spatiotemporal_extreme( ...
    Sol.Beam.Shear.xt,Beam.Mesh.Nodes.acum,Calc.Solver.t);
bridge_events = local_bridge_events( ...
    contact_x_m(1,:),Calc.Solver.t,geometry.bridge_entry_global_x_m, ...
    geometry.bridge_length_m,bridge_signal);

contact_policy = struct( ...
    'max_tensile_peak_n',double(design.contact_max_tensile_peak_n), ...
    'max_positive_fraction', ...
        double(design.contact_max_positive_fraction), ...
    'rule',['admissible iff peak tensile demand and on-track positive ' ...
        'fraction are finite and do not exceed both limits']);
registered_contact_admissible = ...
    isfinite(Sol.F_tension_max) && isfinite(Sol.tension_frac_max) && ...
    Sol.F_tension_max <= contact_policy.max_tensile_peak_n && ...
    Sol.tension_frac_max <= contact_policy.max_positive_fraction;

run = struct();
run.damage = damage;
run.geometry = geometry;
run.controls = struct( ...
    'speed_mps',double(speed_mps), ...
    'temperature_c',double(design.temperature_c), ...
    'vehicle_draw',double(design.vehicle_draw), ...
    'profile_mode','fixed', ...
    'profile_fra_class',double(design.profile_fra_class), ...
    'profile_phase_seed',double(design.profile_phase_seed), ...
    'profile_spectrum_contract',Calc.Profile.spectrum_contract, ...
    'track_model_form',Track.ModelForm, ...
    'profile_x_m',double(Calc.Profile.x), ...
    'profile_h_m',double(Calc.Profile.h), ...
    'time_s',double(Calc.Solver.t), ...
    'wheel_x_m',wheel_x_m, ...
    'fixed_geometry',fixed_geometry_controls);
run.vehicle = struct( ...
    'signal',vehicle_signal, ...
    'channel_names',{vehicle_names}, ...
    'channel_units',{vehicle_units}, ...
    'channel_semantics',{{ ...
        'vehicle generalized vertical acceleration'; ...
        'vehicle generalized vertical acceleration'; ...
        'vehicle generalized vertical acceleration'; ...
        ['Eulerian rail vertical acceleration sampled at the wheel ' ...
         'abscissa; excludes convective moving-point terms and profile hdd']; ...
        ['Eulerian rail vertical acceleration sampled at the wheel ' ...
         'abscissa; excludes convective moving-point terms and profile hdd']; ...
        ['Eulerian rail vertical acceleration sampled at the wheel ' ...
         'abscissa; excludes convective moving-point terms and profile hdd']; ...
        ['Eulerian rail vertical acceleration sampled at the wheel ' ...
         'abscissa; excludes convective moving-point terms and profile hdd']; ...
        'vehicle generalized pitch rate'; ...
        'vehicle generalized pitch rate'; ...
        'vehicle generalized pitch rate'}});
run.physical8 = struct( ...
    'signal',physical8_signal, ...
    'channel_names',{{ ...
        'carbody_vertical_acceleration'; ...
        'front_bogie_vertical_acceleration'; ...
        'rear_bogie_vertical_acceleration'; ...
        'wheelset_1_constrained_vertical_acceleration_proxy'; ...
        'wheelset_2_constrained_vertical_acceleration_proxy'; ...
        'carbody_pitch_rate'; ...
        'front_bogie_pitch_rate'; ...
        'rear_bogie_pitch_rate'}}, ...
    'channel_units',{{ ...
        'm/s^2';'m/s^2';'m/s^2';'m/s^2';'m/s^2'; ...
        'rad/s';'rad/s';'rad/s'}}, ...
    'wheelset_active_mask',logical(wheelset_active_mask(1:2,:)), ...
    'channel_schema_id','physical8_v1');
run.bridge = struct( ...
    'signal',bridge_signal, ...
    'channel_names',{{'bridge_midspan_displacement'; ...
    'bridge_midspan_acceleration'}}, ...
    'channel_units',{{'m';'m/s^2'}}, ...
    'midspan_x_m',double(design.L_bridge_m/2), ...
    'maximum_abs_bending_moment_nm', ...
        double(max(abs(Sol.Beam.BM.xt),[],'all')), ...
    'maximum_abs_shear_n',double(max(abs(Sol.Beam.Shear.xt),[],'all')), ...
    'bending_moment_extreme',bending_extreme, ...
    'shear_extreme',shear_extreme, ...
    'leading_wheel_bridge_events',bridge_events);
run.contact = struct( ...
    'force_n',contact_force_n, ...
    'x_m',contact_x_m, ...
    'on_track_mask',contact_on_track, ...
    'wheel_names',{{'wheel_1';'wheel_2';'wheel_3';'wheel_4'}}, ...
    'per_wheel',contact_per_wheel, ...
    'per_vehicle',contact_per_vehicle, ...
    'aggregate_tensile_peak_n',double(Sol.F_tension_max), ...
    'aggregate_positive_fraction',double(Sol.tension_frac_max), ...
    'registered_policy',contact_policy, ...
    'registered_admissible',logical(registered_contact_admissible), ...
    'lost_track',logical(Sol.contactLost_track), ...
    'lost_bridge',logical(Sol.contactLost));
run.modal = struct( ...
    'frequency_hz',double(Beam.Modal.f(:)), ...
    'mode_shapes',double(Beam.Modal.modes), ...
    'mass_matrix',sparse(Beam.Mesh.Mg));
run.damping = struct( ...
    'bridge',local_damping_record(Beam), ...
    'rail',local_damping_record(Track.Rail));
run.physics = struct( ...
    'beam_M',sparse(Beam.Mesh.Mg), ...
    'beam_C',sparse(Beam.Mesh.Cg), ...
    'beam_K',sparse(Beam.Mesh.Kg), ...
    'model_M',sparse(Model.Mesh.Mg), ...
    'model_C',sparse(Model.Mesh.Cg), ...
    'model_K',sparse(Model.Mesh.Kg), ...
    'wheel_h_m',wheel_h_m, ...
    'wheel_hd_mps',wheel_hd_mps, ...
    'wheel_hdd_mps2',wheel_hdd_mps2, ...
    'track_properties',Track, ...
    'track_placement',Model.TrackDmgDbg);

local_assert_finite(run);
end

function fixed = local_fixed_rayleigh(value)
required = {'source_id','bridge_alpha','bridge_beta', ...
    'rail_alpha','rail_beta'};
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(fieldnames(value)),sort(required(:)))
    error('response_signature:FixedRayleighSchema', ...
        ['fixed_rayleigh must be a scalar struct with exactly source_id, ' ...
         'bridge_alpha, bridge_beta, rail_alpha, and rail_beta.']);
end
if ~(ischar(value.source_id) || ...
        (isstring(value.source_id) && isscalar(value.source_id))) || ...
        isempty(strtrim(char(value.source_id)))
    error('response_signature:FixedRayleighSource', ...
        'fixed_rayleigh.source_id must be nonempty scalar text.');
end
for k = 2:numel(required)
    item = value.(required{k});
    if ~(isnumeric(item) && isreal(item) && isscalar(item) && ...
            isfinite(item) && item >= 0)
        error('response_signature:FixedRayleighCoefficient', ...
            '%s must be one finite nonnegative real scalar.',required{k});
    end
end
if value.bridge_alpha == 0 && value.bridge_beta == 0
    error('response_signature:FixedRayleighCoefficient', ...
        'Bridge fixed Rayleigh coefficients cannot both be zero.');
end
if value.rail_alpha == 0 && value.rail_beta == 0
    error('response_signature:FixedRayleighCoefficient', ...
        'Rail fixed Rayleigh coefficients cannot both be zero.');
end
fixed = value;
fixed.source_id = char(value.source_id);
end

function record = local_damping_record(component)
required = {'rayleigh_policy','rayleigh_coefficient_source_id', ...
    'rayleigh_alpha','rayleigh_beta','reference_mode_indices', ...
    'reference_frequencies_rad_s','achieved_reference_damping_ratios'};
for k = 1:numel(required)
    if ~isfield(component.Damping,required{k})
        error('response_signature:MissingDampingLedger', ...
            'Damping ledger field %s is absent.',required{k});
    end
end
w = double(component.Modal.w(:));
elastic = w(w > 0 & isfinite(w));
n_modes = min(5,numel(elastic));
alpha = double(component.Damping.rayleigh_alpha);
beta = double(component.Damping.rayleigh_beta);
record = struct( ...
    'policy',char(component.Damping.rayleigh_policy), ...
    'coefficient_source_id', ...
        char(component.Damping.rayleigh_coefficient_source_id), ...
    'alpha',alpha, ...
    'beta',beta, ...
    'reference_mode_indices', ...
        double(component.Damping.reference_mode_indices(:)'), ...
    'reference_frequencies_rad_s', ...
        double(component.Damping.reference_frequencies_rad_s(:)'), ...
    'achieved_reference_damping_ratios', ...
        double(component.Damping.achieved_reference_damping_ratios(:)'), ...
    'first_modal_frequencies_rad_s',elastic(1:n_modes)', ...
    'first_modal_damping_ratios', ...
        (alpha./(2*elastic(1:n_modes)) + beta.*elastic(1:n_modes)/2)', ...
    'matrix_size',double(size(component.Mesh.Cg)), ...
    'matrix_nnz',double(nnz(component.Mesh.Cg)), ...
    'matrix_frobenius_norm',double(norm(component.Mesh.Cg,'fro')));
end

function [force_first,x_first,on_track_first,per_wheel,per_vehicle] = ...
        local_contact_diagnostics(sol_vehicle,calc_vehicle,profile_length_m)
n_vehicles = numel(sol_vehicle);
if n_vehicles ~= numel(calc_vehicle) || n_vehicles < 1
    error('response_signature:ContactShape', ...
        'Solver and calculation vehicle inventories must agree and be nonempty.');
end
n_wheels = size(sol_vehicle(1).F_onBeam,1);
if n_wheels ~= 4
    error('response_signature:ContactShape', ...
        'The response fixture requires exactly four wheels per vehicle.');
end

n_rows = n_vehicles*n_wheels;
vehicle_index = zeros(n_rows,1);
wheel_index = zeros(n_rows,1);
wheel = cell(n_rows,1);
tensile_peak_n = zeros(n_rows,1);
compressive_minimum_n = zeros(n_rows,1);
absolute_peak_n = zeros(n_rows,1);
positive_fraction = zeros(n_rows,1);
on_track_sample_count = zeros(n_rows,1);
vehicle_tensile_peak_n = zeros(n_vehicles,1);
vehicle_positive_fraction = zeros(n_vehicles,1);
vehicle_lost_track = false(n_vehicles,1);
vehicle_lost_bridge = false(n_vehicles,1);
vehicle_on_track_sample_count = zeros(n_vehicles,1);

for vehicle = 1:n_vehicles
    force_n = double(sol_vehicle(vehicle).F_onBeam);
    x_m = double(calc_vehicle(vehicle).x_path);
    if ~isequal(size(force_n),size(x_m)) || size(force_n,1) ~= n_wheels
        error('response_signature:ContactShape', ...
            'Every force history must match its four-wheel position grid.');
    end
    on_track = x_m >= 0 & x_m <= profile_length_m;
    if any(sum(on_track,2) == 0)
        error('response_signature:EmptyContactWindow', ...
            'At least one wheel has no sample inside the modeled track.');
    end
    for wheel_number = 1:n_wheels
        row = (vehicle-1)*n_wheels+wheel_number;
        selected_force_n = force_n(wheel_number,on_track(wheel_number,:));
        vehicle_index(row) = vehicle;
        wheel_index(row) = wheel_number;
        wheel{row} = sprintf('vehicle_%d_wheel_%d',vehicle,wheel_number);
        tensile_peak_n(row) = max(selected_force_n);
        compressive_minimum_n(row) = min(selected_force_n);
        absolute_peak_n(row) = max(abs(selected_force_n));
        positive_fraction(row) = mean(selected_force_n > 0);
        on_track_sample_count(row) = numel(selected_force_n);
    end
    all_selected_force_n = force_n(on_track);
    vehicle_tensile_peak_n(vehicle) = max(all_selected_force_n);
    vehicle_positive_fraction(vehicle) = mean(all_selected_force_n > 0);
    vehicle_lost_track(vehicle) = logical(sol_vehicle(vehicle).contactLost_track);
    vehicle_lost_bridge(vehicle) = logical(sol_vehicle(vehicle).contactLost);
    vehicle_on_track_sample_count(vehicle) = numel(all_selected_force_n);
    tolerance_n = 1e-12*max(1,abs(vehicle_tensile_peak_n(vehicle)));
    if abs(vehicle_tensile_peak_n(vehicle) - ...
            double(sol_vehicle(vehicle).F_onTrack_max)) > tolerance_n || ...
            abs(vehicle_positive_fraction(vehicle) - ...
            double(sol_vehicle(vehicle).tension_frac)) > 10*eps
        error('response_signature:ContactDefinitionMismatch', ...
            'Recomputed per-wheel diagnostics disagree with B66 vehicle fields.');
    end
end

per_wheel = table(vehicle_index,wheel_index,wheel,tensile_peak_n, ...
    compressive_minimum_n,absolute_peak_n,positive_fraction, ...
    on_track_sample_count, ...
    'VariableNames',{'vehicle_index','wheel_index','wheel', ...
    'signed_tensile_peak_n','compressive_minimum_n','absolute_peak_n', ...
    'positive_fraction','on_track_sample_count'});
per_vehicle = table((1:n_vehicles)',vehicle_tensile_peak_n, ...
    vehicle_positive_fraction,vehicle_on_track_sample_count, ...
    vehicle_lost_track,vehicle_lost_bridge, ...
    'VariableNames',{'vehicle_index','signed_tensile_peak_n', ...
    'positive_fraction','on_track_sample_count','lost_track','lost_bridge'});
force_first = double(sol_vehicle(1).F_onBeam);
x_first = double(calc_vehicle(1).x_path);
on_track_first = x_first >= 0 & x_first <= profile_length_m;
end

function extreme = local_spatiotemporal_extreme(values_xt,x_m,time_s)
values_xt = double(values_xt);
x_m = double(x_m(:));
time_s = double(time_s(:));
if size(values_xt,1) ~= numel(x_m) || ...
        size(values_xt,2) ~= numel(time_s)
    error('response_signature:BridgeExtremeShape', ...
        'Bridge x-by-time field does not match node and time coordinates.');
end
[absolute_value,linear_index] = max(abs(values_xt),[],'all','linear');
[x_index,time_index] = ind2sub(size(values_xt),linear_index);
extreme = struct( ...
    'signed_value',values_xt(linear_index), ...
    'absolute_value',absolute_value, ...
    'bridge_x_m',x_m(x_index), ...
    'time_s',time_s(time_index), ...
    'x_index',x_index, ...
    'time_index',time_index);
end

function events = local_bridge_events( ...
        leading_wheel_x_m,time_s,deck_global_x_m,bridge_length_m,bridge_signal)
leading_wheel_x_m = double(leading_wheel_x_m(:));
time_s = double(time_s(:));
if numel(leading_wheel_x_m) ~= numel(time_s) || ...
        size(bridge_signal,2) ~= numel(time_s)
    error('response_signature:BridgeEventShape', ...
        'Leading-wheel, bridge-response, and time grids must align.');
end
target_x_m = [deck_global_x_m;deck_global_x_m+bridge_length_m];
sample_index = zeros(2,1);
for event = 1:2
    [~,sample_index(event)] = min(abs(leading_wheel_x_m-target_x_m(event)));
end
events = struct( ...
    'event',{{'leading_wheel_entry';'leading_wheel_exit'}}, ...
    'target_global_x_m',target_x_m, ...
    'realized_global_x_m',leading_wheel_x_m(sample_index), ...
    'time_s',time_s(sample_index), ...
    'sample_index',sample_index, ...
    'midspan_displacement_m',bridge_signal(1,sample_index)', ...
    'midspan_acceleration_mps2',bridge_signal(2,sample_index)');
end

function [h,hd,hdd,x] = local_wheel_paths(calc_vehicle)
n_vehicles = numel(calc_vehicle);
reference_size = size(calc_vehicle(1).h_path);
h = zeros([reference_size,n_vehicles]);
hd = h;
hdd = h;
x = h;
for vehicle = 1:n_vehicles
    if ~isequal(size(calc_vehicle(vehicle).h_path),reference_size) || ...
            ~isequal(size(calc_vehicle(vehicle).hd_path),reference_size) || ...
            ~isequal(size(calc_vehicle(vehicle).hdd_path),reference_size) || ...
            ~isequal(size(calc_vehicle(vehicle).x_path),reference_size)
        error('response_signature:WheelPathShape', ...
            'Every vehicle must expose the same wheel-path array shape.');
    end
    h(:,:,vehicle) = double(calc_vehicle(vehicle).h_path);
    hd(:,:,vehicle) = double(calc_vehicle(vehicle).hd_path);
    hdd(:,:,vehicle) = double(calc_vehicle(vehicle).hdd_path);
    x(:,:,vehicle) = double(calc_vehicle(vehicle).x_path);
end
end

function local_assert_finite(run)
arrays = { ...
    run.vehicle.signal,run.bridge.signal,run.contact.force_n, ...
    run.modal.frequency_hz,run.modal.mode_shapes, ...
    run.physics.wheel_h_m,run.physics.wheel_hd_mps, ...
    run.physics.wheel_hdd_mps2};
for k = 1:numel(arrays)
    if ~isreal(arrays{k}) || any(~isfinite(arrays{k}(:)))
        error('response_signature:NonfiniteOutput', ...
            'The production solve returned a complex or nonfinite signature.');
    end
end
end
