function metrics = response_signature_metrics( ...
        time_s,signal,channel_names,channel_units,bands_hz,band_names, ...
        harmonic_frequencies_hz,harmonic_names)
%RESPONSE_SIGNATURE_METRICS Deterministic RMS, peak, and Welch-band metrics.
%
% This implementation deliberately uses only base MATLAB.  The estimator is
% fixed for the exploratory response-signature inventory:
%   * 2048-sample periodic Hann windows;
%   * 1024-sample overlap;
%   * constant removal independently in every segment;
%   * 2048-point FFT and one-sided density scaling; and
%   * rectangular frequency-bin summation for band mean-square contribution.
%
% Optional named harmonic frequencies add an exact-frequency least-squares
% sinusoidal amplitude and the nearest Welch-bin density.  The exact target is
% retained, so this metric does not depend on a reporting-band boundary.
%
% These are reporting definitions, not physical-response acceptance bands.

time_s = double(time_s(:)');
signal = double(signal);
n_channels = size(signal,1);
n_samples = size(signal,2);
if n_samples ~= numel(time_s) || n_channels < 1 || n_samples < 2
    error('response_signature:MetricShape', ...
        'signal must be channels-by-time and match time_s.');
end
if any(~isfinite(time_s)) || any(~isfinite(signal(:))) || ...
        any(diff(time_s) <= 0)
    error('response_signature:MetricFinite', ...
        'time_s and signal must be finite, with strictly increasing time.');
end
dt_s = median(diff(time_s));
uniform_error_s = max(abs(diff(time_s) - dt_s));
if uniform_error_s > 1e-10 * max(1,abs(dt_s))
    error('response_signature:NonuniformTime', ...
        'The Welch fixture requires a uniformly sampled time axis.');
end
sample_rate_hz = 1/dt_s;
nyquist_hz = sample_rate_hz/2;

channel_names = local_cell_text(channel_names,'channel_names');
channel_units = local_cell_text(channel_units,'channel_units');
band_names = local_cell_text(band_names,'band_names');
if numel(channel_names) ~= n_channels || numel(channel_units) ~= n_channels
    error('response_signature:MetricMetadata', ...
        'Each signal row requires exactly one channel name and unit.');
end
if ~isnumeric(bands_hz) || size(bands_hz,2) ~= 2 || ...
        size(bands_hz,1) ~= numel(band_names) || ...
        any(~isfinite(bands_hz(:))) || any(bands_hz(:,1) < 0) || ...
        any(bands_hz(:,2) <= bands_hz(:,1))
    error('response_signature:MetricMetadata', ...
        'bands_hz must contain one finite increasing [low high] row per name.');
end
if any(bands_hz(:,2) > nyquist_hz)
    error('response_signature:PsdBandBeyondNyquist', ...
        ['Every requested PSD band must end at or below the %.9g Hz ' ...
         'Nyquist frequency.'],nyquist_hz);
end

if nargin < 7 || isempty(harmonic_frequencies_hz)
    harmonic_frequencies_hz = zeros(0,1);
end
if nargin < 8 || isempty(harmonic_names)
    harmonic_names = cell(0,1);
else
    harmonic_names = local_cell_text(harmonic_names,'harmonic_names');
end
harmonic_frequencies_hz = double(harmonic_frequencies_hz(:));
if numel(harmonic_names) ~= numel(harmonic_frequencies_hz) || ...
        any(~isfinite(harmonic_frequencies_hz)) || ...
        any(harmonic_frequencies_hz <= 0) || ...
        any(harmonic_frequencies_hz >= nyquist_hz)
    error('response_signature:MetricMetadata', ...
        ['Harmonics require one name per finite target frequency strictly ' ...
         'between zero and Nyquist.']);
end

segment_length = 2048;
overlap_length = 1024;
nfft = 2048;
if n_samples < segment_length
    error('response_signature:TooFewSamples', ...
        'At least %d samples are required by the fixed Welch estimator.', ...
        segment_length);
end

[frequency_hz,psd_density,segment_count] = local_welch( ...
    signal,sample_rate_hz,segment_length,overlap_length,nfft);
frequency_resolution_hz = sample_rate_hz/nfft;

rms_value = sqrt(mean(signal.^2,2));
absolute_peak = max(abs(signal),[],2);
n_bands = size(bands_hz,1);
band_energy = zeros(n_channels,n_bands);
realized_band_low_hz = zeros(n_bands,1);
realized_band_high_hz = zeros(n_bands,1);
realized_bin_count = zeros(n_bands,1);
for band = 1:n_bands
    selected = frequency_hz >= bands_hz(band,1) & ...
        frequency_hz <= bands_hz(band,2);
    if ~any(selected)
        error('response_signature:EmptyPsdBand', ...
            'PSD band %s contains no estimator frequency bin.', ...
            band_names{band});
    end
    band_energy(:,band) = sum(psd_density(:,selected),2) * ...
        frequency_resolution_hz;
    selected_frequency_hz = frequency_hz(selected);
    realized_band_low_hz(band) = selected_frequency_hz(1);
    realized_band_high_hz(band) = selected_frequency_hz(end);
    realized_bin_count(band) = numel(selected_frequency_hz);
end

psd_density_units = cellfun(@(unit) sprintf('(%s)^2/Hz',unit), ...
    channel_units(:),'UniformOutput',false);
band_energy_units = cellfun(@(unit) sprintf('(%s)^2',unit), ...
    channel_units(:),'UniformOutput',false);

row_count = n_channels*n_bands;
summary = table( ...
    repmat(channel_names(:),n_bands,1), ...
    repmat(channel_units(:),n_bands,1), ...
    repelem(band_names(:),n_channels,1), ...
    repelem(bands_hz(:,1),n_channels,1), ...
    repelem(bands_hz(:,2),n_channels,1), ...
    repelem(realized_band_low_hz,n_channels,1), ...
    repelem(realized_band_high_hz,n_channels,1), ...
    repelem(realized_bin_count,n_channels,1), ...
    repmat(rms_value,n_bands,1), ...
    repmat(absolute_peak,n_bands,1), ...
    reshape(band_energy,row_count,1), ...
    repmat(psd_density_units,n_bands,1), ...
    repmat(band_energy_units,n_bands,1), ...
    'VariableNames',{'channel','signal_unit','psd_band', ...
    'band_low_hz','band_high_hz','realized_band_low_hz', ...
    'realized_band_high_hz','realized_bin_count','signal_rms', ...
    'signal_abs_peak','psd_band_energy','psd_density_unit', ...
    'psd_band_energy_unit'});

band_metadata = table(band_names(:),bands_hz(:,1),bands_hz(:,2), ...
    realized_band_low_hz,realized_band_high_hz,realized_bin_count, ...
    'VariableNames',{'psd_band','requested_low_hz','requested_high_hz', ...
    'realized_low_hz','realized_high_hz','realized_bin_count'});

harmonic_summary = local_harmonic_summary( ...
    time_s,signal,channel_names,channel_units,harmonic_frequencies_hz, ...
    harmonic_names,frequency_hz,psd_density,psd_density_units);

metrics = struct();
metrics.summary = summary;
metrics.frequency_hz = frequency_hz;
metrics.psd_density = psd_density;
metrics.psd_density_units = psd_density_units;
metrics.channel_names = channel_names(:);
metrics.channel_units = channel_units(:);
metrics.band_metadata = band_metadata;
metrics.harmonic_summary = harmonic_summary;
metrics.estimator = struct( ...
    'name','Welch one-sided PSD (base-MATLAB implementation)', ...
    'sample_rate_hz',sample_rate_hz, ...
    'segment_length_samples',segment_length, ...
    'overlap_samples',overlap_length, ...
    'window','periodic Hann', ...
    'detrend','segment mean removal', ...
    'nfft',nfft, ...
    'segment_count',segment_count, ...
    'frequency_resolution_hz',frequency_resolution_hz, ...
    'nyquist_hz',nyquist_hz, ...
    'psd_density_quantity','signal-unit squared per Hz', ...
    'band_quantity','mean-square contribution in signal-unit squared', ...
    'band_integration','sum of included one-sided PSD bins times df', ...
    'harmonic_amplitude_estimator', ...
        'least-squares constant + cosine + sine at exact target frequency');
end

function summary = local_harmonic_summary( ...
        time_s,signal,channel_names,channel_units,target_hz,harmonic_names, ...
        frequency_hz,psd_density,psd_density_units)
n_channels = size(signal,1);
n_harmonics = numel(target_hz);
if n_harmonics == 0
    summary = table();
    return;
end

amplitude = zeros(n_channels,n_harmonics);
nearest_density = zeros(n_channels,n_harmonics);
nearest_bin_hz = zeros(n_harmonics,1);
nearest_bin_offset_hz = zeros(n_harmonics,1);
time_column_s = time_s(:);
for harmonic = 1:n_harmonics
    omega = 2*pi*target_hz(harmonic);
    basis = [ones(numel(time_column_s),1), ...
        cos(omega*time_column_s),sin(omega*time_column_s)];
    coefficient = basis\signal';
    amplitude(:,harmonic) = hypot(coefficient(2,:),coefficient(3,:))';
    [~,bin] = min(abs(frequency_hz-target_hz(harmonic)));
    nearest_bin_hz(harmonic) = frequency_hz(bin);
    nearest_bin_offset_hz(harmonic) = ...
        nearest_bin_hz(harmonic)-target_hz(harmonic);
    nearest_density(:,harmonic) = psd_density(:,bin);
end

row_count = n_channels*n_harmonics;
summary = table( ...
    repmat(channel_names(:),n_harmonics,1), ...
    repmat(channel_units(:),n_harmonics,1), ...
    repelem(harmonic_names(:),n_channels,1), ...
    repelem(target_hz(:),n_channels,1), ...
    reshape(amplitude,row_count,1), ...
    repelem(nearest_bin_hz,n_channels,1), ...
    repelem(nearest_bin_offset_hz,n_channels,1), ...
    reshape(nearest_density,row_count,1), ...
    repmat(psd_density_units(:),n_harmonics,1), ...
    'VariableNames',{'channel','signal_unit','harmonic', ...
    'target_frequency_hz','exact_frequency_amplitude', ...
    'nearest_welch_bin_hz','nearest_welch_bin_offset_hz', ...
    'nearest_welch_psd_density','psd_density_unit'});
end

function [frequency_hz,mean_psd,n_segments] = local_welch( ...
        signal,sample_rate_hz,segment_length,overlap_length,nfft)
step = segment_length-overlap_length;
starts = 1:step:(size(signal,2)-segment_length+1);
n_segments = numel(starts);
window = 0.5 - 0.5*cos(2*pi*(0:segment_length-1)/segment_length);
window_power = sum(window.^2);
n_one_sided = floor(nfft/2)+1;
mean_psd = zeros(size(signal,1),n_one_sided);
for k = 1:n_segments
    segment = signal(:,starts(k)+(0:segment_length-1));
    segment = segment-mean(segment,2);
    spectrum = fft(segment.*window,nfft,2);
    density = abs(spectrum(:,1:n_one_sided)).^2 / ...
        (sample_rate_hz*window_power);
    if rem(nfft,2) == 0
        density(:,2:end-1) = 2*density(:,2:end-1);
    else
        density(:,2:end) = 2*density(:,2:end);
    end
    mean_psd = mean_psd+density;
end
mean_psd = mean_psd/n_segments;
frequency_hz = (0:n_one_sided-1)*(sample_rate_hz/nfft);
end

function value = local_cell_text(value,label)
if isstring(value)
    value = cellstr(value(:));
elseif ischar(value)
    value = {value};
elseif iscell(value)
    value = value(:);
else
    error('response_signature:MetricMetadata', ...
        '%s must be text or a cell array of text.',label);
end
if any(~cellfun(@(x) ischar(x) && isrow(x) && ~isempty(x),value))
    error('response_signature:MetricMetadata', ...
        '%s entries must be nonempty character rows.',label);
end
end
