function save_progress(data, DC, run_path, gen_schema, gen_fingerprint, ...
        matlab_release, campaign_matlab_release, release_qualification_run, ...
        actual_matlab_environment_sha256, ...
        campaign_matlab_environment_sha256, ...
        generator_source_root_sha256, qualification_source_sha256, ...
        run_folder_observation)
%SAVE_PROGRESS Atomically save one state with fail-closed R12 provenance.
%   All arguments are mandatory. Provenance is stored inside DATA and as cheap
%   top-level stamps used by A00's resume guard. The duplicate representations
%   are cross-checked here so a caller cannot accidentally stamp a payload with
%   provenance different from the payload it contains.

    narginchk(12, 13);
    if ~isstruct(data) || ~isscalar(data)
        error('save_progress:Data', 'data must be a scalar struct.');
    end
    validateattributes(DC, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'}, mfilename, 'DC');
    run_path = local_text(run_path, 'run_path');
    if ~isfolder(run_path)
        error('save_progress:RunPath', ...
            'run_path must be an existing directory: %s', run_path);
    end
    % Legacy diagnostic callers may omit the observation; they still capture
    % and pin the real directory before their first write. Production passes
    % A00's earlier observation so replacement since orchestration is caught.
    if nargin < 13
        run_folder_observation = ttbi.directory_observation(run_path);
    end
    ttbi.assert_generation_output_directory( ...
        run_path, run_folder_observation);
    gen_schema = local_text(gen_schema, 'gen_schema');
    gen_fingerprint = local_sha(gen_fingerprint, 'gen_fingerprint');
    matlab_release = local_text(matlab_release, 'matlab_release');
    campaign_matlab_release = local_text( ...
        campaign_matlab_release, 'campaign_matlab_release');
    if ~islogical(release_qualification_run) || ...
            ~isscalar(release_qualification_run)
        error('save_progress:QualificationMode', ...
            'release_qualification_run must be one logical scalar.');
    end
    actual_matlab_environment_sha256 = local_sha( ...
        actual_matlab_environment_sha256, ...
        'actual_matlab_environment_sha256');
    campaign_matlab_environment_sha256 = local_sha( ...
        campaign_matlab_environment_sha256, ...
        'campaign_matlab_environment_sha256');
    generator_source_root_sha256 = local_sha( ...
        generator_source_root_sha256, 'generator_source_root_sha256');
    qualification_source_sha256 = local_qualification_sha( ...
        qualification_source_sha256, release_qualification_run);

    required_payload = { ...
        'gen_schema', 'gen_fingerprint', 'channel_schema_id', ...
        'state_uid', 'state_seed_id', ...
        'random_stream_schedule_version', ...
        'matlab_release', 'campaign_matlab_release', ...
        'release_qualification_run', ...
        'actual_matlab_environment_descriptor', ...
        'actual_matlab_environment_sha256', ...
        'campaign_matlab_environment_descriptor', ...
        'campaign_matlab_environment_sha256', ...
        'generator_source_root_sha256', ...
        'generator_source_digest_lines', 'generator_source_file_count', ...
        'qualification_source_sha256'};
    if ~all(isfield(data, required_payload))
        missing = required_payload(~isfield(data, required_payload));
        error('save_progress:PayloadProvenance', ...
            'data lacks required provenance field(s): %s', ...
            strjoin(missing, ', '));
    end

    local_equal_text(data.gen_schema, gen_schema, 'gen_schema');
    local_equal_text(data.gen_fingerprint, gen_fingerprint, 'gen_fingerprint');
    channel_schema_id = local_text( ...
        data.channel_schema_id, 'data.channel_schema_id');
    if ~strcmp(channel_schema_id, 'physical8_v1')
        error('save_progress:ChannelSchema', ...
            ['data.channel_schema_id must be the current physical8_v1 ' ...
             'payload contract.']);
    end
    state_uid = local_text(data.state_uid, 'data.state_uid');
    if ~isa(data.state_seed_id, 'uint32') || ...
            ~isscalar(data.state_seed_id) || data.state_seed_id == 0
        error('save_progress:StateSeedID', ...
            'data.state_seed_id must be one nonzero uint32 scalar.');
    end
    random_stream_schedule_version = local_text( ...
        data.random_stream_schedule_version, ...
        'data.random_stream_schedule_version');
    local_equal_text(data.matlab_release, matlab_release, 'matlab_release');
    local_equal_text(data.campaign_matlab_release, ...
        campaign_matlab_release, 'campaign_matlab_release');
    if ~islogical(data.release_qualification_run) || ...
            ~isscalar(data.release_qualification_run) || ...
            data.release_qualification_run ~= release_qualification_run
        error('save_progress:PayloadMismatch', ...
            'data.release_qualification_run differs from its top-level stamp.');
    end
    actual_descriptor = local_multiline_text( ...
        data.actual_matlab_environment_descriptor, ...
        'actual_matlab_environment_descriptor');
    local_equal_text(data.actual_matlab_environment_sha256, ...
        actual_matlab_environment_sha256, ...
        'actual_matlab_environment_sha256');
    if ~strcmp(local_text_sha256(actual_descriptor), ...
            actual_matlab_environment_sha256)
        error('save_progress:ActualEnvironmentDescriptor', ...
            ['data.actual_matlab_environment_descriptor does not reproduce ' ...
             'its SHA-256 stamp.']);
    end
    campaign_descriptor = local_multiline_text( ...
        data.campaign_matlab_environment_descriptor, ...
        'campaign_matlab_environment_descriptor');
    local_equal_text(data.campaign_matlab_environment_sha256, ...
        campaign_matlab_environment_sha256, ...
        'campaign_matlab_environment_sha256');
    if ~strcmp(local_text_sha256(campaign_descriptor), ...
            campaign_matlab_environment_sha256)
        error('save_progress:CampaignEnvironmentDescriptor', ...
            ['data.campaign_matlab_environment_descriptor does not reproduce ' ...
             'its SHA-256 stamp.']);
    end
    local_equal_text(data.generator_source_root_sha256, ...
        generator_source_root_sha256, 'generator_source_root_sha256');
    source_lines = local_multiline_text(data.generator_source_digest_lines, ...
        'generator_source_digest_lines');
    if ~strcmp(local_text_sha256(source_lines), generator_source_root_sha256)
        error('save_progress:GeneratorSourceDescriptor', ...
            ['data.generator_source_digest_lines does not reproduce its ' ...
             'generator source-root SHA-256 stamp.']);
    end
    validateattributes(data.generator_source_file_count, {'numeric'}, ...
        {'real', 'finite', 'scalar', 'integer', 'positive'}, ...
        mfilename, 'data.generator_source_file_count');
    source_line_count = sum(source_lines == newline) + 1;
    if data.generator_source_file_count ~= source_line_count
        error('save_progress:GeneratorSourceCount', ...
            ['data.generator_source_file_count=%d but its canonical digest ' ...
             'descriptor contains %d lines.'], ...
            data.generator_source_file_count, source_line_count);
    end
    local_equal_text(data.qualification_source_sha256, ...
        qualification_source_sha256, 'qualification_source_sha256');

    file_gen_schema = gen_schema;
    file_gen_fingerprint = gen_fingerprint;
    file_state_uid = state_uid;
    file_state_seed_id = data.state_seed_id;
    file_random_stream_schedule_version = random_stream_schedule_version;
    file_matlab_release = matlab_release;
    file_campaign_matlab_release = campaign_matlab_release;
    file_release_qualification_run = release_qualification_run;
    file_actual_matlab_environment_sha256 = ...
        actual_matlab_environment_sha256;
    file_campaign_matlab_environment_sha256 = ...
        campaign_matlab_environment_sha256;
    file_generator_source_root_sha256 = generator_source_root_sha256;
    file_qualification_source_sha256 = qualification_source_sha256;

    filename = sprintf('%04d.mat', DC);
    final_path = fullfile(run_path, filename);
    tmp_path = fullfile(run_path, sprintf('.%04d.mat.tmp', DC));
    ttbi.assert_generation_output_directory( ...
        run_path, run_folder_observation);
    if exist(tmp_path, 'file')
        delete(tmp_path);
    end
    save(tmp_path, 'data', 'file_gen_schema', 'file_gen_fingerprint', ...
        'file_state_uid', 'file_state_seed_id', ...
        'file_random_stream_schedule_version', ...
        'file_matlab_release', 'file_campaign_matlab_release', ...
        'file_release_qualification_run', ...
        'file_actual_matlab_environment_sha256', ...
        'file_campaign_matlab_environment_sha256', ...
        'file_generator_source_root_sha256', ...
        'file_qualification_source_sha256');
    ttbi.assert_generation_output_directory( ...
        run_path, run_folder_observation);
    if isfile(final_path)
        error('save_progress:StateCollision', ...
            ['Refusing to replace an existing numbered state. Resume ' ...
             'validation must classify every existing state before workers ' ...
             'start: %s'], final_path);
    end
    [moved, move_message] = movefile(tmp_path, final_path);
    if ~moved
        error('save_progress:AtomicMove', ...
            'Could not publish the completed state atomically: %s', ...
            move_message);
    end
    ttbi.assert_generation_output_directory( ...
        run_path, run_folder_observation);
end

function value = local_text(value, label)
    if isstring(value) && isscalar(value)
        value = char(value);
    end
    if ~ischar(value) || ~isrow(value) || isempty(value) || ...
            any(value == char(13)) || any(value == newline) || ...
            any(value == char(0))
        error('save_progress:Text', ...
            '%s must be one nonempty character row without control bytes.', label);
    end
end

function value = local_sha(value, label)
    value = local_text(value, label);
    if isempty(regexp(value, '^[0-9a-f]{64}$', 'once'))
        error('save_progress:SHA256', ...
            '%s must be one lowercase SHA-256 digest.', label);
    end
end

function value = local_multiline_text(value, label)
    if isstring(value) && isscalar(value)
        value = char(value);
    end
    if ~ischar(value) || ~isrow(value) || isempty(value) || ...
            any(value == char(13)) || any(value == char(0))
        error('save_progress:MultilineText', ...
            '%s must be one nonempty LF-only character row.', label);
    end
end

function value = local_qualification_sha(value, qualification_run)
    value = local_text(value, 'qualification_source_sha256');
    if qualification_run
        if isempty(regexp(value, '^[0-9a-f]{64}$', 'once'))
            error('save_progress:QualificationSHA256', ...
                ['Qualification data require the lowercase SHA-256 identity ' ...
                 'inserted by make_micro_smoke.py.']);
        end
    elseif ~strcmp(value, 'PRODUCTION')
        error('save_progress:ProductionSource', ...
            'Production data require qualification_source_sha256=PRODUCTION.');
    end
end

function local_equal_text(actual, expected, label)
    actual = local_text(actual, ['data.' label]);
    if ~strcmp(actual, expected)
        error('save_progress:PayloadMismatch', ...
            'data.%s differs from its top-level stamp.', label);
    end
end

function sha256 = local_text_sha256(text)
    bytes = unicode2native(text, 'UTF-8');
    md = java.security.MessageDigest.getInstance('SHA-256');
    raw = md.digest(bytes);
    sha256 = lower(sprintf('%02x', typecast(int8(raw), 'uint8')));
end
