function smoke_familytable()
%SMOKE_FAMILYTABLE Real MATLAB-to-Python smoke for the R11 state contract.
%
% This deliberately keeps the small eight-row family inventory used by the
% original smoke, but writes every field required by
% core.dataset.read_state_table.  The Python half independently recomputes
% every SHA-derived root/named stream seed, so agreement cannot come from row
% order or from trusting values embedded in this fixture.

out_dir = fullfile('Results', '_smoke_familytable');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

% ---- Fixed eight-row semantic family fixture -----------------------------
n_supp = 4;
n_states = 8;
Npass = 3;
damage_seed = 1;
L_bridge = 60;
num_spans = 3;
scour_supports = [2 3];
random_stream_schedule_version = 'uid-named-substreams-v2';
state_stream_names = ...
    {'operations','crack','profile-state','track','profile-phase'};
passage_stream_names = {'profile-passage','oor-passage'};

StateFamily = [repmat({'target_healthy'}, 2, 1); ...
               repmat({'scour_only'},     2, 1); ...
               repmat({'bearing_only'},   1, 1); ...
               repmat({'nuisance_only'},  1, 1); ...
               repmat({'joint'},          2, 1)];
AnchorTarget = [0; 0; 2; 3; 1; 0; 0; 0];
AnchorLevel = [0; 0; 1; 2; 1; 0; 0; 0];

DamageStates = zeros(n_states, n_supp);
DamageStates(3, 2) = 0.15;
DamageStates(4, 3) = 0.30;
DamageStates(7, 2:3) = [0.10 0.40];
DamageStates(8, 2:3) = [0.05 0.10];

LatentBearingFixity = zeros(n_states, 2);
LatentBearingFixity(5, 1) = 0.2375;
LatentBearingFixity(7, :) = [0.10 0.40];
LatentBearingFixity(8, :) = [0.30 0.20];
BearingFixity = LatentBearingFixity;  % active-bearing R11 rung

LatentCrackOn = logical([0; 0; 0; 0; 0; 1; 1; 0]);
CrackOn = LatentCrackOn;              % active-crack R11 rung

StateUID = cell(n_states, 1);
StateUID{1} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'target_healthy', 0, 0, 1);
StateUID{2} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'target_healthy', 0, 0, 2);
StateUID{3} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'scour_only', 2, 1, 1);
StateUID{4} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'scour_only', 3, 2, 1);
StateUID{5} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'bearing_only', 1, 1, 1);
StateUID{6} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'nuisance_only', 0, 0, 1);
% Joint UIDs carry their stable joint-design level, while the family table's
% AnchorLevel remains zero because joint rows are not controlled anchors.
StateUID{7} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'joint', 0, 1, 1);
StateUID{8} = ttbi.state_uid(L_bridge, num_spans, scour_supports, ...
    'joint', 0, 2, 1);

StateSeedID = ttbi.state_seed_ids(StateUID, damage_seed);
[StateNamedStreamSeedID, PassageNamedStreamSeedID] = ...
    ttbi.named_stream_seed_ids(StateSeedID, StateUID, Npass, ...
        random_stream_schedule_version, state_stream_names, ...
        passage_stream_names);
% MATLAB reshape is column-major.  Python authenticates this against
% expected_passage_named.reshape(n_states, -1, order="F").
PassageNamedStreamSeedIDFlat = reshape( ...
    PassageNamedStreamSeedID, n_states, []);

k_ref_bear = 2.31e9;
BearingStates = k_ref_bear .* BearingFixity ./ (1 - BearingFixity);
assert(all(BearingFixity(:) >= 0 & BearingFixity(:) < 1), ...
    'fixture bearing fixity must stay in [0,1)');
assert(max(abs(BearingFixity(:) - ...
    BearingStates(:) ./ (BearingStates(:) + k_ref_bear))) < 1e-15, ...
    'fixture fixity-to-k_r transform is not exactly invertible');
save(fullfile(out_dir, 'damage_states.mat'), ...
    'DamageStates', 'BearingStates', 'BearingFixity', ...
    'LatentBearingFixity', 'k_ref_bear', 'scour_supports', ...
    'StateFamily', 'AnchorTarget', 'AnchorLevel', ...
    'StateUID', 'StateSeedID', 'LatentCrackOn', 'CrackOn', ...
    'StateNamedStreamSeedID', 'PassageNamedStreamSeedID', ...
    'PassageNamedStreamSeedIDFlat', ...
    'random_stream_schedule_version', 'state_stream_names', ...
    'passage_stream_names');

% read_state_table authenticates damage_seed from the canonical generator
% JSON in case_info, never from a row/DC-derived fallback.
generation_config_json = jsonencode(struct('damage_seed', damage_seed));
case_info = struct( ...
    'generation_config_json', generation_config_json, ...
    'damage_seed', damage_seed);
save(fullfile(out_dir, 'case_info.mat'), 'case_info');

% ---- MATLAB's own save/load contract -------------------------------------
S = load(fullfile(out_dir, 'damage_states.mat'));
assert(iscellstr(S.StateFamily) && isequal(S.StateFamily, StateFamily), ...
    'StateFamily did not survive save/load as an identical cellstr'); %#ok<ISCLSTR>
assert(iscellstr(S.StateUID) && isequal(S.StateUID, StateUID), ...
    'StateUID did not survive save/load as an identical cellstr'); %#ok<ISCLSTR>
assert(islogical(S.LatentCrackOn) && ...
    isequal(S.LatentCrackOn, LatentCrackOn), ...
    'LatentCrackOn did not survive save/load as logical');
assert(islogical(S.CrackOn) && isequal(S.CrackOn, CrackOn), ...
    'CrackOn did not survive save/load as logical');
assert(isa(S.StateSeedID, 'uint32') && ...
    isequal(S.StateSeedID, StateSeedID), ...
    'StateSeedID did not survive save/load as uint32');
assert(isequal(S.DamageStates, DamageStates) && ...
    isequal(S.LatentBearingFixity, LatentBearingFixity) && ...
    isequal(S.BearingFixity, BearingFixity), ...
    'physical/latent state matrices changed in the round trip');
assert(isequal(S.PassageNamedStreamSeedIDFlat, ...
    reshape(S.PassageNamedStreamSeedID, n_states, [])), ...
    'passage named-stream flat layout is not MATLAB column-major');
fprintf('[PASS] complete R11 damage_states.mat round-trips in MATLAB\n');

% ---- Resume-check equality on one real saved data struct -----------------
dc_idx = 3;
data = struct();
data.scour_vector = DamageStates(dc_idx, :);
data.bearing_fixity = BearingFixity(dc_idx, :);
data.bearing_vector = BearingStates(dc_idx, :);
data.scour_supports = scour_supports;
data.state_family = StateFamily{dc_idx};
data.state_uid = StateUID{dc_idx};
data.state_seed_id = StateSeedID(dc_idx);
fstate = fullfile(out_dir, 'state_roundtrip.mat');
save(fstate, 'data');
D = load(fstate);
d_ = D.data;
assert(isequal(d_.scour_vector, DamageStates(dc_idx, :)), ...
    'scour row isequal failed');
assert(isequal(d_.bearing_fixity, BearingFixity(dc_idx, :)), ...
    'fixity row isequal failed');
assert(isequal(d_.bearing_vector, BearingStates(dc_idx, :)), ...
    'bearing row isequal failed');
assert(isequal(d_.scour_supports, scour_supports), ...
    'scour_supports isequal failed');
assert(strcmp(char(d_.state_family), StateFamily{dc_idx}), ...
    'state_family strcmp failed');
assert(strcmp(char(d_.state_uid), StateUID{dc_idx}), ...
    'state_uid strcmp failed');
assert(isequal(d_.state_seed_id, StateSeedID(dc_idx)), ...
    'state_seed_id isequal failed');
fprintf('[PASS] resume identity checks survive a real MATLAB save/load\n');

% ---- JSON determinism for representative R11 fields ----------------------
fp_cfg = struct( ...
    'schema', 'smoke-r11', ...
    'damage_seed', damage_seed, ...
    'StateFamily', {StateFamily}, ...
    'StateUID', {StateUID}, ...
    'StateSeedID', StateSeedID, ...
    'LatentBearingFixity', LatentBearingFixity, ...
    'LatentCrackOn', LatentCrackOn, ...
    'random_stream_schedule_version', random_stream_schedule_version, ...
    'state_stream_names', {state_stream_names}, ...
    'passage_stream_names', {passage_stream_names});
j1 = jsonencode(fp_cfg);
j2 = jsonencode(fp_cfg);
assert((ischar(j1) || isstring(j1)) && strcmp(j1, j2), ...
    'jsonencode is not deterministic for the same R11 struct');
assert(contains(j1, '"uid-named-substreams-v2"') && ...
    contains(j1, '"target_healthy"') && contains(j1, 'true'), ...
    'jsonencode dropped an R11 identity/latent field');
fprintf('[PASS] representative R11 generation JSON is deterministic\n');

fprintf('\nsmoke_familytable: ALL PASS\n');
fprintf('Now run the pinned Python check_familytable_roundtrip.py.\n');
end
