function smoke_generation_worker()
%SMOKE_GENERATION_WORKER Generate and consume one coherent modular dataset.
%
% The smoke selects one F40-M nuisance state before identity construction,
% executes it as canonical state 0001 through the real solver, and uses the
% production manifest/publication helpers.  The reduced six-state catalogue is
% explicitly qualification-only and therefore cannot impersonate campaign
% output; the selected one-state package still exercises the exact production
% identity, sidecar, resume, and publication machinery.

inputs = struct( ...
    'STAGE', 'F40-M', ...
    'n_states_multi', 1, ...
    'Npass', 1, ...
    'n_healthy_states', 1, ...
    'n_anchor_levels', 1, ...
    'n_anchor_reps', 1, ...
    'n_nuisance_states', 1, ...
    'qualification_run', true);
campaign = ttbi.campaign_setup(inputs);
full_design = ttbi.build_state_design(campaign);
assert(full_design.n_states == 6);
assert(campaign.use_crack_eov && ...
    ~campaign.use_track_eov && ~campaign.use_oor_eov);
assert(strcmp(campaign.profile_mode, 'fixed'));
selected_index = find(strcmp( ...
    full_design.StateFamily, 'nuisance_only'), 1, 'first');
assert(isscalar(selected_index));
state_design = ttbi.select_single_state_design( ...
    full_design, selected_index);
assert(state_design.n_states == 1 && state_design.CrackOn(1));

scratch = tempname;
mkdir(scratch);
cleanup = onCleanup(@() rmdir(scratch, 's'));
publication_folder = fullfile(scratch, 'publication');
mkdir(publication_folder);

[source_root, source_lines, source_count] = ...
    ttbi.smoke_generator_source_boundary();

actual_descriptor = 'smoke-generation-worker-actual-environment';
campaign_descriptor = 'smoke-generation-worker-campaign-environment';
provenance = struct( ...
    'matlab_release', ['R' version('-release')], ...
    'campaign_matlab_release', ['R' version('-release')], ...
    'actual_matlab_environment_descriptor', actual_descriptor, ...
    'actual_matlab_environment_sha256', ttbi.sha256(actual_descriptor), ...
    'campaign_matlab_environment_descriptor', campaign_descriptor, ...
    'campaign_matlab_environment_sha256', ttbi.sha256(campaign_descriptor), ...
    'generator_source_root_sha256', source_root, ...
    'generator_source_digest_lines', source_lines, ...
    'generator_source_file_count', source_count, ...
    'qualification_source_sha256', 'PRODUCTION', ...
    'release_qualification_run', false);
identity = ttbi.build_generation_identity( ...
    campaign, state_design, provenance);
provenance.gen_schema = identity.gen_schema;
provenance.gen_fingerprint = identity.gen_fingerprint;

runtime = struct();
runtime.run_folder = publication_folder;
runtime.run_folder_observation = ...
    ttbi.directory_observation(publication_folder);
runtime.contact = struct( ...
    'max_tension_N', 24000, ...
    'max_tension_fraction', 0.002);
runtime.provenance = provenance;
context = ttbi.build_execution_context(campaign, state_design, runtime);
assert(strcmp(context.identity.channel_schema_id, ...
    identity.channel_schema_id));
assert(strcmp(context.identity.state_design_kind, ...
    identity.state_design_kind));
ttbi.smoke_generation_output_boundary(scratch, context);
ttbi.smoke_reject_unauthenticated_generation_pool(context);
ttbi.run_generation_states(context, false, 1);
assert(isempty(gcp('nocreate')), ...
    'Generation runner leaked its fresh process pool.');

output_path = fullfile(publication_folder, '0001.mat');
assert(isfile(output_path));
saved = load(output_path);
assert(strcmp(saved.file_state_uid, state_design.StateUID{1}));
assert(saved.file_state_seed_id == state_design.StateSeedID(1));
assert(strcmp(saved.data.state_family, 'nuisance_only'));
assert(saved.data.crack_on && any(saved.data.crack_log(:) ~= 0));
assert(strcmp(saved.data.profile_mode, 'fixed'));
assert(all(saved.data.profile_log == 4));
assert(isequal(size(saved.data.contact_log), [1, 4]));
assert(all(isfinite(saved.data.contact_log), 'all'));
assert(iscell(saved.data.track_log) && isempty(saved.data.track_log{1}));
assert(iscell(saved.data.oor_log) && isempty(saved.data.oor_log{1}));

completed = ttbi.validate_resume_states(publication_folder, context);
assert(isequal(completed, true));
ttbi.smoke_resume_payload_mutations( ...
    output_path, 1, scratch, context);

descriptor = ttbi.build_case_descriptor(campaign, state_design);
case_info = ttbi.build_case_info( ...
    campaign, state_design, descriptor, identity, provenance, ...
    'smoke-generation-worker');
ttbi.write_run_manifest( ...
    publication_folder, case_info, campaign, state_design, ...
    context.run_folder_observation);
ttbi.publish_generation_completion(publication_folder, context);
assert(isfile(fullfile(publication_folder, '_GENERATION_COMPLETE')));
manifest = validate_dataset_digest_manifest(publication_folder, 1);
assert(strcmp(manifest.schema, 'source-digests-v2'));
assert(numel(manifest.names) == 3);
ttbi.validate_generation_completion_marker( ...
    publication_folder, manifest.root);

ttbi.smoke_rejected_publication( ...
    publication_folder, scratch, context);
fprintf(['SMOKE GENERATION WORKER: PASS ' ...
    '(one F40-M nuisance state x one passage from a nonpublishable ' ...
    'qualification catalogue, deferred track/OOR disabled, fresh ' ...
    'ProcessPool + worker source ' ...
    'attestation/teardown, production identity/sidecars, authenticated ' ...
    'consumer, stale-credential and hard-link guards)\n']);
end
