%SMOKE_DRY_BALLAST_SIGN_SENSITIVITY Fast CRN/sign-transform contract test.

clear; clc
inputs = struct( ...
    'STAGE', 'F40-M', ...
    'n_states_multi', 1, ...
    'Npass', 1, ...
    'n_healthy_states', 1, ...
    'n_anchor_levels', 1, ...
    'n_anchor_reps', 1, ...
    'n_nuisance_states', 1, ...
    'qualification_run', true);
production_config = ttbi.campaign_setup(inputs);
assert(~production_config.use_track_eov, ...
    'Paper-1 production must keep the deferred track EOV disabled.');
base_config = production_config;
base_config.use_track_eov = true;
assert(~isfield(base_config, 'ballast_dry_stiffness_arm'), ...
    'Dormant sampler fixture unexpectedly contains a sensitivity arm.');

retained_config = base_config;
retained_config.ballast_dry_stiffness_arm = 'retained-stiffening';
soft_config = base_config;
soft_config.ballast_dry_stiffness_arm = 'reciprocal-softening';
Track = A02_Track();

saw_dry = false;
saw_wet = false;
persistent_seed = [];
for seed = 1:100
    [~, default_state] = ttbi.sample_track_damage( ...
        struct(), struct(), Track, base_config, seed, 1);
    [~, retained_state] = ttbi.sample_track_damage( ...
        struct(), struct(), Track, retained_config, seed, 1);
    [~, soft_state] = ttbi.sample_track_damage( ...
        struct(), struct(), Track, soft_config, seed, 1);

    % The explicit retained arm is numerically and structurally identical to
    % the configuration with no sensitivity field.
    assert(isfield(retained_state, 'ballast_dry_stiffness_arm') && ...
        strcmp(retained_state.ballast_dry_stiffness_arm, ...
            'retained-stiffening'), ...
        'Explicit retained sensitivity arm was not persisted in track state.');
    retained_numeric_state = rmfield(retained_state, ...
        'ballast_dry_stiffness_arm');
    assert(isequaln(default_state, retained_numeric_state), ...
        'Default sampling changed relative to explicit retained-stiffening.');
    assert(strcmp(soft_state.ballast_dry_stiffness_arm, ...
        'reciprocal-softening'), ...
        'Reciprocal sensitivity arm was not persisted in track state.');

    retained_ballast = retained_state.ballast_patches;
    soft_ballast = soft_state.ballast_patches;
    assert(isequal(size(retained_ballast), size(soft_ballast)), ...
        'Paired arms changed the number of ballast patches.');
    assert(isequaln(retained_ballast(:, [1 2 4]), ...
        soft_ballast(:, [1 2 4])), ...
        'Paired arms changed patch coordinates or damping draws.');

    retained_other = rmfield(retained_state, ...
        {'ballast_patches', 'ballast_dry_stiffness_arm'});
    soft_other = rmfield(soft_state, ...
        {'ballast_patches', 'ballast_dry_stiffness_arm'});
    assert(isequaln(retained_other, soft_other), ...
        ['Paired arms changed a hanging-sleeper, pad, or coordinate ' ...
         'latent variable.']);

    dry_rows = retained_ballast(:, 3) > 1;
    wet_rows = retained_ballast(:, 3) < 1;
    if any(dry_rows)
        saw_dry = true;
        expected_soft = 1 ./ retained_ballast(dry_rows, 3);
        assert(isequaln(soft_ballast(dry_rows, 3), expected_soft), ...
            'Dry reciprocal arm is not exactly 1/eta_k_base.');
        log_error = abs(abs(log(soft_ballast(dry_rows, 3))) - ...
            abs(log(retained_ballast(dry_rows, 3))));
        assert(all(log_error < 20 * eps), ...
            'Dry reciprocal transform did not preserve log-distance from 1.');
        if isempty(persistent_seed)
            persistent_seed = seed;
        end
    end
    if any(wet_rows)
        saw_wet = true;
        assert(isequaln(soft_ballast(wet_rows, 3), ...
            retained_ballast(wet_rows, 3)), ...
            'Wet-patch stiffness changed in the dry-sign sensitivity.');
    end
end
assert(saw_dry && saw_wet, ...
    'Seed sweep did not exercise both dry and wet ballast branches.');

% The optional arm must be absent from the dormant default identity and bound
% into both explicit sensitivity fingerprints. Reuse one current qualification
% state so this smoke cannot drift behind the state-identity schema.
full_state = ttbi.build_state_design(production_config);
state = ttbi.select_single_state_design(full_state, 1);
hex64 = repmat('a', 1, 64);
provenance = struct( ...
    'campaign_matlab_release', 'R2024b', ...
    'campaign_matlab_environment_sha256', hex64, ...
    'generator_source_root_sha256', hex64, ...
    'qualification_source_sha256', 'PRODUCTION');
default_identity = ttbi.build_generation_identity( ...
    base_config, state, provenance);
retained_identity = ttbi.build_generation_identity( ...
    retained_config, state, provenance);
soft_identity = ttbi.build_generation_identity( ...
    soft_config, state, provenance);
assert(~contains(default_identity.generation_config_json, ...
    'ballast_dry_stiffness_arm'), ...
    'Ordinary generation identity unexpectedly contains sensitivity metadata.');
assert(contains(retained_identity.generation_config_json, ...
    '"ballast_dry_stiffness_arm":"retained-stiffening"') && ...
    contains(soft_identity.generation_config_json, ...
    '"ballast_dry_stiffness_arm":"reciprocal-softening"'), ...
    'Sensitivity arm was not serialized in generation_config_json.');
assert(~strcmp(default_identity.gen_fingerprint, ...
        retained_identity.gen_fingerprint) && ...
    ~strcmp(retained_identity.gen_fingerprint, soft_identity.gen_fingerprint), ...
    'Default, retained, and reciprocal configurations share a fingerprint.');

% Persistent per-state reuse must not redraw or re-transform the descriptor.
[~, soft_first] = ttbi.sample_track_damage( ...
    struct(), struct(), Track, soft_config, persistent_seed, 1);
[Damage_second, soft_second, log_second] = ttbi.sample_track_damage( ...
    struct(), soft_first, Track, soft_config, persistent_seed, 2);
assert(isequaln(soft_first, soft_second) && ...
    isequaln(log_second, soft_first) && ...
    isequaln(Damage_second.track, soft_first), ...
    'Per-state reciprocal descriptor was not reused exactly.');
local_assert_throws(@() ttbi.sample_track_damage( ...
    struct(), soft_first, Track, retained_config, persistent_seed, 2), ...
    'ttbi:sample_track_damage:SensitivityArmMismatch');
local_assert_throws(@() ttbi.sample_track_damage( ...
    struct(), soft_first, Track, base_config, persistent_seed, 2), ...
    'ttbi:sample_track_damage:SensitivityArmMismatch');

% Invalid configuration must fail before changing the caller's RNG state.
invalid_config = base_config;
invalid_config.ballast_dry_stiffness_arm = 'soft';
rng(987654, 'twister');
rng_before = rng;
local_assert_throws(@() ttbi.sample_track_damage( ...
    struct(), struct(), Track, invalid_config, 12, 1), ...
    'ttbi:dry_ballast_stiffness_arm:UnsupportedArm');
rng_after = rng;
assert(isequaln(rng_before, rng_after), ...
    'Invalid sensitivity configuration consumed an RNG draw.');
local_assert_throws(@() ttbi.dry_ballast_stiffness_arm(3), ...
    'ttbi:dry_ballast_stiffness_arm:InvalidType');
local_assert_throws(@() ttbi.dry_ballast_stiffness_arm('Retained-stiffening'), ...
    'ttbi:dry_ballast_stiffness_arm:UnsupportedArm');

% Exercise the same authenticated parent/descendant layout used by A00.  The
% parent must remain a single observed component; the nested sensitivity
% namespace is created one component at a time only after its parent is
% reauthenticated.
smoke_root = 'Results_sensitivity_smoke_contract';
assert(~ttbi.path_entry_exists(smoke_root), ...
    'A stale dry-ballast output-boundary smoke directory exists.');
[made, message] = mkdir(smoke_root);
assert(made, 'Could not create output-boundary smoke root: %s', message);
cleanup = onCleanup(@() local_remove_smoke_tree(smoke_root));
root_observation = ttbi.directory_observation(smoke_root);
smoke_run_folder = fullfile(smoke_root, ...
    'dry_ballast_stiffness_sign', 'retained-stiffening', 'smoke-case');
run_observation = ttbi.ensure_generation_output_directory( ...
    smoke_run_folder, smoke_root, root_observation);
assert(isfolder(smoke_run_folder), ...
    'Authenticated sensitivity output chain was not created.');
ttbi.assert_generation_output_directory( ...
    smoke_run_folder, run_observation);
local_assert_throws(@() ttbi.ensure_generation_output_directory( ...
    smoke_run_folder, fullfile(smoke_root, ...
        'dry_ballast_stiffness_sign', 'retained-stiffening'), ...
    root_observation), 'ttbi:GenerationOutputPath');
local_remove_smoke_tree(smoke_root);
clear cleanup

fprintf(['DRY-BALLAST SIGN SENSITIVITY: PASS\n' ...
    '  default invariant; exact CRN pairing; reciprocal log-distance; ' ...
    'wet/damping/location/count/pad/hanging latents unchanged\n']);

function local_assert_throws(callable, expected_id)
try
    callable();
catch err
    assert(strcmp(err.identifier, expected_id), ...
        'Expected %s, received %s.', expected_id, err.identifier);
    return;
end
error('smoke_dry_ballast_sign_sensitivity:MissingError', ...
    'Expected %s, but the call succeeded.', expected_id);
end

function local_remove_smoke_tree(path)
if isfolder(path)
    [removed, message] = rmdir(path, 's');
    assert(removed, 'Could not remove output-boundary smoke tree: %s', message);
end
end
