function smoke_response_signature_metrics()
%SMOKE_RESPONSE_SIGNATURE_METRICS Fast no-solver contract for the harness.

[healthy,catalog,design] = response_signature_damage_catalog();
assert(numel(catalog) == 9, ...
    'response_signature smoke: active inventory count changed');
assert(all(healthy.scour_rates == 0) && isempty(healthy.track) && ...
    isempty(healthy.oor_poly), ...
    'response_signature smoke: healthy descriptor is not an identity');
names = {catalog.name};
assert(isequal(names,{ ...
    'scour','bearing_fixity','crack','ballast_patch', ...
    'hanging_sleepers','pad_service_stiffness', ...
    'pad_service_damping','pad_failure','wheel_polygonization'}), ...
    'response_signature smoke: inventory/order mismatch');
roles = {catalog.role};
assert(strcmp(roles{1},'active support-loss regression target') && ...
    contains(roles{2},'target') && contains(roles{2},'not physical') && ...
    strcmp(roles{3},'bridge-condition nuisance') && ...
    all(strcmp(roles(4:8),'track-condition nuisance/EOV')) && ...
    strcmp(roles{9},'wheel-condition nuisance'), ...
    'response_signature smoke: service/fixity role labels are unsafe');
assert(design.temperature_c == 18 && strcmp(design.case_label,'V80_T18'), ...
    'response_signature smoke: canonical V80_T18 fixture drifted');
assert(isequal(design.psd_bands_hz,[0.2 15]), ...
    'response_signature smoke: default reporting band drifted');
assert(design.contact_max_tensile_peak_n == 24000 && ...
    design.contact_max_positive_fraction == 0.002, ...
    'response_signature smoke: registered contact policy drifted');
expected_polygon_hz = design.polygon_row(3)*(design.speed_kmh/3.6) / ...
    (2*pi*design.wheel_radius_m);
assert(design.polygon_harmonic_frequency_hz == expected_polygon_hz && ...
    expected_polygon_hz > design.psd_bands_hz(2), ...
    'response_signature smoke: polygon harmonic target is missing or band-bound');
assert(all(strcmp({catalog(1:3).first_changed_quantity}, ...
    'bridge_stiffness_state_specific_rayleigh_damping')), ...
    'response_signature smoke: structural boundary incorrectly claims K-only');

sample_rate_hz = 1024;
n_samples = 4096;
time_s = (0:n_samples-1)/sample_rate_hz;
signal = [ ...
    2*sin(2*pi*4*time_s); ...
    0.5*cos(2*pi*40*time_s)];
bands_hz = [3 5;39 41];
band_names = {'four_hz';'forty_hz'};
metrics_a = response_signature_metrics( ...
    time_s,signal,{'low';'high'},{'m/s^2';'rad/s'}, ...
    bands_hz,band_names,4,{'four_hz_exact'});
metrics_b = response_signature_metrics( ...
    time_s,signal,{'low';'high'},{'m/s^2';'rad/s'}, ...
    bands_hz,band_names,4,{'four_hz_exact'});
assert(isequaln(metrics_a,metrics_b), ...
    'response_signature smoke: metric extraction is not deterministic');
assert(metrics_a.estimator.segment_length_samples == 2048 && ...
    metrics_a.estimator.overlap_samples == 1024 && ...
    metrics_a.estimator.nfft == 2048 && ...
    strcmp(metrics_a.estimator.window,'periodic Hann'), ...
    'response_signature smoke: fixed Welch parameters drifted');

summary = metrics_a.summary;
low_four = summary.psd_band_energy( ...
    strcmp(summary.channel,'low') & strcmp(summary.psd_band,'four_hz'));
low_forty = summary.psd_band_energy( ...
    strcmp(summary.channel,'low') & strcmp(summary.psd_band,'forty_hz'));
high_four = summary.psd_band_energy( ...
    strcmp(summary.channel,'high') & strcmp(summary.psd_band,'four_hz'));
high_forty = summary.psd_band_energy( ...
    strcmp(summary.channel,'high') & strcmp(summary.psd_band,'forty_hz'));
assert(low_four > 1e6*max(low_forty,realmin) && ...
    high_forty > 1e6*max(high_four,realmin), ...
    'response_signature smoke: PSD bands do not isolate known tones');
assert(abs(low_four-2) < 1e-12 && abs(high_forty-0.125) < 1e-12, ...
    'response_signature smoke: one-sided PSD absolute scaling drifted');
assert(abs(summary.signal_rms(1)-sqrt(2)) < 1e-12 && ...
    abs(summary.signal_abs_peak(1)-2) < 1e-12, ...
    'response_signature smoke: RMS/peak definitions drifted');
four_hz_row = strcmp(summary.channel,'low') & ...
    strcmp(summary.psd_band,'four_hz');
assert(summary.realized_band_low_hz(four_hz_row) == 3 && ...
    summary.realized_band_high_hz(four_hz_row) == 5 && ...
    summary.realized_bin_count(four_hz_row) == 5 && ...
    strcmp(summary.psd_density_unit{four_hz_row},'(m/s^2)^2/Hz') && ...
    strcmp(summary.psd_band_energy_unit{four_hz_row},'(m/s^2)^2'), ...
    'response_signature smoke: PSD realized-bin/unit metadata drifted');
harmonic = metrics_a.harmonic_summary;
low_harmonic = strcmp(harmonic.channel,'low');
high_harmonic = strcmp(harmonic.channel,'high');
assert(abs(harmonic.exact_frequency_amplitude(low_harmonic)-2) < 1e-12 && ...
    abs(harmonic.exact_frequency_amplitude(high_harmonic)) < 1e-12 && ...
    harmonic.target_frequency_hz(low_harmonic) == 4 && ...
    harmonic.nearest_welch_bin_hz(low_harmonic) == 4, ...
    'response_signature smoke: exact polygon-harmonic estimator drifted');

local_assert_throws(@() response_signature_metrics( ...
    time_s(1:100),signal(:,1:100),{'low';'high'}, ...
    {'m/s^2';'rad/s'},bands_hz,band_names), ...
    'response_signature:TooFewSamples');
local_assert_throws(@() response_signature_metrics( ...
    [time_s(1:1000),time_s(1001)+1e-5,time_s(1002:end)], ...
    signal,{'low';'high'},{'m/s^2';'rad/s'},bands_hz,band_names), ...
    'response_signature:NonuniformTime');
local_assert_throws(@() response_signature_metrics( ...
    time_s,signal,{'low';'high'},{'m/s^2';'rad/s'}, ...
    [500 700],{'beyond_nyquist'}), ...
    'response_signature:PsdBandBeyondNyquist');
local_assert_throws(@() response_signature_study({'not_a_mechanism'}), ...
    'response_signature:UnknownIntervention');

fprintf(['RESPONSE SIGNATURE METRICS: PASS ' ...
    '(9 catalog descriptors; fixed Welch and exact-harmonic contracts)\n']);
end

function local_assert_throws(call,expected_identifier)
try
    call();
catch caught
    assert(strcmp(caught.identifier,expected_identifier), ...
        'Expected %s, received %s.',expected_identifier,caught.identifier);
    return;
end
error('response_signature smoke: missing expected error %s', ...
    expected_identifier);
end
