function report = smoke_response_signature_pair()
%SMOKE_RESPONSE_SIGNATURE_PAIR Two-solve production-chain CRN fingerprint.
%
% This deliberately runs only healthy versus one 30% support-loss passage.
% It proves the full executable chain without pretending to execute the
% nine-intervention inventory or the registered 50-passage study.

report = response_signature_study({'scour'});
assert(strcmp(report.status,'exploratory/nonqualifying'));
assert(isscalar(report.pairs) && ...
    strcmp(report.pairs(1).name,'scour'));
pair = report.pairs(1);
geometry = report.healthy.geometry;
assert(geometry.bridge_elements_per_sleeper_spacing == 3 && ...
    geometry.rail_elements_per_sleeper_spacing == 2 && ...
    all(abs(geometry.support_coordinate_error_m) <= ...
    geometry.support_coordinate_tolerance_m) && ...
    geometry.all_supports_on_nodes_within_tolerance, ...
    'full response-signature smoke did not use the aligned L60 mesh');
assert(pair.crn_controls_exactly_equal, ...
    'full response-signature smoke lost CRN equality');
assert(isfield(report.healthy.controls,'fixed_geometry') && ...
    ~isfield(report.healthy.controls.fixed_geometry,'track_frame_offset_m') && ...
    pair.state_specific_geometry.track_frame_offset_delta_m == 0, ...
    'full response-signature smoke mixed damage placement into CRN controls');
assert(pair.physics_change_counts.beam_M_nnz == 0 && ...
    pair.physics_change_counts.model_M_nnz == 0 && ...
    pair.physics_change_counts.beam_K_nnz > 0 && ...
    pair.physics_change_counts.model_K_nnz > 0 && ...
    pair.physics_change_counts.beam_C_nnz > 0 && ...
    pair.physics_change_counts.model_C_nnz > 0 && ...
    pair.rayleigh_damping.state_specific_rayleigh_recomputed && ...
    contains(pair.rayleigh_damping.interpretation,'not a fixed-C K-only'), ...
    'full response-signature smoke violated the scour K+Rayleigh-C boundary');
assert(pair.physics_change_counts.wheel_h_count == 0 && ...
    pair.physics_change_counts.wheel_hd_count == 0 && ...
    pair.physics_change_counts.wheel_hdd_count == 0, ...
    'full response-signature smoke changed a CRN wheel path');
assert(pair.vehicle_response_changed_exactly, ...
    'full response-signature smoke produced no vehicle response change');
names = report.healthy.vehicle_waveforms.channel_names;
assert(all(contains(names(4:7),'rail_eulerian_vertical_acc_under_wheel_')) && ...
    all(contains(report.healthy.vehicle_waveforms.channel_semantics(4:7), ...
    'excludes convective moving-point terms')), ...
    'full response-signature smoke mislabeled B17 Eulerian rail acceleration');
assert(height(pair.vehicle_metric_comparison) == 10 && ...
    height(pair.bridge_metric_comparison) == 2 && ...
    height(pair.contact.summary) == 20 && ...
    height(pair.bridge_extreme_comparison) == 2 && ...
    height(pair.bridge_event_comparison) == 4, ...
    'full response-signature smoke did not emit all requested signatures');
assert(pair.contact.registered_policy.max_tensile_peak_n == 24000 && ...
    pair.contact.registered_policy.max_positive_fraction == 0.002 && ...
    isfinite(pair.contact.healthy_aggregate_tensile_peak_n) && ...
    isfinite(pair.contact.intervention_aggregate_tensile_peak_n) && ...
    isfinite(pair.contact.healthy_aggregate_positive_fraction) && ...
    isfinite(pair.contact.intervention_aggregate_positive_fraction) && ...
    pair.contact.healthy_registered_admissible && ...
    pair.contact.intervention_registered_admissible && ...
    pair.contact.pair_registered_admissible && ...
    pair.bilateral_contact_admissible, ...
    'full response-signature smoke failed the registered contact policy');
assert(all(isfinite(pair.bridge_extreme_comparison.healthy_bridge_x_m)) && ...
    all(isfinite(pair.bridge_extreme_comparison.intervention_bridge_x_m)) && ...
    all(pair.bridge_event_comparison.healthy_time_s == ...
    pair.bridge_event_comparison.intervention_time_s), ...
    'full response-signature smoke omitted bridge extrema/event coordinates');
assert(numel(pair.modal.mac) == 5 && ...
    all(isfinite(pair.modal.mac)) && ...
    all(isfinite(pair.modal.frequency_delta_hz)), ...
    'full response-signature smoke did not emit five matched modes');

fprintf(['RESPONSE SIGNATURE FULL PAIR: PASS ' ...
    '(healthy versus 30%% support loss; no response-direction gate)\n']);
end
