function smoke_r11_provenance_serialization
%SMOKE_R11_PROVENANCE_SERIALIZATION Exercise the real R11 state-save contract.
%   Writes only tiny fixtures below a fresh OS temporary directory, calls the
%   production save_progress function, verifies exact top-level/payload stamps,
%   proves fifteen provenance mutations fail before publication, and cleans up.

schema = 'audit-2026-07-27-r11';
fingerprint = repmat('a', 1, 64);
actual_environment = current_matlab_environment();
[actual_environment_sha, actual_environment_descriptor] = ...
    matlab_environment_identity(actual_environment);

this_dir = fileparts(mfilename('fullpath'));
repo_dir = fileparts(this_dir);
lock_path = fullfile(repo_dir, 'environment', ...
    'campaign-py313-cu128.json');
assert(isfile(lock_path), 'smoke_r11:MissingEnvironmentLock', ...
    'Campaign environment lock is missing: %s', lock_path);
lock = jsondecode(fileread(lock_path));
expected_cross_language_sha = ...
    '958e7fe28f70577e9cb77aba0443c127d0a99726042a4618f7cce88d557fce79';
assert(isstruct(lock) && isscalar(lock) && ...
    isfield(lock, 'schema') && ...
    strcmp(lock.schema, 'ttbi-campaign-environment-v2') && ...
    isfield(lock, 'matlab_environment') && ...
    isfield(lock, 'matlab_environment_sha256'), ...
    'smoke_r11:InvalidEnvironmentLock', ...
    'Environment lock must contain the reviewed v2 MATLAB identity.');
[campaign_environment_sha, campaign_environment_descriptor] = ...
    matlab_environment_identity(lock.matlab_environment);
assert(strcmp(campaign_environment_sha, ...
    lock.matlab_environment_sha256), ...
    'smoke_r11:LockDigestMismatch', ...
    'Environment lock digest does not authenticate its canonical descriptor.');
assert(strcmp(campaign_environment_sha, expected_cross_language_sha), ...
    'smoke_r11:CrossLanguageDigest', ...
    ['MATLAB canonical bytes no longer match the independently computed ' ...
     'Python SHA-256 fixture.']);
assert(strcmp(actual_environment_sha, campaign_environment_sha), ...
    'smoke_r11:WrongMATLABEnvironment', ...
    'Actual environment %s differs from campaign environment %s.', ...
    actual_environment_sha, campaign_environment_sha);

[source_root, source_lines, source_count] = generator_source_root();
assert(~isempty(regexp(source_root, '^[0-9a-f]{64}$', 'once')) && ...
    source_count > 0 && ~isempty(source_lines), ...
    'smoke_r11:SourceRoot', ...
    'Reviewed MATLAB source-root identity is malformed or empty.');

actual_release = actual_environment.release;
campaign_release = lock.matlab_environment.release;
qualification_source = 'PRODUCTION';
run_dir = tempname;
[made, message] = mkdir(run_dir);
assert(made, 'smoke_r11:TempCreateFailed', ...
    'Could not create temporary smoke directory: %s', message);
cleanup_guard = onCleanup(@() local_cleanup(run_dir));

payload = struct( ...
    'gen_schema', schema, ...
    'gen_fingerprint', fingerprint, ...
    'state_uid', ...
        ['ttbi-state-v1|Lmm=060000|spans=3|scour=0203|' ...
         'family=joint|target=00|level=0001|rep=001'], ...
    'state_seed_id', uint32(123456789), ...
    'random_stream_schedule_version', 'uid-named-substreams-v2', ...
    'matlab_release', actual_release, ...
    'campaign_matlab_release', campaign_release, ...
    'release_qualification_run', false, ...
    'actual_matlab_environment_descriptor', actual_environment_descriptor, ...
    'actual_matlab_environment_sha256', actual_environment_sha, ...
    'campaign_matlab_environment_descriptor', ...
        campaign_environment_descriptor, ...
    'campaign_matlab_environment_sha256', campaign_environment_sha, ...
    'generator_source_root_sha256', source_root, ...
    'generator_source_digest_lines', source_lines, ...
    'generator_source_file_count', source_count, ...
    'qualification_source_sha256', qualification_source, ...
    'serialization_sentinel', uint32(11));

save_progress(payload, 1, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, ...
    actual_environment_sha, campaign_environment_sha, source_root, ...
    qualification_source);
local_validate_state(fullfile(run_dir, '0001.mat'), payload);
assert(~isfile(fullfile(run_dir, '.0001.mat.tmp')), ...
    'smoke_r11:AtomicTempRemained', ...
    'save_progress left its temporary file behind.');
fprintf('R11 exact environment/source top-level + payload provenance: PASS\n');

wrong_sha = repmat('b', 1, 64);
bad = payload;
bad.actual_matlab_environment_sha256 = wrong_sha;
local_must_reject(@() save_progress(bad, 2, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 2, 'payload actual-environment digest');

bad = payload;
bad.campaign_matlab_environment_sha256 = wrong_sha;
local_must_reject(@() save_progress(bad, 3, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 3, 'payload campaign-environment digest');

bad = payload;
bad.generator_source_root_sha256 = wrong_sha;
local_must_reject(@() save_progress(bad, 4, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 4, 'payload generator-source root');

bad = payload;
bad.qualification_source_sha256 = wrong_sha;
local_must_reject(@() save_progress(bad, 5, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 5, 'payload qualification-source identity');

local_must_reject(@() save_progress(payload, 6, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, wrong_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 6, 'top-level actual-environment digest');

local_must_reject(@() save_progress(payload, 7, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    wrong_sha, source_root, qualification_source), ...
    run_dir, 7, 'top-level campaign-environment digest');

local_must_reject(@() save_progress(payload, 8, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, wrong_sha, qualification_source), ...
    run_dir, 8, 'top-level generator-source root');

local_must_reject(@() save_progress(payload, 9, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, true, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 9, 'qualification mode with PRODUCTION sentinel');

bad = rmfield(payload, 'actual_matlab_environment_sha256');
local_must_reject(@() save_progress(bad, 10, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 10, 'missing payload environment identity');

bad = payload;
bad.actual_matlab_environment_descriptor = ...
    [bad.actual_matlab_environment_descriptor 'x'];
local_must_reject(@() save_progress(bad, 11, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 11, 'descriptor inconsistent with actual-environment digest');

bad = payload;
bad.generator_source_digest_lines = ...
    [bad.generator_source_digest_lines newline 'forged:source'];
local_must_reject(@() save_progress(bad, 12, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 12, 'source descriptor inconsistent with source-root digest');

bad = payload;
bad.state_uid = '';
local_must_reject(@() save_progress(bad, 13, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 13, 'empty semantic state UID');

bad = payload;
bad.state_seed_id = uint32(0);
local_must_reject(@() save_progress(bad, 14, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 14, 'reserved zero state seed');

bad = payload;
bad.random_stream_schedule_version = ...
    ['uid-named-substreams-v2' newline 'forged'];
local_must_reject(@() save_progress(bad, 15, run_dir, schema, fingerprint, ...
    actual_release, campaign_release, false, actual_environment_sha, ...
    campaign_environment_sha, source_root, qualification_source), ...
    run_dir, 15, 'multiline random-stream schedule');

% The identity helper itself must reject a field-set mutation.
bad_environment = actual_environment;
bad_environment.unreviewed_field = 'forbidden';
identity_rejected = false;
try
    matlab_environment_identity(bad_environment);
catch
    identity_rejected = true;
end
assert(identity_rejected, 'smoke_r11:EnvironmentMutationEscaped', ...
    'Environment identity accepted an unreviewed extra field.');

clear cleanup_guard
assert(~isfolder(run_dir), 'smoke_r11:CleanupFailed', ...
    'Temporary smoke directory was not removed: %s', run_dir);
fprintf(['R11 PROVENANCE SERIALIZATION: ALL PASS ' ...
    '(15 mutations rejected; temp cleaned)\n']);
end

function local_validate_state(path, expected)
assert(isfile(path), 'smoke_r11:MissingState', ...
    'save_progress did not publish %s.', path);
inventory = whos('-file', path);
actual_names = sort(string({inventory.name}));
expected_names = sort([ ...
    "data", "file_gen_schema", "file_gen_fingerprint", ...
    "file_state_uid", "file_state_seed_id", ...
    "file_random_stream_schedule_version", ...
    "file_matlab_release", "file_campaign_matlab_release", ...
    "file_release_qualification_run", ...
    "file_actual_matlab_environment_sha256", ...
    "file_campaign_matlab_environment_sha256", ...
    "file_generator_source_root_sha256", ...
    "file_qualification_source_sha256"]);
assert(isequal(actual_names, expected_names), ...
    'smoke_r11:TopLevelInventory', ...
    'Unexpected top-level state-file inventory in %s.', path);

saved = load(path);
checks = { ...
    'file_gen_schema', 'gen_schema'; ...
    'file_gen_fingerprint', 'gen_fingerprint'; ...
    'file_state_uid', 'state_uid'; ...
    'file_random_stream_schedule_version', ...
        'random_stream_schedule_version'; ...
    'file_matlab_release', 'matlab_release'; ...
    'file_campaign_matlab_release', 'campaign_matlab_release'; ...
    'file_actual_matlab_environment_sha256', ...
        'actual_matlab_environment_sha256'; ...
    'file_campaign_matlab_environment_sha256', ...
        'campaign_matlab_environment_sha256'; ...
    'file_generator_source_root_sha256', 'generator_source_root_sha256'; ...
    'file_qualification_source_sha256', 'qualification_source_sha256'};
for k = 1:size(checks, 1)
    local_require_text(saved.(checks{k, 1}), expected.(checks{k, 2}), ...
        checks{k, 1});
end
assert(isa(saved.file_state_seed_id, 'uint32') && ...
    isscalar(saved.file_state_seed_id) && ...
    saved.file_state_seed_id == expected.state_seed_id, ...
    'smoke_r11:StateSeedMismatch', ...
    'Top-level semantic state seed is absent, malformed, or mismatched.');
assert(islogical(saved.file_release_qualification_run) && ...
    isscalar(saved.file_release_qualification_run) && ...
    ~saved.file_release_qualification_run, ...
    'smoke_r11:QualificationNotFalse', ...
    'Top-level qualification marker must be logical false.');
assert(isequaln(saved.data, expected), ...
    'smoke_r11:PayloadMismatch', ...
    'Serialized data payload differs from the supplied provenance fixture.');
end

function local_require_text(value, expected, label)
assert(ischar(value) && isrow(value) && strcmp(value, expected), ...
    'smoke_r11:TextMismatch', ...
    '%s is absent, malformed, or mismatched.', label);
end

function local_must_reject(action, run_dir, index, label)
rejected = false;
try
    action();
catch
    rejected = true;
end
assert(rejected, 'smoke_r11:MutationEscaped', ...
    'save_progress accepted mutation: %s.', label);
assert(~isfile(fullfile(run_dir, sprintf('%04d.mat', index))) && ...
    ~isfile(fullfile(run_dir, sprintf('.%04d.mat.tmp', index))), ...
    'smoke_r11:MutationPublished', ...
    'Rejected mutation left a state or temporary file: %s.', label);
fprintf('R11 mutation rejected (%s): PASS\n', label);
end

function local_cleanup(path)
if isfolder(path)
    rmdir(path, 's');
end
end
